"""
One-off decoder for the IRAF PLIO (.pl) bad-pixel masks distributed for
Subaru/MOIRCS (mcsbadpix_oct2016.tar.gz), written so the masks can be
shipped with PypeIt as compressed FITS files.

Not part of PypeIt.  Generated by JXP and Claude.

File layout (deduced from the files; consistent with IRAF's pl_save):
    - 3 big-endian int32: magic, header length (chars), mask length (shorts)
    - text header (padded to an even number of bytes)
    - mask, as big-endian int16:
        * 40 shorts: PL descriptor (20 int32; naxes, axlen, llop, ...)
        * the line index (one llbuf offset per image line), itself stored
          as a PLIO line list
        * llbuf: the concatenated per-line line lists
"""
from pathlib import Path
import argparse

import numpy as np


def pl_l2pi(ll, npix, xs=1):
    """
    Decode a PLIO line list into an integer pixel array.

    Port of ``pl_l2pi`` from CFITSIO's ``pliocomp.c``.

    Generated by JXP and Claude.

    Args:
        ll (`numpy.ndarray`_):
            int16 line list, starting with its header.
        npix (:obj:`int`):
            Number of pixels to decode.
        xs (:obj:`int`, optional):
            1-indexed first pixel to decode.

    Returns:
        `numpy.ndarray`_: int64 array of ``npix`` decoded pixel values.
    """
    ll = np.asarray(ll, dtype=np.int64)
    out = np.zeros(npix, dtype=np.int64)
    # Old vs. new line-list header formats
    if ll[2] > 0:
        lllen, first = int(ll[2]), 3
    else:
        lllen, first = int((ll[4] << 15) + ll[3]), int(ll[1])
    xe = xs + npix - 1
    op, x1, pv = 0, 1, 1
    ip = first
    while ip < lllen:
        word = int(ll[ip])
        opcode, data = (word >> 12) & 0xF, word & 0xFFF
        if opcode in (0, 4, 5):
            # Zero run (0), high-value run (4), zeros ending in pv (5)
            x2 = x1 + data - 1
            i1, i2 = max(x1, xs), min(x2, xe)
            n = i2 - i1 + 1
            if n > 0:
                if opcode == 4:
                    out[op:op + n] = pv
                elif opcode == 5 and i2 == x2:
                    out[op + n - 1] = pv
                op += n
            x1 = x2 + 1
        elif opcode == 1:
            # Set the high value from this and the next word
            pv = (int(ll[ip + 1]) << 12) + data
            ip += 1
        elif opcode == 2:
            pv += data
        elif opcode == 3:
            pv -= data
        elif opcode in (6, 7):
            # Increment/decrement the high value and output one pixel
            pv += data if opcode == 6 else -data
            if xs <= x1 <= xe:
                out[op] = pv
                op += 1
            x1 += 1
        ip += 1
        if x1 > xe:
            break
    return out


def read_pl(path):
    """
    Read an IRAF ``.pl`` mask saved by ``pl_save``.

    Generated by JXP and Claude.

    Args:
        path (:obj:`str`, `Path`_):
            The ``.pl`` file.

    Returns:
        `numpy.ndarray`_: The 2D mask, shape ``(ny, nx)`` (FITS/numpy
        order), with the integer mask values.
    """
    buf = Path(path).read_bytes()
    _, sz_hdr, sz_mask = np.frombuffer(buf[:12], '>i4')
    off = 12 + sz_hdr + (sz_hdr % 2)
    mask = np.frombuffer(buf[off:off + 2 * sz_mask], '>i2').astype(np.int64)

    # Descriptor: 20 int32 stored as pairs of int16 (high, low)
    desc = (mask[0:40:2] << 16) + (mask[1:40:2] & 0xFFFF)
    naxes = int(desc[1])
    nx, ny = int(desc[2]), int(desc[3])
    llop = int(desc[9])
    if naxes != 2:
        raise ValueError(f'Expected a 2D mask, got naxes={naxes}')

    # The line index is a line list starting right after the descriptor;
    # llbuf (llop shorts) fills the end of the mask
    index = pl_l2pi(mask[40:], ny)
    llbuf = mask[-llop:]

    img = np.zeros((ny, nx), dtype=np.int64)
    for j in range(ny):
        # Offsets into llbuf are 0-indexed; offset 0 is the empty line
        img[j] = pl_l2pi(llbuf[index[j]:], nx)
    return img


def main():
    """
    Command-line entry point.

    Generated by JXP and Claude.
    """
    parser = argparse.ArgumentParser(description='Decode IRAF .pl masks')
    parser.add_argument('files', nargs='+', help='.pl files')
    args = parser.parse_args()
    for f in args.files:
        img = read_pl(f)
        vals, cnts = np.unique(img, return_counts=True)
        print(f, img.shape, dict(zip(vals.tolist(), cnts.tolist())))


if __name__ == '__main__':
    main()
