"""
Build the MOIRCS static bad-pixel masks shipped with PypeIt from the
decoded IRAF masks (see decode_plio.py).

The largest connected masked region (the beam-splitter shadow joined with
the reference-pixel border and vignetted corners) is removed, keeping only
the isolated detector defects.  Masks are written in raw orientation.

Not part of PypeIt.  Generated by JXP and Claude.
"""
from pathlib import Path

import numpy as np
from astropy.io import fits
from scipy import ndimage
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from decode_plio import read_pl

OUT = Path('/Users/xavier/Projects/PypeIt/PypeIt/pypeit/data/'
           'static_calibs/subaru_moircs')

fig, ax = plt.subplots(2, 2, figsize=(10, 10))
for i, pl in enumerate(['mask1_oct16.pl', 'mask2_oct16.pl']):
    det = i + 1
    full = read_pl(pl).astype(bool)
    # Drop the largest connected region (shadow + border + corners)
    lab, _ = ndimage.label(full)
    sizes = np.bincount(lab.ravel())
    sizes[0] = 0
    defects = full & (lab != np.argmax(sizes))

    hdr = fits.Header()
    hdr['ORIGIN'] = ('mcsbadpix_oct2016.tar.gz', 'NAOJ MOIRCS BPM archive')
    hdr['SRCFILE'] = (pl, 'Decoded IRAF PLIO mask')
    hdr['DET'] = (det, 'MOIRCS chip (DET-ID)')
    hdr['COMMENT'] = 'Raw orientation. Beam-splitter shadow removed; ' \
                     'only isolated defects kept.'
    fits.writeto(OUT / f'bpm_moircs_det{det}.fits.gz',
                 defects.astype(np.uint8), hdr, overwrite=True)
    print(det, f'full {full.mean():.4f} -> defects {defects.mean():.5f}')

    ax[0, i].imshow(full, origin='lower', cmap='gray_r')
    ax[0, i].set_title(f'chip {det}: original IRAF mask (imaging)')
    # Dilate for visibility
    ax[1, i].imshow(ndimage.binary_dilation(defects, iterations=3),
                    origin='lower', cmap='gray_r')
    ax[1, i].set_title(f'chip {det}: shipped mask (defects, dilated x3)')
plt.tight_layout()
plt.savefig('bpm_review.png', dpi=70)
