#!/usr/bin/env python3
#
# See top-level LICENSE.rst file for Copyright information
#
# -*- coding: utf-8 -*-

"""
This script runs the PypeIt development suite of tests
"""
import sys
import shutil
import os
from test_scripts.test_main import main

if __name__ == '__main__':
    # Check for pypeit executable
    if shutil.which("run_pypeit") is None:
        raise RuntimeError("You need to install run_pypeit in your PATH")

    # Check for PYPEIT_DEV
    if 'PYPEIT_DEV' not in os.environ:
        raise EnvironmentError('Enviroment must include PYPEIT_DEV, which points to the '
                               'top-level directory with the dev-suite raw data.')

    # Giddy up
    sys.exit(main())


