#!/usr/bin/env python3
#
# See top-level LICENSE.rst file for Copyright information
#
# -*- coding: utf-8 -*-

"""
This script runs the PypeIt development suite of tests
"""

import sys
import os
import subprocess

from IPython import embed


def parser(options=None):
    import argparse

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter,
                                     description='Sync/copy the RAW_DATA')

    parser.add_argument('developer', type=str, default=None, help='Developer (jxp)')
    parser.add_argument('-c', '--copy', default=False, action='store_true',
                        help='Use copy instead of sync')
    parser.add_argument('-d', '--dryrun', default=False, action='store_true',
                        help='Only list the steps')
    parser.add_argument('-p', '--print', default=False, action='store_true',
                        help='Only print the command')

    return parser.parse_args() if options is None else parser.parse_args(options)


def main():

    pargs = parser()

    #
    if pargs.developer == 'jxp':
        if pargs.copy:
            command = 'copy'
        else:
            command = 'sync'
        p = ['rclone', command, 'GoogleDrive:UCO/PypeIt/PypeIt-development-suite/RAW_DATA', 'RAW_DATA', '-v']
        if pargs.dryrun:
            p += ['--dry-run']
        if pargs.print:
            print(' '.join(p))
            return
        subprocess.run(p, check=True)
    elif pargs.developer == 'rjc':
        if pargs.copy:
            command = 'copy'
        else:
            command = 'sync'
        p = ['rclone', command, 'PypeIt:RAW_DATA', 'RAW_DATA', '-v']
        if pargs.dryrun:
            p += ['--dry-run']
        if pargs.print:
            print(' '.join(p))
            return
        subprocess.run(p, check=True)

if __name__ == '__main__':
    # Check for rclone
    if not any([os.access(os.path.join(path, 'rclone'), os.X_OK)
                for path in os.environ["PATH"].split(os.pathsep)]):
        raise RuntimeError("You need to install rclone in your PATH")

    # Giddy up
    main()



