"""
Module to run tests on scripts
"""
import os
import glob
import numpy as np

from pypeit import specobjs

def test_bok_bc_manual(redux_out):
    """ Checks that the manual extraction with FWHM is working for Bok BC"""
    instr = 'bok_bc' 
    rdxdir = os.path.join(redux_out, instr, '300')
    scidir = os.path.join(rdxdir, 'Science')

    spec1d_files = glob.glob(os.path.join(scidir, 'spec1d*.fits')) 
    spec1d_files.sort()
    sobjs = specobjs.SpecObjs.from_fitsfile(spec1d_files[1]) # 0 should be the standard

    hand_sobj = sobjs[sobjs.hand_extract_flag]
    # Test
    assert np.isclose(hand_sobj.BOX_R_PIX[0], 4.)  # Value in the pypeit file


def test_ech_manual(redux_out):
    """ Checks that the manual extraction of VLT X-Shooter worked"""
    instr = 'vlt_xshooter' 
    rdxdir = os.path.join(redux_out, instr, 'VIS_manual')
    scidir = os.path.join(rdxdir, 'Science')

    spec1d_files = glob.glob(os.path.join(scidir, 'spec1d*.fits')) 
    spec1d_files.sort()
    sobjs = specobjs.SpecObjs.from_fitsfile(spec1d_files[1]) # 0 should be the standard

    # Count em (15 orders)
    hand_sobj = sobjs[sobjs.hand_extract_flag]
    assert len(hand_sobj) == 15

def test_shane_hamspec_forced_extraction(redux_out):
    """
    Check the Shane/Hamspec forced slit-center extraction (Extraction #1 /
    Q&A 47-50): the standard star fills the ~6 px Loral orders, so
    ``force_center_obj`` must produce one object per good order with valid
    boxcar and optimal extractions and no sky model.

    Generated by JXP and Claude.
    """
    for setup, min_orders in zip(['Hamilton', 'Hamilton_e2v'], [15, 50]):
        scidir = os.path.join(redux_out, 'shane_hamspec', setup, 'Science')
        spec1d_files = glob.glob(os.path.join(scidir, 'spec1d*.fits'))
        assert len(spec1d_files) > 0, f'No {setup} spec1d written ' \
                                      '(forced extraction failed)!'

        sobjs = specobjs.SpecObjs.from_fitsfile(spec1d_files[0])
        # One forced object per good order (the passing runs extract
        # 19 for Hamilton and 64 for Hamilton_e2v)
        assert sobjs.nobj >= min_orders, \
            f'Only {sobjs.nobj} {setup} orders extracted!'
        _check_hamspec_sobjs(sobjs)


def _check_hamspec_sobjs(sobjs):
    """
    Check each forced Hamspec object: trace at the order center and valid
    boxcar + optimal extractions with real signal.

    Generated by JXP and Claude.
    """
    for so in sobjs:
        # Trace forced to the order center
        assert np.isclose(so.SPAT_FRACPOS, 0.5), \
            'Hamspec object not at the forced order center!'
        # Both boxcar and optimal extractions present with real signal
        for counts, ivar in [(so.BOX_COUNTS, so.BOX_COUNTS_IVAR),
                             (so.OPT_COUNTS, so.OPT_COUNTS_IVAR)]:
            assert counts is not None, 'Missing Hamspec extraction!'
            gpm = ivar > 0
            assert np.median(counts[gpm]
                             * np.sqrt(ivar[gpm])) > 5., \
                f'Low S/N in Hamspec order {so.ECH_ORDER}!'
