"""
Regenerate PypeIt's auto-built doc tables into a scratch directory and
compare them with the versions in ``PypeIt/doc``.

This shows which generated files a ``build-docs`` run would change, without
running it (it would rewrite shared files in ``PypeIt/doc``).  Only the
generators that depend on spectrograph classes are run: the parameter
listing (``build_par_rst.py``), the detector table
(``build_detector_table.py``), the spectrograph table
(``build_spectbl_rst.py``) and the cached-data table
(``build_cache_data_tbl.py``).

Usage::

    python regen_doc_tables.py /path/to/outdir [--grep subaru_moircs]

Generated by JXP and Claude
"""

import argparse
import difflib
import importlib.util
from importlib import resources
from pathlib import Path

# Generated file -> its path relative to PypeIt/doc
TARGETS = {'pypeit_par.rst': 'pypeit_par.rst',
           'inst_detector_table.rst': 'include/inst_detector_table.rst',
           'spectrographs_table.rst': 'include/spectrographs_table.rst',
           'data_dir.rst': 'include/data_dir.rst'}


def load_doc_script(scripts_dir, name):
    """
    Import one of the ``PypeIt/doc/scripts`` generators as a module.

    Generated by JXP and Claude

    Args:
        scripts_dir (`Path`_):
            The ``PypeIt/doc/scripts`` directory.
        name (:obj:`str`):
            Script name without the ``.py`` extension.

    Returns:
        module: The imported module (its ``__main__`` block is not run).
    """
    spec = importlib.util.spec_from_file_location(
        name, scripts_dir / f'{name}.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def regenerate(outdir):
    """
    Write the generated tables into ``outdir``.

    ``build_par_rst.py`` has no function to call, so its ``__main__`` block
    is run with the output path replaced.

    Generated by JXP and Claude

    Args:
        outdir (`Path`_):
            Output directory (must exist).

    Returns:
        `Path`_: The ``PypeIt/doc`` directory of the installed package.
    """
    doc_dir = resources.files('pypeit').parent / 'doc'
    scripts_dir = doc_dir / 'scripts'
    load_doc_script(scripts_dir, 'build_detector_table') \
        .write_detector_table(outdir / 'inst_detector_table.rst')
    load_doc_script(scripts_dir, 'build_spectbl_rst') \
        .write_spec_table(outdir)
    load_doc_script(scripts_dir, 'build_cache_data_tbl') \
        .write_table(outdir / 'data_dir.rst')
    # Redirect the parameter listing to outdir
    src = (scripts_dir / 'build_par_rst.py').read_text()
    old = "output_rst = pypeit_root / 'doc' / 'pypeit_par.rst'"
    if old not in src:
        raise ValueError('build_par_rst.py changed; update this script')
    src = src.replace(old, f"output_rst = Path(r'{outdir}') / "
                           "'pypeit_par.rst'")
    exec(compile(src, 'build_par_rst.py', 'exec'),
         {'__name__': '__main__', 'Path': Path})
    return doc_dir


def compare(doc_dir, outdir, grep=None):
    """
    Print a unified diff of each regenerated file against ``PypeIt/doc``.

    Generated by JXP and Claude

    Args:
        doc_dir (`Path`_):
            The ``PypeIt/doc`` directory.
        outdir (`Path`_):
            Directory with the regenerated files.
        grep (:obj:`str`, optional):
            If given, only diff lines containing this string are printed,
            plus a count of the other changed lines.

    Returns:
        :obj:`dict`: Number of changed lines per file.
    """
    nchanged = {}
    for name, rel in TARGETS.items():
        old = (doc_dir / rel).read_text().splitlines()
        new = (outdir / name).read_text().splitlines()
        diff = [d for d in difflib.unified_diff(old, new, lineterm='', n=0)
                if d[:1] in '+-' and d[:3] not in ['+++', '---']]
        nchanged[rel] = len(diff)
        print(f'== doc/{rel}: {len(diff)} changed lines')
        shown = diff if grep is None else [d for d in diff if grep in d]
        for d in shown:
            print('  ' + d.rstrip())
        if grep is not None and len(shown) < len(diff):
            print(f'  ({len(diff) - len(shown)} other changed lines)')
    return nchanged


def main():
    """
    Command-line entry point.

    Generated by JXP and Claude
    """
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('outdir', type=Path, help='scratch output directory')
    parser.add_argument('--grep', help='only show diff lines with this text')
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    doc_dir = regenerate(args.outdir.resolve())
    compare(doc_dir, args.outdir, grep=args.grep)


if __name__ == '__main__':
    main()
