"""
Sketch (mock-up) of the PypeIt Dashboard **Calibrations View**.

Generated by JXP and Claude.

Purpose
-------
A *non-functional* layout sketch (not production code) of the Dashboard's
Calibrations tab, as specified in the Calibrations section of
``pypeitdev/dashboard/pypeit_dashboard_design.md`` (requirements C1-C16).  It
renders a static PNG so we have something concrete to react to before building
the real PyQt6 widget.

Design notes (the "thinking", so this is easy to modify)
--------------------------------------------------------
The Calibrations view is the drill-down for a single (calibration group,
detector/mosaic).  Top to bottom, the sketch lays it out as:

  1. **Tab bar** (Status | Calibrations) -- Calibrations active here.
  2. **Header banner** with run context + PypeIt logo (shared with Status).
  3. **Scope toolbar**: the calib-group and detector/mosaic drop-downs.  [C2]
  4. **Step-button row**: one button per calibration step, left->right in
     ``default_steps()`` order with arrow connectors, color-coded by status,
     each with a glyph; ``bpm`` is omitted.  The *selected* step is ringed in
     the high-contrast SELECT_COLOR (magenta -- the earlier blue was hard to
     see).  [C3, C4, C12, C13]
  5. **Detail panel** for the selected step (``wv_calib``): metrics (C6), a
     **scrollable input-file list** with per-file view actions (C7), the output
     file with "inspect" launchers (C8), a non-green "(re)generate" control
     wrapping ``pypeit_run_to_calibstep`` (C10), **clickable QA thumbnails**
     that open a full view (C9), and a **scrollable per-slit/order list** (C11).
  6. A **status color key** (unified palette).

Shared helpers (palette, pills, tab bar, header+logo, scope toolbar, color key,
chips) come from ``utils.py`` (reuse, design principle #2).

Example content mirrors the real ``shane_kast_blue_A`` reduction: MultiSlit
pipeline, calib group 0, DET01, one slit (S0175).  Steps ``dark`` and
``scattlight`` are present but not required (grey); the rest succeeded (green).
The selected step ``wv_calib`` shows its real metric (slit 175 rms = 0.074 px)
and the names of its QA PNGs.  Per the design decision the QA entries are drawn
as plain clickable *boxes* (placeholders), not previews of the actual PNGs.

Drawing approach: Matplotlib patches/text on a 0..100 x 0..100 canvas (larger y
at top).  No interactivity.

Inputs / Outputs
----------------
Inputs : none (example content hard-coded below).
Outputs: writes ``dashboard_calibrations.png`` to the directory *above* this
         script (``pypeitdev/dashboard/``) and returns its path.
"""

import os
from matplotlib import pyplot as plt
from matplotlib.patches import Rectangle, FancyBboxPatch, FancyArrow

import utils
from utils import (PALETTE, status_text_color, draw_status_pill, draw_tab_bar,
                   draw_header, draw_logo, draw_scope_toolbar, draw_color_key,
                   chip, SELECT_COLOR)


# --- Example content: MultiSlit calib steps for shane_kast_blue, group 0 -----
# (step_label, status_key); order = default_steps() minus the hidden 'bpm'.
CALIB_STEPS = [
    ('bias',       'success'),
    ('dark',       'not_required'),
    ('slits',      'success'),
    ('arc',        'success'),
    ('tiltimg',    'success'),
    ('wv_calib',   'success'),   # <-- the selected step in this sketch
    ('tilts',      'success'),
    ('scattlight', 'not_required'),
    ('flats',      'success'),
]
SELECTED_STEP = 'wv_calib'

# Real input frame(s) and QA PNGs for the selected wv_calib step.
INPUT_FILES = ['b1.fits.gz']
QA_FILES = ['Arc_1dfit_A_0_DET01_S0175.png',
            'Arc_FWHMfit_A_0_DET01_S0175.png',
            'Arc_tilts_2d_A_0_DET01_S0175.png']
# Per-slit/order rows: (slit_id, status_key, rms).
SLIT_ROWS = [('175', 'success', '0.074')]


def _draw_step_buttons(ax, top_y):
    """
    Draw the dependency-ordered row of color-coded calibration step buttons.

    Generated by JXP and Claude.

    Buttons are laid out left->right in ``default_steps()`` order with arrow
    connectors; the selected step is ringed in the high-contrast SELECT_COLOR
    and points to the detail panel below.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    top_y : float
        Top edge (data coords) of the button row.

    Returns
    -------
    float
        The y just below the button row.
    """
    ax.text(4, top_y + 0.4, 'Calibration steps  (dependency order)',
            fontsize=9, fontweight='bold', color='#37474F', va='bottom')

    n = len(CALIB_STEPS)
    x0, x1 = 4.5, 97.5
    gap = 1.4
    bw = (x1 - x0 - gap * (n - 1)) / n
    bh = 4.2
    y0 = top_y - bh
    for i, (label, status_key) in enumerate(CALIB_STEPS):
        fill, edge, glyph, _lbl = PALETTE[status_key]
        x = x0 + i * (bw + gap)
        selected = (label == SELECTED_STEP)
        btn_edge = SELECT_COLOR if selected else edge
        lw = 3.5 if selected else 1.2
        ax.add_patch(FancyBboxPatch((x, y0), bw, bh,
                     boxstyle='round,pad=0.1,rounding_size=0.7',
                     facecolor=fill, edgecolor=btn_edge, linewidth=lw))
        txt_c = status_text_color(status_key)
        ax.text(x + bw / 2, y0 + bh * 0.62, label, ha='center', va='center',
                fontsize=8.2, fontweight='bold', color=txt_c)
        ax.text(x + bw / 2, y0 + bh * 0.28, glyph, ha='center', va='center',
                fontsize=9, color=txt_c)
        if i < n - 1:
            ax.add_patch(FancyArrow(x + bw + 0.1, y0 + bh / 2, gap - 0.2, 0,
                         width=0.05, head_width=0.9, head_length=0.6,
                         length_includes_head=True, color='#90A4AE'))
        if selected:
            # Magenta pointer triangle toward the detail panel.
            ax.plot([x + bw / 2 - 1.2, x + bw / 2 + 1.2, x + bw / 2],
                    [y0 - 0.2, y0 - 0.2, y0 - 1.6], color=SELECT_COLOR,
                    linewidth=2.0)
    return y0 - 1.8


def _panel_label(ax, x, y, text):
    """
    Draw a small bold sub-heading inside the detail panel.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x, y : float
        Anchor (data coords).
    text : str
        Sub-heading text.

    Returns
    -------
    None
    """
    ax.text(x, y, text, fontsize=9, fontweight='bold', color='#37474F',
            va='center')


def _scroll_viewport(ax, x, y_top, w, h):
    """
    Draw a bordered scrollable-list viewport with a scrollbar track + thumb.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x, y_top : float
        Top-left corner (data coords).
    w, h : float
        Width and height of the viewport (data units).

    Returns
    -------
    None
    """
    ax.add_patch(Rectangle((x, y_top - h), w, h, facecolor='white',
                           edgecolor='#B0BEC5'))
    # Scrollbar track + thumb on the right edge.
    sb_x = x + w - 1.0
    ax.add_patch(Rectangle((sb_x, y_top - h), 0.8, h, facecolor='#ECEFF1',
                           edgecolor='#CFD8DC'))
    ax.add_patch(Rectangle((sb_x, y_top - h * 0.55), 0.8, h * 0.5,
                           facecolor='#B0BEC5', edgecolor='#90A4AE'))


def _draw_input_list(ax, x, y_top, w):
    """
    Draw the scrollable list of input files, each with a "view" action.

    Generated by JXP and Claude.

    Raw frames open with ``pypeit_view_fits``; processed frames with ``ginga``
    (here the wv_calib input is the raw arc ``b1.fits.gz``).

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x, y_top : float
        Top-left corner (data coords).
    w : float
        Width of the list.

    Returns
    -------
    float
        The y just below the list.
    """
    h = 6.5
    _scroll_viewport(ax, x, y_top, w, h)
    y = y_top - 2.0
    for fn in INPUT_FILES:
        ax.text(x + 1.0, y, fn, fontsize=8.2, family='monospace',
                color='#455A64', va='center')
        chip(ax, x + w - 14.5, y - 1.0, 11.5, 'view (pypeit_view_fits)')
        y -= 2.6
    ax.text(x + 1.0, y, '… scrollable: one row per input frame '
            '(bias/flats have many)', fontsize=7.4, color='#B0BEC5',
            va='center', style='italic')
    return y_top - h


def _draw_slit_list(ax, x, y_top, w):
    """
    Draw the scrollable per-slit / per-order status list.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x, y_top : float
        Top-left corner (data coords).
    w : float
        Width of the list.

    Returns
    -------
    float
        The y just below the list.
    """
    h = 7.0
    _scroll_viewport(ax, x, y_top, w, h)
    # Column headers inside the viewport.
    ax.text(x + 1.0, y_top - 1.4, 'Slit', fontsize=8.2, fontweight='bold',
            color='#37474F', va='center')
    ax.text(x + 7.0, y_top - 1.4, 'Status', fontsize=8.2, fontweight='bold',
            color='#37474F', va='center')
    ax.text(x + 22.0, y_top - 1.4, 'rms (px)', fontsize=8.2, fontweight='bold',
            color='#37474F', va='center')
    y = y_top - 3.4
    for slit, status_key, rms in SLIT_ROWS:
        ax.text(x + 1.0, y, slit, fontsize=8.2, family='monospace',
                color='#212121', va='center')
        draw_status_pill(ax, x + 5.5, y, status_key, width=11)
        ax.text(x + 22.0, y, rms, fontsize=8.2, family='monospace',
                color='#2E7D32', va='center')
        y -= 2.4
    ax.text(x + 1.0, y, '… scrollable: one row per slit / order '
            '(MOS & echelle have many)', fontsize=7.4, color='#B0BEC5',
            va='center', style='italic')
    return y_top - h


def _draw_qa_thumb(ax, x, y_top, w, h, filename):
    """
    Draw one clickable QA-file box (a placeholder, not a PNG preview).

    Generated by JXP and Claude.

    The box represents a QA file; an enlarge glyph indicates it is clickable to
    open a full view of the PNG (C9).  Per the design decision we do NOT render
    the actual PNG here -- the box stands in for it.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x, y_top : float
        Top-left corner of the box (data coords).
    w, h : float
        Box size (data units).
    filename : str
        QA PNG file name (shown as a label beside the box).

    Returns
    -------
    None
    """
    ax.add_patch(Rectangle((x, y_top - h), w, h, facecolor='#CFD8DC',
                           edgecolor='#90A4AE'))
    # Enlarge affordance: the box is clickable to open the full PNG view.
    ax.text(x + w - 0.6, y_top - 1.0, '↗', ha='right', va='center',
            fontsize=11, color='#1565C0')
    ax.text(x + w + 1.0, y_top - h / 2, filename, fontsize=7.4,
            family='monospace', color='#455A64', va='center')


def _draw_detail_panel(ax, top_y):
    """
    Draw the detail panel for the selected step (``wv_calib``).

    Generated by JXP and Claude.

    Two columns: (left) metrics, scrollable input-file list, output file +
    inspect launchers, and the (re)generate control; (right) clickable QA
    thumbnails and the scrollable per-slit/order list.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    top_y : float
        Top edge (data coords) of the panel.

    Returns
    -------
    None
    """
    bottom = 9.0
    ax.add_patch(Rectangle((4, bottom), 94, top_y - bottom, facecolor='#FAFAFA',
                           edgecolor='#B0BEC5', linewidth=1.2))
    ax.add_patch(Rectangle((4, top_y - 3.2), 94, 3.2, facecolor='#ECEFF1',
                           edgecolor='#B0BEC5'))
    ax.text(5.5, top_y - 1.6, 'wv_calib  —  Wavelength Calibration',
            fontsize=11, fontweight='bold', color='#263238', va='center')
    draw_status_pill(ax, 78, top_y - 1.6, 'success', width=14)

    lx = 6.5          # left column x
    rx = 52           # right column x

    # --- Left column ---------------------------------------------------------
    y = top_y - 5.0
    _panel_label(ax, lx, y, 'Metrics  (from state.py; grows as it does)')
    ax.text(lx + 1, y - 2.2, 'slit 175:   rms = 0.074 px  ✓ (< 0.1)',
            fontsize=9, family='monospace', color='#2E7D32', va='center')

    y -= 4.6
    _panel_label(ax, lx, y, 'Input files')
    y = _draw_input_list(ax, lx, y - 1.0, 41)

    y -= 1.4
    _panel_label(ax, lx, y, 'Output file')
    ax.text(lx + 1, y - 2.2, 'WaveCalib_A_0_DET01.fits', fontsize=8.5,
            family='monospace', color='#455A64', va='center')
    chip(ax, lx + 1, y - 4.6, 20, 'inspect  (pypeit_chk_wavecalib)')
    chip(ax, lx + 22, y - 4.6, 18, 'show  (pypeit_show_wvcalib)',
         fill='#37474F')

    y -= 8.6
    _panel_label(ax, lx, y, '(Re)generate  —  enabled (PypeIt not running)')
    # Teal action color, deliberately NOT green (green = "success" status).
    chip(ax, lx + 1, y - 3.0, 40,
         '↻  run_to_calibstep wv_calib  (+ preceding steps)', fill='#00796B')

    # --- Right column: QA thumbnails + per-slit list -------------------------
    qy = top_y - 5.0
    _panel_label(ax, rx, qy, 'QA files  (click a thumbnail to open full view)')
    ty = qy - 1.5
    for fn in QA_FILES:
        _draw_qa_thumb(ax, rx + 1, ty, 9.0, 5.2, fn)
        ty -= 6.2

    _panel_label(ax, rx, ty - 0.5, 'Per-slit / order status  (C11)')
    _draw_slit_list(ax, rx, ty - 2.0, 42)


def make_calibrations_sketch(outpath=None):
    """
    Build the Calibrations View sketch and save it as a PNG.

    Generated by JXP and Claude.

    Parameters
    ----------
    outpath : str, optional
        Destination PNG path.  If None, writes ``dashboard_calibrations.png`` to
        the directory *above* this script (``pypeitdev/dashboard/``).

    Returns
    -------
    str
        The absolute path of the written PNG.
    """
    if outpath is None:
        here = os.path.dirname(os.path.abspath(__file__))
        parent = os.path.dirname(here)
        outpath = os.path.join(parent, 'images', 'dashboard_calibrations.png')

    fig, ax = plt.subplots(figsize=(11.5, 9.6), dpi=140)
    ax.add_patch(Rectangle((0, 0), 100, 100, facecolor='#FFFFFF',
                           edgecolor='#90A4AE', linewidth=1.5))

    draw_tab_bar(ax, active='calibrations')
    draw_logo(ax)
    draw_header(ax)
    draw_scope_toolbar(ax, y0=83.5, include_filter=False)
    after_buttons = _draw_step_buttons(ax, top_y=80.5)
    _draw_detail_panel(ax, top_y=after_buttons - 0.5)
    draw_color_key(ax, y=6.5)

    ax.text(50, 2.0, 'PypeIt Dashboard — Calibrations View (layout sketch; '
            'example: shane_kast_blue 600/4310, wv_calib selected)',
            ha='center', fontsize=8.5, color='#90A4AE', style='italic')

    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off')  # larger y at top matches the top-down layout
    fig.subplots_adjust(left=0.01, right=0.99, top=0.99, bottom=0.01)
    fig.savefig(outpath, dpi=140)
    plt.close(fig)
    return outpath


if __name__ == '__main__':
    path = make_calibrations_sketch()
    print('Wrote: {0}'.format(path))
