"""
Layout-check harness for the PypeIt Dashboard (Stage 0 slice).

This imports the **real** ``pypeit.dashboard`` widgets (it does not mock or
re-implement them), builds the main window with representative example data
(the ``shane_kast_blue`` 600/4310 dataset), and grabs it offscreen to PNGs
across the light/dark x default/resized matrix described in
``pypeit_dashboard_coding.md`` (*Checking and modifying the layout*).

It is **design-phase tooling**, not shipped production code, so it lives in
``pypeitdev/dashboard/py/`` beside the matplotlib sketches.

Run (headless)::

    QT_QPA_PLATFORM=offscreen python dashboard_layout_check.py \\
        [--pypeit_file PATH] [--outdir DIR]

Generated by JXP and Claude.
"""

import os
# Force the offscreen Qt platform before any Qt import, so the harness runs
# without a display (mirrors source_headless_test.sh).
os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')

import sys
import shutil
import tempfile
import argparse
from pathlib import Path

from qtpy.QtWidgets import QApplication
from qtpy.QtGui import QPalette, QColor
from qtpy.QtCore import Qt

from pypeit.dashboard.model import DashboardModel
from pypeit.dashboard.view.main_window import DashboardMainWindow

# The committed CI-safe fixtures in the main repo (minimal .pypeit + the
# synthesized *_state.json cases).  The harness stages these into a temp
# reduction directory so the Status view renders populated, real widgets.
_TESTS_FILES = (Path(__file__).resolve().parents[4]
                / 'PypeIt' / 'pypeit' / 'tests' / 'files')
_FIXTURE_CASES = ('healthy', 'failed', 'not_started')

# The render matrix: (label, (width, height)).
_SIZES = (('default', (1650, 900)), ('resized', (1100, 700)))


def make_dark_palette():
    """
    Build a Qt Fusion-style dark palette for the dark-theme render (S0-Q8).

    Generated by JXP and Claude.

    Returns:
        `QPalette`_: A dark color palette.
    """
    palette = QPalette()
    dark = QColor(53, 53, 53)
    base = QColor(35, 35, 35)
    text = QColor(220, 220, 220)
    palette.setColor(QPalette.Window, dark)
    palette.setColor(QPalette.WindowText, text)
    palette.setColor(QPalette.Base, base)
    palette.setColor(QPalette.AlternateBase, dark)
    palette.setColor(QPalette.Text, text)
    palette.setColor(QPalette.Button, dark)
    palette.setColor(QPalette.ButtonText, text)
    palette.setColor(QPalette.ToolTipBase, base)
    palette.setColor(QPalette.ToolTipText, text)
    palette.setColor(QPalette.Highlight, QColor(38, 79, 120))
    palette.setColor(QPalette.HighlightedText, Qt.white)
    return palette


def stage_model(case, tmpdir):
    """
    Stage a reduction directory from the committed fixtures and build a
    :class:`DashboardModel` for it (load path; no RAW_DATA, no derive).

    Generated by JXP and Claude.

    Args:
        case (:obj:`str`):
            Fixture case name (e.g. ``healthy``); ``None`` stages no state
            file (a true "not started, no file" case).
        tmpdir (`pathlib.Path`_):
            Directory to stage into.

    Returns:
        :class:`DashboardModel`: The model for the staged reduction.
    """
    pf = tmpdir / 'shane_kast_blue_A.pypeit'
    pf.write_text((_TESTS_FILES / 'dashboard_shane_kast_blue.pypeit')
                  .read_text())
    if case is not None:
        (tmpdir / 'shane_kast_blue_A_state.json').write_text(
            (_TESTS_FILES / f'dashboard_state_{case}.json').read_text())
    return DashboardModel(str(pf), derive=False)


def render_matrix(outdir):
    """
    Render the Status view across fixture-case x theme x size to PNGs.

    Generated by JXP and Claude.

    Args:
        outdir (:obj:`str`, `pathlib.Path`_):
            Directory into which the PNGs are written.

    Returns:
        list: The list of written PNG paths (as :obj:`str`).
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    app = QApplication.instance() or QApplication(sys.argv)
    app.setStyle('Fusion')
    light_palette = app.palette()
    dark_palette = make_dark_palette()
    written = []

    for case in _FIXTURE_CASES:
        for theme, palette in (('light', light_palette),
                               ('dark', dark_palette)):
            # Apply the theme palette before building the window so child
            # widgets inherit it (StatusView detects light/dark from it).
            app.setPalette(palette)
            for size_label, (width, height) in _SIZES:
                tmpdir = Path(tempfile.mkdtemp())
                try:
                    model = stage_model(case, tmpdir)
                    window = DashboardMainWindow(model)
                    window.resize(width, height)
                    app.processEvents()
                    out = (outdir /
                           f'dashboard_status_{case}_{theme}_'
                           f'{size_label}.png')
                    window.grab().save(str(out))
                    written.append(str(out))
                    print(f'wrote {out}')
                finally:
                    shutil.rmtree(tmpdir, ignore_errors=True)
    # Restore the light palette to avoid leaking state if reused.
    app.setPalette(light_palette)
    return written


def parse_args(options=None):
    """
    Parse command-line arguments for the harness.

    Generated by JXP and Claude.

    Args:
        options (:obj:`list`, optional):
            Argument list to parse (defaults to ``sys.argv``).

    Returns:
        `argparse.Namespace`_: The parsed arguments.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--outdir', type=str,
                        default=str(Path(__file__).parent / 'layout_check'),
                        help='Directory for the rendered PNGs.')
    return parser.parse_args(options)


def main():
    """
    Harness entry point: render the matrix and report the outputs.

    Generated by JXP and Claude.

    Returns:
        int: Process exit code (0 on success).
    """
    args = parse_args()
    render_matrix(args.outdir)
    return 0


if __name__ == '__main__':
    sys.exit(main())
