"""
Sketch (mock-up) of the PypeIt Dashboard **Status View**.

Generated by JXP and Claude.

Purpose
-------
This is a *non-functional* layout sketch, not production code.  It renders a
static PNG that shows the proposed look of the Dashboard's default "Status View"
as specified in the Initialization section of
``pypeitdev/dashboard/pypeit_dashboard_design.md``.  The intent is to give us
something concrete to react to before building the real PyQt6 widget.

Design notes (the "thinking", so this is easy to modify)
--------------------------------------------------------
The Status View is the landing page and answers "where does this reduction
stand?".  The sketch lays it out top-to-bottom as:

  1. A **tab bar** (Status | Calibrations) -- the Status tab is active here.
  2. A **header banner** with the run context + the PypeIt logo.  [R6]
  3. A **summary strip** (global health across the whole run).  [R7]
  4. A **scope toolbar**: drop-downs to pick the calibration group and the
     detector/mosaic, plus a filter and a refresh button.  [R12, R16]
  5. A compact **configuration-overview navigator**: a small (group x detector)
     grid, each cell colored by its worst step status.  [R17]
  6. A **Calibrations** section: the per-step status table for the *selected*
     (group, detector).  Columns Step | Required | Status | Output.  [R3, R8,
     R9, R10]
  7. A **Science frames** section, given equal prominence.  [R15, R18]
  8. A **color key** for the Dashboard-wide status palette.  [R10]

Shared drawing helpers (palette, status pills, tab bar, header+logo, scope
toolbar, color key) live in ``utils.py`` and are imported here (reuse, design
principle #2).

Example content mirrors the *real* outputs of the Shane Kast blue 600/4310
reduction (calib group 0, DET01; ``dark`` and ``scattlight`` optional/undone;
three science/standard frames with spec2d + spec1d written).  ``bpm`` is an
internal step with no output and is not shown.

Drawing approach: Matplotlib patches + text on a 0..100 x 0..100 canvas; larger
y at the top (no y-inversion).  No interactivity; this is purely a picture.

Inputs / Outputs
----------------
Inputs : none (the example state is hard-coded below).
Outputs: writes ``dashboard_status_view.png`` to the directory *above* this
         script (i.e. ``pypeitdev/dashboard/``) and returns its path.
"""

import os
from matplotlib import pyplot as plt
from matplotlib.patches import Rectangle

import utils
from utils import (PALETTE, status_text_color, draw_status_pill, draw_tab_bar,
                   draw_header, draw_logo, draw_scope_toolbar, draw_color_key)


# --- Example state, mirroring the real shane_kast_blue_A reduction -----------
# Calibration steps: (step_label, required, status_key, output_file).  Order =
# MultiSlit/Echelle processing order from default_steps(), minus hidden 'bpm'.
EXAMPLE_STEPS = [
    ('bias',       True,  'success',      'Bias_A_0_DET01.fits'),
    ('dark',       False, 'not_required', '--'),
    ('slits',      True,  'success',      'Slits_A_0_DET01.fits.gz'),
    ('arc',        True,  'success',      'Arc_A_0_DET01.fits'),
    ('tiltimg',    True,  'success',      'Tiltimg_A_0_DET01.fits'),
    ('wv_calib',   True,  'success',      'WaveCalib_A_0_DET01.fits'),
    ('tilts',      True,  'success',      'Tilts_A_0_DET01.fits'),
    ('scattlight', False, 'not_required', '--'),
    ('flats',      True,  'success',      'Flat_A_0_DET01.fits'),
]

# Science frames: (frame, type, overall_status, spec2d_status, spec1d_status).
EXAMPLE_SCIENCE = [
    ('b24-Feige66',    'standard', 'success', 'success', 'success'),
    ('b27-J1217p3905', 'science',  'success', 'success', 'success'),
    ('b28-J1217p3905', 'science',  'success', 'success', 'success'),
]

# Column x-edges in the 0..100 data space for the Calibrations table.
CAL_COLS = {
    'step':     (4, 26),
    'required': (26, 40),
    'status':   (40, 62),
    'output':   (62, 98),
}
# Column x-edges for the Science table.
SCI_COLS = {
    'frame':  (4, 28),
    'type':   (28, 42),
    'status': (42, 62),
    'spec2d': (62, 78),
    'spec1d': (78, 94),
}


def _draw_summary(ax):
    """
    Draw the global at-a-glance summary strip.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.

    Returns
    -------
    None
    """
    ax.add_patch(Rectangle((4, 84.0), 94, 3.4, facecolor='#F1F8E9',
                           edgecolor='#C5E1A5'))
    ax.text(5.5, 85.7, 'Run summary:   Calibrations 7/7 required ✓     '
            '3/3 science frames reduced ✓     0 ✗ fail     0 ▶ running',
            color='#33691E', fontsize=9.5, va='center', fontweight='bold')


def _aggregate_color(statuses):
    """
    Pick the "worst" status key for an overview cell.

    Generated by JXP and Claude.

    Parameters
    ----------
    statuses : list of str
        Status keys for the steps in a (group, detector) cell.

    Returns
    -------
    str
        A key into :data:`utils.PALETTE` (fail > running > required_undone >
        success).
    """
    for worst in ('fail', 'running', 'required_undone'):
        if worst in statuses:
            return worst
    return 'success'


def _draw_overview_grid(ax):
    """
    Draw the compact (group x detector) configuration-overview navigator.

    Generated by JXP and Claude.

    Each cell is colored by the worst step status for that (group, detector).
    For instruments with many groups/detectors this becomes a small heat-map
    and a click-to-scope navigator; here the Kast example is a single 1x1 cell.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.

    Returns
    -------
    float
        The y just below the overview block.
    """
    top = 78.4
    ax.text(4, top - 0.6, 'Configuration overview (group × detector):',
            fontsize=9, fontweight='bold', color='#37474F', va='center')
    groups = ['0']
    dets = ['DET01']
    cell = {('0', 'DET01'): _aggregate_color([s[2] for s in EXAMPLE_STEPS])}
    cx0, cy0, cw, ch = 8, top - 3.6, 7.0, 2.2
    for j, d in enumerate(dets):
        ax.text(cx0 + j * (cw + 1) + cw / 2, top - 1.9, d, ha='center',
                fontsize=7.5, color='#546E7A')
    for i, g in enumerate(groups):
        ax.text(cx0 - 1.0, cy0 + ch / 2 - i * (ch + 0.6), 'grp ' + g,
                ha='right', va='center', fontsize=7.5, color='#546E7A')
        for j, d in enumerate(dets):
            key = cell[(g, d)]
            fill, edge, glyph, _label = PALETTE[key]
            x = cx0 + j * (cw + 1)
            y = cy0 - i * (ch + 0.6)
            ax.add_patch(Rectangle((x, y), cw, ch, facecolor=fill,
                                   edgecolor=edge))
            ax.text(x + cw / 2, y + ch / 2, glyph, ha='center', va='center',
                    fontsize=9, color=status_text_color(key))
    ax.text(20, top - 2.6, 'click a cell to scope the tables below  •  '
            'scales to many groups/detectors without stacking everything',
            fontsize=8, color='#90A4AE', va='center', style='italic')
    return cy0 - 1.0


def _section_heading(ax, y, text):
    """
    Draw a prominent section heading bar.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    y : float
        Top edge (data coords) of the heading bar.
    text : str
        Heading text.

    Returns
    -------
    float
        The y just below the heading bar.
    """
    ax.add_patch(Rectangle((4, y - 3.0), 94, 3.0, facecolor='#37474F',
                           edgecolor='#37474F'))
    ax.text(5.5, y - 1.5, text, fontsize=11, fontweight='bold', color='white',
            va='center')
    return y - 3.0


def _draw_calib_section(ax, top_y):
    """
    Draw the Calibrations section (heading + column headers + step rows).

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    top_y : float
        Top edge (data coords) of the section.

    Returns
    -------
    float
        The y just below the section.
    """
    y = _section_heading(ax, top_y, 'Calibrations  —  Group 0 · DET01')
    hdr = {'step': 'Step', 'required': 'Required', 'status': 'Status',
           'output': 'Output file'}
    for key, (x0, _x1) in CAL_COLS.items():
        ax.text(x0 + 0.6, y - 1.3, hdr[key], fontsize=9, fontweight='bold',
                color='#37474F', va='center')
    y -= 2.4
    row_h = 2.3
    for i, (label, required, status_key, output) in enumerate(EXAMPLE_STEPS):
        y0 = y - row_h
        if i % 2 == 0:
            ax.add_patch(Rectangle((4, y0), 94, row_h, facecolor='#FAFAFA',
                                   edgecolor='none'))
        yc = y0 + row_h / 2.0
        ax.text(CAL_COLS['step'][0] + 0.6, yc, label, va='center',
                fontsize=9.5, family='monospace', color='#212121')
        req_txt = 'required' if required else 'optional'
        req_col = '#37474F' if required else '#9E9E9E'
        ax.text(CAL_COLS['required'][0] + 0.6, yc, req_txt, va='center',
                fontsize=9, color=req_col)
        draw_status_pill(ax, CAL_COLS['status'][0], yc, status_key)
        ax.text(CAL_COLS['output'][0] + 0.6, yc, output, va='center',
                fontsize=8, family='monospace', color='#455A64')
        y = y0
    ax.add_patch(Rectangle((4, y), 94, top_y - 3.0 - y, facecolor='none',
                           edgecolor='#B0BEC5', linewidth=1.0))
    return y


def _draw_science_section(ax, top_y):
    """
    Draw the Science frames section, given equal prominence to Calibrations.

    Generated by JXP and Claude.

    Columns: Frame | Type | Status | spec2d | spec1d.  Per-frame *step* status
    (object finding / extraction) will populate as ``state.py`` is extended
    (R15); for now the example shows the products that were produced.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    top_y : float
        Top edge (data coords) of the section.

    Returns
    -------
    float
        The y just below the section.
    """
    y = _section_heading(ax, top_y, 'Science frames  —  Group 0 · DET01')
    hdr = {'frame': 'Frame', 'type': 'Type', 'status': 'Status',
           'spec2d': 'spec2d', 'spec1d': 'spec1d'}
    for key, (x0, _x1) in SCI_COLS.items():
        ax.text(x0 + 0.6, y - 1.3, hdr[key], fontsize=9, fontweight='bold',
                color='#37474F', va='center')
    y -= 2.4
    row_h = 2.3
    for i, (frame, ftype, stat, s2d, s1d) in enumerate(EXAMPLE_SCIENCE):
        y0 = y - row_h
        if i % 2 == 0:
            ax.add_patch(Rectangle((4, y0), 94, row_h, facecolor='#FAFAFA',
                                   edgecolor='none'))
        yc = y0 + row_h / 2.0
        ax.text(SCI_COLS['frame'][0] + 0.6, yc, frame, va='center',
                fontsize=9.5, family='monospace', color='#212121')
        ax.text(SCI_COLS['type'][0] + 0.6, yc, ftype, va='center', fontsize=9,
                color='#37474F')
        draw_status_pill(ax, SCI_COLS['status'][0], yc, stat)
        draw_status_pill(ax, SCI_COLS['spec2d'][0], yc, s2d, width=10)
        draw_status_pill(ax, SCI_COLS['spec1d'][0], yc, s1d, width=10)
        y = y0
    ax.add_patch(Rectangle((4, y), 94, top_y - 3.0 - y, facecolor='none',
                           edgecolor='#B0BEC5', linewidth=1.0))
    ax.text(5.5, y - 1.4, 'per-frame object-finding / extraction status will '
            'populate as state.py tracks it (R15);  long lists scroll & filter '
            '(R19)', fontsize=8, color='#90A4AE', va='center', style='italic')
    return y - 2.6


def make_status_view_sketch(outpath=None):
    """
    Build the Status View sketch and save it as a PNG.

    Generated by JXP and Claude.

    Parameters
    ----------
    outpath : str, optional
        Destination PNG path.  If None, writes ``dashboard_status_view.png`` to
        the directory *above* this script (``pypeitdev/dashboard/``).

    Returns
    -------
    str
        The absolute path of the written PNG.
    """
    if outpath is None:
        here = os.path.dirname(os.path.abspath(__file__))
        parent = os.path.dirname(here)
        outpath = os.path.join(parent, 'images', 'dashboard_status_view.png')

    fig, ax = plt.subplots(figsize=(11.5, 9.6), dpi=140)
    ax.add_patch(Rectangle((0, 0), 100, 100, facecolor='#FFFFFF',
                           edgecolor='#90A4AE', linewidth=1.5))

    draw_tab_bar(ax, active='status')
    draw_logo(ax)
    draw_header(ax)
    _draw_summary(ax)
    draw_scope_toolbar(ax, y0=80.0, include_filter=True)
    after_grid = _draw_overview_grid(ax)

    bottom = _draw_calib_section(ax, top_y=after_grid - 1.0)
    bottom = _draw_science_section(ax, top_y=bottom - 2.0)
    draw_color_key(ax, y=bottom - 2.5)

    ax.text(50, 1.4, 'PypeIt Dashboard — Status View (layout sketch; '
            'example data: shane_kast_blue 600/4310)', ha='center',
            fontsize=8.5, color='#90A4AE', style='italic')

    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off')  # larger y at top matches the top-down layout
    fig.subplots_adjust(left=0.01, right=0.99, top=0.99, bottom=0.01)
    fig.savefig(outpath, dpi=140)
    plt.close(fig)
    return outpath


if __name__ == '__main__':
    path = make_status_view_sketch()
    print('Wrote: {0}'.format(path))
