"""
Layout-check harness for the PypeIt Dashboard (Stage 0 slice).

This imports the **real** ``pypeit.dashboard`` widgets (it does not mock or
re-implement them), builds the main window with representative example data
(the ``shane_kast_blue`` 600/4310 dataset), and grabs it offscreen to PNGs
across the light/dark x default/resized matrix described in
``pypeit_dashboard_coding.md`` (*Checking and modifying the layout*).

It is **design-phase tooling**, not shipped production code, so it lives in
``pypeitdev/dashboard/py/`` beside the matplotlib sketches.

Run (headless)::

    QT_QPA_PLATFORM=offscreen python dashboard_layout_check.py \\
        [--pypeit_file PATH] [--outdir DIR]

Generated by JXP and Claude.
"""

import os
# Force the offscreen Qt platform before any Qt import, so the harness runs
# without a display (mirrors source_headless_test.sh).
os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')

import sys
import argparse
from pathlib import Path

from qtpy.QtWidgets import QApplication
from qtpy.QtGui import QPalette, QColor
from qtpy.QtCore import Qt

from pypeit.dashboard.model import read_header_info
from pypeit.dashboard.view.main_window import DashboardMainWindow

# Default example dataset: the shane_kast_blue 600/4310 reduction in the dev
# suite (the same one behind the design sketches and the workflow example).
_DEFAULT_PYPEIT_FILE = (
    'REDUX_OUT/shane_kast_blue/600_4310_d55/shane_kast_blue_A/'
    'shane_kast_blue_A.pypeit')

# The render matrix: (label, (width, height)).
_SIZES = (('default', (1650, 900)), ('resized', (1100, 700)))


def default_pypeit_file():
    """
    Return the path to the default example ``.pypeit`` file, resolved
    against ``$PYPEIT_DEV`` when set.

    Generated by JXP and Claude.

    Returns:
        str: The path to the example ``.pypeit`` file.
    """
    dev = os.environ.get('PYPEIT_DEV')
    if dev is not None:
        return str(Path(dev) / _DEFAULT_PYPEIT_FILE)
    return _DEFAULT_PYPEIT_FILE


def make_dark_palette():
    """
    Build a Qt Fusion-style dark palette for the dark-theme render (S0-Q8).

    Generated by JXP and Claude.

    Returns:
        `QPalette`_: A dark color palette.
    """
    palette = QPalette()
    dark = QColor(53, 53, 53)
    base = QColor(35, 35, 35)
    text = QColor(220, 220, 220)
    palette.setColor(QPalette.Window, dark)
    palette.setColor(QPalette.WindowText, text)
    palette.setColor(QPalette.Base, base)
    palette.setColor(QPalette.AlternateBase, dark)
    palette.setColor(QPalette.Text, text)
    palette.setColor(QPalette.Button, dark)
    palette.setColor(QPalette.ButtonText, text)
    palette.setColor(QPalette.ToolTipBase, base)
    palette.setColor(QPalette.ToolTipText, text)
    palette.setColor(QPalette.Highlight, QColor(38, 79, 120))
    palette.setColor(QPalette.HighlightedText, Qt.white)
    return palette


def render_matrix(pypeit_file, outdir):
    """
    Render the main window across the theme x size matrix to PNGs.

    Generated by JXP and Claude.

    Args:
        pypeit_file (:obj:`str`):
            Path to the example ``.pypeit`` file used as data.
        outdir (:obj:`str`, `pathlib.Path`_):
            Directory into which the PNGs are written.

    Returns:
        list: The list of written PNG paths (as :obj:`str`).
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    app = QApplication.instance() or QApplication(sys.argv)
    app.setStyle('Fusion')
    light_palette = app.palette()
    dark_palette = make_dark_palette()

    header_info = read_header_info(pypeit_file)
    written = []

    for theme, palette in (('light', light_palette),
                           ('dark', dark_palette)):
        # Apply the theme palette before building the window so child
        # widgets inherit it.
        app.setPalette(palette)
        for size_label, (width, height) in _SIZES:
            window = DashboardMainWindow(header_info)
            window.resize(width, height)
            # Process pending events so the layout settles before grabbing.
            app.processEvents()
            out = outdir / f'dashboard_main_{theme}_{size_label}.png'
            window.grab().save(str(out))
            written.append(str(out))
            print(f'wrote {out}')
    # Restore the light palette to avoid leaking state if reused.
    app.setPalette(light_palette)
    return written


def parse_args(options=None):
    """
    Parse command-line arguments for the harness.

    Generated by JXP and Claude.

    Args:
        options (:obj:`list`, optional):
            Argument list to parse (defaults to ``sys.argv``).

    Returns:
        `argparse.Namespace`_: The parsed arguments.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--pypeit_file', type=str,
                        default=default_pypeit_file(),
                        help='Example .pypeit file to render.')
    parser.add_argument('--outdir', type=str,
                        default=str(Path(__file__).parent / 'layout_check'),
                        help='Directory for the rendered PNGs.')
    return parser.parse_args(options)


def main():
    """
    Harness entry point: render the matrix and report the outputs.

    Generated by JXP and Claude.

    Returns:
        int: Process exit code (0 on success).
    """
    args = parse_args()
    render_matrix(args.pypeit_file, args.outdir)
    return 0


if __name__ == '__main__':
    sys.exit(main())
