"""
Generate the dashboard's ``*_state.json`` test fixtures.

These are small, deterministic ``RunPypeItState`` JSON files used by the
CI-safe headless tests of ``pypeit.dashboard.model`` (Stage 1).  They are
**synthesized via the current `RunPypeItState` model** (not copied from a
real reduction) so they always validate against the current schema and need
no RAW_DATA.  They model a ``shane_kast_blue`` 600/4310 long-slit reduction
(one calibration group ``0``, one detector ``DET01``, one slit ``175``).

Run::

    python make_state_fixtures.py [--outdir DIR]

(defaults to ``PypeIt/pypeit/tests/files``).

Generated by JXP and Claude.
"""

import argparse
from pathlib import Path

from pypeit.state import (RunPypeItState, BiasCalibState, ArcCalibState,
                          TiltImgCalibState, SlitEdgesState, WvCalibState,
                          TiltsState, FlatsState, DarkCalibState,
                          ScattLightCalibState, SlitEdges, WvCalibSlit,
                          TiltsSlit, FlatsSlit, FlatCorrectionMetric)

# Default output: the main-repo CI-safe test files directory.
_DEFAULT_OUTDIR = (Path(__file__).resolve().parents[4]
                   / 'PypeIt' / 'pypeit' / 'tests' / 'files')

CALIB = 0
DET = 1
SLIT = 175
BIAS_FILES = [f'b{n}.fits.gz' for n in range(14, 24)]
ARC_FILES = ['b1.fits.gz']
FLAT_FILES = [f'b{n}.fits.gz' for n in range(3, 14)]


def _base(pypeit_file='shane_kast_blue_A.pypeit', current_step='flats',
          previous_step='scattlight'):
    """
    Build a ``RunPypeItState`` with the required scalar fields set.

    Generated by JXP and Claude.

    Args:
        pypeit_file (:obj:`str`): The reduction file name.
        current_step (:obj:`str`): The ``current_step`` field value.
        previous_step (:obj:`str`): The ``previous_step`` field value.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: A state with no calib entries.
    """
    return RunPypeItState(pypeit_file=pypeit_file, current_step=current_step,
                          current_det=DET, current_calibID=CALIB,
                          previous_step=previous_step)


def healthy_state():
    """
    A fully successful long-slit calibration state.

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: The healthy state.
    """
    st = _base()
    st.bias = [BiasCalibState(calib_id=CALIB, det=DET, required=True,
                              status='success', input_files=BIAS_FILES,
                              output_file='Bias_A_0_DET01.fits',
                              mean=1024.3, std=3.7)]
    st.arc = [ArcCalibState(calib_id=CALIB, det=DET, required=True,
                            status='success', input_files=ARC_FILES,
                            output_file='Arc_A_0_DET01.fits')]
    st.tiltimg = [TiltImgCalibState(calib_id=CALIB, det=DET, required=True,
                                    status='success', input_files=ARC_FILES,
                                    output_file='Tiltimg_A_0_DET01.fits')]
    st.slits = [SlitEdgesState(calib_id=CALIB, det=DET, required=True,
                               status='success', input_files=FLAT_FILES,
                               output_file='Slits_A_0_DET01.fits.gz',
                               nslits=1,
                               slits={SLIT: SlitEdges(status='success',
                                                      center=512.0,
                                                      slitord_id=SLIT)})]
    st.wv_calib = [WvCalibState(calib_id=CALIB, det=DET, required=True,
                                status='success', input_files=ARC_FILES,
                                output_file='WaveCalib_A_0_DET01.fits',
                                slits={SLIT: WvCalibSlit(status='success',
                                                         rms=0.074)})]
    st.tilts = [TiltsState(calib_id=CALIB, det=DET, required=True,
                           status='success', input_files=ARC_FILES,
                           output_file='Tilts_A_0_DET01.fits.gz',
                           slits={SLIT: TiltsSlit(status='success',
                                                  rms=0.019)})]
    st.flats = [FlatsState(calib_id=CALIB, det=DET, required=True,
                           status='success', input_files=FLAT_FILES,
                           output_file='Flat_A_0_DET01.fits',
                           types=['pixelflat', 'illumflat'])]
    # Optional steps that were not run (and not required).
    st.dark = [DarkCalibState(calib_id=CALIB, det=DET, required=False,
                              status='undone')]
    st.scattlight = [ScattLightCalibState(calib_id=CALIB, det=DET,
                                          required=False, status='undone')]
    return st


def not_started_state():
    """
    A valid state with no calibration entries ("not started").

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: The empty state.
    """
    return _base(current_step='none', previous_step='none')


def partial_state():
    """
    A partially completed state: early steps done, later ones required but
    still undone.

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: The partial state.
    """
    st = _base(current_step='slits', previous_step='tiltimg')
    st.bias = [BiasCalibState(calib_id=CALIB, det=DET, required=True,
                              status='success', input_files=BIAS_FILES,
                              output_file='Bias_A_0_DET01.fits',
                              mean=1024.3, std=3.7)]
    st.arc = [ArcCalibState(calib_id=CALIB, det=DET, required=True,
                            status='success', input_files=ARC_FILES,
                            output_file='Arc_A_0_DET01.fits')]
    st.slits = [SlitEdgesState(calib_id=CALIB, det=DET, required=True,
                               status='success', input_files=FLAT_FILES,
                               output_file='Slits_A_0_DET01.fits.gz',
                               nslits=1)]
    # Required-but-not-yet-generated downstream steps.
    st.wv_calib = [WvCalibState(calib_id=CALIB, det=DET, required=True,
                                status='undone')]
    st.tilts = [TiltsState(calib_id=CALIB, det=DET, required=True,
                           status='undone')]
    st.flats = [FlatsState(calib_id=CALIB, det=DET, required=True,
                           status='undone')]
    return st


def failed_state():
    """
    A state with one failed step (``wv_calib``).

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: The failed-step state.
    """
    st = partial_state()
    st.current_step = 'wv_calib'
    st.wv_calib = [WvCalibState(calib_id=CALIB, det=DET, required=True,
                                status='fail', input_files=ARC_FILES)]
    return st


def multidet_state():
    """
    A multi-slit, multi-detector state (2 detectors, several slits each)
    with **flats per-slit per-correction** metrics and a ``skip`` slit, for
    the CI-safe Calibrations-view tests (S3-Q11/Q14/Q15/Q16).

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: The multi-detector state.
    """
    st = RunPypeItState(pypeit_file='shane_kast_blue_A.pypeit',
                        current_step='flats', current_det=2,
                        current_calibID=0, previous_step='scattlight')
    slit_ids = [10, 20, 30]
    corrections = ['pixelflat', 'spat_illum']
    for det in (1, 2):
        st.bias.append(BiasCalibState(calib_id=0, det=det, required=True,
                                      status='success', mean=1000.0 + det,
                                      std=3.0,
                                      output_file=f'Bias_A_0_DET0{det}.fits'))
        st.arc.append(ArcCalibState(calib_id=0, det=det, required=True,
                                    status='success',
                                    output_file=f'Arc_A_0_DET0{det}.fits'))
        st.tiltimg.append(TiltImgCalibState(
            calib_id=0, det=det, required=True, status='success',
            output_file=f'Tiltimg_A_0_DET0{det}.fits'))
        st.slits.append(SlitEdgesState(
            calib_id=0, det=det, required=True, status='success',
            nslits=len(slit_ids),
            output_file=f'Slits_A_0_DET0{det}.fits.gz',
            slits={s: SlitEdges(status='success', center=100.0 * s,
                                slitord_id=s) for s in slit_ids}))
        st.wv_calib.append(WvCalibState(
            calib_id=0, det=det, required=True, status='success',
            output_file=f'WaveCalib_A_0_DET0{det}.fits',
            slits={s: WvCalibSlit(status='success', rms=0.05 + 0.001 * s)
                   for s in slit_ids}))
        st.tilts.append(TiltsState(
            calib_id=0, det=det, required=True, status='success',
            output_file=f'Tilts_A_0_DET0{det}.fits.gz',
            slits={s: TiltsSlit(status='success', rms=0.02 + 0.001 * s)
                   for s in slit_ids}))
        # Flats: per-slit per-correction metrics; the last slit is skipped.
        flat_slits = {}
        for i, s in enumerate(slit_ids):
            status = 'skip' if i == len(slit_ids) - 1 else 'success'
            flat_slits[s] = FlatsSlit(
                status=status,
                corrections={
                    c: FlatCorrectionMetric(mean=1.0 + 0.01 * i,
                                            rms=0.03 + 0.001 * i)
                    for c in corrections})
        st.flats.append(FlatsState(
            calib_id=0, det=det, required=True, status='success',
            output_file=f'Flat_A_0_DET0{det}.fits',
            corrections=corrections, pixelflat_source='raw',
            pixelflat_files=[f'b{n}.fits.gz' for n in range(3, 8)],
            illumflat_files=[f'b{n}.fits.gz' for n in range(8, 11)],
            input_files=[f'b{n}.fits.gz' for n in range(3, 11)],
            slits=flat_slits))
    return st


def echelle_state():
    """
    A fixed-format **echelle** state (keck_nires-like): one detector, one
    calibration group, several spectral **orders**, with the shared
    calibrations named ``*_all_*`` (slits/flats) as PypeIt does for echelle.
    Used by the CI-safe per-order rendering tests (S3b-Q4).

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.state.RunPypeItState`: The echelle state.
    """
    st = RunPypeItState(pypeit_file='keck_nires_A.pypeit',
                        current_step='flats', current_det=1,
                        current_calibID=0, previous_step='tilts')
    orders = [3, 4, 5, 6, 7]
    st.arc = [ArcCalibState(calib_id=0, det=1, required=True,
                            status='success',
                            output_file='Arc_A_0_DET01.fits')]
    st.tiltimg = [TiltImgCalibState(calib_id=0, det=1, required=True,
                                    status='success',
                                    output_file='Tiltimg_A_0_DET01.fits')]
    # Shared (across-group) calibrations are named *_all_* for echelle.
    st.slits = [SlitEdgesState(calib_id=0, det=1, required=True,
                               status='success', nslits=len(orders),
                               output_file='Slits_A_all_DET01.fits.gz',
                               slits={o: SlitEdges(status='success',
                                                   center=512.0,
                                                   slitord_id=o)
                                      for o in orders})]
    st.wv_calib = [WvCalibState(calib_id=0, det=1, required=True,
                                status='success',
                                output_file='WaveCalib_A_0_DET01.fits',
                                slits={o: WvCalibSlit(status='success',
                                                      rms=0.05 + 0.005 * o)
                                       for o in orders})]
    st.tilts = [TiltsState(calib_id=0, det=1, required=True, status='success',
                           output_file='Tilts_A_0_DET01.fits',
                           slits={o: TiltsSlit(status='success',
                                               rms=0.02 + 0.002 * o)
                                  for o in orders})]
    st.flats = [FlatsState(calib_id=0, det=1, required=True, status='success',
                           output_file='Flat_A_all_DET01.fits',
                           corrections=['pixelflat', 'spat_illum'],
                           pixelflat_source='raw',
                           slits={o: FlatsSlit(
                               status='success',
                               corrections={'pixelflat': FlatCorrectionMetric(
                                   mean=1.0, rms=0.03)}) for o in orders})]
    return st


def write_fixtures(outdir):
    """
    Write all fixtures (healthy, not-started, partial, failed, malformed).

    Generated by JXP and Claude.

    Args:
        outdir (:obj:`str`, `pathlib.Path`_):
            Directory to write the fixtures into.

    Returns:
        list: The written file paths (as :obj:`str`).
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    written = []

    cases = {
        'dashboard_state_healthy.json': healthy_state(),
        'dashboard_state_not_started.json': not_started_state(),
        'dashboard_state_partial.json': partial_state(),
        'dashboard_state_failed.json': failed_state(),
        'dashboard_state_multidet.json': multidet_state(),
        'dashboard_state_echelle.json': echelle_state(),
    }
    for name, state in cases.items():
        path = outdir / name
        # round_trip + exclude_none mirrors RunPypeItState.write().
        text = state.model_dump_json(exclude_none=True, indent=4,
                                     round_trip=True)
        path.write_text(text)
        written.append(str(path))

    # A deliberately malformed (truncated, invalid JSON) state file (R11).
    bad = outdir / 'dashboard_state_malformed.json'
    bad.write_text('{ "pypeit_file": "shane_kast_blue_A.pypeit", '
                   '"current_step": ')  # truncated on purpose
    written.append(str(bad))

    for w in written:
        print(f'wrote {w}')
    return written


def main():
    """
    Entry point: parse args and write the fixtures.

    Generated by JXP and Claude.

    Returns:
        int: Process exit code (0 on success).
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--outdir', type=str, default=str(_DEFAULT_OUTDIR),
                        help='Directory for the fixture JSON files.')
    args = parser.parse_args()
    write_fixtures(args.outdir)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
