"""
Shared helpers for the PypeIt Dashboard layout **sketches**.

Generated by JXP and Claude.

Purpose
-------
The Status-view and Calibrations-view sketch modules
(``dashboard_status_view.py`` and ``dashboard_calibrations.py``) share a lot of
drawing code: the unified status palette, status "pills", the tab bar, the
header banner (with the PypeIt logo), the scope toolbar, the color key, and
small action chips.  To avoid duplication (design principle #2, "reuse, don't
reinvent") those common pieces live here and are imported by both sketches.

These are mock-up helpers, not production widgets; they draw onto a Matplotlib
axis whose data coordinates run 0..100 in x and y, with larger y at the top.

Inputs / Outputs
----------------
This module defines constants and drawing helpers; it writes nothing on import.
Each helper draws onto a provided ``matplotlib.axes.Axes`` and returns ``None``
unless noted.
"""

import os
from matplotlib.patches import Rectangle, FancyBboxPatch
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
import matplotlib.image as mpimg


# --- Dashboard-wide status palette (unified; see design doc R10) -------------
# Each status maps to (fill_color, edge_color, glyph, label).  "required_undone"
# is white so it needs a visible edge; "not_used" is a dimmed grey.
PALETTE = {
    'success':         ('#2E7D32', '#2E7D32', '✓', 'success'),
    'running':         ('#EF6C00', '#EF6C00', '▶', 'running'),
    'fail':            ('#C62828', '#C62828', '✗', 'fail'),
    'required_undone': ('#FFFFFF', '#9E9E9E', '○', 'to do'),
    'not_required':    ('#9E9E9E', '#9E9E9E', '–', 'optional'),
    'not_used':        ('#E0E0E0', '#CFCFCF', '–', 'n/a'),
}
# Dark fills want white text; light fills want near-black text.
LIGHT_TEXT_ON = {'success', 'fail', 'running'}

# Color used to highlight a *selected* item (e.g. a calibration step button).
# Magenta reads clearly against the green/grey/white status fills (the earlier
# blue was hard to see) -- see design doc.
SELECT_COLOR = '#D81B60'


def status_text_color(status_key):
    """
    Return a readable text color for a status cell.

    Generated by JXP and Claude.

    Parameters
    ----------
    status_key : str
        One of the keys in :data:`PALETTE`.

    Returns
    -------
    str
        ``'white'`` for dark-filled cells, else ``'#212121'`` (near-black).
    """
    return 'white' if status_key in LIGHT_TEXT_ON else '#212121'


def find_logo():
    """
    Locate the PypeIt logo PNG.

    Generated by JXP and Claude.

    Prefers the downscaled local copy committed under
    ``pypeitdev/dashboard/images/``; falls back to the full-resolution original
    in the sibling ``PypeIt`` repo.

    Returns
    -------
    str or None
        Absolute path to the logo image, or None if it cannot be found.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    orig = 'PypeIt_color_white_txt_black_background.png'
    # Candidate locations relative to this file (py/ is under dashboard/).
    candidates = [
        os.path.join(here, '..', 'images', 'pypeit_logo.png'),
        os.path.join(here, '..', '..', '..', '..', 'PypeIt', 'doc', '_static',
                     orig),
    ]
    for path in candidates:
        if os.path.isfile(path):
            return os.path.abspath(path)
    return None


def place_image(ax, path, center, zoom):
    """
    Place a raster image (undistorted) centered at a data coordinate.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    path : str
        Path to the image file.
    center : tuple of float
        (x, y) center in data coordinates.
    zoom : float
        Pixel zoom passed to ``OffsetImage`` (preserves aspect ratio).

    Returns
    -------
    bool
        True if the image was placed, False if it could not be read.
    """
    try:
        img = mpimg.imread(path)
    except (FileNotFoundError, OSError, ValueError):
        return False
    box = OffsetImage(img, zoom=zoom)
    ab = AnnotationBbox(box, center, frameon=False, xycoords='data',
                        box_alignment=(0.5, 0.5))
    ax.add_artist(ab)
    return True


def draw_status_pill(ax, x0, y_center, status_key, width=16):
    """
    Draw a single color-coded status pill with glyph + label.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x0 : float
        Left x of the cell (data coords).
    y_center : float
        Vertical center of the row (data coords).
    status_key : str
        Key into :data:`PALETTE`.
    width : float, optional
        Pill width in data units.

    Returns
    -------
    None
    """
    fill, edge, glyph, label = PALETTE[status_key]
    pill = FancyBboxPatch((x0 + 0.6, y_center - 1.0), width, 2.0,
                          boxstyle='round,pad=0.12,rounding_size=0.5',
                          facecolor=fill, edgecolor=edge, linewidth=1.2)
    ax.add_patch(pill)
    ax.text(x0 + 1.6, y_center, glyph, ha='center', va='center',
            fontsize=10, color=status_text_color(status_key))
    ax.text(x0 + 3.0, y_center, label, va='center', fontsize=9,
            color=status_text_color(status_key))


def chip(ax, x, y, w, text, fill='#1565C0', fg='white'):
    """
    Draw a small action chip/button.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    x, y : float
        Lower-left corner (data coords).
    w : float
        Chip width.
    text : str
        Chip label.
    fill, fg : str, optional
        Fill and text colors.

    Returns
    -------
    None
    """
    ax.add_patch(FancyBboxPatch((x, y), w, 2.0,
                 boxstyle='round,pad=0.1,rounding_size=0.4',
                 facecolor=fill, edgecolor=fill))
    ax.text(x + w / 2, y + 1.0, text, ha='center', va='center', fontsize=7.8,
            color=fg)


def draw_tab_bar(ax, active='status'):
    """
    Draw the (Status | Calibrations) tab bar.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on (data coords 0..100).
    active : str, optional
        Which tab is active: ``'status'`` or ``'calibrations'``.

    Returns
    -------
    None
    """
    on, off_bg, off_fg = '#1565C0', '#ECEFF1', '#546E7A'
    s_active = active == 'status'
    ax.add_patch(Rectangle((4, 95.5), 18, 4.0,
                           facecolor=on if s_active else off_bg,
                           edgecolor=on if s_active else '#B0BEC5'))
    ax.text(13, 97.5, 'Status', ha='center', va='center',
            color='white' if s_active else off_fg, fontsize=11,
            fontweight='bold' if s_active else 'normal')
    ax.add_patch(Rectangle((22.5, 95.5), 22, 4.0,
                           facecolor=on if not s_active else off_bg,
                           edgecolor=on if not s_active else '#B0BEC5'))
    ax.text(33.5, 97.5, 'Calibrations', ha='center', va='center',
            color='white' if not s_active else off_fg, fontsize=11,
            fontweight='bold' if not s_active else 'normal')


def draw_header(ax):
    """
    Draw the run-context header banner.

    Generated by JXP and Claude.

    The PypeIt logo is drawn separately (see :func:`draw_logo`) so it does not
    overlap the banner text.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.

    Returns
    -------
    None
    """
    ax.add_patch(Rectangle((4, 88.0), 94, 6.7, facecolor='#0D47A1',
                           edgecolor='#0D47A1'))
    ax.text(5.5, 93.0, 'shane_kast_blue_A.pypeit', color='white',
            fontsize=13, fontweight='bold', va='center')
    ax.text(5.5, 91.0, 'shane_kast_blue   •   MultiSlit   •   Setup A',
            color='#BBDEFB', fontsize=9.5, va='center')
    ax.text(5.5, 89.4, 'Redux dir:  REDUX_OUT/shane_kast_blue/600_4310_d55/'
            'shane_kast_blue_A', color='#90CAF9', fontsize=8.5, va='center')


def draw_logo(ax):
    """
    Place the PypeIt logo in the top-right corner of the window.

    Generated by JXP and Claude.

    The logo lives in the empty band to the right of the tabs (above the header
    banner) so it never overlaps view content.  Uses the downscaled local copy
    (600x317 px); zoom ~0.19 makes it ~7 x-units wide.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on (data coords 0..100).

    Returns
    -------
    None
    """
    logo = find_logo()
    if logo is not None:
        place_image(ax, logo, center=(92.0, 97.4), zoom=0.19)


def draw_scope_toolbar(ax, y0, include_filter=True):
    """
    Draw the scope toolbar: calib-group and detector drop-downs + controls.

    Generated by JXP and Claude.

    The drop-downs are the anti-clutter mechanism: they scope the detailed
    tables/buttons below to a single (calibration group, detector/mosaic).

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    y0 : float
        Bottom edge (data coords) of the 3-unit-tall toolbar.
    include_filter : bool, optional
        If True, include a "Filter" control (used by the Status view).

    Returns
    -------
    None
    """
    yc = y0 + 1.5

    def dropdown(x, w, label):
        ax.add_patch(Rectangle((x, y0), w, 3.0, facecolor='white',
                               edgecolor='#607D8B'))
        ax.text(x + 0.8, yc, label, va='center', fontsize=9, color='#263238')
        ax.text(x + w - 1.2, yc, '▾', va='center', ha='center', fontsize=9,
                color='#607D8B')

    ax.text(4, yc, 'Scope:', va='center', fontsize=9.5, fontweight='bold',
            color='#37474F')
    dropdown(12, 22, 'Calib group:  0')
    dropdown(35, 22, 'Detector:  DET01')
    if include_filter:
        ax.add_patch(Rectangle((74, y0), 13, 3.0, facecolor='white',
                               edgecolor='#9E9E9E'))
        ax.text(80.5, yc, 'Filter ▾', ha='center', va='center', fontsize=9,
                color='#424242')
    ax.add_patch(Rectangle((88, y0), 9.5, 3.0, facecolor='#1565C0',
                           edgecolor='#1565C0'))
    ax.text(92.7, yc, '↻ Refresh', ha='center', va='center', fontsize=9,
            color='white')


def draw_color_key(ax, y):
    """
    Draw the Dashboard-wide status color key on a single row.

    Generated by JXP and Claude.

    Parameters
    ----------
    ax : matplotlib.axes.Axes
        Axis to draw on.
    y : float
        Vertical center (data coords) of the key row.

    Returns
    -------
    None
    """
    ax.text(4, y, 'Status key', fontsize=9, fontweight='bold',
            color='#37474F', va='center')
    order = ['success', 'running', 'fail', 'required_undone', 'not_required',
             'not_used']
    x = 16
    for key in order:
        fill, edge, glyph, label = PALETTE[key]
        ax.add_patch(FancyBboxPatch((x, y - 0.9), 1.8, 1.8,
                     boxstyle='round,pad=0.1,rounding_size=0.4',
                     facecolor=fill, edgecolor=edge, linewidth=1.0))
        ax.text(x + 0.9, y, glyph, ha='center', va='center', fontsize=9,
                color=status_text_color(key))
        ax.text(x + 2.4, y, label, va='center', fontsize=8.5, color='#546E7A')
        x += 13.5
