"""
Which object get_std picks in each run5 standard spec1d file.

For each HIP59174 spec1d file: the number of objects, the detectors, the
object chosen as the standard (highest S/N over all detectors), its
wavelength range and median counts, and the four highest-S/N objects.

Usage (from flux/): python inspect_std.py

Generated by JXP and Claude
"""
import glob

import numpy as np

from pypeit import specobjs


def main():
    """
    Print the standard chosen in each standard spec1d file.

    Generated by JXP and Claude
    """
    files = sorted(glob.glob('../run5/Science/spec1d_*HIP59174*.fits'))
    for f in files:
        sobjs = specobjs.SpecObjs.from_fitsfile(f, chk_version=False)
        std = sobjs.get_std(multi_spec_det=None, split_mosaic=True)
        if isinstance(std, specobjs.SpecObjs):
            std = std[0]
        print(f.split('/')[-1][:20], 'nobj', sobjs.nobj,
              'dets', np.unique(sobjs.DET), 'std:', std.NAME, std.DET,
              'S/N %.0f' % std.S2N)
        w = std.OPT_WAVE
        m = std.OPT_MASK
        print('   wave %.0f-%.0f  npix %d, good %d, counts med %.0f' % (
            w[m].min(), w[m].max(), w.size, m.sum(),
            np.median(std.OPT_COUNTS[m])))
        for i in np.argsort(sobjs.S2N)[::-1][:4]:
            print('   ', sobjs[i].NAME, '%.1f' % sobjs[i].S2N)


if __name__ == '__main__':
    main()
