"""
Tests for the manual spatial-flexure correction (PypeIt Issue #2180).
"""
import numpy as np

from astropy.table import Table

from pypeit.pypeit_steps import get_manual_flexure


def test_manual_flexure():
    """
    Test the manual spatial-flexure sentinel (Issue #2180): NaN in the
    pypeit-file ``shift`` column means "no manual value"; any finite
    value (including 0.) is a user-requested override.

    Builds an in-memory `astropy.table.Table`_ mimicking the fitstbl
    (inputs) and checks the float-or-None return value of
    :func:`pypeit.pypeit_steps.get_manual_flexure` (outputs).

    Generated by JXP and Claude.
    """
    # Mimic the fitstbl: NaN default, one finite override, and an
    # explicit 0. override (which is still "manual")
    tbl = Table()
    tbl['filename'] = ['a.fits', 'b.fits', 'c.fits']
    tbl['shift'] = [np.nan, 2.5, 0.]

    # NaN default -> no manual flexure
    assert get_manual_flexure(tbl, 0) is None, \
        'NaN shift should mean no manual flexure'
    # Finite value -> manual flexure
    assert get_manual_flexure(tbl, 1) == 2.5, \
        'Finite shift should be returned as the manual flexure'
    # 0. is finite and therefore a valid manual override
    assert get_manual_flexure(tbl, 2) == 0., \
        'A shift of 0. should still count as a manual flexure'

    # Missing column -> no manual flexure
    tbl_noshift = Table()
    tbl_noshift['filename'] = ['a.fits']
    assert get_manual_flexure(tbl_noshift, 0) is None, \
        'Missing shift column should mean no manual flexure'
