"""
Dev-suite test of the PypeIt Dashboard model's **derive** path (R5).

Deriving the reduction state instantiates :class:`~pypeit.pypeit.PypeIt`
and so requires RAW_DATA; it therefore lives here in the dev suite rather
than in the CI-safe main-repo tests (which cover the load path and all the
pure logic).  See ``dashboard_dev_stages_0-1.md`` (S1-Q5).

Generated by JXP and Claude.
"""

import os
import shutil
from pathlib import Path

import pytest

from pypeit.scripts.setup import Setup
from pypeit.dashboard.model import DashboardModel, LOAD_DERIVED


def test_dashboard_model_derive(tmp_path):
    """
    With no state file present, the model derives the state the
    ``pypeit_status`` way and exposes the expected calibration steps.

    Generated by JXP and Claude.

    Args:
        tmp_path (`pathlib.Path`_): Pytest temporary directory.

    Returns:
        None.
    """
    dev = os.environ.get('PYPEIT_DEV')
    if dev is None:
        pytest.skip('PYPEIT_DEV not set')
    rawdir = Path(dev) / 'RAW_DATA' / 'shane_kast_blue' / '600_4310_d55'
    if not rawdir.is_dir():
        pytest.skip('RAW_DATA/shane_kast_blue/600_4310_d55 not available')

    # Stage a small raw subset and run pypeit_setup to write a .pypeit file.
    testraw = tmp_path / 'RAW'
    testraw.mkdir()
    for fname in ['b1.fits.gz', 'b11.fits.gz', 'b12.fits.gz', 'b13.fits.gz',
                  'b21.fits.gz', 'b22.fits.gz', 'b23.fits.gz']:
        shutil.copy(rawdir / fname, testraw / fname)

    outdir = tmp_path / 'REDUX'
    Setup.main(Setup.parse_args(['-r', str(testraw), '-s', 'shane_kast_blue',
                                 '-c', 'all', '-o',
                                 '--output_path', str(outdir)]))
    configdir = outdir / 'shane_kast_blue_A'
    pyp_file = configdir / 'shane_kast_blue_A.pypeit'
    assert pyp_file.is_file(), 'pypeit_setup did not write the .pypeit file'

    # No <root>_state.json in configdir -> the model derives the state (R5).
    model = DashboardModel(str(pyp_file), redux_path=str(configdir),
                           derive=True)
    assert model.load_status == LOAD_DERIVED
    assert model.is_started()

    # The required MultiSlit calibration steps should be present and flagged
    # as in-pipeline.
    table = model.status_table()
    in_pipe_steps = set(table[table['in_pipeline'].astype(bool)]['step'])
    assert {'bias', 'arc', 'slits', 'wv_calib', 'tilts', 'flats'} \
        <= in_pipe_steps
    # The single (calib_id, det) pair is enumerated.
    assert model.calib_det_pairs() == [(0, 1)]
