"""Summarize slits and wavelength solutions per detector.
Generated by JXP and Claude (dev script, not part of PypeIt)."""
import sys, glob
import numpy as np
from pypeit.wavecalib import WaveCalib
from pypeit.slittrace import SlitTraceSet
for f in sorted(glob.glob('Calibrations/WaveCalib_*')):
    wc = WaveCalib.from_file(f, chk_version=False)
    sl = SlitTraceSet.from_file(f.replace('WaveCalib', 'Slits') + '.gz',
                                chk_version=False)
    print(f, 'nslits', sl.nslits)
    for i, ws in enumerate(wc.wv_fits):
        if ws is None or ws.pypeitfit is None:
            print(f'  slit {sl.spat_id[i]:5d} no fit'); continue
        w = ws.pypeitfit.eval(np.array([0., 0.5, 1.]))
        print(f'  slit {sl.spat_id[i]:5d} rms={ws.rms:.3f} '
              f'nlin={len(ws.pixel_fit):3d} wave(0,mid,end)={w.round(0)}')
