"""
Build the Subaru/MOIRCS HK500 full_template (reid_arxiv) from the
holy-grail OH solution of one slit that covers the whole HK500 range.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit import dataPaths
from pypeit.core.wavecal import wvutils
from pypeit.wavecalib import WaveCalib

# DET02 slit spat_id=289: rms 0.30 pix, 71 lines, light from ~1.29-2.31 um
wcfile = 'subaru_moircs_A/Calibrations/WaveCalib_A_0_DET02.fits'
wc = WaveCalib.from_file(wcfile, chk_version=False)
idx = [w.spat_id for w in wc.wv_fits if w is not None].index(289)
wv = wc.wv_fits[idx]

# Keep only pixels with light; outside ~12500-23500 A the solution is an
# extrapolation and there is no flux (grism/filter cut-offs)
keep = (wv.wave_soln > 12500.) & (wv.wave_soln < 23500.)
wave, flux = wv.wave_soln[keep], wv.spec[keep]

# full_template expects the template to be *longer* than the observed
# spectra (it pads the observed spectrum).  The slits are shifted by up to
# ~1000 pixels relative to one another, so extend the template to NTOT
# pixels with zero flux, extrapolating the wavelengths linearly with the
# dispersion at each end.
NTOT = 4000
nlo = (NTOT - wave.size) // 2
nhi = NTOT - wave.size - nlo
dlo = wave[1] - wave[0]
dhi = wave[-1] - wave[-2]
wave = np.concatenate([wave[0] - dlo * np.arange(nlo, 0, -1), wave,
                       wave[-1] + dhi * np.arange(1, nhi + 1)])
flux = np.concatenate([np.zeros(nlo), flux, np.zeros(nhi)])
print(f'spat {wv.spat_id}: rms={wv.rms:.3f} nlines={len(wv.wave_fit)} '
      f'npix={keep.sum()} wave={wave.min():.0f}-{wave.max():.0f}')

wvutils.write_template(wave, flux, 1, str(dataPaths.reid_arxiv.path),
                       'subaru_moircs_HK500.fits', overwrite=True)

plt.figure(figsize=(14, 4))
plt.plot(wave, flux, 'k-', lw=0.6, drawstyle='steps-mid')
plt.xlabel('Wavelength (A, vacuum)')
plt.title('subaru_moircs_HK500.fits (DET02, spat 289)')
plt.tight_layout()
plt.savefig('hk500_template.png', dpi=70)
