"""
Make the QA figures for report_HK500/ (subaru_moircs_report_HK500.md).

Dev script; not part of PypeIt.  Generated by JXP and Claude.
"""
from pathlib import Path
import glob
import json
import logging
import os
import shutil

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import ndimage, stats

from pypeit import spec2dobj, specobjs
from pypeit.slittrace import SlitTraceSet
from pypeit.wavecalib import WaveCalib
from pypeit.flatfield import FlatImages

logging.disable(logging.INFO)

HERE = Path(__file__).parent
# The reduction and output directories can be changed with the
# MOIRCS_RUN and MOIRCS_OUT environment variables
RUN = Path(os.environ.get('MOIRCS_RUN',
                          HERE / 'run2' / 'subaru_moircs_A'))
HG = HERE / 'subaru_moircs_A'                # holy-grail calibrations
OUT = Path(os.environ.get('MOIRCS_OUT', HERE / 'report_HK500'))
OUT.mkdir(exist_ok=True)
DETS = ['DET01', 'DET02']
LINELIST = Path('/Users/xavier/Projects/PypeIt/PypeIt/pypeit/data/'
                'arc_lines/lists/OH_NIRES_lines.dat')

# Reference palette (dataviz skill, slots 1-3) and neutral inks
BLUE, ORANGE, AQUA = '#2a78d6', '#eb6834', '#1baf7a'
INK, MUTED, GRID, SURF = '#1f1f1e', '#6b6a64', '#e4e3dd', '#fcfcfb'
plt.rcParams.update({
    'figure.facecolor': SURF, 'axes.facecolor': SURF,
    'axes.edgecolor': MUTED, 'axes.labelcolor': INK, 'text.color': INK,
    'xtick.color': MUTED, 'ytick.color': MUTED, 'axes.grid': True,
    'grid.color': GRID, 'grid.linewidth': 0.6, 'axes.axisbelow': True,
    'axes.spines.top': False, 'axes.spines.right': False,
    'font.size': 10, 'legend.frameon': False,
})
summary = {}


def load_wc(base, det):
    """Return WaveCalib and SlitTraceSet for a run directory and det."""
    wc = WaveCalib.from_file(base / f'Calibrations/WaveCalib_A_0_{det}.fits',
                             chk_version=False)
    sl = SlitTraceSet.from_file(base / f'Calibrations/Slits_A_0_{det}.fits.gz',
                                chk_version=False)
    return wc, sl


def ok_fit(w):
    return w is not None and w.pypeitfit is not None


# ---------------------------------------------------------------------------
# F1, F4, F6, F9: copy existing figures
shutil.copy(HERE / 'prep2_raw_overview.png', OUT / 'f1_raw_overview.png')
shutil.copy(HERE / 'bpm' / 'bpm_review.png', OUT / 'f9_bpm.png')
png = RUN / 'QA' / 'PNGs'
shutil.copy(png / 'Arc_1dfit_A_0_DET01_S0852.png', OUT / 'f4a_arcfit_det1.png')
shutil.copy(png / 'Arc_1dfit_A_0_DET02_S1442.png', OUT / 'f4b_arcfit_det2.png')
shutil.copy(png / 'Arc_tilts_2d_A_0_DET01_S0852.png', OUT / 'f6_tilts_det1.png')
for f in sorted(png.glob('pos_MCSP00237323*DET01_S1245_obj_prof.png')):
    shutil.copy(f, OUT / 'f8b_objprof.png')

# ---------------------------------------------------------------------------
# F2: slit map, colored by wavelength-calibration status
fig, ax = plt.subplots(1, 2, figsize=(13, 7))
summary['slits'] = {}
for i, det in enumerate(DETS):
    wc, sl = load_wc(RUN, det)
    flat = FlatImages.from_file(RUN / f'Calibrations/Flat_A_0_{det}.fits',
                                chk_version=False)
    img = flat.pixelflat_raw
    v = np.nanpercentile(img, [5, 99])
    ax[i].imshow(img, origin='lower', vmin=v[0], vmax=v[1], cmap='gray',
                 aspect='auto')
    ax[i].grid(False)
    left, right, _ = sl.select_edges()
    spec = np.arange(img.shape[0])
    box = sl.bitmask.flagged(sl.mask, flag='BOXSLIT')
    nsci = nok = 0
    for j in range(sl.nslits):
        good = ok_fit(wc.wv_fits[j])
        c = BLUE if good else ORANGE
        ls = ':' if box[j] else '-'
        ax[i].plot(left[:, j], spec, color=c, lw=1, ls=ls)
        ax[i].plot(right[:, j], spec, color=c, lw=1, ls=ls)
        if not box[j]:
            nsci += 1
            nok += good
    summary['slits'][det] = dict(nslits=int(sl.nslits), nbox=int(box.sum()),
                                 nsci=nsci, nsci_wave_ok=int(nok))
    ax[i].set_title(f'{det}: {nsci} science slits ({nok} calibrated), '
                    f'{box.sum()} boxes', fontsize=10)
    ax[i].set_xlabel('spatial pixel')
ax[0].set_ylabel('spectral pixel')
ax[1].plot([], [], color=BLUE, label='wavelength-calibrated')
ax[1].plot([], [], color=ORANGE, label='not calibrated')
ax[1].plot([], [], color=MUTED, ls=':', label='alignment box (dotted)')
ax[1].legend(loc='upper right', fontsize=8, frameon=True)
fig.suptitle('Slit edges on the lamp-on dome flat')
fig.tight_layout()
fig.savefig(OUT / 'f2_slits.png', dpi=80)
plt.close(fig)

# ---------------------------------------------------------------------------
# F3: wavelength calibration per slit, holy-grail vs reidentify
fig, ax = plt.subplots(2, 2, figsize=(13, 6.5), sharex='col')
summary['wave'] = {}
for i, det in enumerate(DETS):
    wcr, sl = load_wc(RUN, det)
    wch, _ = load_wc(HG, det)
    box = sl.bitmask.flagged(sl.mask, flag='BOXSLIT')
    sci = np.where(~box)[0]
    x = np.arange(sci.size)
    rms = {}
    nlin = {}
    for name, wc in [('holy-grail', wch), ('reidentify', wcr)]:
        rms[name] = np.array([wc.wv_fits[j].rms if ok_fit(wc.wv_fits[j])
                              else np.nan for j in sci])
        nlin[name] = np.array([len(wc.wv_fits[j].pixel_fit)
                               if ok_fit(wc.wv_fits[j]) else 0 for j in sci])
    w = 0.4
    for k, (name, c) in enumerate([('holy-grail', ORANGE),
                                   ('reidentify', BLUE)]):
        ax[0, i].bar(x + (k - 0.5) * w, np.nan_to_num(rms[name]), w * 0.9,
                     color=c, label=name)
        ax[1, i].bar(x + (k - 0.5) * w, nlin[name], w * 0.9, color=c)
        # Mark failures
        bad = np.isnan(rms[name])
        ax[0, i].plot(x[bad] + (k - 0.5) * w, np.full(bad.sum(), 0.02), 'x',
                      color=c, ms=7, mew=2)
    ax[0, i].set_title(f'{det}', fontsize=10)
    ax[0, i].set_ylabel('fit RMS (pixels)')
    ax[1, i].set_ylabel('lines in fit')
    ax[1, i].set_xticks(x)
    ax[1, i].set_xticklabels([str(sl.spat_id[j]) for j in sci], rotation=90,
                             fontsize=8)
    ax[1, i].set_xlabel('slit (spat_id)')
    summary['wave'][det] = {
        name: dict(nsolved=int(np.isfinite(rms[name]).sum()),
                   nsci=int(sci.size),
                   rms_median=float(np.nanmedian(rms[name])),
                   rms_max=float(np.nanmax(rms[name])),
                   nlines_median=float(np.median(nlin[name][nlin[name] > 0])))
        for name in rms}
ax[0, 0].legend(loc='upper left', fontsize=8)
fig.suptitle('Wavelength solutions of the science slits '
             '(x = no solution)')
fig.tight_layout()
fig.savefig(OUT / 'f3_wavecal.png', dpi=80)
plt.close(fig)

# ---------------------------------------------------------------------------
# F5: wavelength accuracy
#  (a) fit residuals of all lines used, in Angstrom, vs wavelength
#  (b) independent check: centroids of isolated OH lines measured directly
#      in each slit's sky spectrum vs the line-list wavelength
ll = np.loadtxt(LINELIST, skiprows=1, usecols=(1, 5), delimiter='|')
llw, lla = ll[:, 0], ll[:, 1]
# Isolated strong lines: no line with >25% of its amplitude within 80 A
# (~2 FWHM at R~500)
iso = []
for k in np.where((llw > 13500) & (llw < 22800))[0]:
    near = (np.abs(llw - llw[k]) < 80.) & (np.arange(llw.size) != k)
    if lla[k] > np.percentile(lla, 60) and not np.any(lla[near]
                                                       > 0.25 * lla[k]):
        iso.append(llw[k])
iso = np.array(iso)

res_w, res_d = [], []
chk_w, chk_d, chk_det = [], [], []
for det in DETS:
    wc, sl = load_wc(RUN, det)
    for j, wv in enumerate(wc.wv_fits):
        if not ok_fit(wv):
            continue
        npix = wv.spec.size
        # (a) fit residuals
        model = wv.pypeitfit.eval(wv.pixel_fit / (npix - 1))
        res_w.append(wv.wave_fit)
        res_d.append(wv.wave_fit - model)
        # (b) Gaussian-weighted centroid of each isolated line
        pix = np.arange(npix)
        cont = ndimage.median_filter(wv.spec, 61)
        flux = wv.spec - cont
        for lam in iso:
            if lam < wv.wave_soln.min() or lam > wv.wave_soln.max():
                continue
            p0 = np.interp(lam, wv.wave_soln, pix)
            win = (pix > p0 - 6) & (pix < p0 + 6)
            if win.sum() < 8:
                continue
            # Require a clear peak inside the window (robust noise)
            noise = stats.median_abs_deviation(
                flux[(pix > p0 - 60) & (pix < p0 + 60)], scale='normal')
            if flux[win].max() < 3 * noise:
                continue
            pc = p0
            for _ in range(5):
                wgt = np.exp(-0.5 * ((pix - pc) / 2.5) ** 2) * win \
                    * np.clip(flux, 0, None)
                if wgt.sum() <= 0:
                    break
                pc = np.sum(wgt * pix) / wgt.sum()
            if abs(pc - p0) > 3:
                continue
            chk_w.append(lam)
            chk_d.append(np.interp(pc, pix, wv.wave_soln) - lam)
            chk_det.append(det)
res_w, res_d = np.concatenate(res_w), np.concatenate(res_d)
chk_w, chk_d = np.array(chk_w), np.array(chk_d)
chk_det = np.array(chk_det)
disp = 7.6  # A/pix
# Split the residuals into a per-line offset shared by all slits (blends of
# OH lines at R~500 shift the effective line centre) and the slit-to-slit
# scatter about it (the relative precision between slits)
keys = np.round(res_w, 1)
uniq, inv, cnt = np.unique(keys, return_inverse=True, return_counts=True)
line_off = np.array([np.median(res_d[inv == u]) for u in range(uniq.size)])
use = cnt[inv] >= 5
demeaned = (res_d - line_off[inv])[use]
fig, ax = plt.subplots(1, 2, figsize=(13, 4.5), sharey=True)
ax[0].plot(res_w, res_d, '.', color=BLUE, ms=3, alpha=0.6)
ax[0].axhline(0, color=MUTED, lw=1)
ax[0].set_title(f'(a) Fit residuals, all 32 slits: {res_d.size} lines, '
                f'robust std '
                f'{stats.median_abs_deviation(res_d, scale="normal"):.1f} A',
                fontsize=10)
ax[0].set_xlabel('wavelength (A, vacuum)')
ax[0].set_ylabel('measured - fit (A)')
good_lines = cnt >= 5
ax[1].plot(uniq[good_lines], line_off[good_lines], 'o', color=ORANGE,
           ms=5, mec=SURF, mew=0.5, label='per-line offset (all slits)')
ax[1].plot(res_w[use], demeaned, '.', color=BLUE, ms=3, alpha=0.5,
           label='slit-to-slit scatter about it')
ax[1].axhline(0, color=MUTED, lw=1)
ax[1].set_title(f'(b) Per-line offsets: robust std '
                f'{stats.median_abs_deviation(line_off[good_lines], scale="normal"):.1f} A;'
                f' slit-to-slit: '
                f'{stats.median_abs_deviation(demeaned, scale="normal"):.1f} A',
                fontsize=10)
ax[1].set_xlabel('wavelength (A, vacuum)')
ax[1].legend(loc='lower right', fontsize=8)
ax[0].set_ylim(-25, 25)
for a in ax:
    sec = a.secondary_yaxis('right', functions=(lambda y: y / disp,
                                                 lambda p: p * disp))
    sec.set_ylabel('pixels')
fig.tight_layout()
fig.savefig(OUT / 'f5_wave_accuracy.png', dpi=80)
plt.close(fig)
summary['accuracy'] = dict(
    nfit=int(res_d.size),
    fit_robust_std_A=float(stats.median_abs_deviation(res_d,
                                                      scale='normal')),
    nlines_ge5=int(good_lines.sum()),
    line_offset_robust_std_A=float(stats.median_abs_deviation(
        line_off[good_lines], scale='normal')),
    slit_to_slit_robust_std_A=float(stats.median_abs_deviation(
        demeaned, scale='normal')),
    niso_lines=int(iso.size), nchk=int(chk_d.size),
    chk_median_A=float(np.median(chk_d)) if chk_d.size else None,
    chk_robust_std_A=float(stats.median_abs_deviation(
        chk_d, scale='normal')) if chk_d.size else None)

# ---------------------------------------------------------------------------
# F7: sky subtraction residuals
sci2d = sorted(glob.glob(str(RUN / 'Science' / 'spec2d_*323*.fits')))[0]
fig = plt.figure(figsize=(13, 8))
gs = fig.add_gridspec(2, 3, width_ratios=[1, 1, 0.9])
summary['skysub'] = {}
for i, det in enumerate(DETS):
    s2 = spec2dobj.Spec2DObj.from_file(sci2d, det, chk_version=False)
    good = (s2.bpmmask.mask == 0) & (s2.ivarmodel > 0)
    chi = np.where(good, (s2.sciimg - s2.skymodel - s2.objmodel)
                   * np.sqrt(s2.ivarmodel), np.nan)
    a = fig.add_subplot(gs[:, i])
    a.imshow(chi, origin='lower', vmin=-4, vmax=4, cmap='gray',
             aspect='auto')
    a.grid(False)
    a.set_title(f'{det}: (A-B - sky - obj) / sigma', fontsize=10)
    a.set_xlabel('spatial pixel')
    c = chi[np.isfinite(chi)]
    summary['skysub'][det] = dict(
        chi_median=float(np.median(c)),
        chi_robust_std=float(stats.median_abs_deviation(c, scale='normal')),
        frac_gt5=float(np.mean(np.abs(c) > 5)))
    h = fig.add_subplot(gs[i, 2])
    bins = np.linspace(-6, 6, 121)
    h.hist(c, bins=bins, density=True, color=BLUE if i == 0 else ORANGE,
           histtype='stepfilled', alpha=0.8, label=det)
    h.plot(bins, stats.norm.pdf(bins), color=INK, lw=1.2, label='N(0,1)')
    h.set_yscale('log')
    h.set_ylim(1e-5, 1)
    h.set_title(f'{det}: robust std '
                f'{summary["skysub"][det]["chi_robust_std"]:.2f}, '
                f'|chi|>5: {100 * summary["skysub"][det]["frac_gt5"]:.2f}%',
                fontsize=9)
    h.legend(fontsize=8)
fig.axes[0].set_ylabel('spectral pixel')
fig.tight_layout()
fig.savefig(OUT / 'f7_skysub.png', dpi=80)
plt.close(fig)

# ---------------------------------------------------------------------------
# F8: extracted spectra, A and B exposures overlaid
spec1d = sorted(glob.glob(str(RUN / 'Science' / 'spec1d_*.fits')))
sobjs = [specobjs.SpecObjs.from_fitsfile(f, chk_version=False)
         for f in spec1d]
names = [o.NAME for o in sobjs[0]]
fig, ax = plt.subplots(len(names), 1, figsize=(13, 2.3 * len(names)),
                       sharex=True)
summary['objects'] = []
for k, o in enumerate(sobjs[0]):
    slit, det = o.SLITID, o.DET
    for lab, so, c in [('A (323)', sobjs[0], BLUE), ('B (325)', sobjs[1],
                                                     ORANGE)]:
        m = [x for x in so if x.SLITID == slit and x.DET == det]
        if not m:
            continue
        x = m[0]
        wv, fl, iv = x.OPT_WAVE, x.OPT_COUNTS, x.OPT_COUNTS_IVAR
        gd = (wv > 13000) & (wv < 23000) & (iv > 0) & x.OPT_MASK
        smooth = ndimage.median_filter(np.where(gd, fl, np.nan), 9)
        ax[k].plot(wv[gd], smooth[gd], color=c, lw=0.9, label=lab)
    # Atmospheric water-absorption gaps
    for lo, hi in [(13450, 14500), (18000, 19500)]:
        ax[k].axvspan(lo, hi, color=GRID, alpha=0.7, lw=0)
    sn = np.nanmedian(o.OPT_COUNTS * np.sqrt(o.OPT_COUNTS_IVAR))
    ax[k].set_title(f'{o.NAME}   (median S/N per pixel {sn:.1f}, '
                    f'FWHM {o.FWHM:.1f} pix)', fontsize=9, loc='left')
    ax[k].set_ylabel('counts')
    summary['objects'].append(dict(name=o.NAME, sn=float(sn),
                                   fwhm=float(o.FWHM)))
ax[0].legend(loc='upper right', fontsize=8, ncol=2)
ax[-1].set_xlabel('wavelength (A, vacuum)  -  grey: telluric water bands')
fig.suptitle('Optimal extractions (9-pixel median filter); A and B '
             'exposures overlaid', y=1.0)
fig.tight_layout()
fig.savefig(OUT / 'f8_spec1d.png', dpi=80)
plt.close(fig)

# ---------------------------------------------------------------------------
# F10: normalized pixel flat
fig, ax = plt.subplots(1, 2, figsize=(13, 5))
summary['flat'] = {}
for i, det in enumerate(DETS):
    flat = FlatImages.from_file(RUN / f'Calibrations/Flat_A_0_{det}.fits',
                                chk_version=False)
    pf = flat.pixelflat_norm
    _, sl = load_wc(RUN, det)
    on = sl.slit_img(initial=False) >= 0
    vals = pf[on & (pf != 1)]
    ax[i].imshow(pf, origin='lower', vmin=0.95, vmax=1.05, cmap='gray',
                 aspect='auto')
    ax[i].grid(False)
    rstd = stats.median_abs_deviation(vals, scale='normal')
    summary['flat'][det] = dict(pixel_rstd=float(rstd))
    ax[i].set_title(f'{det} pixelflat_norm (0.95-1.05); robust std in '
                    f'slits {100 * rstd:.1f}%', fontsize=10)
fig.tight_layout()
fig.savefig(OUT / 'f10_pixelflat.png', dpi=80)
plt.close(fig)

(OUT / 'summary.json').write_text(json.dumps(summary, indent=1))
print(json.dumps(summary, indent=1))
