"""
Build a multi-spectrum reid_arxiv for Subaru/MOIRCS HK500 from the good
holy-grail OH solutions of the dev-suite mask (both detectors), for use
with the 'reidentify' method.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import sys
import numpy as np
from astropy.table import Table

from pypeit import dataPaths
from pypeit.wavecalib import WaveCalib

outname = sys.argv[1] if len(sys.argv) > 1 else 'subaru_moircs_HK500.fits'
rows = []
for det in [1, 2]:
    wc = WaveCalib.from_file(
        f'subaru_moircs_A/Calibrations/WaveCalib_A_0_DET0{det}.fits',
        chk_version=False)
    for w in wc.wv_fits:
        if w is None or w.pypeitfit is None:
            continue
        # Require a good fit and a monotonic solution over the full detector
        mono = np.all(np.diff(w.wave_soln) > 0)
        if w.rms > 0.5 or len(w.wave_fit) < 40 or not mono:
            print(f'skip DET0{det} spat {w.spat_id} rms={w.rms:.2f} '
                  f'n={len(w.wave_fit)} mono={mono}')
            continue
        rows.append((w.wave_soln, w.spec, det * 10000 + w.spat_id))
nspec = rows[0][0].size
tbl = Table(names=('wave', 'flux', 'order'),
            dtype=(f'({nspec},)>f8', f'({nspec},)>f8', '>i8'))
for r in rows:
    tbl.add_row(r)
tbl.meta['BINSPEC'] = 1
tbl.write(dataPaths.reid_arxiv.path / outname, format='fits',
          overwrite=True)
print(f'Wrote {len(tbl)} spectra to {outname}')
