"""
Feasibility test: map MOIRCS .mdp mask coordinates onto the detectors
using the undispersed mask image (MCSP00237201/202).

Result (2026-10-04, cosmos2_z3eelg_v01.mdp):
  chip1: n=16 matched (3 holes), affine rms 1.7 px
     det_x =  0.0050*mx + 1.0163*my -  145.0
     det_y = -1.0175*mx + 0.0075*my + 2278.2
  chip2: n=15 matched (4 holes), affine rms 1.2 px
     det_x = -0.0037*mx + 1.0116*my - 1727.5
     det_y = -1.0112*mx - 0.0042*my + 2317.6
i.e. mask x -> -detector y (spatial), mask y -> +detector x (spectral);
scale ~1.01-1.02, rotation ~0.3 deg; zero point depends on the mask.

Dev script; generated by JXP and Claude.
"""
import numpy as np
from astropy.io import fits
from scipy import ndimage

RAW = ('/Users/xavier/Projects/PypeIt/PypeIt-development-suite/RAW_DATA/'
       'subaru_moircs/HK500/MCSP00237')


def read_mdp(path):
    """Return (x, y) of each opening and its type ('B' slit, 'C' hole)."""
    xy, typ = [], []
    for line in open(path):
        p = line.split()
        xy.append((float(p[0]), float(p[1])))
        typ.append('C' if 'C,' in line[:70] else 'B')
    return np.array(xy), np.array(typ)


def detect(frame):
    """Centroids of the openings in an undispersed mask image."""
    d = fits.getdata(RAW + frame + '.fits').astype(float)
    r = ndimage.median_filter(d - ndimage.median_filter(d, size=(1, 41)), 3)
    lab, _ = ndimage.label(r > np.percentile(r, 99) * 1.5)
    out = []
    for o in ndimage.find_objects(lab):
        h, w = o[0].stop - o[0].start, o[1].stop - o[1].start
        if h * w < 200:
            continue
        sub = r[o] * (lab[o] > 0)
        yy, xx = np.indices(sub.shape)
        out.append((o[1].start + (sub * xx).sum() / sub.sum(),
                    o[0].start + (sub * yy).sum() / sub.sum()))
    return np.array(out)


if __name__ == '__main__':
    m, typ = read_mdp('cosmos2_z3eelg_v01.mdp')
    # Initial flip+shift guesses from a brute-force hole match
    for chip, frame, bx, by in [(1, '201', -114.5, 2270.6),
                                (2, '202', -1701.4, 2292.2)]:
        det = detect(frame)
        px, py = m[:, 1] + bx, -m[:, 0] + by
        for tol in [10, 5, 5]:
            d = np.hypot(px[:, None] - det[None, :, 0],
                         py[:, None] - det[None, :, 1])
            j = np.argmin(d, axis=1)
            ok = d[np.arange(len(m)), j] < tol
            A = np.c_[m[ok], np.ones(ok.sum())]
            cx, *_ = np.linalg.lstsq(A, det[j[ok], 0], rcond=None)
            cy, *_ = np.linalg.lstsq(A, det[j[ok], 1], rcond=None)
            A = np.c_[m, np.ones(len(m))]
            px, py = A @ cx, A @ cy
        res = np.hypot(px[ok] - det[j[ok], 0], py[ok] - det[j[ok], 1])
        print(f'chip{chip}: n={ok.sum()} rms={np.sqrt(np.mean(res**2)):.2f}')
        print('  det_x = %.4f*mx + %.4f*my + %.1f' % tuple(cx))
        print('  det_y = %.4f*mx + %.4f*my + %.1f' % tuple(cy))
