"""
Feasibility tests for MOIRCS slit-mask matching without RA/Dec
(prompt Implementation #13).  Uses the run_docs HK500 reduction.

1. Slit identification (MASKDEF_ID): predict each .mdp opening's spatial
   centre on each chip with the instrument flip/scale (from
   mask_map_test.py), find the per-chip zero point by a 1D scan, and match
   to the traced slits.
2. Object positions: compare the detected objects' mean A/B position with
   the slit centre (targets are expected at the slit centre).

Dev script; generated by JXP and Claude.
"""
import glob
import json
import logging

import numpy as np

from pypeit import specobjs
from pypeit.slittrace import SlitTraceSet

logging.disable(logging.INFO)
RUN = 'run_docs/subaru_moircs_A'


def read_mdp(path):
    """Return x, y, length, type and catalogue id of each opening."""
    rows = []
    for line in open(path):
        p = line.split()
        typ = 'C' if 'C,' in line[:70] else 'B'
        oid = int(line.split('"id":')[1].split(',')[0])
        rows.append((float(p[0]), float(p[1]), float(p[2]), typ, oid))
    x, y, length, typ, oid = map(np.array, zip(*rows))
    return x, y, length, typ, oid


def match_slits():
    mx, my, length, typ, ids = read_mdp('cosmos2_z3eelg_v01.mdp')
    for det, scale, yrange in [('DET01', 1.0175, (583, 2105)),
                               ('DET02', 1.0112, (1741, 3431))]:
        sl = SlitTraceSet.from_file(
            f'{RUN}/Calibrations/Slits_A_0_{det}.fits.gz', chk_version=False)
        mid = sl.left_init.shape[0] // 2
        tc = (sl.left_init[mid] + sl.right_init[mid]) / 2
        on = (my >= yrange[0]) & (my <= yrange[1])
        pc = -scale * mx[on]
        offs = np.arange(-500, 4000, 0.5)
        score = [np.sum(np.min(np.abs((pc + o)[:, None] - tc[None, :]),
                               axis=0) < 6) for o in offs]
        o = offs[int(np.argmax(score))]
        d = np.abs((pc + o)[:, None] - tc[None, :])
        dm = d.min(axis=0)
        print(f'{det}: matched {np.sum(dm < 6)}/{tc.size} traced slits '
              f'(zero point {o:.1f}; max |dpos| {dm.max():.1f} px)')


def object_offsets():
    pos = {}
    for f, lab in zip(sorted(glob.glob(f'{RUN}/Science/spec1d_*.fits')),
                      ['A', 'B']):
        for o in specobjs.SpecObjs.from_fitsfile(f, chk_version=False):
            pos.setdefault((o.DET, o.SLITID), {})[lab] = o.SPAT_PIXPOS
    for (det, slit), p in sorted(pos.items()):
        sl = SlitTraceSet.from_file(
            f'{RUN}/Calibrations/Slits_A_0_{det}.fits.gz', chk_version=False)
        i = np.where(sl.spat_id == slit)[0][0]
        mid = sl.left_init.shape[0] // 2
        cen = (sl.left_init[mid, i] + sl.right_init[mid, i]) / 2
        off = (p['A'] + p['B']) / 2 - cen
        print(f'{det} slit {slit:5d}: mean(A,B) - centre = {off:+5.1f} px '
              f'({off * 0.116:+.2f}"), A-B = {p["A"] - p["B"]:+.1f} px')


if __name__ == '__main__':
    match_slits()
    object_offsets()
