"""Plot slit edges over the trace image, colored by wavecal success.
Generated by JXP and Claude (dev script, not part of PypeIt)."""
import sys
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pypeit.edgetrace import EdgeTraceSet
from pypeit.wavecalib import WaveCalib
from pypeit.slittrace import SlitTraceSet

tag = sys.argv[1] if len(sys.argv) > 1 else 'run'
fig, ax = plt.subplots(1, 2, figsize=(16, 9))
for i, det in enumerate(['DET01', 'DET02']):
    edges = EdgeTraceSet.from_file(f'Calibrations/Edges_A_0_{det}.fits.gz',
                                   chk_version=False)
    slits = SlitTraceSet.from_file(f'Calibrations/Slits_A_0_{det}.fits.gz',
                                   chk_version=False)
    try:
        wc = WaveCalib.from_file(f'Calibrations/WaveCalib_A_0_{det}.fits',
                                 chk_version=False)
        ok = [w is not None and w.pypeitfit is not None for w in wc.wv_fits]
    except Exception:
        ok = [False] * slits.nslits
    img = edges.traceimg.image
    v = np.nanpercentile(img, [5, 99])
    ax[i].imshow(img, origin='lower', vmin=v[0], vmax=v[1], cmap='gray',
                 aspect='auto')
    left, right, _ = slits.select_edges()
    spec = np.arange(img.shape[0])
    for j in range(slits.nslits):
        c = 'lime' if ok[j] else 'red'
        ax[i].plot(left[:, j], spec, color=c, lw=0.7)
        ax[i].plot(right[:, j], spec, color=c, lw=0.7, ls='--')
        ax[i].text(slits.center[img.shape[0] // 2, j], 20,
                   str(slits.spat_id[j]), color=c, fontsize=7, rotation=90)
    ax[i].set_title(f'{det}: {slits.nslits} slits '
                    f'({sum(ok)} wavecal ok; green=ok, red=fail)')
plt.tight_layout()
plt.savefig(f'../slits_{tag}.png', dpi=70)
