"""Offline tuning of full_template for MOIRCS HK500 against the holy-grail
solutions.  Dev script; generated by JXP and Claude."""
import sys, logging
import numpy as np
from pypeit.wavecalib import WaveCalib
from pypeit.core.wavecal import autoid
from pypeit.spectrographs.util import load_spectrograph

spec = load_spectrograph('subaru_moircs')
RAW = ('/Users/xavier/Projects/PypeIt/PypeIt-development-suite/RAW_DATA/'
       'subaru_moircs/HK500/MCSP00237323.fits')


def run(det, **kw):
    hg = WaveCalib.from_file(
        f'subaru_moircs_A/Calibrations/WaveCalib_A_0_DET0{det}.fits',
        chk_version=False)
    arcs = hg.arc_spectra
    par = spec.config_specific_par(RAW)['calibrations']['wavelengths']
    for k, v in kw.items():
        if k != 'nsnippet':
            par[k] = v
    nsl = arcs.shape[1]
    fits, _ = autoid.full_template(arcs, par['lamps'], par, np.arange(nsl),
                                   det, 1, nsnippet=kw.get('nsnippet', 2),
                                   slit_ids=np.arange(nsl),
                                   measured_fwhms=[None] * nsl)
    x = np.arange(arcs.shape[0])
    out = []
    for i in range(nsl):
        f = fits.get(str(i))
        h = hg.wv_fits[i]
        if f is None or f.pypeitfit is None:
            out.append((i, None, None, None)); continue
        wt = f.pypeitfit.eval(x / (x.size - 1))
        dw = None
        if h is not None and h.pypeitfit is not None:
            # Compare where the holy-grail fit has lines
            sel = (h.wave_soln > h.wave_fit.min()) & \
                  (h.wave_soln < h.wave_fit.max())
            dw = np.median(np.abs(wt[sel] - h.wave_soln[sel]))
        out.append((i, f.rms, len(f.pixel_fit), dw))
    return out


if __name__ == '__main__':
    logging.disable(logging.INFO)
    kw = eval(f"dict({sys.argv[1] if len(sys.argv) > 1 else ''})")
    for det in [1, 2]:
        res = run(det, **kw)
        good = [r for r in res if r[1] is not None and r[1] < 0.5
                and r[2] >= 30]
        print(f'DET0{det} {kw}: {len(good)} good (rms<0.5, >=30 lines)')
        for r in res:
            print('   ', r)
