"""Offline test of 'reidentify' for MOIRCS HK500 vs holy-grail.
Dev script; generated by JXP and Claude."""
import sys, logging
import numpy as np
from pypeit.wavecalib import WaveCalib
from pypeit.core.wavecal import autoid
from pypeit.spectrographs.util import load_spectrograph

logging.disable(logging.INFO)
spec = load_spectrograph('subaru_moircs')
RAW = ('/Users/xavier/Projects/PypeIt/PypeIt-development-suite/RAW_DATA/'
       'subaru_moircs/HK500/MCSP00237323.fits')
arxiv = sys.argv[1]
kw = eval(f"dict({sys.argv[2] if len(sys.argv) > 2 else ''})")
for det in [1, 2]:
    hg = WaveCalib.from_file(
        f'subaru_moircs_A/Calibrations/WaveCalib_A_0_DET0{det}.fits',
        chk_version=False)
    arcs = hg.arc_spectra
    par = spec.config_specific_par(RAW)['calibrations']['wavelengths']
    par['method'] = 'reidentify'
    par['reid_arxiv'] = arxiv
    for k, v in kw.items():
        par[k] = v
    nsl = arcs.shape[1]
    reid = autoid.ArchiveReid(arcs, par['lamps'], par, ok_mask=np.arange(nsl),
                              measured_fwhms=[None] * nsl)
    _, fits = reid.get_results()
    x = np.arange(arcs.shape[0])
    ngood = 0
    for i in range(nsl):
        f = fits.get(str(i)); h = hg.wv_fits[i]
        if f is None or f.pypeitfit is None:
            print(f'   {det} {i:2d} spat {hg.spat_id[i] if hasattr(hg,"spat_id") else ""} none'
                  f' | hg {"ok" if h is not None and h.pypeitfit is not None else "fail"}')
            continue
        wt = f.pypeitfit.eval(x / (x.size - 1))
        dw = None
        if h is not None and h.pypeitfit is not None:
            sel = (h.wave_soln > h.wave_fit.min()) & \
                  (h.wave_soln < h.wave_fit.max())
            dw = np.median(np.abs(wt[sel] - h.wave_soln[sel]))
        good = f.rms < 0.5 and len(f.pixel_fit) >= 30 \
            and (dw is None or dw < 5)
        ngood += good
        hgs = f'hg rms {h.rms:.2f} n={len(h.wave_fit)}' \
            if h is not None and h.pypeitfit is not None else 'hg fail'
        print(f'   {det} {i:2d} rms {f.rms:.3f} n={len(f.pixel_fit):3d} '
              f'|dw|={dw if dw is None else round(dw, 2)}  ({hgs}) '
              f'{"GOOD" if good else ""}')
    print(f'DET0{det} {kw}: {ngood} good')
