"""
Check that the 2016 MOIRCS static bad-pixel masks shipped with PypeIt
(``static_calibs/subaru_moircs/bpm_moircs_det{1,2}.fits.gz``) still match
the bad pixels in the 2026 VB_K frames.

Uses raw frames only (no PypeIt reduction):

- Flat outliers: the median lamp-on minus lamp-off dome flat is divided by
  a 5x5 median-filtered version of itself; pixels in illuminated regions
  deviating by more than ``NSIG`` robust sigma are outliers.
- Hot pixels: pixels in the median lamp-off frame (7 s) more than
  ``NSIG_HOT`` robust sigma above a 5x5 median-filtered version of itself
  (the high-pass removes the thermal emission through the slits).
- Strong flat defects: flat outliers deviating by more than
  ``STRONG`` (fractional), i.e. dead or very hot pixels.
- Unmasked strong defects and hot pixels are split into compact groups
  (bounding box at most ``COMPACT`` pixels on a side; candidate detector
  defects) and elongated groups (slit gaps and alignment-box edges, i.e.
  slit structure rather than detector defects).

For each chip it reports the fraction of masked (illuminated) pixels that
are flat outliers, for the mask as shipped and for flipped/transposed
copies (controls, as in the HK500 check), and the fraction of flat outliers
and hot pixels that the mask covers (to find defects new since 2016).

Not part of PypeIt.  Generated by JXP and Claude.
"""
from pathlib import Path
import json
import sys

import numpy as np
from astropy.io import fits
from scipy import ndimage
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit import dataPaths

# The shared module vbk_paths.py (raw-data location) is one level up
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import vbk_paths  # noqa: E402

# Raw data: the minimum example set (environment variable MOIRCS_VBK_DATA)
BPM = dataPaths.static_calibs.path / 'subaru_moircs'
OUT = Path(__file__).parent
NSIG = 5.0
NSIG_HOT = 10.0
STRONG = 0.2
COMPACT = 3
# Data section (EFP-MIN = 5, EFP-RNG = 2041 -> 0-indexed 4..2043)
SEC = (slice(4, 2044), slice(4, 2044))


def median_stack(subdir, det_id):
    """
    Median-combine the primary images of all files of one chip.

    Generated by JXP and Claude.

    Args:
        subdir (:obj:`str`):
            Frame group of :data:`vbk_paths.GROUPS` (e.g.
            ``domeflat_on``).
        det_id (:obj:`int`):
            MOIRCS chip (``DET-ID``), 1 or 2.

    Returns:
        `numpy.ndarray`_: Median image (ADU), full 2048x2048 frame.
    """
    imgs = []
    for f in vbk_paths.group_files(subdir, det_id=det_id):
        imgs.append(fits.getdata(f, 0).astype(float))
    return np.median(imgs, axis=0)


def robust_sigma(x):
    """
    Robust standard deviation from the median absolute deviation.

    Generated by JXP and Claude.

    Args:
        x (`numpy.ndarray`_):
            Values.

    Returns:
        :obj:`float`: 1.4826 times the median absolute deviation.
    """
    return 1.4826 * np.median(np.abs(x - np.median(x)))


def check_chip(det_id):
    """
    Compare the static mask of one chip with flat outliers and hot pixels.

    Generated by JXP and Claude.

    Args:
        det_id (:obj:`int`):
            MOIRCS chip (``DET-ID``), 1 or 2.

    Returns:
        tuple: A :obj:`dict` of statistics and a :obj:`dict` of images
        (``flat``, ``outlier``, ``hot``, ``mask``) for the figure.
    """
    mask = fits.getdata(BPM / f'bpm_moircs_det{det_id}.fits.gz').astype(bool)
    on = median_stack('domeflat_on', det_id)
    off = median_stack('domeflat_off', det_id)
    flat = on - off

    # Illuminated pixels: well inside the slits (avoid edges and gaps)
    smooth = ndimage.median_filter(flat, size=5)
    level = np.median(smooth[SEC][smooth[SEC] > 0])
    illum = np.zeros_like(flat, dtype=bool)
    illum[SEC] = smooth[SEC] > 0.3 * level
    illum = ndimage.binary_erosion(illum, iterations=3)

    # Flat outliers: deviation from the local 5x5 median
    resid = np.zeros_like(flat)
    resid[illum] = flat[illum] / smooth[illum] - 1.
    sig = robust_sigma(resid[illum])
    outlier = illum & (np.abs(resid) > NSIG * sig)

    # Strong flat defects (dead or very hot pixels)
    strong = illum & (np.abs(resid) > STRONG)

    # Hot pixels in the lamp-off stack: high-pass first, since the K-band
    # lamp-off frames show thermal emission through the slits
    hp = off - ndimage.median_filter(off, size=5)
    hot = np.zeros_like(off, dtype=bool)
    sig_off = robust_sigma(hp[SEC])
    hot[SEC] = hp[SEC] > NSIG_HOT * sig_off

    stats = dict(det=det_id, nmask=int(mask.sum()),
                 nmask_illum=int((mask & illum).sum()),
                 flat_resid_sigma=float(sig),
                 n_outlier=int(outlier.sum()), n_strong=int(strong.sum()),
                 n_hot=int(hot.sum()))
    # Fraction of masked (illuminated) pixels that are flat outliers,
    # for the shipped mask and for orientation controls
    controls = {'as_shipped': mask, 'flip_x': mask[:, ::-1],
                'flip_y': mask[::-1, :], 'transpose': mask.T}
    for key, m in controls.items():
        n = (m & illum).sum()
        stats[f'frac_masked_outlier_{key}'] = \
            float((m & outlier).sum() / n) if n else None
    # Completeness: which outliers / hot pixels the mask covers
    stats['frac_outlier_masked'] = float((outlier & mask).sum()
                                         / max(outlier.sum(), 1))
    stats['frac_strong_masked'] = float((strong & mask).sum()
                                        / max(strong.sum(), 1))
    stats['frac_hot_masked'] = float((hot & mask).sum() / max(hot.sum(), 1))
    stats['n_unmasked_strong'] = int((strong & ~mask).sum())
    # Unmasked outliers: isolated pixels or clusters?
    new = outlier & ~mask
    lab, nlab = ndimage.label(new)
    sizes = np.bincount(lab.ravel())[1:]
    stats['n_unmasked_outlier'] = int(new.sum())
    stats['n_unmasked_groups'] = int(nlab)
    stats['largest_unmasked_group'] = int(sizes.max()) if nlab else 0
    # Unmasked hot pixels
    stats['n_unmasked_hot'] = int((hot & ~mask).sum())
    # Unmasked strong defects + hot pixels: compact vs elongated groups
    cand = (strong | hot) & ~mask
    lab, nlab = ndimage.label(cand, structure=np.ones((3, 3)))
    compact = np.zeros_like(cand)
    for k, sl in enumerate(ndimage.find_objects(lab), start=1):
        if max(sl[0].stop - sl[0].start, sl[1].stop - sl[1].start) \
                <= COMPACT:
            compact[sl] |= lab[sl] == k
    stats['n_unmasked_compact_px'] = int(compact.sum())
    stats['n_unmasked_compact_groups'] = int(
        ndimage.label(compact, structure=np.ones((3, 3)))[1])
    stats['n_unmasked_elongated_px'] = int((cand & ~compact).sum())
    stats['frac_new_vs_mask'] = float(compact.sum() / mask.sum())
    return stats, dict(flat=flat, outlier=outlier, hot=hot, mask=mask,
                       illum=illum, strong=strong, compact=compact)


def main():
    """
    Run the check on both chips, print and save the statistics and a figure.

    Generated by JXP and Claude.
    """
    allstats = []
    fig, ax = plt.subplots(2, 3, figsize=(18, 12))
    for i, det_id in enumerate([1, 2]):
        stats, img = check_chip(det_id)
        allstats.append(stats)
        print(json.dumps(stats, indent=1))
        lo, hi = np.percentile(img['flat'][SEC], [2, 98])
        ax[i, 0].imshow(img['flat'], origin='lower', cmap='gray',
                        vmin=lo, vmax=hi)
        ax[i, 0].set_title(f'chip {det_id}: lamp-on - lamp-off (median)')
        # Masked pixels (red), unmasked flat outliers (cyan)
        rgb = np.zeros(img['flat'].shape + (3,))
        rgb[..., 0] = ndimage.binary_dilation(img['mask'], iterations=2)
        new = img['compact']
        rgb[..., 1] = ndimage.binary_dilation(new, iterations=2)
        rgb[..., 2] = rgb[..., 1]
        ax[i, 1].imshow(rgb, origin='lower')
        ax[i, 1].set_title(f'chip {det_id}: mask (red), unmasked compact '
                           'defects (cyan); dilated x2')
        # Zoom on a central region, flat with mask contours
        zs = (slice(900, 1100), slice(900, 1100))
        ax[i, 2].imshow(img['flat'][zs], origin='lower', cmap='gray',
                        vmin=lo, vmax=hi)
        yy, xx = np.nonzero(img['mask'][zs])
        ax[i, 2].scatter(xx, yy, s=12, facecolors='none', edgecolors='r')
        yy, xx = np.nonzero(img['compact'][zs])
        ax[i, 2].scatter(xx, yy, s=12, marker='x', color='c')
        ax[i, 2].set_title(f'chip {det_id}: zoom x,y=900-1100 '
                           '(o masked, x unmasked defect)')
    plt.tight_layout()
    plt.savefig(OUT / 'bpm_check_vbk.png', dpi=60)
    with open(OUT / 'bpm_check_vbk.json', 'w') as fh:
        json.dump(allstats, fh, indent=1)


if __name__ == '__main__':
    main()
