"""
Check whether the unmasked compact defects found by ``check_bpm.py`` are
persistent detector defects or noise: repeat the detection on two
independent halves of the lamp-on/lamp-off frames (exposures 1-3 vs 4-7)
and count how many candidates are found in both.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json

import numpy as np
from astropy.io import fits
from scipy import ndimage

import check_bpm as cb


def stack(subdir, det_id, idx):
    """
    Median-combine a subset of the files of one chip.

    Generated by JXP and Claude.

    Args:
        subdir (:obj:`str`):
            Frame group of ``vbk_paths.GROUPS``.
        det_id (:obj:`int`):
            MOIRCS chip (``DET-ID``).
        idx (:obj:`slice`):
            Which exposures (in time order) to use.

    Returns:
        `numpy.ndarray`_: Median image (ADU).
    """
    files = cb.vbk_paths.group_files(subdir, det_id=det_id)[idx]
    return np.median([fits.getdata(f, 0).astype(float) for f in files],
                     axis=0)


def flags(on, off):
    """
    Strong flat defects and hot pixels for one set of frames, as in
    ``check_bpm.check_chip``.

    Generated by JXP and Claude.

    Args:
        on (`numpy.ndarray`_):
            Lamp-on stack.
        off (`numpy.ndarray`_):
            Lamp-off stack.

    Returns:
        `numpy.ndarray`_: Boolean image of flagged pixels.
    """
    flat = on - off
    smooth = ndimage.median_filter(flat, size=5)
    level = np.median(smooth[cb.SEC][smooth[cb.SEC] > 0])
    illum = np.zeros_like(flat, dtype=bool)
    illum[cb.SEC] = smooth[cb.SEC] > 0.3 * level
    illum = ndimage.binary_erosion(illum, iterations=3)
    resid = np.zeros_like(flat)
    resid[illum] = flat[illum] / smooth[illum] - 1.
    strong = illum & (np.abs(resid) > cb.STRONG)
    hp = off - ndimage.median_filter(off, size=5)
    hot = np.zeros_like(off, dtype=bool)
    hot[cb.SEC] = hp[cb.SEC] > cb.NSIG_HOT * cb.robust_sigma(hp[cb.SEC])
    return strong | hot


def main():
    """
    Print, per chip, how many of the compact candidates from the full
    stacks are flagged in both independent halves.

    Generated by JXP and Claude.
    """
    out = []
    for det_id in [1, 2]:
        _, img = cb.check_chip(det_id)
        cand = img['compact']
        fa = flags(stack('domeflat_on', det_id, slice(0, 3)),
                   stack('domeflat_off', det_id, slice(0, 3)))
        fb = flags(stack('domeflat_on', det_id, slice(3, 7)),
                   stack('domeflat_off', det_id, slice(3, 7)))
        # Allow a 1-pixel tolerance
        fa = ndimage.binary_dilation(fa)
        fb = ndimage.binary_dilation(fb)
        both = cand & fa & fb
        res = dict(det=det_id, n_candidates=int(cand.sum()),
                   n_in_both_halves=int(both.sum()),
                   frac_persistent=float(both.sum() / max(cand.sum(), 1)),
                   # Same check for the shipped mask (reference)
                   frac_mask_persistent=float(
                       (img['mask'] & img['illum'] & fa & fb).sum()
                       / max((img['mask'] & img['illum']).sum(), 1)))
        print(res)
        out.append(res)
    with open(cb.OUT / 'persistence_check.json', 'w') as fh:
        json.dump(out, fh, indent=1)


if __name__ == '__main__':
    main()
