"""
Search a 2D-coadded VB_K spec2d file for emission-line candidates.

The coadd of A-B and B-A frames (aligned on the positive trace) shows a
real source as a positive image with two negative images at about the
dither offset on either side, each with half the flux.  For each science
slit:

1. the continuum is removed with a running median along the spectral
   direction (each spatial column separately);
2. a matched filter (2D Gaussian, the size of an unresolved line from a
   compact source) turns the image into an S/N map,
   ``S/N = conv(f * ivar, k) / sqrt(conv(ivar, k**2))``;
3. local maxima above ``--snr`` are candidates;
4. each candidate is checked for the negative images at
   ``+/- --offset`` pixels;
5. it is flagged when it lies within ``--sky_tol`` of a sky emission line
   (a possible sky residual).  The sky lines are found in the OH spectra
   of the slits stored in the run's ``WaveCalib`` file, so lines missing
   from the line lists are included.  (The sky model of a 2D coadd of A-B
   frames holds almost no sky lines.)
6. candidates in other slits at the same wavelength (+/-
   ``--repeat_tol``) are noted: they could be sky residuals missed by
   step 5, or sources at the same redshift.

Writes a candidate table for all inputs, a detector-wide S/N map per
detector with the candidates marked, and postage stamps with a 1D boxcar
spectrum of the candidates with negative images and no sky line.

Usage::

    python find_emission_lines.py <outdir> <coadd spec2d>:<det>:<WaveCalib>

Generated by JXP and Claude
"""

import argparse
from pathlib import Path

import matplotlib
import numpy as np
from scipy import ndimage

from pypeit import spec2dobj
from pypeit.wavecalib import WaveCalib

matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402 (after the backend is set)


def snr_map(img, ivar, gpm, sig_spec=2.5, sig_spat=2.5, cont_width=51):
    """
    Matched-filter S/N map of the continuum-subtracted image.

    Generated by JXP and Claude

    Args:
        img (`numpy.ndarray`_):
            Sky-subtracted image (spectral, spatial).
        ivar (`numpy.ndarray`_):
            Inverse variance of ``img``.
        gpm (`numpy.ndarray`_):
            Good-pixel mask.
        sig_spec (:obj:`float`, optional):
            Gaussian sigma of the filter along the spectrum (pixels).
        sig_spat (:obj:`float`, optional):
            Gaussian sigma of the filter along the slit (pixels).
        cont_width (:obj:`int`, optional):
            Width of the running median that removes the continuum
            (spectral pixels).

    Returns:
        tuple: The continuum-subtracted image and the S/N map.
    """
    w = np.where(gpm, ivar, 0.)
    f = np.where(gpm, img, 0.)
    # Continuum: running median along the spectral axis
    cont = ndimage.median_filter(f, size=(cont_width, 1), mode='nearest')
    hp = f - cont
    # Matched filter with a separable Gaussian kernel k (normalized to a
    # peak of 1; the normalization cancels in the S/N)
    num = ndimage.gaussian_filter(hp * w, (sig_spec, sig_spat),
                                  mode='constant')
    den = ndimage.gaussian_filter(w, (sig_spec / np.sqrt(2.),
                                      sig_spat / np.sqrt(2.)),
                                  mode='constant')
    # gaussian_filter normalizes its kernel to unit sum: num is
    # conv(f*ivar, k) / (2 pi s1 s2) and den is conv(ivar, k**2) /
    # (pi s1 s2) for the peak-1 kernel k, so the S/N needs this factor
    fac = 2. * np.sqrt(np.pi * sig_spec * sig_spat)
    with np.errstate(invalid='ignore', divide='ignore'):
        snr = fac * num / np.sqrt(den)
    return hp, np.where(den > 0, snr, 0.)


def find_candidates(snr, slitmask, spat_ids, sky_waves, waveimg, offset,
                    thresh, sky_tol=8., edge=4):
    """
    Find local S/N maxima in the science slits and characterize them.

    Generated by JXP and Claude

    Args:
        snr (`numpy.ndarray`_):
            Matched-filter S/N map.
        slitmask (`numpy.ndarray`_):
            Slit ID of each pixel (-1 outside the slits).
        spat_ids (:obj:`list`):
            IDs of the science slits to search.
        sky_waves (`numpy.ndarray`_):
            Wavelengths of the sky emission lines (A).
        waveimg (`numpy.ndarray`_):
            Wavelength of each pixel.
        offset (:obj:`float`):
            Distance of the negative images (pixels).
        thresh (:obj:`float`):
            S/N threshold.
        sky_tol (:obj:`float`, optional):
            Distance (A) from a sky line within which a candidate is
            flagged.
        edge (:obj:`int`, optional):
            Pixels ignored at each slit edge.

    Returns:
        :obj:`list`: One dict per candidate.
    """
    cands = []
    peak = (snr == ndimage.maximum_filter(snr, size=(9, 9))) \
        & (snr > thresh)
    for sid in spat_ids:
        inslit = slitmask == sid
        # Shrink the slit by ``edge`` pixels on each side
        inner = ndimage.binary_erosion(inslit, np.ones((1, 2 * edge + 1)))
        for row, col in zip(*np.where(peak & inner)):
            negs = []
            for sgn in [-1, 1]:
                c = int(round(col + sgn * offset))
                lo, hi = max(c - 3, 0), min(c + 4, snr.shape[1])
                box = (slice(max(row - 3, 0), row + 4), slice(lo, hi))
                if np.all(slitmask[box] == sid):
                    negs.append(float(np.min(snr[box])))
            # A real source has its negative images at about -1/2 of its
            # S/N; require their mean to be clearly negative
            neg_ok = len(negs) > 0 \
                and np.mean(negs) < -0.25 * snr[row, col]
            cands.append(dict(
                slit=int(sid), row=int(row), col=int(col),
                wave=float(waveimg[row, col]), snr=float(snr[row, col]),
                negs=negs, neg_ok=neg_ok,
                oh=bool(np.any(np.abs(sky_waves - waveimg[row, col])
                               < sky_tol))))
    return cands


def sky_lines(wavecalib_file, nsig=5., width=51):
    """
    Find the sky emission lines in the OH spectra of a ``WaveCalib`` file.

    Generated by JXP and Claude

    Args:
        wavecalib_file (:obj:`str`):
            ``WaveCalib`` file of the reduction.
        nsig (:obj:`float`, optional):
            Detection threshold (robust sigma of the continuum-subtracted
            spectrum).
        width (:obj:`int`, optional):
            Width of the running median that removes the continuum.

    Returns:
        `numpy.ndarray`_: Wavelengths (A) of the sky-line peaks, from all
        solved slits.
    """
    wc = WaveCalib.from_file(wavecalib_file, chk_version=False)
    waves = []
    for i, w in enumerate(wc.wv_fits):
        if w is None or w.pypeitfit is None:
            continue
        spec = wc.arc_spectra[:, i]
        hp = spec - ndimage.median_filter(spec, size=width, mode='nearest')
        noise = 1.4826 * np.median(np.abs(hp - np.median(hp)))
        pk = (hp == ndimage.maximum_filter(hp, size=5)) & (hp > nsig * noise)
        waves.append(w.wave_soln[pk])
    return np.concatenate(waves) if waves else np.zeros(0)


def plot_map(snr, slitmask, cands, title, outfile):
    """
    Plot the detector-wide S/N map with the candidates marked.

    Generated by JXP and Claude

    Args:
        snr (`numpy.ndarray`_):
            S/N map.
        slitmask (`numpy.ndarray`_):
            Slit ID image (-1 outside the slits).
        cands (:obj:`list`):
            Candidates from :func:`find_candidates`.
        title (:obj:`str`):
            Plot title.
        outfile (`Path`_):
            Output PNG.
    """
    fig, ax = plt.subplots(figsize=(9, 9))
    show = np.where(slitmask >= 0, snr, np.nan)
    ax.imshow(show, origin='lower', cmap='gray', vmin=-4, vmax=6,
              aspect='auto', interpolation='nearest')
    for c in cands:
        color = 'tab:red' if c.get('good') else 'tab:orange'
        ax.plot(c['col'], c['row'], 'o', mfc='none', mec=color, ms=12,
                mew=1.5)
    ax.set_xlabel('spatial pixel')
    ax.set_ylabel('spectral pixel')
    ax.set_title(title + '\nred: negative images and no sky line; '
                 'orange: no negative images or on a sky line',
                 loc='left', fontsize=9)
    fig.tight_layout()
    fig.savefig(outfile, dpi=100)
    plt.close(fig)


def plot_stamps(cands, hp, snr, ivar, gpm, waveimg, slitmask, offset,
                title, outfile, half_spec=60, half_spat=45):
    """
    Plot a postage stamp and a 1D boxcar spectrum for each candidate.

    Generated by JXP and Claude

    Args:
        cands (:obj:`list`):
            Candidates to plot.
        hp (`numpy.ndarray`_):
            Continuum-subtracted image.
        snr (`numpy.ndarray`_):
            S/N map.
        ivar (`numpy.ndarray`_):
            Inverse variance.
        gpm (`numpy.ndarray`_):
            Good-pixel mask.
        waveimg (`numpy.ndarray`_):
            Wavelength image.
        slitmask (`numpy.ndarray`_):
            Slit ID image.
        offset (:obj:`float`):
            Distance of the negative images (pixels).
        title (:obj:`str`):
            Figure title.
        outfile (`Path`_):
            Output PNG.
        half_spec (:obj:`int`, optional):
            Half height of the stamps (spectral pixels).
        half_spat (:obj:`int`, optional):
            Half width of the stamps (spatial pixels).
    """
    if len(cands) == 0:
        return
    n = len(cands)
    fig, axes = plt.subplots(n, 2, figsize=(9, 2.4 * n), squeeze=False,
                             gridspec_kw=dict(width_ratios=[1, 2.2]))
    nspec, nspat = hp.shape
    for ax2, ax1, c in zip(axes[:, 0], axes[:, 1], cands):
        r0, r1 = max(c['row'] - half_spec, 0), min(c['row'] + half_spec,
                                                   nspec)
        c0, c1 = max(c['col'] - half_spat, 0), min(c['col'] + half_spat,
                                                   nspat)
        stamp = np.where(slitmask[r0:r1, c0:c1] == c['slit'],
                         snr[r0:r1, c0:c1], np.nan)
        ax2.imshow(stamp, origin='lower', cmap='gray', vmin=-4, vmax=6,
                   aspect='auto', extent=(c0, c1, r0, r1))
        for dx in [0, -offset, offset]:
            ax2.axvline(c['col'] + dx, color='tab:red', lw=0.6,
                        ls='-' if dx == 0 else ':')
        ax2.set_title(f"slit {c['slit']}  S/N {c['snr']:.1f}", fontsize=8,
                      loc='left')
        ax2.tick_params(labelsize=7)
        # 1D boxcar spectrum (+/- 4 px) at the candidate, in the
        # continuum-subtracted image; inverse-variance weighted per row
        cols = slice(max(c['col'] - 4, 0), c['col'] + 5)
        w = np.where(gpm[:, cols], ivar[:, cols], 0.)
        flux = np.sum(np.where(gpm[:, cols], hp[:, cols], 0.), axis=1)
        err = np.sqrt(np.sum(np.where(w > 0, 1. / np.where(w > 0, w, 1.),
                                      0.), axis=1))
        wv = waveimg[:, c['col']]
        sel = slice(max(c['row'] - 150, 0), min(c['row'] + 150, nspec))
        ax1.step(wv[sel] / 1e4, flux[sel], where='mid', lw=0.8,
                 color='k')
        ax1.fill_between(wv[sel] / 1e4, -err[sel], err[sel], step='mid',
                         color='0.8')
        ax1.axvline(c['wave'] / 1e4, color='tab:red', lw=0.6)
        ax1.set_title(f"{c['wave']:.1f} A"
                      + ('  (sky line)' if c['oh'] else '')
                      + ('  (same wavelength in another slit)'
                         if c.get('repeat') else '')
                      + ('' if c['neg_ok'] else '  (no negative images)'),
                      fontsize=8, loc='left')
        ax1.tick_params(labelsize=7)
    axes[-1, 1].set_xlabel('wavelength (um)')
    fig.suptitle(title, fontsize=10, x=0.01, ha='left')
    fig.tight_layout()
    fig.savefig(outfile, dpi=90)
    plt.close(fig)


def main():
    """
    Command-line entry point.

    Generated by JXP and Claude
    """
    p = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    p.add_argument('outdir', type=Path)
    p.add_argument('inputs', nargs='+',
                   help='2D-coadded spec2d file, detector and WaveCalib '
                        'file, as file:det:wavecalib')
    p.add_argument('--snr', type=float, default=5.,
                   help='S/N threshold of the matched filter')
    p.add_argument('--offset', type=float, default=26.,
                   help='distance of the negative images (pixels)')
    p.add_argument('--sky_tol', type=float, default=8.,
                   help='distance from a sky line that is flagged (A)')
    p.add_argument('--repeat_tol', type=float, default=6.,
                   help='wavelength tolerance of the repeat test (A)')
    args = p.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    data, allc = {}, []
    for inp in args.inputs:
        fname, det, wcfile = inp.split(':')
        det = f'DET0{int(det)}'
        sky_waves = sky_lines(wcfile)
        s2d = spec2dobj.Spec2DObj.from_file(fname, det, chk_version=False)
        img = s2d.sciimg - s2d.skymodel
        gpm = (s2d.bpmmask.mask == 0) & (s2d.ivarmodel > 0)
        hp, snr = snr_map(img, s2d.ivarmodel, gpm)
        slitmask = s2d.slits.slit_img()
        sci = s2d.slits.mask == 0
        cands = find_candidates(snr, slitmask, list(s2d.slits.spat_id[sci]),
                                sky_waves, s2d.waveimg, args.offset,
                                args.snr, sky_tol=args.sky_tol)
        for c in cands:
            c['det'] = det
        allc += cands
        data[det] = (s2d, hp, snr, gpm, slitmask, Path(fname).name)

    # Repeat test: another slit with a candidate at the same wavelength
    for c in allc:
        c['repeat'] = any((o['det'], o['slit']) != (c['det'], c['slit'])
                          and abs(o['wave'] - c['wave']) < args.repeat_tol
                          for o in allc)
        c['good'] = c['neg_ok'] and not c['oh']
    allc.sort(key=lambda c: -c['snr'])

    lines = [f'# {len(allc)} peaks with S/N > {args.snr}; good = negative '
             'images present and no sky line within '
             f'{args.sky_tol:.0f} A; repeat = a candidate in another slit '
             f'within {args.repeat_tol:.0f} A',
             '# det    slit   row   col   wave(A)    S/N    negatives '
             'neg_ok sky  repeat good']
    for c in allc:
        negs = ','.join(f'{n:.1f}' for n in c['negs']) or '-'
        lines.append(f"{c['det']} {c['slit']:5d} {c['row']:5d} "
                     f"{c['col']:5d} {c['wave']:9.1f} {c['snr']:6.1f} "
                     f"{negs:>12s} {str(c['neg_ok']):>6s} "
                     f"{str(c['oh']):>5s} {str(c['repeat']):>6s} "
                     f"{str(c['good']):>5s}")
    (args.outdir / 'candidates.txt').write_text('\n'.join(lines) + '\n')
    print('\n'.join(lines))

    for det, (s2d, hp, snr, gpm, slitmask, name) in data.items():
        cands = [c for c in allc if c['det'] == det]
        plot_map(snr, slitmask, cands, f'{name[:40]}... {det}',
                 args.outdir / f'snr_map_{det}.png')
        plot_stamps([c for c in cands if c['good']], hp, snr,
                    s2d.ivarmodel, gpm, s2d.waveimg, slitmask, args.offset,
                    f'{det}: candidates with negative images, no sky line',
                    args.outdir / f'stamps_{det}.png')


if __name__ == '__main__':
    main()
