"""
Figures for the summary of the full science set (2D coadd and lines).

Two coadds can be shown (``--variant``): ``header`` (``coadd2d/``,
header dither offsets, uniform weights; figures in ``lines/``) and
``bright`` (``coadd2d_bright/``, offsets and weights from the DET01
target; figures in ``lines_bright/``).  Writes:

- ``stamps_selected.png``: postage stamps (matched-filter S/N) and 1D
  boxcar spectra of the candidates kept after the visual check;
- ``target_1d.png``: the 1D spectrum of the DET01 target from the 2D
  coadd (counts, optimal extraction), lightly smoothed;
- ``drift.png`` (``bright`` only): the target's position in each frame
  and the coadd offsets from the target and from the headers.

Usage::

    python make_summary_figs.py --variant bright

Generated by JXP and Claude
"""

import argparse
from pathlib import Path

import matplotlib
import numpy as np
from scipy import ndimage

from pypeit import spec2dobj
from pypeit.specobjs import SpecObjs

from find_emission_lines import plot_stamps, snr_map
from make_coadd2d_bright import read_offsets, target_objects

matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402 (after the backend is set)

HERE = Path(__file__).resolve().parent
COADD = HERE / '{}' / 'det{}' / 'Science_coadd' \
    / '{}_MCSA00352031-MCSA00352103-CC0958_PA200_1.fits'
VARIANTS = {'header': ('coadd2d', 'lines'),
            'bright': ('coadd2d_bright', 'lines_bright')}
# Candidates kept after the visual check (<outdir>/candidates.txt):
# (det, coadd slit, row, column, wavelength, S/N, run5 slit).  Coadd slit
# IDs differ between the two coadds.
SELECTED = {
    'header': [
        (1, 1822, 995, 1811, 23097.4, 8.9, 1855),
        (2, 76, 883, 73, 23075.2, 7.1, 314),
        (1, 928, 1039, 931, 23069.9, 6.8, 1003),
        (2, 594, 1492, 594, 23111.2, 6.3, 787),
        (2, 866, 1051, 869, 23117.5, 5.2, 1017),
        (2, 1014, 263, 997, 20702.1, 5.6, 1179),
        (1, 86, 895, 86, 23265.4, 5.3, 98)],
    # DET02 884 (= header 866) peaks at S/N 4.7, below the search
    # threshold; it is shown for comparison
    'bright': [
        (1, 1864, 995, 1854, 23097.4, 8.8, 1855),
        (2, 78, 882, 76, 23073.2, 6.1, 314),
        (1, 952, 1039, 955, 23069.9, 6.7, 1003),
        (2, 606, 1492, 606, 23111.2, 6.0, 787),
        (2, 884, 1050, 890, 23115.6, 4.7, 1017),
        (2, 1036, 264, 1020, 20704.1, 6.7, 1179),
        (1, 87, 895, 87, 23265.5, 5.0, 98)],
}
# Not kept: the target-slit peak at 20088 A (S/N 6.7-7.2) lies in the
# 2.0 um CO2 telluric band, where the target's continuum changes quickly.


def selected_stamps(variant, outfile):
    """
    Plot the stamps of the selected candidates, both detectors in one
    figure.

    Generated by JXP and Claude

    Args:
        variant (:obj:`str`):
            ``header`` or ``bright``.
        outfile (`Path`_):
            Output PNG.
    """
    selected = SELECTED[variant]
    panels = []
    for det in [1, 2]:
        f = str(COADD).format(VARIANTS[variant][0], det, 'spec2d')
        s2d = spec2dobj.Spec2DObj.from_file(f, f'DET0{det}',
                                            chk_version=False)
        gpm = (s2d.bpmmask.mask == 0) & (s2d.ivarmodel > 0)
        hp, snr = snr_map(s2d.sciimg - s2d.skymodel, s2d.ivarmodel, gpm)
        slitmask = s2d.slits.slit_img()
        for d, sid, row, col, wave, sn, run5 in selected:
            if d != det:
                continue
            cand = dict(slit=sid, row=row, col=col, wave=wave, snr=sn,
                        oh=False, neg_ok=True)
            tmp = outfile.with_name(f'_stamp_{det}_{sid}_{row}.png')
            plot_stamps([cand], hp, snr, s2d.ivarmodel, gpm, s2d.waveimg,
                        slitmask, 26., f'DET0{det} slit {sid} '
                        f'(run5 slit {run5})', tmp)
            panels.append(tmp)
    # Stack the single-candidate figures vertically, in the listed order
    order = [outfile.with_name(f'_stamp_{d}_{s}_{r}.png')
             for d, s, r, *_ in selected]
    imgs = [plt.imread(p) for p in order]
    width = max(i.shape[1] for i in imgs)
    rows = [np.pad(i, ((0, 0), (0, width - i.shape[1]), (0, 0)),
                   constant_values=1.) for i in imgs]
    plt.imsave(outfile, np.vstack(rows))
    for p in panels:
        p.unlink()


def target_1d(variant, outfile, smooth=3):
    """
    Plot the coadded 1D spectrum of the DET01 target.

    Generated by JXP and Claude

    Args:
        variant (:obj:`str`):
            ``header`` or ``bright``.
        outfile (`Path`_):
            Output PNG.
        smooth (:obj:`int`, optional):
            Width of the boxcar smoothing (pixels) for display.
    """
    sobjs = SpecObjs.from_fitsfile(
        str(COADD).format(VARIANTS[variant][0], 1, 'spec1d'),
        chk_version=False)
    # The target is the highest-S/N object on DET01
    obj = max([s for s in sobjs if s.DET == 'DET01'], key=lambda s: s.S2N)
    wave, flux = obj.OPT_WAVE, obj.OPT_COUNTS
    ivar, gpm = obj.OPT_COUNTS_IVAR, obj.OPT_MASK & (obj.OPT_WAVE > 1e4)
    err = np.where(ivar > 0, 1. / np.sqrt(np.where(ivar > 0, ivar, 1.)),
                   np.nan)
    fs = ndimage.uniform_filter1d(np.where(gpm, flux, 0.), smooth)
    fig, ax = plt.subplots(figsize=(9, 3.6))
    ax.fill_between(wave[gpm] / 1e4, -err[gpm], err[gpm], color='0.85',
                    step='mid', label='1 sigma per pixel')
    ax.step(wave[gpm] / 1e4, fs[gpm], where='mid', color='k', lw=0.7,
            label=f'counts ({smooth}-px boxcar)')
    ax.axvspan(1.90, 1.98, color='tab:blue', alpha=0.08, lw=0)
    ax.text(1.902, 0.92, 'deep telluric bands',
            transform=ax.get_xaxis_transform(), fontsize=8,
            color='tab:blue')
    ax.axvspan(2.00, 2.06, color='tab:orange', alpha=0.08, lw=0)
    ax.text(2.002, 0.92, 'CO2 bands', transform=ax.get_xaxis_transform(),
            fontsize=8, color='tab:orange')
    ax.axvline(2.00882, color='tab:red', lw=0.8, ls=':')
    ax.set_xlabel('wavelength (um)')
    ax.set_ylabel('counts (2D coadd)')
    ax.set_title(f'DET01 target (run5 slit 469): {obj.NAME}, '
                 f'S/N {obj.S2N:.1f}; dotted: 20088 A peak (not kept)',
                 loc='left', fontsize=9)
    ax.legend(fontsize=8, frameon=False, loc='upper right')
    lo, hi = np.nanpercentile(fs[gpm], [1, 99.5])
    ax.set_ylim(min(lo, -3 * np.nanmedian(err[gpm])), 1.3 * hi)
    fig.tight_layout()
    fig.savefig(outfile, dpi=110)
    plt.close(fig)


def drift(outfile, platescale=0.116):
    """
    Plot the target's position per frame and the two sets of offsets.

    Generated by JXP and Claude

    Args:
        outfile (`Path`_):
            Output PNG.
        platescale (:obj:`float`, optional):
            Arcsec per spatial pixel.
    """
    objs = target_objects()
    sci = HERE / 'det1' / 'Science'
    files = sorted(sci.glob('spec1d_*.fits'))
    mjd, dith = [], []
    for f in files:
        hdr = SpecObjs.from_fitsfile(str(f), chk_version=False).header
        mjd.append(hdr['MJD'])
        dith.append(hdr['DITHOFF'])
    ut = (np.array(mjd) % 1) * 24.
    pos = np.array([o.SPAT_PIXPOS for o in objs])
    dith = np.array(dith)
    isa = dith < 0
    off_t = read_offsets(HERE / 'coadd2d_bright' / 'det1' / 'run.log')
    off_h = (dith - dith[0]) / platescale
    fig, axes = plt.subplots(2, 1, figsize=(8, 5.6), sharex=True)
    ax = axes[0]
    for sel, lab, col in [(isa, 'A frames', 'tab:blue'),
                          (~isa, 'B frames', 'tab:orange')]:
        ax.plot(ut[sel], pos[sel] - np.median(pos[sel]), 'o-', color=col,
                ms=4, lw=0.8, label=lab)
    ax.axhline(0, color='0.5', lw=0.6)
    ax.set_ylabel('target position - median (px)')
    ax.set_title('DET01 target position along the slit in each A-B frame',
                 loc='left', fontsize=9)
    ax.legend(fontsize=8, frameon=False)
    ax = axes[1]
    ax.plot(ut, off_t - off_h, 'ko', ms=4,
            label='offset from the target - offset from the headers')
    ax.axhline(0, color='0.5', lw=0.6)
    ax.set_ylabel('offset difference (px)')
    ax.set_xlabel('UT (h), 2026-05-29')
    ax.legend(fontsize=8, frameon=False)
    fig.tight_layout()
    fig.savefig(outfile, dpi=110)
    plt.close(fig)


def main():
    """
    Write the summary figures.

    Generated by JXP and Claude
    """
    p = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    p.add_argument('--variant', choices=list(VARIANTS), default='bright')
    args = p.parse_args()
    out = HERE / VARIANTS[args.variant][1]
    out.mkdir(exist_ok=True)
    selected_stamps(args.variant, out / 'stamps_selected.png')
    target_1d(args.variant, out / 'target_1d.png')
    if args.variant == 'bright':
        drift(out / 'drift.png')
    print(f'Wrote the figures to {out}')


if __name__ == '__main__':
    main()
