"""
Write the 2D-coadd files that align the frames on the continuum target.

The DET01 target (run slit 469) is detected in every A-B frame at S/N
~1.  Its position gives the offsets between frames, including the
spatial drift during the night that the header dither offsets do not
record.  The two detectors are assumed to share the same relative
offsets, so DET02 (no bright object) uses the DET01 values.

Two steps:

``det1``
    Write ``coadd2d_bright/det1/vbk_sci_all_det1.coadd2d`` with
    ``offsets = auto``, ``weights = auto`` and ``user_obj_ids`` set to
    the target's ``SPAT_PIXPOS_ID`` in each frame (PypeIt requires
    ``weights = auto`` with ``user_obj_ids``).  Then run
    ``pypeit_coadd_2dspec`` on it (log in ``run.log``).
``det2``
    Read the offsets from the DET01 log, compute the weights as
    ``pypeit_coadd_2dspec`` does (:func:`pypeit.core.coadd.sn_weights` on
    the target's optimal extraction; constant weights for S/N < 3), and
    write ``coadd2d_bright/det2/vbk_sci_all_det2.coadd2d`` with both as
    lists.

Usage::

    python make_coadd2d_bright.py det1
    (run pypeit_coadd_2dspec in coadd2d_bright/det1)
    python make_coadd2d_bright.py det2

Generated by JXP and Claude
"""

import argparse
import re
from pathlib import Path

import numpy as np

from pypeit.core import coadd
from pypeit.specobjs import SpecObjs

HERE = Path(__file__).resolve().parent
OUT = HERE / 'coadd2d_bright'
TARGET_SLIT = 469


def spec2d_files(det):
    """
    List the spec2d files of one detector, in the order used for coadds.

    Generated by JXP and Claude

    Args:
        det (:obj:`int`):
            Detector (1 or 2).

    Returns:
        tuple: The Science directory and the sorted file names.
    """
    sci = HERE / f'det{det}' / 'Science'
    return sci, sorted(p.name for p in sci.glob('spec2d_*.fits'))


def target_objects():
    """
    Find the target in the DET01 spec1d file of each frame.

    Generated by JXP and Claude

    Returns:
        :obj:`list`: The target's :class:`~pypeit.specobj.SpecObj` in each
        frame, in the order of :func:`spec2d_files`.

    Raises:
        ValueError: If a frame does not have exactly one object in the
        target slit.
    """
    sci, files = spec2d_files(1)
    objs = []
    for f in files:
        s1 = sci / f.replace('spec2d_', 'spec1d_')
        t = [s for s in SpecObjs.from_fitsfile(str(s1), chk_version=False)
             if s.SLITID == TARGET_SLIT and s.DET == 'DET01']
        if len(t) != 1:
            raise ValueError(f'{len(t)} objects in slit {TARGET_SLIT} of {f}')
        objs.append(t[0])
    return objs


def write_coadd2d(det, coadd2d_lines, header):
    """
    Write a ``.coadd2d`` file for one detector.

    Generated by JXP and Claude

    Args:
        det (:obj:`int`):
            Detector (1 or 2).
        coadd2d_lines (:obj:`list`):
            Lines of the ``[coadd2d]`` block (without the header line).
        header (:obj:`list`):
            Comment lines at the top of the file.

    Returns:
        `Path`_: The file written.
    """
    sci, files = spec2d_files(det)
    lines = header + ['[rdx]', '  spectrograph = subaru_moircs',
                      f'  detnum = {det}', '', '[coadd2d]'] \
        + coadd2d_lines + ['', 'spec2d read', f'  path {sci}', '  filename'] \
        + [f'  {f}' for f in files] + ['spec2d end', '']
    out = OUT / f'det{det}' / f'vbk_sci_all_det{det}.coadd2d'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines))
    return out


def read_offsets(logfile):
    """
    Read the offsets table that ``pypeit_coadd_2dspec`` logs.

    Generated by JXP and Claude

    Args:
        logfile (`Path`_):
            Log of the DET01 coadd.

    Returns:
        `numpy.ndarray`_: Offsets in pixels, one per file.
    """
    text = re.sub(r'\x1b\[[0-9;]*m', '', logfile.read_text())
    block = text.split('Summary of offsets from user object')[1]
    rows = re.findall(r'^\s+(\d+)\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s*$',
                      block.split('Performing 2D coadd')[0], flags=re.M)
    return np.array([float(r[1]) for r in rows])


def target_weights(objs, nspec=2040):
    """
    Compute the frame weights from the target, as the 2D coadd does.

    Generated by JXP and Claude

    Args:
        objs (:obj:`list`):
            Target :class:`~pypeit.specobj.SpecObj` in each frame.
        nspec (:obj:`int`, optional):
            Number of spectral pixels (sets ``sn_smooth_npix`` to 10% of
            it, as in :class:`~pypeit.coadd2d.CoAdd2D`).

    Returns:
        tuple: The rms S/N and the (scalar) weight of each frame.
    """
    fluxes, ivars, gpms = [], [], []
    for o in objs:
        _, flux, ivar, gpm = o.get_opt_ext()
        fluxes.append(flux)
        ivars.append(ivar)
        gpms.append(gpm)
    rms_sn, weights = coadd.sn_weights(fluxes, ivars, gpms,
                                       sn_smooth_npix=0.1 * nspec,
                                       weight_method='auto')
    return np.asarray(rms_sn), np.array([np.median(w) for w in weights])


def main():
    """
    Command-line entry point.

    Generated by JXP and Claude
    """
    p = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    p.add_argument('step', choices=['det1', 'det2'])
    args = p.parse_args()

    if args.step == 'det1':
        ids = [int(o.SPAT_PIXPOS_ID) for o in target_objects()]
        out = write_coadd2d(1, [
            '  offsets = auto', '  weights = auto',
            '  user_obj_ids = ' + ', '.join(str(i) for i in ids)], [
            '# VB_K mask MO_CC0958PA200_1: 2D coadd of the 32 science '
            'frames, DET01.',
            '# Offsets and weights from the continuum target in slit 469',
            '# (user_obj_ids: its SPAT_PIXPOS_ID in each frame, in the',
            '# order of the files).  DET02 uses the offsets and weights',
            '# found here.'])
        print(f'Wrote {out}')
        return

    offsets = read_offsets(OUT / 'det1' / 'run.log')
    rms_sn, weights = target_weights(target_objects())
    if offsets.size != weights.size:
        raise ValueError(f'{offsets.size} offsets but {weights.size} files')
    out = write_coadd2d(2, [
        '  offsets = ' + ', '.join(f'{o:.2f}' for o in offsets),
        '  weights = ' + ', '.join(f'{w:.4f}' for w in weights)], [
        '# VB_K mask MO_CC0958PA200_1: 2D coadd of the 32 science frames, '
        'DET02.',
        '# DET02 has no bright object: the offsets and weights are those',
        '# measured on the DET01 target (coadd2d_bright/det1), assuming that',
        '# both detectors share the same relative offsets.  Written by',
        '# make_coadd2d_bright.py det2.'])
    for i, (o, s, w) in enumerate(zip(offsets, rms_sn, weights)):
        print(f'{i:2d} offset {o:7.2f} px  rms S/N {s:5.2f}  weight {w:.4f}')
    print(f'Wrote {out}')


if __name__ == '__main__':
    main()
