"""
Check the group of emission-line candidates at 2.307-2.312 um.

Five slits (run5 slits DET01 1003 and 1855, DET02 314, 787 and 1017) have
a candidate between 23070 and 23118 A, where the sky spectrum has no
emission line.  For either coadd (``--variant header``: ``coadd2d/``,
``bright``: ``coadd2d_bright/``), this script:

1. measures, at each spectral row near 23090 A, the mean matched-filter
   S/N over the whole length of every science slit (excluding +/- 12 px
   around each candidate).  A sky residual (e.g. a variable sky line)
   would raise it in every slit; a source raises only its own slit;
2. plots the 1D boxcar spectra of the five candidates on a common
   wavelength axis.

Usage::

    python plot_line_group.py --variant bright

Generated by JXP and Claude
"""

import argparse
from pathlib import Path

import matplotlib
import numpy as np

from pypeit import spec2dobj

from find_emission_lines import snr_map

matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402 (after the backend is set)

HERE = Path(__file__).resolve().parent
COADD = 'Science_coadd/spec2d_MCSA00352031-MCSA00352103-CC0958_PA200_1.fits'
# (det, coadd slit, row, column) of the five candidates in each coadd
# (<outdir>/candidates.txt; coadd slit IDs differ between the coadds)
VARIANTS = {'header': ('coadd2d', 'lines'),
            'bright': ('coadd2d_bright', 'lines_bright')}
GROUPS = {
    'header': [('DET01', 928, 1039, 931), ('DET01', 1822, 995, 1811),
               ('DET02', 76, 883, 73), ('DET02', 594, 1492, 594),
               ('DET02', 866, 1051, 869)],
    'bright': [('DET01', 952, 1039, 955), ('DET01', 1864, 995, 1854),
               ('DET02', 78, 882, 76), ('DET02', 606, 1492, 606),
               ('DET02', 884, 1050, 890)]}
WAVE0, HALF = 23090., 120.


def load(variant, det):
    """
    Read a coadd and compute its S/N map.

    Generated by JXP and Claude

    Args:
        variant (:obj:`str`):
            ``header`` or ``bright``.
        det (:obj:`str`):
            Detector name.

    Returns:
        tuple: The Spec2DObj, the continuum-subtracted image, the S/N map,
        the good-pixel mask and the slit image.
    """
    f = HERE / VARIANTS[variant][0] / f'det{det[-1]}' / COADD
    s2d = spec2dobj.Spec2DObj.from_file(str(f), det, chk_version=False)
    gpm = (s2d.bpmmask.mask == 0) & (s2d.ivarmodel > 0)
    hp, snr = snr_map(s2d.sciimg - s2d.skymodel, s2d.ivarmodel, gpm)
    return s2d, hp, snr, gpm, s2d.slits.slit_img()


def main():
    """
    Write ``<outdir>/line_group_2p31.png`` and print the slit-wide S/N.

    Generated by JXP and Claude
    """
    p = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    p.add_argument('--variant', choices=list(VARIANTS), default='bright')
    args = p.parse_args()
    group = GROUPS[args.variant]
    fig, axes = plt.subplots(2, 1, figsize=(8, 7.5),
                             gridspec_kw=dict(height_ratios=[1, 2.2]))
    offs = 0.
    for det in ['DET01', 'DET02']:
        s2d, hp, snr, gpm, slitmask = load(args.variant, det)
        sci = s2d.slits.spat_id[s2d.slits.mask == 0]
        mine = [g for g in group if g[0] == det]
        # 1. slit-wide mean S/N per row near WAVE0
        for sid in sci:
            inslit = slitmask == sid
            for g in mine:
                if g[1] == sid:
                    inslit[:, max(g[3] - 12, 0):g[3] + 13] = False
            cols = np.where(inslit.any(axis=0))[0]
            ccol = int(np.median(cols))
            wv = s2d.waveimg[:, ccol]
            rows = np.where(np.abs(wv - WAVE0) < HALF)[0]
            if rows.size == 0:
                continue
            prof = np.array([snr[r, inslit[r]].mean() for r in rows])
            cand = sid in [g[1] for g in mine]
            axes[0].plot(wv[rows], prof, lw=1.4 if cand else 0.6,
                         color='tab:red' if cand else '0.6')
            print(f'{det} slit {sid:5d}: max slit-wide mean S/N '
                  f'{prof.max():5.2f} at {wv[rows][prof.argmax()]:.0f} A'
                  + ('  (candidate slit)' if cand else ''))
        # 2. 1D spectra of the candidates
        for _, sid, row, col in mine:
            cs = slice(col - 4, col + 5)
            w = np.where(gpm[:, cs], s2d.ivarmodel[:, cs], 0.)
            flux = np.sum(np.where(gpm[:, cs], hp[:, cs], 0.), axis=1)
            err = np.sqrt(np.sum(np.where(w > 0, 1. / np.where(
                w > 0, w, 1.), 0.), axis=1))
            wv = s2d.waveimg[:, col]
            sel = np.abs(wv - WAVE0) < 250.
            scale = 1. / np.median(err[sel])
            axes[1].step(wv[sel], flux[sel] * scale + offs, where='mid',
                         lw=0.9, color='k')
            axes[1].text(WAVE0 + 255, offs, f'{det} slit {sid}',
                         fontsize=8, va='center')
            axes[1].plot(wv[row], offs + 6, 'v', color='tab:red', ms=5)
            offs += 10.
    axes[0].axhline(0, color='0.3', lw=0.6)
    axes[0].set_ylabel('slit-wide mean S/N')
    axes[0].set_title('All science slits (grey) and the candidate slits '
                      '(red), candidates masked', loc='left', fontsize=9)
    axes[1].set_xlabel('wavelength (A)')
    axes[1].set_ylabel('boxcar flux / median error (offset)')
    axes[1].set_title('1D spectra at the candidates (red: peak)',
                      loc='left', fontsize=9)
    fig.tight_layout()
    out = HERE / VARIANTS[args.variant][1] / 'line_group_2p31.png'
    fig.savefig(out, dpi=100)
    print(f'Wrote {out}')


if __name__ == '__main__':
    main()
