"""Check the VB_K OH wavelength solution with the evening ThAr arcs.

Usage: python arc_check.py <redux_dir> [outdir]

PypeIt has no K-band Th line list, and the ThAr frames are untyped in
the PypeIt file, so no arc products are made from them.  Instead:

1. Build the arc image of each detector from the 4 ThAr frames
   (``buildimage_fromlist``, with the arc-frame processing of the run,
   but a plain mean: ``clip = False``).  The lamp lights a different
   part of the mask in each frame, so the default sigma-clipped mean
   rejects the bright frames on the lines and distorts the profiles
   (up to 2.7 px shifts).  Each frame is also measured on its own.
2. For each solved science slit, collapse the central 60% of the slit
   along the run's tilts onto the slit-centre spectral coordinate (the
   coordinate of the OH wavelength solution), so the whole slit width
   contributes and the line tilts do not broaden the lines.
3. Predict where the Ar lines of ``Ar_IR_MOSFIRE`` fall with the OH
   solution and measure them in the continuum-subtracted spectrum
   (continuum from PypeIt's ``detect_lines``).  The lines (Ar and OH)
   are flat-topped (the image of the ~6 px slit), so a Gaussian fit to
   the top (``detect_lines``) is unstable on the bright ThAr lines and
   often splits a line into two peaks.  Each line is measured instead
   by its first moment within +-7 px, iterated from the highest pixel
   near the prediction.  A
   first pass (+-4 px) gives the median offset per chip; the second
   pass searches +-1.5 px around it.  A line is kept if its peak is
   >= 8 sigma and no other line within 10-18 px exceeds 15% of its peak
   (blends with unlisted Th lines).
4. Control: the science sky (frame A) goes through the same steps
   with the OH lines used in the fit, so the method itself should give
   ~0 offset there.
5. Per chip: the trend with wavelength within slits, a fit of the slit
   median offsets with a line in the slit's spatial position (shift
   plus rotation, as for the standards), and the agreement between the
   single frames.  ``arc_vs_spat.png`` adds the standards' OH offsets
   from ``std_oh_offset_run2.txt``.

Writes ``<outdir>/arc_offsets.txt`` (one row per measured line and
image: ``mean`` or a single frame ``f0``-``f3``), ``arc_oh_control.txt``,
``arc_summary.txt``, and the figures ``arc_offsets.png``,
``arc_profiles.png`` and ``arc_vs_spat.png``.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import copy
import sys
from pathlib import Path

import numpy as np
from astropy.stats import sigma_clipped_stats
from astropy.table import Table, vstack
from matplotlib import pyplot as plt

from pypeit.core import arc
from pypeit.core.wavecal import waveio
from pypeit.images import buildimage
from pypeit.slittrace import SlitTraceSet
from pypeit.spectrographs.util import load_spectrograph

import vbk_paths
from pypeit.wavecalib import WaveCalib
from pypeit.wavetilts import WaveTilts

# Raw data: the minimum example set (environment variable MOIRCS_VBK_DATA).
# Chip-1 names; the MOIRCS reader opens the chip-2 companion for det 2
ARCS = [vbk_paths.raw_file(n) for n in vbk_paths.GROUPS['arc']]
SCI = vbk_paths.raw_file(352031)
WMIN, WMAX = 18000., 25000.  # Ar_IR_MOSFIRE lines used (25 lines)
FWHM = 6.0  # measured OH line FWHM (Implementation #4)
HW = 7  # half-width (px) of the first-moment window
NSIG_MIN = 8.  # minimum peak significance
ISO = (10, 18)  # range (px) checked for neighbouring lines
ISO_FRAC = 0.15  # maximum neighbour peak / line peak
SLIT_FRAC = (0.2, 0.8)  # central part of each slit used
COLORS = {1: '#2a78d6', 2: '#eb6834'}


def load_calibs(redux, det):
    """Load the slits, tilts image, and wavelength solutions of a run.

    Generated by JXP and Claude.

    Args:
        redux (Path): Reduction directory (with ``Calibrations/``).
        det (int): 1-indexed detector.

    Returns:
        tuple: (`SlitTraceSet`, tilts image (`numpy.ndarray`_, 0-1),
        `WaveCalib`).
    """
    cal = redux / 'Calibrations'
    slits = SlitTraceSet.from_file(cal / f'Slits_A_0_DET0{det}.fits.gz',
                                   chk_version=False)
    tilts = WaveTilts.from_file(cal / f'Tilts_A_0_DET0{det}.fits',
                                chk_version=False)
    slitmask = slits.slit_img()
    tiltimg = tilts.fit2tiltimg(slitmask)
    wc = WaveCalib.from_file(cal / f'WaveCalib_A_0_DET0{det}.fits',
                             chk_version=False)
    return slits, tiltimg, wc


def build_image(spec, par, files, det, clip=False):
    """Process and combine raw frames with the arc-frame parameters.

    Generated by JXP and Claude.

    Args:
        spec (Spectrograph): The MOIRCS spectrograph.
        par (ParSet): Run parameters (VB_K configuration).
        files (list): Chip-1 file names.
        det (int): 1-indexed detector.
        clip (bool): Sigma-clip when combining (PypeIt's default).

    Returns:
        tuple: image (e-) and bad-pixel mask (True = bad).
    """
    fpar = copy.deepcopy(par['calibrations']['arcframe'])
    fpar['process']['clip'] = clip
    img = buildimage.buildimage_fromlist(spec, det, fpar,
                                         [str(f) for f in files])
    return img.image, img.fullmask.mask > 0


def collapse_slit(img, bpm, slits, tiltimg, idx):
    """Collapse the central part of a slit along the tilts.

    Each pixel's tilt value times (nspec-1) is its spectral position at
    the slit centre, i.e. the coordinate of the wavelength solution.
    Pixels are averaged in 1-pixel bins of that coordinate.

    Generated by JXP and Claude.

    Args:
        img (numpy.ndarray): Processed image.
        bpm (numpy.ndarray): Bad-pixel mask (True = bad).
        slits (SlitTraceSet): Slits.
        tiltimg (numpy.ndarray): Tilts image (0-1).
        idx (int): 0-indexed slit.

    Returns:
        numpy.ndarray: Spectrum (nspec,), NaN where no pixel fell.
    """
    nspec, nspat = img.shape
    left, right, _ = slits.select_edges()
    cols = np.arange(nspat)[None, :]
    lo = (left[:, idx] + SLIT_FRAC[0] * (right[:, idx] - left[:, idx]))
    hi = (left[:, idx] + SLIT_FRAC[1] * (right[:, idx] - left[:, idx]))
    use = (cols >= lo[:, None]) & (cols <= hi[:, None]) & ~bpm
    pos = np.round(tiltimg[use] * (nspec - 1)).astype(int)
    ok = (pos >= 0) & (pos < nspec)
    tot = np.bincount(pos[ok], weights=img[use][ok], minlength=nspec)
    num = np.bincount(pos[ok], minlength=nspec)
    with np.errstate(invalid='ignore', divide='ignore'):
        return np.where(num > 0, tot / num, np.nan)


def contsub(spec1d):
    """Continuum-subtract a spectrum as ``detect_lines`` does, and
    measure its noise.

    Generated by JXP and Claude.

    Args:
        spec1d (numpy.ndarray): Spectrum (NaNs allowed).

    Returns:
        tuple: continuum-subtracted spectrum (0 where undefined) and its
        robust standard deviation away from the lines.
    """
    bad = ~np.isfinite(spec1d)
    s = np.where(bad, 0., spec1d)
    out = arc.detect_lines(s, sigdetect=5., fwhm=FWHM, bpm=bad)
    cs = out[6]
    _, _, std = sigma_clipped_stats(cs[~bad], sigma=2.5)
    return cs, std


def moment(cs, guess, noise):
    """First-moment centroid of a line, iterated from a first guess.

    Generated by JXP and Claude.

    Args:
        cs (numpy.ndarray): Continuum-subtracted spectrum.
        guess (float): Starting position (px).
        noise (float): Noise per pixel of ``cs``.

    Returns:
        tuple: centroid (px) and its error (px), or (None, None) if the
        window leaves the spectrum or holds no flux.
    """
    c = guess
    for _ in range(5):
        lo, hi = int(np.round(c)) - HW, int(np.round(c)) + HW + 1
        if lo < 0 or hi > cs.size:
            return None, None
        x = np.arange(lo, hi)
        f = np.clip(cs[lo:hi], 0., None)
        if f.sum() <= 0:
            return None, None
        c_new = np.sum(x * f) / f.sum()
        if abs(c_new - c) < 1e-3:
            c = c_new
            break
        c = c_new
    err = noise * np.sqrt(np.sum((x - c) ** 2)) / f.sum()
    return c, err


def match(pred, cs, noise, center, window):
    """Measure the lines at the predicted positions.

    Generated by JXP and Claude.

    Args:
        pred (numpy.ndarray): Predicted positions (px).
        cs (numpy.ndarray): Continuum-subtracted spectrum.
        noise (float): Noise per pixel of ``cs``.
        center (float): Expected offset (px).
        window (float): Half-width of the search window (px).

    Returns:
        list: (index into pred, offset px, error px, peak significance).
    """
    out = []
    n = cs.size
    # The flat-topped lines are located on a boxcar-smoothed copy (width
    # ~ the plateau), whose maximum is the line centre to ~1 px
    sm = np.convolve(cs, np.ones(HW) / HW, mode='same')
    for k, p in enumerate(pred):
        lo = int(np.floor(p + center - window))
        hi = int(np.ceil(p + center + window)) + 1
        if lo < 2 * HW or hi > n - 2 * HW:
            continue
        ipk = lo + int(np.argmax(sm[lo:hi]))
        # The smoothed maximum must be a local maximum, not a slope
        # rising towards another line outside the window
        if sm[ipk] < np.max(sm[ipk - 3:ipk + 4]):
            continue
        peak = np.max(cs[ipk - 3:ipk + 4])
        if peak < NSIG_MIN * noise:
            continue
        c, err = moment(cs, float(ipk), noise)
        if c is None or abs(c - p - center) > window + 1.:
            continue
        # Neighbouring (e.g. Th) lines that would bias the moment
        ic = int(np.round(c))
        side = np.r_[np.arange(ic - ISO[1], ic - ISO[0] + 1),
                     np.arange(ic + ISO[0], ic + ISO[1] + 1)]
        side = side[(side >= 0) & (side < n)]
        if np.max(cs[side]) > ISO_FRAC * peak:
            continue
        out.append((k, c - p, err, peak / noise))
    return out


def predict(wfit, waves, nspec):
    """Pixel positions of lines from a wavelength solution.

    Generated by JXP and Claude.

    Args:
        wfit (WaveFit): Slit solution.
        waves (numpy.ndarray): Wavelengths (A, vacuum).
        nspec (int): Number of spectral pixels.

    Returns:
        tuple: positions (px) of the lines inside the slit's range, the
        corresponding wavelengths, and whether each lies within the
        range of the fitted OH lines (else extrapolated).
    """
    wsol = wfit.wave_soln
    inside = (waves > wsol[3]) & (waves < wsol[-4])
    w = waves[inside]
    pix = np.interp(w, wsol, np.arange(nspec))
    fitted = (w >= wfit.wave_fit.min()) & (w <= wfit.wave_fit.max())
    return pix, w, fitted


def measure_det(redux, det, spec, par, ar_waves):
    """Measure Ar-line and control OH-line offsets on one detector.

    Generated by JXP and Claude.

    Args:
        redux (Path): Reduction directory.
        det (int): 1-indexed detector.
        spec (Spectrograph): MOIRCS.
        par (ParSet): Run parameters.
        ar_waves (numpy.ndarray): Ar wavelengths (A, vacuum).

    Returns:
        tuple: (Table of Ar lines, Table of OH control lines, dict of
        example spectra for the profile figure).
    """
    slits, tiltimg, wc = load_calibs(redux, det)
    images = [('mean',) + build_image(spec, par, ARCS, det)]
    images += [(f'f{k}',) + build_image(spec, par, [f], det)
               for k, f in enumerate(ARCS)]
    sciimg, scibpm = build_image(spec, par, [SCI], det)
    nspec = sciimg.shape[0]
    good = [i for i, w in enumerate(wc.wv_fits)
            if w is not None and w.pypeitfit is not None]
    # Pass 1 on the mean image: Ar lines within +-4 px, for the offset of
    # the chip
    first = []
    for i in good:
        cs, noise = contsub(collapse_slit(images[0][1], images[0][2],
                                          slits, tiltimg, i))
        pix, _, _ = predict(wc.wv_fits[i], ar_waves, nspec)
        first += [m[1] for m in match(pix, cs, noise, 0., 4.)]
    med0 = float(np.median(first))
    rows_ar, rows_oh, examples = [], [], {}
    for i in good:
        wfit = wc.wv_fits[i]
        sid = int(slits.spat_id[i])
        pix, w, fitted = predict(wfit, ar_waves, nspec)
        # Ar lines, pass 2, on the mean image and each frame
        for lab, img, bpm in images:
            cs, noise = contsub(collapse_slit(img, bpm, slits, tiltimg, i))
            if lab == 'mean':
                examples[sid] = dict(arc=cs)
            for k, d, e, ns in match(pix, cs, noise, med0, 1.5):
                rows_ar.append((lab, det, sid, w[k], pix[k], d, e, ns,
                                fitted[k]))
        # Control: OH lines of the fit, in the science sky, same method
        cs, noise = contsub(collapse_slit(sciimg, scibpm, slits, tiltimg,
                                          i))
        examples[sid]['sky'] = cs
        opix = np.interp(wfit.wave_fit, wfit.wave_soln, np.arange(nspec))
        for k, d, e, ns in match(opix, cs, noise, 0., 1.5):
            rows_oh.append(('sci', det, sid, wfit.wave_fit[k], opix[k], d,
                            e, ns, True))
    names = ('frame', 'det', 'spat_id', 'wave', 'pix_pred', 'offset',
             'err', 'nsig', 'in_fit_range')
    return (Table(rows=rows_ar, names=names),
            Table(rows=rows_oh, names=names), examples)


def summarize(tab, label):
    """Per-chip and per-slit statistics of the offsets.

    Generated by JXP and Claude.

    Args:
        tab (Table): Measured lines of one image (``measure_det``).
        label (str): Header for the printout.

    Returns:
        list: Lines of text.
    """
    out = [f'== {label} ==']
    for det in (1, 2):
        t = tab[tab['det'] == det]
        sids = np.unique(t['spat_id'])
        nl = np.array([np.sum(t['spat_id'] == s) for s in sids])
        per = np.array([np.median(t['offset'][t['spat_id'] == s])
                        for s in sids])
        two = nl >= 2
        mad = 1.4826 * np.median(np.abs(t['offset']
                                        - np.median(t['offset'])))
        out.append(f'DET0{det}: {len(t)} lines in {sids.size} slits; '
                   f'{two.sum()} slits with >= 2 lines')
        out.append(f'  all lines: median offset {np.median(t["offset"]):+.3f}'
                   f' px, std {np.std(t["offset"]):.3f}, robust std '
                   f'{mad:.3f}')
        if two.any():
            out.append(f'  slits with >= 2 lines: median of slit medians '
                       f'{np.median(per[two]):+.3f} px, std '
                       f'{np.std(per[two]):.3f} px, range '
                       f'[{per[two].min():+.2f}, {per[two].max():+.2f}]')
        for s, n, p in zip(sids, nl, per):
            ts = t[t['spat_id'] == s]
            if n > 15:
                out.append(f'    slit {s:5d}: {n:2d} lines, median '
                           f'{p:+.3f} px')
                continue
            out.append(f'    slit {s:5d}: {n:2d} lines, median {p:+.3f} px:'
                       + ' '.join(f'{w:.0f}:{d:+.2f}'
                                  for w, d in zip(ts['wave'],
                                                  ts['offset'])))
    return out


def trend(tab):
    """Offset trend with wavelength within the slits.

    Removes each slit's median offset (the part a shift would explain)
    and fits the residuals of all slits with >= 3 lines with a line in
    wavelength.

    Generated by JXP and Claude.

    Args:
        tab (Table): Measured lines of one image.

    Returns:
        list: Lines of text.
    """
    out = ['== Trend with wavelength within slits (slit medians removed) ==']
    for det in (1, 2):
        t = tab[tab['det'] == det]
        x, y = [], []
        for s in np.unique(t['spat_id']):
            ts = t[t['spat_id'] == s]
            if len(ts) < 3:
                continue
            x += list((ts['wave'] - 22000.) / 1000.)
            y += list(ts['offset'] - np.median(ts['offset']))
        x, y = np.array(x), np.array(y)
        if x.size < 5:
            out.append(f'DET0{det}: too few lines')
            continue
        p, cov = np.polyfit(x, y, 1, cov=True)
        res = y - np.polyval(p, x)
        out.append(f'DET0{det}: {x.size} lines; slope {p[0]:+.3f} +- '
                   f'{np.sqrt(cov[0, 0]):.3f} px per 1000 A; scatter '
                   f'{np.std(y):.3f} px before, {np.std(res):.3f} after')
    return out


def rotation(tab):
    """Fit the slit median offsets with a line in the slit position.

    A shift plus a small rotation of the spectra between the arc and
    science frames gives an offset that is linear in the slit's spatial
    position (as found for the standards in Implementation #4).

    Generated by JXP and Claude.

    Args:
        tab (Table): Measured lines of one image.

    Returns:
        tuple: (list of text lines, dict det -> (spat_ids, slit medians,
        fit coefficients)).
    """
    out = ['== Slit median offsets vs slit spatial position ==']
    fits = {}
    for det in (1, 2):
        t = tab[tab['det'] == det]
        sids = np.unique(t['spat_id'])
        med = np.array([np.median(t['offset'][t['spat_id'] == s])
                        for s in sids])
        p, cov = np.polyfit(sids, med, 1, cov=True)
        res = med - np.polyval(p, sids)
        fits[det] = (sids, med, p)
        out.append(f'DET0{det}: offset = {np.polyval(p, 1024):+.3f} px at '
                   f'spat 1024, slope {1e3 * p[0]:+.3f} +- '
                   f'{1e3 * np.sqrt(cov[0, 0]):.3f} px per 1000 px; slit '
                   f'rms about the line {np.std(res):.3f} px')
        out.append('    residuals: ' + ' '.join(
            f'{s}:{r:+.2f}' for s, r in zip(sids, res)))
    return out, fits


def std_offsets(path):
    """Read the standards' per-slit OH offsets (standard - science) from
    the output of ``std_oh_offset.py``, averaged over the 4 frames.

    Generated by JXP and Claude.

    Args:
        path (Path): ``std_oh_offset_run2.txt``.

    Returns:
        dict: det -> {spat_id: offset (px)}; empty if no file.
    """
    out = {1: {}, 2: {}}
    if not path.exists():
        return out
    det = None
    for line in path.read_text().splitlines():
        if line.startswith('DET0'):
            det = int(line[4])
        elif 'per slit:' in line:
            for item in line.split('per slit:')[1].split():
                sid, off = item.split(':')
                out[det].setdefault(int(sid), []).append(float(off))
    return {d: {k: float(np.mean(v)) for k, v in o.items()}
            for d, o in out.items()}


def plot_rotation(fits, std, outfile):
    """Slit median offsets vs slit position, with the standards.

    Generated by JXP and Claude.

    Args:
        fits (dict): ``rotation`` output.
        std (dict): ``std_offsets`` output.
        outfile (str): PNG file name.
    """
    fig, axes = plt.subplots(1, 2, figsize=(10, 3.8), sharey=True)
    for ax, det in zip(axes, (1, 2)):
        sids, med, p = fits[det]
        ax.plot(sids, med, 'o', color=COLORS[det],
                label='ThAr Ar lines - OH solution')
        x = np.array([0, 2040])
        ax.plot(x, np.polyval(p, x), color=COLORS[det], lw=0.8)
        if std[det]:
            k = sorted(std[det])
            ax.plot(k, [std[det][j] for j in k], 's', mfc='none',
                    color='0.3', label='standards OH - science OH')
        ax.axhline(0., color='k', lw=0.5)
        ax.set_title(f'DET0{det}', loc='left', fontsize=10)
        ax.set_xlabel('slit spat_id (px)')
        ax.legend(fontsize=8, frameon=False)
        for sp in ('top', 'right'):
            ax.spines[sp].set_visible(False)
    axes[0].set_ylabel('median offset per slit (px)')
    fig.tight_layout()
    fig.savefig(outfile, dpi=130)
    plt.close(fig)


def frame_consistency(ar):
    """Compare the single frames with each other.

    Generated by JXP and Claude.

    Args:
        ar (Table): All Ar measurements (mean image and single frames).

    Returns:
        list: Lines of text.
    """
    out = ['== Single frames (lines measured in >= 2 frames) ==']
    single = ar[ar['frame'] != 'mean']
    for det in (1, 2):
        t = single[single['det'] == det]
        dev = []
        for s in np.unique(t['spat_id']):
            for w in np.unique(t['wave'][t['spat_id'] == s]):
                tw = t[(t['spat_id'] == s) & (t['wave'] == w)]
                if len(tw) >= 2:
                    dev += list(tw['offset'] - np.mean(tw['offset']))
        dev = np.array(dev)
        out.append(f'DET0{det}: {dev.size} measurements; std about the '
                   f'line mean {np.std(dev):.3f} px, max |dev| '
                   f'{np.max(np.abs(dev)):.3f} px' if dev.size else
                   f'DET0{det}: none')
        for f in np.unique(t['frame']):
            tf = t[t['frame'] == f]
            out.append(f'  {f}: {len(tf):2d} lines in '
                       f'{np.unique(tf["spat_id"]).size:2d} slits, '
                       f'median offset {np.median(tf["offset"]):+.3f} px')
    return out


def plot(ar, oh, outfile):
    """Offsets versus wavelength, one panel per chip.

    Generated by JXP and Claude.

    Args:
        ar (Table): Ar-line offsets of the mean image.
        oh (Table): OH control offsets.
        outfile (str): PNG file name.
    """
    fig, axes = plt.subplots(2, 1, figsize=(10, 7.5), sharex=True)
    for ax, det in zip(axes, (1, 2)):
        o = oh[oh['det'] == det]
        ax.scatter(o['wave'] / 1e4, o['offset'], s=4, color='0.75',
                   label='OH (sky)', zorder=1)
        t = ar[ar['det'] == det]
        sids = np.unique(t['spat_id'])
        cmap = plt.get_cmap('turbo', max(sids.size, 2))
        for j, s in enumerate(sids):
            ts = t[t['spat_id'] == s]
            ax.errorbar(ts['wave'] / 1e4, ts['offset'], yerr=ts['err'],
                        fmt='o', ms=5, color=cmap(j), lw=1,
                        label=f'{s}', zorder=3)
            ax.plot(ts['wave'] / 1e4, ts['offset'], color=cmap(j), lw=0.6,
                    zorder=2)
        if len(t):
            ax.axhline(np.median(t['offset']), color=COLORS[det], ls='--',
                       lw=1)
        ax.axhline(0., color='k', lw=0.5)
        ax.set_ylabel('measured - predicted (px)')
        ax.set_title(f'DET0{det}: Ar lines in the ThAr arcs vs the OH '
                     'solution (grey: OH lines in the science sky)',
                     loc='left', fontsize=10)
        ax.legend(fontsize=7, ncol=9, frameon=False, loc='lower left',
                  title='slit spat_id', title_fontsize=7)
        ax.set_ylim(-2, 1.5)
        for sp in ('top', 'right'):
            ax.spines[sp].set_visible(False)
    axes[-1].set_xlabel('Wavelength (um, vacuum)')
    fig.tight_layout()
    fig.savefig(outfile, dpi=130)
    plt.close(fig)


def plot_profiles(examples, ar, oh, outfile):
    """Profiles of strong Ar and OH lines in the same slits.

    Generated by JXP and Claude.

    Args:
        examples (dict): (det, spat_id) -> continuum-subtracted ``arc``
            and ``sky`` spectra.
        ar, oh (Table): Ar (mean image) and OH measurements.
        outfile (str): PNG file name.
    """
    fig, axes = plt.subplots(1, 2, figsize=(10, 3.8), sharey=True)
    for ax, det in zip(axes, (1, 2)):
        t = ar[ar['det'] == det]
        # The slit with the most Ar lines; its strongest Ar and OH lines
        sids, n = np.unique(t['spat_id'], return_counts=True)
        sid = sids[np.argmax(n)]
        for tab, key, col, lab in ((t, 'arc', COLORS[det], 'Ar (ThAr)'),
                                   (oh[oh['det'] == det], 'sky', '0.3',
                                    'OH (sky)')):
            ts = tab[tab['spat_id'] == sid]
            r = ts[np.argmax(ts['nsig'])]
            c = r['pix_pred'] + r['offset']
            spec1d = examples[(det, sid)][key]
            x = np.arange(spec1d.size) - c
            m = np.abs(x) < 15
            ax.plot(x[m], spec1d[m] / spec1d[m].max(), 'o-', ms=3,
                    color=col, label=f'{lab} {r["wave"]:.0f} A')
        ax.axvline(0., color='k', lw=0.5)
        ax.set_title(f'DET0{det} slit {sid}', loc='left', fontsize=10)
        ax.set_xlabel('pixel - centroid')
        ax.legend(fontsize=8, frameon=False)
        for sp in ('top', 'right'):
            ax.spines[sp].set_visible(False)
    axes[0].set_ylabel('normalized flux')
    fig.tight_layout()
    fig.savefig(outfile, dpi=130)
    plt.close(fig)


def main():
    """Run the check on both detectors.  Generated by JXP and Claude."""
    redux = Path(sys.argv[1] if len(sys.argv) > 1 else 'run5')
    outdir = Path(sys.argv[2] if len(sys.argv) > 2 else 'wavecheck')
    outdir.mkdir(exist_ok=True)
    spec = load_spectrograph('subaru_moircs')
    par = spec.config_specific_par(str(SCI))
    lines, _, _ = waveio.load_line_lists(['Ar_IR_MOSFIRE'])
    w = np.asarray(lines['wave'])
    ar_waves = np.sort(w[(w > WMIN) & (w < WMAX)])
    print(f'{ar_waves.size} Ar lines in {WMIN:.0f}-{WMAX:.0f} A')
    ars, ohs, examples = [], [], {}
    for det in (1, 2):
        ar, oh, ex = measure_det(redux, det, spec, par, ar_waves)
        ars.append(ar)
        ohs.append(oh)
        examples.update({(det, k): v for k, v in ex.items()})
    ar, oh = vstack(ars), vstack(ohs)
    for t in (ar, oh):
        for c in ('wave', 'pix_pred', 'offset', 'err', 'nsig'):
            t[c].format = '.3f'
    ar.write(outdir / 'arc_offsets.txt', format='ascii.fixed_width',
             overwrite=True)
    oh.write(outdir / 'arc_oh_control.txt', format='ascii.fixed_width',
             overwrite=True)
    mean = ar[ar['frame'] == 'mean']
    text = summarize(mean, 'Ar lines in the mean ThAr image '
                     '(measured - predicted)')
    text += trend(mean)
    rtext, fits = rotation(mean)
    text += rtext
    text += frame_consistency(ar)
    text += summarize(oh, 'Control: OH lines in the science sky')
    text += trend(oh)
    # Line-by-line view: which Ar lines are measured, and how often
    text.append('== Ar lines (mean image): slits measured, median offset ==')
    for wv in ar_waves:
        for det in (1, 2):
            t = mean[(mean['det'] == det)
                     & (np.abs(mean['wave'] - wv) < 0.01)]
            if len(t):
                text.append(f'  {wv:9.2f} DET0{det}: {len(t):2d} slits, '
                            f'median {np.median(t["offset"]):+.3f} px')
    print('\n'.join(text))
    (outdir / 'arc_summary.txt').write_text('\n'.join(text) + '\n')
    plot(mean, oh, outdir / 'arc_offsets.png')
    plot_profiles(examples, mean, oh, outdir / 'arc_profiles.png')
    plot_rotation(fits, std_offsets(Path('std_oh_offset_run2.txt')),
                  outdir / 'arc_vs_spat.png')
    print(f'Wrote {outdir}/arc_offsets.txt, arc_oh_control.txt, '
          'arc_summary.txt, arc_offsets.png, arc_profiles.png, '
          'arc_vs_spat.png')


if __name__ == '__main__':
    main()
