"""
Compare the wavelength solutions of two reductions (e.g. run3,
holy-grail, against run4, reidentify), slit by slit.

Usage: python compare_wave_runs.py <redux_ref> <redux_new>

Per science slit: number of lines, the stored rms, the rms recomputed
from the fit residuals divided by the true dispersion (median
dlambda/dpixel of the solution), and the median and maximum
|lambda_new - lambda_ref| over the fitted range of the reference.

The recomputed rms is needed because holy-grail divides the rms in A by
its pattern-match dispersion estimate, which for some VB_K slits is
~1.0 A/px instead of ~1.94 A/px, so its stored rms is ~2x too large.

Also compares the extracted OPT_WAVE of every object matched by name
in the spec1d files of both reductions.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import sys
from pathlib import Path

import numpy as np

from pypeit.specobjs import SpecObjs
from pypeit.wavecalib import WaveCalib


def true_rms(w):
    """
    Rms of a wavelength fit in pixels, using the true dispersion.

    Generated by JXP and Claude.

    Args:
        w (WaveFit): A wavelength fit.

    Returns:
        float: Rms of the unmasked fit residuals (A) divided by the
        median dispersion of the solution (A/px).
    """
    f = w.pypeitfit
    m = f.gpm.astype(bool)
    rms_ang = np.sqrt(np.mean((f.yval[m] - f.eval(f.xval[m]))**2))
    return rms_ang / np.median(np.diff(w.wave_soln))


def compare_wavecalib(ref, new):
    """
    Compare two WaveCalib files slit by slit and print a table.

    Generated by JXP and Claude.

    Args:
        ref (Path): Reference WaveCalib file.
        new (Path): New WaveCalib file.

    Returns:
        dict: Summary (number solved, median/max true rms) for both.
    """
    wr = WaveCalib.from_file(ref, chk_version=False)
    wn = WaveCalib.from_file(new, chk_version=False)
    print(f'{ref.name}')
    print('  spat | ref: n  rms_st rms_px | new: n  rms_st rms_px '
          '| med|dl| max|dl| (A) | new range (A)')
    out = {'ref': [], 'new': []}
    for r, n in zip(wr.wv_fits, wn.wv_fits):
        ok_r = r is not None and r.pypeitfit is not None
        ok_n = n is not None and n.pypeitfit is not None
        if not (ok_r or ok_n):
            continue
        spat = int((r if ok_r else n).spat_id)
        line = f'  {spat:4d} |'
        for tag, w, ok in (('ref', r, ok_r), ('new', n, ok_n)):
            if ok:
                t = true_rms(w)
                out[tag].append(t)
                line += f' {len(w.wave_fit):3d} {w.rms:6.3f} {t:6.3f} |'
            else:
                line += '   no fit           |'
        if ok_r and ok_n:
            sel = (r.wave_soln > r.wave_fit.min()) \
                & (r.wave_soln < r.wave_fit.max())
            dw = np.abs(n.wave_soln[sel] - r.wave_soln[sel])
            line += f' {np.median(dw):6.2f} {dw.max():6.2f} |'
        else:
            line += '              |'
        if ok_n:
            line += f' {n.wave_soln[0]:.0f}-{n.wave_soln[-1]:.0f}'
        print(line)
    summ = {}
    for tag in ('ref', 'new'):
        v = np.array(out[tag])
        summ[tag] = (v.size, np.median(v), v.max())
        print(f'  {tag}: solved {v.size}, true rms median {np.median(v):.3f}'
              f' max {v.max():.3f} px')
    return summ


def compare_spec1d(dref, dnew):
    """
    Compare OPT_WAVE of the objects in matching spec1d files.

    Generated by JXP and Claude.

    Args:
        dref (Path): Reference ``Science`` directory.
        dnew (Path): New ``Science`` directory.

    Returns:
        None
    """
    for fr in sorted(dref.glob('spec1d_*.fits')):
        fn = dnew / fr.name
        if not fn.exists():
            print(f'{fr.name}: missing in new')
            continue
        sr = SpecObjs.from_fitsfile(fr, chk_version=False)
        sn = SpecObjs.from_fitsfile(fn, chk_version=False)
        names_n = {s.NAME: s for s in sn}
        print(f'{fr.name[:40]}: {len(sr)} ref / {len(sn)} new objects')
        for s in sr:
            t = names_n.get(s.NAME)
            if t is None or s.OPT_WAVE is None or t.OPT_WAVE is None:
                continue
            d = np.abs(t.OPT_WAVE - s.OPT_WAVE)
            snr = f'{s.S2N:.1f}/{t.S2N:.1f}' if s.S2N is not None else ''
            if s.S2N is not None and s.S2N > 3:
                print(f'   {s.NAME}: max|dl| {d.max():.3f} A, S/N {snr}')


def main():
    """Command-line wrapper.  Generated by JXP and Claude."""
    ref, new = Path(sys.argv[1]), Path(sys.argv[2])
    for f in sorted((ref / 'Calibrations').glob('WaveCalib_*.fits')):
        compare_wavecalib(f, new / 'Calibrations' / f.name)
    compare_spec1d(ref / 'Science', new / 'Science')


if __name__ == '__main__':
    main()
