"""
Check the spec1d files fluxed with the chip-transfer sensitivity functions.

For each fluxed file: the number of pixels masked by fluxing (counts
valid but flux zero, i.e. outside the sensitivity function or where the
transferred zeropoint is undefined).  For the two DET02 copies (direct and
flatratio modes): the ratio of the fluxes per object, against the expected
s / R(lambda).  For the standard on DET01: the fluxed star against the
stellar model.

Usage::

    python flux_check.py flux

Generated by JXP and Claude
"""

import argparse
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit.core import standard
from pypeit.sensfunc import SensFunc
from pypeit.specobjs import SpecObjs


def masked_by_fluxing(sobj, ext='OPT'):
    """
    Pixels with valid counts but no flux.

    Args:
        sobj (:class:`~pypeit.specobj.SpecObj`):
            Fluxed spectrum.
        ext (:obj:`str`, optional):
            Extraction, ``'OPT'`` or ``'BOX'``.

    Returns:
        :obj:`tuple`: Number of such pixels, and their wavelength range
        (or None).

    Generated by JXP and Claude
    """
    w = sobj[f'{ext}_WAVE']
    bad = (sobj[f'{ext}_COUNTS_IVAR'] > 0) & (sobj[f'{ext}_FLAM_IVAR'] <= 0)
    rng = (w[bad].min(), w[bad].max()) if bad.any() else None
    return int(bad.sum()), rng


def main():
    """
    Command-line entry point; see the module docstring.

    Generated by JXP and Claude
    """
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    parser.add_argument('fluxdir')
    args = parser.parse_args()
    fdir = Path(args.fluxdir)

    for f in sorted((fdir / 'fluxed').glob('spec1d_*.fits')):
        sobjs = SpecObjs.from_fitsfile(f, chk_version=False)
        out = [masked_by_fluxing(s) for s in sobjs]
        n = sum(o[0] for o in out)
        rngs = [o[1] for o in out if o[1] is not None]
        lo = min(r[0] for r in rngs) if rngs else np.nan
        hi = max(r[1] for r in rngs) if rngs else np.nan
        print(f'{f.name}: {sobjs.nobj} objects, DET {set(sobjs.DET)}, '
              f'{n} pixels masked by fluxing'
              + (f' ({lo:.0f}-{hi:.0f} A)' if rngs else ''))

    # DET02, flatratio vs direct
    root = 'spec1d_MCSA00352125-HIP59174_MOIRCS_20260529T082520.088_DET02'
    d = SpecObjs.from_fitsfile(fdir / 'fluxed' / f'{root}_direct.fits',
                               chk_version=False)
    r = SpecObjs.from_fitsfile(fdir / 'fluxed' / f'{root}_flatratio.fits',
                               chk_version=False)
    sd = SensFunc.from_file(fdir / 'sens_HIP59174_A0_pca_det2_direct.fits',
                            chk_version=False)
    sr = SensFunc.from_file(fdir / 'sens_HIP59174_A0_pca_det2_flatratio.fits',
                            chk_version=False)
    # Expected flux ratio flatratio/direct = 10**(-0.4 dzp) = 1/R
    dzp = sr.zeropoint[:, 0] - sd.zeropoint[:, 0]
    print('DET02 flatratio / direct (expected 1/R):')
    fig, ax = plt.subplots(2, 1, figsize=(9, 6), sharex=True)
    worst = 0.
    for a, b in zip(d, r):
        g = (a.OPT_FLAM_IVAR > 0) & (b.OPT_FLAM_IVAR > 0) \
            & (np.abs(a.OPT_FLAM) > 0)
        ratio = b.OPT_FLAM[g] / a.OPT_FLAM[g]
        expect = 10**(-0.4 * np.interp(a.OPT_WAVE[g], sd.wave[:, 0], dzp))
        worst = max(worst, np.max(np.abs(ratio / expect - 1)))
        ax[0].plot(a.OPT_WAVE[g] / 1e4, ratio, '.', ms=1)
    print(f'  max |ratio / expected - 1| over {d.nobj} objects: {worst:.2e}')
    w = sd.wave[:, 0]
    ok = np.isfinite(dzp) & (w > 1)
    inv = 10**(-0.4 * dzp[ok])
    print(f'  1/R: median {np.median(inv):.3f}, range {inv.min():.3f}-'
          f'{inv.max():.3f} over {w[ok].min():.0f}-{w[ok].max():.0f} A')
    ax[0].plot(w[ok] / 1e4, inv, 'k', lw=1, label='1/R')
    ax[0].set_ylim(0.6, 1.0)
    ax[0].set_ylabel('flatratio / direct')
    ax[0].legend()
    ax[1].plot(w[ok] / 1e4, sd.zeropoint[ok, 0], label='direct (chip 1)')
    ax[1].plot(w[ok] / 1e4, sr.zeropoint[ok, 0], label='flatratio')
    ax[1].set_ylabel('zeropoint (mag)')
    ax[1].set_xlabel('wavelength (um)')
    ax[1].legend()
    fig.tight_layout()
    fig.savefig(fdir / 'det2_modes.png', dpi=120)

    # Standard on DET01, fluxed with the chip-1 sensfunc, against the model
    s = SpecObjs.from_fitsfile(
        fdir / 'fluxed' / 'spec1d_MCSA00352125-HIP59174_MOIRCS_'
        '20260529T082520.088_DET01.fits', chk_version=False)
    star = s[np.argmax(s.S2N)]
    model = standard.get_standard_spectrum(spectral_type='A0', V_mag=7.45)
    g = star.OPT_FLAM_IVAR > 0
    m = np.interp(star.OPT_WAVE[g], np.asarray(model.wave),
                  np.asarray(model.flux))
    q = star.OPT_FLAM[g] / m
    print(f'std1 A star ({star.NAME}) fluxed / A0 model: median '
          f'{np.median(q):.3f} (no telluric correction applied)')


if __name__ == '__main__':
    main()
