"""
For one slit, rerun holy-grail and show where along the slit the
solution departs from the stored (run3) one, and which lines the
pattern vote identified (count, pixel range, wrong IDs).

Usage: python holy_rms_where.py <det> <spat> <asis|T> [nseld] [outfile]

- T: triangles only (see holy_rms_check.py, variant T).
- nseld: half-width, in log-dispersion bins, of the window around the
  histogram peak whose pattern solutions vote on the line IDs
  (HolyGrail.solve_slit, default 3 = +-0.8%).
- outfile: optional JSON file for the report (dl every 10 px, and the
  pixels of the identified lines and of the wrong IDs).

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json
import sys

import numpy as np

import holy_rms_check as H
from pypeit.core.wavecal import autoid
from pypeit.spectrographs.util import load_spectrograph
from pypeit.wavecalib import WaveCalib

RAW = ('/mnt/s1data01/work/research/pypeit-development/test_data_moircs/'
       'VB_K/example_MO_CC0958PA200_1/sci/MCSA00352031.fits')


def main():
    """Run one slit and print the comparison.  Generated by JXP and
    Claude."""
    det, spat, variant = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
    nseld = int(sys.argv[4]) if len(sys.argv) > 4 else 3
    autoid.HolyGrail.run_brute_loop = H.make_triangles_only_loop() \
        if variant == 'T' else H.ORIG_LOOP
    orig_ss = H.autoid.HolyGrail.solve_slit

    def solve_slit(self, slit, psols, msols, tcent_ecent, nstore=1,
                   nselw=3, nseld_=3):
        return orig_ss(self, slit, psols, msols, tcent_ecent, nstore, nselw,
                       nseld)
    autoid.HolyGrail.solve_slit = solve_slit

    spec = load_spectrograph('subaru_moircs')
    par = spec.config_specific_par(RAW)['calibrations']['wavelengths']
    par['method'] = 'holy-grail'
    par['match_toler'] = 2.0
    wc = WaveCalib.from_file(f'run3/Calibrations/WaveCalib_A_0_DET0{det}'
                             '.fits', chk_version=False)
    i = [k for k, w in enumerate(wc.wv_fits)
         if w is not None and w.spat_id == spat][0]
    fwhms = np.array([None if w is None else w.fwhm for w in wc.wv_fits],
                     dtype=object)
    hg = autoid.HolyGrail(wc.arc_spectra, par['lamps'], par=par,
                          ok_mask=np.array([i]), measured_fwhms=fwhms,
                          nonlinear_counts=spec.get_detector_par(det)
                          .nonlinear_counts())
    patt, fits = hg.get_results()
    p, f, ref = patt.get(str(i)), fits.get(str(i)), wc.wv_fits[i].wave_soln
    print(f'DET0{det} slit {spat} {variant} nseld={nseld}:', end=' ')
    if f is None:
        print('no solution')
        return
    x = np.arange(ref.size)
    print(f'bdisp {p["bdisp"]:.4f}, nmatch {p["nmatch"]}')
    pix = [0, 250, 500, 750, 1020, 1250, 1500, 1750, ref.size - 1]
    print('  dl (A) at pixel:',
          ' '.join(f'{q}:{f.wave_soln[q] - ref[q]:+.1f}' for q in pix))
    tc_all, _ = hg.get_use_tcent(p['sign'], hg._det_weak[str(i)])
    m = np.where(p['mask'])[0]
    ids, tc = np.asarray(p['IDs'])[m], tc_all[m]
    wrong = np.abs(ids - np.interp(tc, x, ref)) > 3.
    print(f'  pattern-identified lines: {m.size}, pixel range '
          f'{tc.min():.0f}-{tc.max():.0f}; IDs off from run3 by >3 A: '
          f'{wrong.sum()}'
          + (f' at px {np.round(tc[wrong]).astype(int).tolist()}'
             if wrong.any() else ''))
    print(f'  fitted lines: {len(f.pixel_fit)}, pixel range '
          f'{f.pixel_fit.min():.0f}-{f.pixel_fit.max():.0f}')
    if len(sys.argv) > 5:
        out = dict(det=det, spat=spat, variant=variant, nseld=nseld,
                   pix=x[::10].tolist(),
                   dl=np.round(f.wave_soln[::10] - ref[::10], 2).tolist(),
                   ident=np.round(tc[~wrong], 1).tolist(),
                   wrong=np.round(tc[wrong], 1).tolist(),
                   nfit=len(f.pixel_fit))
        with open(sys.argv[5], 'w') as fh:
            json.dump(out, fh)


if __name__ == '__main__':
    main()
