"""
Minimal reproduction: patterns.quadrangles truncates the pattern
dispersion and central wavelength to unsigned integers, while
patterns.triangles returns floats.

Usage: python holy_rms_repro.py

Not part of PypeIt.  Generated by JXP and Claude.
"""
import numpy as np

from pypeit.core.wavecal import patterns

# Twelve lines with irregular spacing, and a linear wavelength solution
det = np.array([10., 31., 55., 92., 140., 171., 230., 266., 333., 370.,
                425., 490.])
for disp_true, w0 in [(1.95, 20000.), (0.5, 5000.)]:
    lines = w0 + disp_true * (det - det[0])
    print(f'True dispersion {disp_true} A/px, central wavelength '
          f'{w0 + disp_true * (1020 - det[0]):.1f} A')
    for name, func in [('triangles', patterns.triangles),
                       ('quadrangles', patterns.quadrangles)]:
        _, _, wcen, disp = func(det, lines, 2040, detsrch=5, lstsrch=5,
                                pixtol=1.0)
        # Solutions whose dispersion is within 1% of the truth
        good = np.abs(disp.astype(float) / disp_true - 1) < 0.01
        vals, cnt = np.unique(disp[disp > 0], return_counts=True)
        mode = vals[np.argmax(cnt)] if vals.size else None
        print(f'  {name:12s} dtype {str(disp.dtype):8s} '
              f'{good.sum():4d} of {disp.size:4d} solutions within 1% of '
              f'the true dispersion; most common value {mode}')
