"""
Check the rms that holy-grail stores in WaveCalib files, and test two
candidate fixes.

holy-grail passes its pattern-match dispersion estimate
(``patt_dict['bdisp'] = 10**dcen``, a bin of a 2-D histogram) to
``wv_fitting.fit_slit`` -> ``iterative_fitting``, which divides the rms
in A by it to get the rms in pixels and also uses it to convert
``match_toler`` (pixels) to A.  When the estimate is wrong, the stored
rms and the matching tolerance are wrong by the same factor.

The estimate is wrong because ``patterns.quadrangles`` (poly=4) stores
the central wavelength and dispersion of each pattern in unsigned
integer arrays (``dtype=np.ulonglong``), which truncates e.g. 1.94 A/px
to 1.

Variants tested (patched at run time; PypeIt files are not edited):
    A: ``quadrangles`` with float arrays for wvcen and disps.
    B: ``fit_slit`` with the dispersion from a linear fit to the
       pattern-matched lines instead of ``bdisp``.
    T: triangles only (``run_brute_loop`` with ``rng_poly = [3]``), i.e.
       holy-grail without the quadrangle search.

Usage:
    python holy_rms_check.py check <WaveCalib file> [...]
        Stored vs recomputed rms for each slit (no rerun).
    python holy_rms_check.py rerun <redux_dir> <raw_file>
        Rerun holy-grail on the arc spectra stored in the WaveCalib
        files: as-is, with fix A, fix B, both, and triangles only.
    python holy_rms_check.py hist <redux_dir> <raw_file> <det> <spat>
            [asis|A]
        For one slit, print the pattern-histogram peak of every
        solve_slit call (triangles first, then quadrangles), how many
        pattern solutions have a dispersion of exactly 1 A/px, and the
        votes near the peak and near the stored (run3) solution.  With
        A, quadrangles use float arrays (fix A).
        Uses the spectrograph defaults for <raw_file>, with
        method='holy-grail' and match_toler=2.0 (as in run3).

Not part of PypeIt.  Generated by JXP and Claude.
"""
import copy
import inspect
import textwrap
import json
import logging
import sys
from multiprocessing import Pool
from pathlib import Path

import numpy as np

from pypeit.core.wavecal import autoid, patterns, wv_fitting
from pypeit.spectrographs.util import load_spectrograph
from pypeit.wavecalib import WaveCalib

logging.disable(logging.WARNING)
ORIG_FIT_SLIT = wv_fitting.fit_slit
ORIG_QUAD = patterns.quadrangles
ORIG_LOOP = autoid.HolyGrail.run_brute_loop
VARIANTS = ['asis', 'A', 'B', 'AB', 'T']


def make_triangles_only_loop():
    """
    Build ``HolyGrail.run_brute_loop`` that searches triangles only
    (variant T), from the installed source.

    Generated by JXP and Claude.

    Returns:
        function: The patched method.
    """
    src = textwrap.dedent(inspect.getsource(ORIG_LOOP))
    old = 'rng_poly = [3, 4]'
    if src.count(old) != 1:
        raise ValueError(f'Expected one "{old}" in run_brute_loop')
    src = src.replace(old, 'rng_poly = [3]')
    ns = dict(vars(autoid))
    exec(src, ns)
    return ns['run_brute_loop']


def make_float_quadrangles():
    """
    Build ``patterns.quadrangles`` with float arrays for wvcen and disps
    (fix A), from the installed source.

    Generated by JXP and Claude.

    Returns:
        function: The patched quadrangles.
    """
    src = inspect.getsource(ORIG_QUAD)
    n = src.count('dtype=np.ulonglong')
    if n != 4:
        raise ValueError(f'Expected 4 ulonglong dtypes, found {n}')
    src = src.replace('dtype=np.ulonglong', 'dtype=float')
    ns = dict(vars(patterns))
    exec(src, ns)
    return ns['quadrangles']


def true_rms(fit):
    """
    Rms of a wavelength fit in pixels from its own dispersion.

    Generated by JXP and Claude.

    Args:
        fit (WaveFit): A wavelength fit.

    Returns:
        tuple: (rms in A, median dispersion in A/px, rms in px).
    """
    f = fit.pypeitfit
    m = f.gpm.astype(bool)
    rms_ang = float(np.sqrt(np.mean((f.yval[m] - f.eval(f.xval[m]))**2)))
    disp = float(np.median(np.diff(fit.wave_soln)))
    return rms_ang, disp, rms_ang / disp


def check(files):
    """
    Print stored vs recomputed rms for each slit of WaveCalib files.

    Generated by JXP and Claude.

    Args:
        files (list): WaveCalib files.

    Returns:
        None
    """
    print('file spat  stored_rms  rms_A  disp(A/px)  true_rms  ratio  '
          'implied_bdisp')
    for fn in files:
        wc = WaveCalib.from_file(fn, chk_version=False)
        for w in wc.wv_fits:
            if w is None or w.pypeitfit is None:
                continue
            ra, d, rp = true_rms(w)
            print(f'{Path(fn).name} {int(w.spat_id):5d}  {w.rms:8.3f}  '
                  f'{ra:6.3f}  {d:8.3f}  {rp:8.3f}  {w.rms / rp:5.2f}  '
                  f'{ra / w.rms:8.3f}')


def fit_slit_fixed(spec, patt_dict, tcent, line_lists, **kwargs):
    """
    fit_slit with the dispersion taken from a linear fit to the
    pattern-matched lines instead of the histogram estimate.

    Generated by JXP and Claude.

    Args:
        spec, patt_dict, tcent, line_lists, kwargs: As for
            :func:`pypeit.core.wavecal.wv_fitting.fit_slit`.

    Returns:
        WaveFit or None: As for fit_slit.
    """
    pd = copy.copy(patt_dict)
    ok = np.where(pd['mask'])[0]
    ids = np.asarray(pd['IDs'], dtype=float)[ok]
    if ok.size >= 2:
        pd['bdisp'] = float(abs(np.polyfit(tcent[ok], ids, 1)[0]))
    return ORIG_FIT_SLIT(spec, pd, tcent, line_lists, **kwargs)


def run_holy(args):
    """
    Run holy-grail on one detector's arc spectra.

    Generated by JXP and Claude.

    Args:
        args (tuple): (redux_dir, raw_file, det, variant), variant in
            VARIANTS.

    Returns:
        dict: Per-slit results.
    """
    redux, raw, det, variant = args
    wv_fitting.fit_slit = fit_slit_fixed if 'B' in variant \
        else ORIG_FIT_SLIT
    # results_brute imports quadrangles from the module at call time
    patterns.quadrangles = make_float_quadrangles() if 'A' in variant \
        else ORIG_QUAD
    autoid.HolyGrail.run_brute_loop = make_triangles_only_loop() \
        if 'T' in variant else ORIG_LOOP
    spec = load_spectrograph('subaru_moircs')
    par = spec.config_specific_par(raw)['calibrations']['wavelengths']
    par['method'] = 'holy-grail'
    par['match_toler'] = 2.0
    wc = WaveCalib.from_file(Path(redux) / 'Calibrations'
                             / f'WaveCalib_A_0_DET0{det}.fits',
                             chk_version=False)
    ok = np.array([i for i, w in enumerate(wc.wv_fits)
                   if w is not None and w.pypeitfit is not None])
    fwhms = np.array([None if w is None else w.fwhm for w in wc.wv_fits],
                     dtype=object)
    hg = autoid.HolyGrail(wc.arc_spectra, par['lamps'], par=par,
                          ok_mask=ok, measured_fwhms=fwhms,
                          nonlinear_counts=spec.get_detector_par(det)
                          .nonlinear_counts())
    patt, fits = hg.get_results()
    out = {}
    for i in ok:
        f, p = fits.get(str(i)), patt.get(str(i))
        if f is None:
            out[int(wc.wv_fits[i].spat_id)] = None
            continue
        ra, d, rp = true_rms(f)
        out[int(wc.wv_fits[i].spat_id)] = dict(
            bdisp=None if p is None else float(p['bdisp']),
            rms=float(f.rms), rms_A=ra, disp=d, true_rms=rp,
            nlin=len(f.wave_fit), wave=f.wave_soln.tolist())
    return det, variant, out


def align(redux, waves):
    """
    Independent check of wavelength solutions: shift and correlation of
    each slit's sky spectrum, on a given wavelength scale, against the
    median sky spectrum of all other slits on their stored (run3)
    scales.

    Generated by JXP and Claude.

    Args:
        redux (str): Reduction directory (stored solutions and spectra).
        waves (dict): (det, spat) -> wavelength array to test.

    Returns:
        dict: (det, spat) -> (best shift in A, cc at the best shift, cc
        at zero shift).
    """
    grid = np.arange(19000., 25000., 1.)
    spec = {}
    for det in [1, 2]:
        wc = WaveCalib.from_file(Path(redux) / 'Calibrations'
                                 / f'WaveCalib_A_0_DET0{det}.fits',
                                 chk_version=False)
        for w in wc.wv_fits:
            if w is not None and w.pypeitfit is not None:
                spec[(det, int(w.spat_id))] = (w.wave_soln, w.spec)

    def on_grid(wave, flux):
        # Continuum-subtracted, normalized; NaN outside the coverage
        f = np.interp(grid, wave, flux, left=np.nan, right=np.nan)
        cont = np.nanpercentile(f, 30)
        f = f - cont
        return f / np.nanpercentile(f, 99)

    out = {}
    lags = np.arange(-150, 151)
    for key, wave in waves.items():
        if wave is None:
            out[key] = None
            continue
        others = [on_grid(*v) for k, v in spec.items() if k != key]
        ref = np.nanmedian(np.array(others), axis=0)
        f = on_grid(np.asarray(wave), spec[key][1])
        cc = []
        for lag in lags:
            g = np.roll(f, lag)
            ok = np.isfinite(g) & np.isfinite(ref)
            ok[:abs(lag)] = False
            ok[len(ok) - abs(lag):] = False
            cc.append(np.corrcoef(g[ok], ref[ok])[0, 1])
        cc = np.array(cc)
        k = int(np.nanargmax(cc))
        out[key] = (float(lags[k]), float(cc[k]), float(cc[150]))
    return out


def rerun(redux, raw):
    """
    Rerun holy-grail as-is and with every variant in VARIANTS, on both
    detectors, in parallel, and print and save the comparison.

    Generated by JXP and Claude.

    Args:
        redux (str): Reduction directory.
        raw (str): A raw science file (for the parameters).

    Returns:
        None
    """
    jobs = [(redux, raw, det, v) for det in [1, 2] for v in VARIANTS]
    with Pool(len(jobs)) as pool:
        res = pool.map(run_holy, jobs)
    r = {(d, v): o for d, v, o in res}
    keys = ('bdisp', 'rms', 'rms_A', 'disp', 'true_rms', 'nlin')
    summ = {}
    print('stored rms / true rms / lines per variant; max|dl| (A) of each '
          'fix against as-is')
    print('det spat | ' + ' | '.join(f'{v:>4s}: bdisp stored  true   n'
                                     for v in VARIANTS)
          + ' | dl ' + ', '.join(VARIANTS[1:]))
    for det in [1, 2]:
        for spat in sorted(r[(det, 'asis')]):
            row = {v: r[(det, v)].get(spat) for v in VARIANTS}
            line = f'  {det} {spat:5d}'
            for v in VARIANTS:
                x = row[v]
                line += ' |   fail' + ' ' * 22 if x is None else \
                    (f' | {x["bdisp"]:10.3f} {x["rms"]:6.3f} '
                     f'{x["true_rms"]:5.3f} {x["nlin"]:3d}')
            dls = {}
            for v in VARIANTS[1:]:
                if row['asis'] is None or row[v] is None:
                    dls[v] = None
                    continue
                dls[v] = float(np.max(np.abs(np.array(row['asis']['wave'])
                                             - np.array(row[v]['wave']))))
            line += ' | ' + ' '.join('  fail' if d is None else f'{d:6.2f}'
                                     for d in dls.values())
            print(line)
            summ[f'{det}_{spat}'] = dict(
                det=det, spat=spat,
                **{f'dl_{v}': dls[v] for v in VARIANTS[1:]},
                **{f'{v}_{k}': (None if row[v] is None else row[v][k])
                   for v in VARIANTS for k in keys})
    # Independent check of every variant's solutions
    print('Alignment against the median of the other slits: best shift '
          '(A), cc at best, cc at 0')
    for v in VARIANTS:
        waves = {(d, sp): (None if o is None else o['wave'])
                 for (d, vv), oo in r.items() if vv == v
                 for sp, o in oo.items()}
        al = align(redux, waves)
        for (d, sp), a in sorted(al.items()):
            key = f'{d}_{sp}'
            summ[key][f'{v}_align'] = a
            if a is not None:
                print(f'  {v:4s} {d} {sp:5d}  shift {a[0]:6.0f}  cc {a[1]:.3f}'
                      f'  cc0 {a[2]:.3f}')
    outfile = Path('holy_rms_rerun.json')
    outfile.write_text(json.dumps(summ, indent=1))
    print(f'Wrote {outfile}')


def hist(redux, raw, det, spat, variant='asis'):
    """
    Print the pattern-histogram peak of each holy-grail solve_slit call
    for one slit.

    Generated by JXP and Claude.

    Args:
        redux (str): Reduction directory.
        raw (str): A raw science file (for the parameters).
        det (int): Detector.
        spat (int): Slit spat_id.
        variant (str): 'asis' or 'A' (float quadrangles).

    Returns:
        None
    """
    patterns.quadrangles = make_float_quadrangles() if variant == 'A' \
        else ORIG_QUAD
    orig = autoid.HolyGrail.solve_slit
    calls = []
    wc = WaveCalib.from_file(Path(redux) / 'Calibrations'
                             / f'WaveCalib_A_0_DET0{det}.fits',
                             chk_version=False)
    i = [k for k, w in enumerate(wc.wv_fits)
         if w is not None and w.spat_id == spat][0]
    # Stored (run3) solution: wavelength at the central pixel, as the
    # pattern central wavelengths are defined, and central dispersion
    w = wc.wv_fits[i]
    npix = w.wave_soln.size
    wtrue = float(w.wave_soln[npix // 2])
    dtrue = float(w.cen_disp)

    def wrapped(self, slit, psols, msols, tcent_ecent, nstore=1, nselw=3,
                nseld=3):
        # Rebuild the histogram exactly as solve_slit does
        hists = []
        n1 = ntot = 0
        for _, _, wv, dp in (psols, msols):
            wv = np.asarray(wv, dtype=float)
            dp = np.asarray(dp, dtype=float)
            ok = (self._binw[0] < wv) & (wv < self._binw[-1]) \
                & (10**self._bind[0] < dp) & (dp < 10**self._bind[-1])
            h, _, _ = np.histogram2d(wv[ok], np.log10(dp[ok]),
                                     bins=[self._binw, self._bind])
            hists.append(h)
            n1 += int(np.sum(dp[ok] == 1.))
            ntot += int(ok.sum())
        h = hists[0] - hists[1]
        pk = patterns.detect_2Dpeaks(np.abs(h))
        b = np.unravel_index(np.argmax(np.abs(pk * h)), h.shape)
        # Votes (positive-sign histogram, as these spectra correlate) in
        # the +-3 x +-3 bin window solve_slit selects around the peak, and
        # in the same window around the stored solution; also a wider
        # window (+-15 dispersion bins, +-3.5%) around the stored solution
        hp = hists[0]
        it = int(np.searchsorted(self._binw, wtrue)) - 1
        jt = int(np.searchsorted(self._bind, np.log10(dtrue))) - 1

        def box(i0, j0, di, dj):
            return int(hp[max(i0 - di, 0):i0 + di + 1,
                          max(j0 - dj, 0):j0 + dj + 1].sum())
        calls.append(dict(
            disp=10**self._bind[b[1]], wcen=self._binw[b[0]],
            count=abs(h[b]), n1=n1, ntot=ntot,
            win_peak=box(b[0], b[1], nselw, nseld),
            win_true=box(it, jt, nselw, nseld),
            wide_true=box(it, jt, nselw, 15),
            peak_true=int(hp[it, jt])))
        return orig(self, slit, psols, msols, tcent_ecent, nstore, nselw,
                    nseld)

    autoid.HolyGrail.solve_slit = wrapped
    spec = load_spectrograph('subaru_moircs')
    par = spec.config_specific_par(raw)['calibrations']['wavelengths']
    par['method'] = 'holy-grail'
    par['match_toler'] = 2.0
    fwhms = np.array([None if w is None else w.fwhm for w in wc.wv_fits],
                     dtype=object)
    hg = autoid.HolyGrail(wc.arc_spectra, par['lamps'], par=par,
                          ok_mask=np.array([i]), measured_fwhms=fwhms,
                          nonlinear_counts=spec.get_detector_par(det)
                          .nonlinear_counts())
    patt, fits = hg.get_results()
    f = fits.get(str(i))
    if f is None:
        print(f'DET0{det} slit {spat} ({variant}): no solution')
    else:
        dl = float(np.max(np.abs(f.wave_soln - w.wave_soln)))
        print(f'DET0{det} slit {spat} ({variant}): final bdisp '
              f'{patt[str(i)]["bdisp"]:.4f} A/px, stored rms {f.rms:.3f} '
              f'px, {len(f.wave_fit)} lines, max|dl| vs run3 {dl:.1f} A')
    print(f'stored (run3) solution: wcen {wtrue:.1f} A, disp {dtrue:.4f} '
          f'A/px')
    print('call  patterns     peak_disp  peak_wcen  peak_count  n(disp==1)'
          '  n_solutions  win_peak  win_true  wide_true')
    for k, c in enumerate(calls):
        # run_brute_loop: poly 3 then 4, 3 x 3 (detsrch, lstsrch) each,
        # unless it returns early
        kind = 'triangles' if k < 9 else 'quadrangles'
        print(f'{k:4d}  {kind:11s}  {c["disp"]:9.4f}  {c["wcen"]:9.1f}  '
              f'{c["count"]:10.0f}  {c["n1"]:10d}  {c["ntot"]:11d}  '
              f'{c["win_peak"]:8d}  {c["win_true"]:8d}  {c["wide_true"]:9d}')


if __name__ == '__main__':
    if sys.argv[1] == 'check':
        check(sys.argv[2:])
    elif sys.argv[1] == 'hist':
        hist(sys.argv[2], sys.argv[3], int(sys.argv[4]), int(sys.argv[5]),
             sys.argv[6] if len(sys.argv) > 6 else 'asis')
    elif sys.argv[1] == 'rerun':
        rerun(sys.argv[2], sys.argv[3])
    else:
        raise ValueError(f'Unknown mode {sys.argv[1]}')
