"""
Collect the numbers for the Implementation #6 report (independent VB_K
wavelength checks with the ThAr arcs and the mask image) into
report_impl6/data.json, and build report_impl6/vbk_wavecheck_report.html
from report_impl6/template.html.

Usage: python make_report_impl6.py [--html-only]

Run ``arc_check.py run5 wavecheck`` and ``mask_wave_check.py run5
wavecheck`` first: their tables in ``wavecheck/`` are read here.  The
arc spectra, line profiles, frame illumination and the clipped-combine
example are recomputed from the raw ThAr frames and run5 calibrations.
With --html-only, only the page is rebuilt from the existing data.json.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json
import logging
import sys
from pathlib import Path

import numpy as np
from astropy.table import Table

from pypeit.core.wavecal import waveio
from pypeit.spectrographs.util import load_spectrograph

import arc_check

logging.disable(logging.WARNING)
HERE = Path(__file__).resolve().parent
OUT = HERE / 'report_impl6'
REDUX = HERE / 'run5'
WCHK = HERE / 'wavecheck'
WSTEP = 8  # wavelength sampling (px) sent for the spectra
PROF_HW = 15  # half-width (px) of the profile cut-outs
# Example profiles: (det, slit, Ar line, OH line), as in arc_profiles.png
PROFILES = [(1, 1388, 20621.86, 20412.7), (2, 787, 20621.86, 20412.7)]
# Clipped-combine example: DET01 slit 1520 (Implementation #6 log)
CLIP_SLIT, CLIP_LINES = 1520, [20991.84, 23851.54]


def read_tables():
    """Read the ``arc_check`` and ``mask_wave_check`` tables.

    Generated by JXP and Claude.

    Returns:
        tuple: Ar lines (all images), OH control lines, mask rows.
    """
    ar = Table.read(WCHK / 'arc_offsets.txt', format='ascii.fixed_width')
    oh = Table.read(WCHK / 'arc_oh_control.txt', format='ascii.fixed_width')
    mw = Table.read(WCHK / 'mask_wave.txt', format='ascii.fixed_width')
    # Booleans come back as strings from the fixed-width tables
    for t in (ar, oh, mw):
        t['in_fit_range'] = np.array([str(v) == 'True'
                                      for v in t['in_fit_range']])
    return ar, oh, mw


def chip_stats(ar, oh):
    """Per-chip numbers for the tables and key facts.

    Generated by JXP and Claude.

    Args:
        ar (Table): Ar lines, all images.
        oh (Table): OH control lines.

    Returns:
        dict: det -> statistics.
    """
    mean = ar[ar['frame'] == 'mean']
    out = {}
    for det in (1, 2):
        t = mean[mean['det'] == det]
        sids = np.unique(t['spat_id'])
        n = np.array([np.sum(t['spat_id'] == s) for s in sids])
        med = np.array([np.median(t['offset'][t['spat_id'] == s])
                        for s in sids])
        p, cov = np.polyfit(sids, med, 1, cov=True)
        # Trend with wavelength, slit medians removed (slits >= 3 lines)
        x, y = [], []
        for s in sids:
            ts = t[t['spat_id'] == s]
            if len(ts) >= 3:
                x += list((ts['wave'] - 22000.) / 1000.)
                y += list(ts['offset'] - np.median(ts['offset']))
        q, qcov = np.polyfit(x, y, 1, cov=True)
        # Single frames: lines measured in >= 2 frames
        sf = ar[(ar['frame'] != 'mean') & (ar['det'] == det)]
        dev = []
        for s in np.unique(sf['spat_id']):
            for w in np.unique(sf['wave'][sf['spat_id'] == s]):
                tw = sf[(sf['spat_id'] == s) & (sf['wave'] == w)]
                if len(tw) >= 2:
                    dev += list(tw['offset'] - np.mean(tw['offset']))
        o = oh[oh['det'] == det]
        omed = [np.median(o['offset'][o['spat_id'] == s])
                for s in np.unique(o['spat_id'])]
        out[det] = dict(
            nslit=int(sids.size), nslit2=int(np.sum(n >= 2)),
            nmin=int(n.min()), nmax=int(n.max()), nline=len(t),
            median=float(np.median(t['offset'])),
            robust=float(1.4826 * np.median(np.abs(
                t['offset'] - np.median(t['offset'])))),
            slit_median=float(np.median(med)), slit_std=float(np.std(med)),
            rot_c=float(np.polyval(p, 1024.)), rot_s=float(1e3 * p[0]),
            rot_se=float(1e3 * np.sqrt(cov[0, 0])),
            rot_rms=float(np.std(med - np.polyval(p, sids))),
            trend=float(q[0]), trend_se=float(np.sqrt(qcov[0, 0])),
            scatter=float(np.std(np.array(y) - np.polyval(q, x))),
            frame_std=float(np.std(dev)), frame_max=float(np.max(np.abs(dev))),
            frame_n=len(dev),
            oh_median=float(np.median(o['offset'])),
            oh_slit_std=float(np.std(omed)))
    return out


def slit_rows(ar, mw, stats):
    """One row per science slit: arc, standards and mask-image results.

    Generated by JXP and Claude.

    Args:
        ar (Table): Ar lines, all images.
        mw (Table): Mask-image rows.
        stats (dict): ``chip_stats`` output.

    Returns:
        list: dicts, DET01 then DET02, by spat_id.
    """
    mean = ar[ar['frame'] == 'mean']
    std = arc_check.std_offsets(HERE / 'std_oh_offset_run2.txt')
    rows = []
    for det in (1, 2):
        t = mean[mean['det'] == det]
        m = mw[mw['det'] == det]
        nslit = np.unique(m['spat_id']).size
        full = [r for r in np.unique(m['row'])
                if np.sum(m['in_fit_range'] & (m['row'] == r)) == nslit]
        _, _, wc = arc_check.load_calibs(REDUX, det)
        waves = {int(w.spat_id): w.wave_soln for w in wc.wv_fits
                 if w is not None and w.pypeitfit is not None}
        for s in np.unique(t['spat_id']):
            ts = t[t['spat_id'] == s]
            med = float(np.median(ts['offset']))
            ms = m[m['spat_id'] == s]
            fit = ms['in_fit_range']
            shape = ms['resid_spat'][fit & np.isin(ms['row'], full)]
            st = stats[det]
            rot = st['rot_c'] + st['rot_s'] / 1e3 * (s - 1024.)
            rows.append(dict(
                det=det, spat=int(s), n=len(ts), arc=round(med, 3),
                arc_res=round(med - rot, 3),
                std=None if int(s) not in std[det]
                else round(std[det][int(s)], 3),
                mrow=round(float(ms['mask_row'][0]), 2),
                mspat=float(ms['mask_spat'][0]),
                tilt=round(float(ms['mask_tilt'][0]), 4),
                lin=round(float(np.median(ms['resid_lin'][fit])), 2),
                zp=round(float(np.median(ms['resid_spat'][fit])), 2),
                shape=round(float(shape.max() - shape.min()), 2),
                w1150=round(float(ms['wave'][ms['row'] == 1150][0]), 1),
                w0=round(float(waves[int(s)][0]), 0),
                w1=round(float(waves[int(s)][-1]), 0)))
    return rows


def mask_rows(mw):
    """Residuals along the detector per slit (both models).

    Generated by JXP and Claude.

    Args:
        mw (Table): Mask-image rows.

    Returns:
        dict: rows, the slope (A per mask px) per detector row and
        detector, and per (det, spat) the residual lists and flags.
    """
    out = dict(rows=[int(r) for r in np.unique(mw['row'])], slits=[],
               slopes={})
    for det in (1, 2):
        m = mw[mw['det'] == det]
        # Slope of wavelength vs mask row at each detector row (linear
        # model, slits inside their fitted range)
        out['slopes'][str(det)] = [
            round(float(np.polyfit(m['mask_row'][k], m['wave'][k], 1)[0]), 3)
            for k in [(m['row'] == r) & m['in_fit_range']
                      for r in out['rows']]]
        for s in np.unique(m['spat_id']):
            ms = m[m['spat_id'] == s]
            out['slits'].append(dict(
                det=det, spat=int(s),
                lin=[round(float(v), 3) for v in ms['resid_lin']],
                spat_res=[round(float(v), 3) for v in ms['resid_spat']],
                fit=[bool(v) for v in ms['in_fit_range']]))
    return out


def images(det, spec, par):
    """Clipped mean, plain mean and single-frame arc images of a chip.

    Generated by JXP and Claude.

    Args:
        det (int): Detector.
        spec (Spectrograph): MOIRCS.
        par (ParSet): Run parameters.

    Returns:
        dict: label -> (image, bad-pixel mask).
    """
    out = {'mean': arc_check.build_image(spec, par, arc_check.ARCS, det)}
    for k, f in enumerate(arc_check.ARCS):
        out[f'f{k}'] = arc_check.build_image(spec, par, [f], det)
    out['clipped'] = arc_check.build_image(spec, par, arc_check.ARCS,
                                           det, clip=True)
    return out


def cutout(cs, c):
    """Profile around a position, normalized to its peak.

    Generated by JXP and Claude.

    Args:
        cs (numpy.ndarray): Continuum-subtracted spectrum.
        c (float): Centre (px).

    Returns:
        dict: x (px from the centre) and y (normalized flux).
    """
    i = int(np.round(c))
    x = np.arange(i - PROF_HW, i + PROF_HW + 1)
    y = cs[x]
    return dict(x=[round(float(v - c), 2) for v in x],
                y=[round(float(v), 4) for v in y / y.max()])


def spectra_and_profiles(ar, oh):
    """Arc spectra of every slit, frame illumination, example profiles
    and the clipped-combine example.

    Generated by JXP and Claude.

    Args:
        ar (Table): Ar lines, all images.
        oh (Table): OH control lines.

    Returns:
        dict: spectra, illum, profiles, clip.
    """
    spec = load_spectrograph('subaru_moircs')
    par = spec.config_specific_par(str(arc_check.SCI))
    mean = ar[ar['frame'] == 'mean']
    lines, _, _ = waveio.load_line_lists(['Ar_IR_MOSFIRE'])
    w = np.asarray(lines['wave'])
    ar_waves = np.sort(w[(w > arc_check.WMIN) & (w < arc_check.WMAX)])
    spectra, illum, profiles, clip, cstats = [], [], [], {}, {}
    for det in (1, 2):
        slits, tiltimg, wc = arc_check.load_calibs(REDUX, det)
        imgs = images(det, spec, par)
        cstats[str(det)] = clip_image_stats(imgs, slits)
        sci = arc_check.build_image(spec, par, [arc_check.SCI], det)
        for i, wfit in enumerate(wc.wv_fits):
            if wfit is None or wfit.pypeitfit is None:
                continue
            sid = int(slits.spat_id[i])
            csn = {k: arc_check.contsub(arc_check.collapse_slit(
                im, bpm, slits, tiltimg, i)) for k, (im, bpm)
                in imgs.items()}
            cs = {k: v[0] for k, v in csn.items()}
            nspec = cs['mean'].size
            tm = mean[(mean['det'] == det) & (mean['spat_id'] == sid)]
            pix, wv, _ = arc_check.predict(wfit, ar_waves, nspec)
            measured = [bool(np.any(np.abs(tm['wave'] - x) < 0.01))
                        for x in wv]
            spectra.append(dict(
                det=det, spat=sid,
                wave=np.round(wfit.wave_soln[::WSTEP], 1).tolist(),
                flux=np.round(cs['mean'], 1).tolist(),
                lines=[dict(w=round(float(a), 2), p=round(float(b), 2),
                            m=c) for a, b, c in zip(wv, pix, measured)]))
            # Line flux per frame over the measured lines, per slit
            cen = tm['pix_pred'] + tm['offset']
            flux = []
            for k in ('f0', 'f1', 'f2', 'f3'):
                flux.append(float(sum(
                    np.sum(np.clip(cs[k][int(c) - 7:int(c) + 8], 0, None))
                    for c in cen)))
            mx = max(flux) if max(flux) > 0 else 1.
            illum.append(dict(det=det, spat=sid,
                              f=[round(v / mx, 3) for v in flux],
                              tot=round(mx, 0)))
            for pdet, pslit, wa, wo in PROFILES:
                if (pdet, pslit) != (det, sid):
                    continue
                ra = tm[np.abs(tm['wave'] - wa) < 0.01][0]
                to = oh[(oh['det'] == det) & (oh['spat_id'] == sid)]
                ro = to[np.argmin(np.abs(to['wave'] - wo))]
                skycs = arc_check.contsub(arc_check.collapse_slit(
                    sci[0], sci[1], slits, tiltimg, i))[0]
                profiles.append(dict(
                    det=det, spat=sid, ar_wave=float(ra['wave']),
                    oh_wave=round(float(ro['wave']), 1),
                    ar=cutout(cs['mean'], ra['pix_pred'] + ra['offset']),
                    oh=cutout(skycs, ro['pix_pred'] + ro['offset'])))
            if (det, sid) == (1, CLIP_SLIT):
                clip = dict(spat=sid, lines=[])
                for wl in CLIP_LINES:
                    p = float(np.interp(wl, wfit.wave_soln,
                                        np.arange(nspec)))
                    i0 = int(np.round(p))
                    x = np.arange(i0 - PROF_HW, i0 + PROF_HW + 1)
                    clip['lines'].append(dict(
                        wave=wl, x=[round(float(v - p), 2) for v in x],
                        **{k: np.round(cs[k][x], 1).tolist()
                           for k in ('clipped', 'mean', 'f1', 'f2')},
                        off={k: offset_of(csn[k], p) for k in
                             ('clipped', 'mean', 'f1', 'f2')}))
    return dict(spectra=spectra, illum=illum, profiles=profiles, clip=clip,
                clipstats=cstats)


def offset_of(csn, p):
    """Offset of a line from its predicted position, measured as in
    ``arc_check.match`` (search +-4 px).

    Generated by JXP and Claude.

    Args:
        csn (tuple): Continuum-subtracted spectrum and its noise.
        p (float): Predicted position (px).

    Returns:
        float or None: measured - predicted (px), or None if the line
        is not measured.
    """
    m = arc_check.match(np.array([p]), csn[0], csn[1], 0., 4.)
    return None if not m else round(float(m[0][1]), 3)


def clip_image_stats(imgs, slits):
    """How the sigma-clipped combine differs from the plain mean on the
    bright (line) pixels of the science slits.

    Generated by JXP and Claude.

    Args:
        imgs (dict): ``images`` output.
        slits (SlitTraceSet): Slits.

    Returns:
        dict: fraction of bright pixels differing by > 5 sigma, the
        median clipped/plain ratio there, and the same fraction on faint
        pixels.
    """
    clipped, mean = imgs['clipped'][0], imgs['mean'][0]
    img = slits.slit_img(exclude_flag=slits.bitmask.exclude_for_reducing)
    sci = np.isin(img, slits.spat_id[slits.mask == 0])
    sig = np.sqrt(np.abs(mean) + 17.5 ** 2)
    big = np.abs(clipped - mean) > 5 * sig
    bright = sci & (mean > 400.)
    faint = sci & (mean < 150.)
    return dict(frac_bright=round(float(np.mean(big[bright])), 3),
                ratio=round(float(np.median(clipped[bright]
                                            / mean[bright])), 3),
                frac_faint=round(float(np.mean(big[faint])), 4),
                npix_bright=int(bright.sum()))


def write_html():
    """Fill the template with data.json.  Generated by JXP and Claude."""
    data = (OUT / 'data.json').read_text()
    html = (OUT / 'template.html').read_text().replace('__DATA__', data)
    out = OUT / 'vbk_wavecheck_report.html'
    out.write_text(html)
    print(f'Wrote {out} ({out.stat().st_size / 1e3:.0f} kB)')


def main():
    """Write report_impl6/data.json and the report page.  Generated by
    JXP and Claude."""
    OUT.mkdir(exist_ok=True)
    if '--html-only' not in sys.argv:
        ar, oh, mw = read_tables()
        stats = chip_stats(ar, oh)
        mean = ar[ar['frame'] == 'mean']
        data = dict(
            stats={str(k): v for k, v in stats.items()},
            slits=slit_rows(ar, mw, stats), mask=mask_rows(mw),
            ar=[[int(r['det']), int(r['spat_id']), float(r['wave']),
                 round(float(r['offset']), 3), round(float(r['err']), 3)]
                for r in mean],
            oh=[[int(r['det']), int(r['spat_id']), round(float(r['wave']), 1),
                 round(float(r['offset']), 3)] for r in oh],
            **spectra_and_profiles(ar, oh))
        (OUT / 'data.json').write_text(
            json.dumps(data, separators=(',', ':')))
        print(f'Wrote {OUT / "data.json"} '
              f'({(OUT / "data.json").stat().st_size / 1e3:.0f} kB)')
    write_html()


if __name__ == '__main__':
    main()
