"""
Build the holy-grail dispersion-truncation bug report page
(report_holy_bug/holy_bug_report.html) from the outputs of
holy_rms_check.py (rerun, hist) and holy_rms_repro.py.

Usage: python make_report_holy_bug.py

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json
import re
from pathlib import Path

import numpy as np

from pypeit.wavecalib import WaveCalib

HERE = Path(__file__).resolve().parent
OUT = HERE / 'report_holy_bug'


def parse_hist(fn):
    """
    Parse the output of ``holy_rms_check.py hist``.

    Generated by JXP and Claude.

    Args:
        fn (Path): Text output.

    Returns:
        dict: Header values and one row per solve_slit call.
    """
    lines = fn.read_text().splitlines()
    m = re.search(r'final bdisp ([\d.]+) A/px, stored rms ([\d.]+)',
                  lines[0])
    calls = []
    for line in lines[2:]:
        p = line.split()
        if len(p) == 6:
            calls.append(dict(call=int(p[0]), kind=p[1], disp=float(p[2]),
                              count=float(p[3]), n1=int(p[4]),
                              ntot=int(p[5])))
    return dict(bdisp=float(m.group(1)), rms=float(m.group(2)),
                calls=calls)


def coverage(redux):
    """
    Wavelength range of each solved slit in a reduction.

    Generated by JXP and Claude.

    Args:
        redux (Path): Reduction directory.

    Returns:
        list: dicts with det, spat, w0, w1 (A).
    """
    out = []
    for det in [1, 2]:
        wc = WaveCalib.from_file(redux / 'Calibrations'
                                 / f'WaveCalib_A_0_DET0{det}.fits',
                                 chk_version=False)
        for w in wc.wv_fits:
            if w is not None and w.pypeitfit is not None:
                out.append(dict(det=det, spat=int(w.spat_id),
                                w0=round(float(w.wave_soln[0])),
                                w1=round(float(w.wave_soln[-1]))))
    return out


def disp_curves(redux, step=20):
    """
    Local dispersion along each slit, relative to the central value.

    Generated by JXP and Claude.

    Args:
        redux (Path): Reduction directory.
        step (int): Sampling in pixels.

    Returns:
        dict: pixel grid and one ratio curve per slit (det, spat).
    """
    curves = []
    pix = None
    for det in [1, 2]:
        wc = WaveCalib.from_file(redux / 'Calibrations'
                                 / f'WaveCalib_A_0_DET0{det}.fits',
                                 chk_version=False)
        for w in wc.wv_fits:
            if w is None or w.pypeitfit is None:
                continue
            d = np.gradient(w.wave_soln)
            pix = np.arange(d.size)[::step]
            curves.append(dict(det=det, spat=int(w.spat_id),
                               ratio=np.round(d[::step] / d[d.size // 2],
                                              4).tolist()))
    return dict(pix=pix.tolist(), curves=curves)


def parse_probe(fn):
    """
    Parse ``holy_rms_check.py hist`` output with vote statistics: the
    stored solution and the last triangle and quadrangle calls.

    Generated by JXP and Claude.

    Args:
        fn (Path): Text output.

    Returns:
        dict: slit, variant, final result line, stored solution, and the
        peak and vote counts of the last triangle and quadrangle calls.
    """
    lines = fn.read_text().splitlines()
    m = re.match(r'DET0(\d) slit (\d+) \((\w+)\): (.*)', lines[0])
    t = re.search(r'wcen ([\d.]+) A, disp ([\d.]+)', lines[1])
    calls = [ln.split() for ln in lines[3:] if ln.strip()
             and ln.split()[0].isdigit()]

    def row(c):
        return dict(disp=float(c[2]), wcen=float(c[3]), count=float(c[4]),
                    ntot=int(c[6]), win_peak=int(c[7]), win_true=int(c[8]),
                    wide_true=int(c[9]))
    tri = [c for c in calls if c[1] == 'triangles']
    quad = [c for c in calls if c[1] == 'quadrangles' and int(c[6]) > 0]
    return dict(det=int(m.group(1)), spat=int(m.group(2)),
                variant=m.group(3), result=m.group(4),
                wtrue=float(t.group(1)), dtrue=float(t.group(2)),
                tri=row(tri[-1]), quad=row(quad[-1]) if quad else None)


def main():
    """Write the data and the page.  Generated by JXP and Claude."""
    OUT.mkdir(exist_ok=True)
    data = dict(
        slits=list(json.loads(
            (HERE / 'holy_rms_rerun.json').read_text()).values()),
        hist=parse_hist(HERE / 'holy_rms_hist337.txt'),
        cover=coverage(HERE / 'run3'),
        disp=disp_curves(HERE / 'run3'),
        where={v: json.loads((OUT / 'where' / f'1855_{v}.json')
                             .read_text()) for v in ('asis', 'T', 'T15')},
        probes=[parse_probe(HERE / f'holy_rms_hist_det{k}.txt')
                for k in ('1_1855_asis', '1_1855_A', '1_469_A',
                          '2_1665_A')],
        repro=(HERE / 'holy_rms_repro.txt').read_text())
    js = json.dumps(data, separators=(',', ':')).replace('</', '<\\/')
    (OUT / 'data.json').write_text(js)
    html = (OUT / 'template.html').read_text().replace('__DATA__', js)
    outfile = OUT / 'holy_bug_report.html'
    outfile.write_text(html)
    print(f'Wrote {outfile} ({outfile.stat().st_size / 1e3:.0f} kB)')


if __name__ == '__main__':
    main()
