"""
Build a multi-spectrum reid_arxiv for Subaru/MOIRCS VB_K from the good
holy-grail OH solutions of the VB_K test mask (both detectors), for use
with the 'reidentify' method.  Adapted from the HK500 script
(pypeitdev/subaru_moircs/make_hk500_reid.py).

Usage: python make_vbk_reid.py <redux_dir> [outfile] [--exclude ID ...]

- redux_dir: reduction with the holy-grail WaveCalib files (run3).
- outfile: output path; default writes subaru_moircs_VB_K.fits into the
  PypeIt reid_arxiv directory.
- --exclude: archive IDs (det*10000 + spat_id) to leave out, e.g. for a
  leave-one-out test.
- --det: use only these detectors (default 1 2).

Not part of PypeIt.  Generated by JXP and Claude.
"""
import argparse
from pathlib import Path

import numpy as np
from astropy.table import Table

from pypeit import dataPaths
from pypeit.wavecalib import WaveCalib

# Selection of good holy-grail solutions (as for HK500)
RMS_MAX = 0.5   # pixels
NLIN_MIN = 40


def select_rows(redux, dets, exclude=(), verbose=True):
    """
    Collect the good holy-grail solutions of a reduction.

    Generated by JXP and Claude.

    Args:
        redux (Path): Reduction directory with ``Calibrations/``.
        dets (list): Detectors to use (1, 2).
        exclude (list): Archive IDs (det*10000 + spat_id) to skip.
        verbose (bool): Print the skipped and used slits.

    Returns:
        list: Tuples of (wave_soln, spec, archive ID), sorted by the
        wavelength of the first pixel.
    """
    rows = []
    for det in dets:
        wc = WaveCalib.from_file(
            redux / 'Calibrations' / f'WaveCalib_A_0_DET0{det}.fits',
            chk_version=False)
        for w in wc.wv_fits:
            if w is None or w.pypeitfit is None:
                continue
            aid = det * 10000 + int(w.spat_id)
            if aid in exclude:
                continue
            # Good fit and a monotonic solution over the full detector
            mono = np.all(np.diff(w.wave_soln) > 0)
            nlin = len(w.wave_fit)
            if w.rms > RMS_MAX or nlin < NLIN_MIN or not mono:
                if verbose:
                    print(f'skip {aid} rms={w.rms:.2f} n={nlin} '
                          f'mono={mono}')
                continue
            rows.append((w.wave_soln, w.spec, aid))
            if verbose:
                print(f'use  {aid} rms={w.rms:.3f} n={nlin} '
                      f'{w.wave_soln[0]:.0f}-{w.wave_soln[-1]:.0f} A')
    # Order by spectral coverage (blue to red) for readability
    rows.sort(key=lambda r: r[0][0])
    return rows


def write_arxiv(rows, outfile):
    """
    Write the archive in the PypeIt reid_arxiv FITS format.

    Generated by JXP and Claude.

    Args:
        rows (list): Output of :func:`select_rows`.
        outfile (Path): Output file.

    Returns:
        `astropy.table.Table`_: The table written.
    """
    nspec = rows[0][0].size
    tbl = Table(names=('wave', 'flux', 'order'),
                dtype=(f'({nspec},)>f8', f'({nspec},)>f8', '>i8'))
    for r in rows:
        tbl.add_row(r)
    tbl.meta['BINSPEC'] = 1
    tbl.write(outfile, format='fits', overwrite=True)
    return tbl


def main():
    """Command-line wrapper.  Generated by JXP and Claude."""
    p = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    p.add_argument('redux', type=Path)
    p.add_argument('outfile', nargs='?', default=None)
    p.add_argument('--exclude', type=int, nargs='*', default=[])
    p.add_argument('--det', type=int, nargs='*', default=[1, 2])
    args = p.parse_args()
    outfile = dataPaths.reid_arxiv.path / 'subaru_moircs_VB_K.fits' \
        if args.outfile is None else Path(args.outfile)
    rows = select_rows(args.redux, args.det, exclude=args.exclude)
    tbl = write_arxiv(rows, outfile)
    wmin = min(r[0][0] for r in rows)
    wmax = max(r[0][-1] for r in rows)
    print(f'Wrote {len(tbl)} spectra ({wmin:.0f}-{wmax:.0f} A) to '
          f'{outfile}')


if __name__ == '__main__':
    main()
