"""
Figures and numbers for the VB_K report (``subaru_moircs_report_VBK.md``).

Uses the final reduction (``run5``: reidentify, ``maxnumber_std = 1``)
and the outputs of the earlier check scripts.  Writes to ``report_vbk/``:

- ``wave_run5.png``: wavelength rms, number of lines and coverage per
  slit;
- ``numbers_run5.txt``: the wavelength ranges and the pixel-flat scatter
  inside the science slits;
- downscaled copies of the QA figures shown in the report.

Usage::

    python make_report_vbk.py

Generated by JXP and Claude
"""

from pathlib import Path

import matplotlib
import numpy as np
from PIL import Image

from pypeit.flatfield import FlatImages
from pypeit.slittrace import SlitTraceSet
from pypeit.wavecalib import WaveCalib

matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402 (after the backend is set)

OUT = Path('report_vbk')
RUN = Path('run5')
C1, C2, INK2 = '#2a78d6', '#eb6834', '#52514e'

# Report figure name -> source figure (made by the earlier scripts)
COPIES = {
    'slits_DET01.png': OUT / 'slits_run5_DET01.png',
    'slits_DET02.png': OUT / 'slits_run5_DET02.png',
    'skysub_A.png': OUT / 'skysub_run5_MCSA00352031.png',
    'raw_striping.png': Path('raw_AB_chip2_striping.png'),
    'bpm_check.png': Path('bpm_check/bpm_check_vbk.png'),
    'reid_arxiv.png': Path('reid/vbk_reid_arxiv.png'),
    'arc_offsets.png': Path('wavecheck/arc_offsets.png'),
    'arc_vs_spat.png': Path('wavecheck/arc_vs_spat.png'),
    'mask_wave.png': Path('wavecheck/mask_wave.png'),
    'sens_A0_pca.png': Path('flux/qa_sens_A0_pca.png'),
    'sens_telluric_offset.png':
        Path('flux/qa_sens_A0_pca_telluric_offset.png'),
    'flat_ratio.png': Path('flux/flat_ratio_det1_to_det2.png'),
    'sky_ratio.png': Path('flux/sky_ratio.png'),
    'det2_modes.png': Path('flux/det2_modes.png'),
}


def good_fits(det):
    """
    Read the solved wavelength fits of one detector of ``run5``.

    Generated by JXP and Claude

    Args:
        det (:obj:`int`):
            Detector (1 or 2).

    Returns:
        :obj:`list`: ``(spat_id, WaveFit)`` tuples for the solved slits,
        sorted by the blue end of the solution.
    """
    wc = WaveCalib.from_file(
        RUN / 'Calibrations' / f'WaveCalib_A_0_DET0{det}.fits',
        chk_version=False)
    fits = [(s, w) for s, w in zip(wc.spat_ids, wc.wv_fits)
            if w is not None and w.pypeitfit is not None]
    return sorted(fits, key=lambda f: f[1].wave_soln[0])


def fig_wave():
    """
    Plot the rms, number of lines and wavelength range of each slit.

    Generated by JXP and Claude

    Returns:
        :obj:`list`: One text line per detector with the ranges.
    """
    fig, axes = plt.subplots(2, 2, figsize=(10, 6.5),
                             gridspec_kw=dict(height_ratios=[1, 1.4]))
    lines = []
    for col, det in enumerate([1, 2]):
        fits = good_fits(det)
        x = np.arange(len(fits))
        rms = np.array([w.rms for _, w in fits])
        # Lines in the fit, and those kept after its rejection
        nlin = np.array([len(w.pixel_fit) for _, w in fits])
        nkept = np.array([w.pypeitfit.gpm.sum() for _, w in fits])
        ax = axes[0, col]
        ax.plot(x, rms, 's', color=C1, label='rms (px)')
        ax.set_ylim(0, 0.3)
        ax.set_xticks(x, [str(s) for s, _ in fits], rotation=60,
                      fontsize=8)
        ax.set_title(f'DET0{det}: rms and lines per slit', loc='left')
        ax2 = ax.twinx()
        ax2.plot(x, nlin, 'o', color=C2, mfc='none', label='lines')
        ax2.plot(x, nkept, '.', color=C2, label='kept')
        ax2.set_ylim(0, 70)
        if col == 0:
            ax.set_ylabel('rms (px)', color=C1)
        else:
            ax2.set_ylabel('lines fitted (o), kept (.)', color=C2)
        ax = axes[1, col]
        for i, (s, w) in enumerate(fits):
            ax.plot([w.wave_soln[0] / 1e4, w.wave_soln[-1] / 1e4], [i, i],
                    color=C1, lw=2, alpha=0.35)
            ax.plot([w.wave_fit.min() / 1e4, w.wave_fit.max() / 1e4],
                    [i, i], color=C1, lw=6, solid_capstyle='butt')
        ax.axvline(2.499, color=INK2, lw=1, ls='--')
        ax.set_yticks(range(len(fits)), [str(s) for s, _ in fits],
                      fontsize=8)
        ax.set_xlim(1.85, 2.6)
        ax.set_xlabel('wavelength (um)')
        ax.set_title('range: fitted lines (thick), solution (thin); '
                     'dashed: end of OH list', loc='left', fontsize=9)
        lines.append(f'DET0{det}: {len(fits)} slits, rms '
                     f'{rms.min():.3f}-{rms.max():.3f} px (median '
                     f'{np.median(rms):.3f}), lines {nlin.min()}-'
                     f'{nlin.max()} (kept {nkept.min()}-{nkept.max()}), '
                     'solutions '
                     f'{min(w.wave_soln[0] for _, w in fits):.0f}-'
                     f'{max(w.wave_soln[-1] for _, w in fits):.0f} A')
    fig.tight_layout()
    fig.savefig(OUT / 'wave_run5.png', dpi=110)
    plt.close(fig)
    return lines


def flat_stats(det):
    """
    Measure the pixel-flat scatter inside the science slits.

    The scatter is the robust standard deviation (1.4826 x MAD) of the
    normalized pixel flat over the central 80% of each science slit (box
    slits excluded).  The row median is the median of the flat along the
    spatial direction at each spectral row, over the same pixels.

    Generated by JXP and Claude

    Args:
        det (:obj:`int`):
            Detector (1 or 2).

    Returns:
        :obj:`str`: One line with the scatter and the row-median range.
    """
    cal = RUN / 'Calibrations'
    flat = FlatImages.from_file(cal / f'Flat_A_0_DET0{det}.fits',
                                chk_version=False)
    slits = SlitTraceSet.from_file(cal / f'Slits_A_0_DET0{det}.fits.gz',
                                   chk_version=False)
    img = flat.pixelflat_norm
    left, right, _ = slits.select_edges()
    # Science slits only: no bits set in the slit mask
    sci = slits.mask == 0
    spat = np.arange(img.shape[1])
    sel = np.zeros(img.shape, dtype=bool)
    for i in np.where(sci)[0]:
        lo = left[:, i] + 0.1 * (right[:, i] - left[:, i])
        hi = right[:, i] - 0.1 * (right[:, i] - left[:, i])
        sel |= (spat[None, :] > lo[:, None]) & (spat[None, :] < hi[:, None])
    vals = img[sel & (img > 0)]
    mad = 1.4826 * np.median(np.abs(vals - np.median(vals)))
    masked = np.where(sel & (img > 0), img, np.nan)
    rowmed = np.nanmedian(masked, axis=1)
    inner = rowmed[100:-100]
    return (f'DET0{det}: {sci.sum()} science slits, scatter '
            f'{100 * mad:.2f}%, row median {np.nanmin(inner):.4f}-'
            f'{np.nanmax(inner):.4f} (rows 100 to -100), '
            f'{np.nanmin(rowmed):.4f}-{np.nanmax(rowmed):.4f} (all rows)')


def copy_small(src, dst, width=1100):
    """
    Copy a PNG, downscaled to at most ``width`` pixels.

    Generated by JXP and Claude

    Args:
        src (`Path`_):
            Source PNG.
        dst (`Path`_):
            Output PNG.
        width (:obj:`int`, optional):
            Maximum width in pixels.
    """
    img = Image.open(src)
    if img.width > width:
        img = img.resize((width, round(img.height * width / img.width)),
                         Image.LANCZOS)
    img.save(dst, optimize=True)


def main():
    """
    Write the report figures and numbers.

    Generated by JXP and Claude
    """
    OUT.mkdir(exist_ok=True)
    lines = fig_wave()
    lines += [flat_stats(det) for det in [1, 2]]
    (OUT / 'numbers_run5.txt').write_text('\n'.join(lines) + '\n')
    print('\n'.join(lines))
    for name, src in COPIES.items():
        copy_small(src, OUT / name)
        print(f'copied {src} -> {OUT / name}')


if __name__ == '__main__':
    main()
