"""
Collect the numbers for the Implementation #7 report (VB_K standards,
spliced sensitivity function, and the chip-1 to chip-2 transfer) into
report_impl7/data.json, and build report_impl7/vbk_fluxing_report.html
from report_impl7/template.html.

Usage: python make_report_impl7.py [--html-only]

Run first (see the Implementation #7 log): the coadds and sensfunc runs
in ``flux/``, ``transfer_sensfunc.py sens ... --qa
flux/flat_ratio_det1_to_det2``, ``sky_ratio_check.py run5
flux/sky_ratio``, and ``pypeit_flux_calib flux/vbk_chip_transfer.flux``.
With --html-only, only the page is rebuilt from the existing data.json.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json
import logging
import sys
from pathlib import Path

import numpy as np

from pypeit.core import standard
from pypeit.flatfield import FlatImages
from pypeit.onespec import OneSpec
from pypeit.sensfunc import SensFunc
from pypeit.slittrace import SlitTraceSet
from pypeit.specobjs import SpecObjs

from sensfunc_check import telluric_offset
from transfer_sensfunc import slit_flat_spectra

logging.disable(logging.WARNING)

OUT = Path('report_impl7')
FLUX = Path('flux')
CAL = Path('run5/Calibrations')
DISP = 1.95
# 2MASS Ks = 7.359 (F0 = 4.283e-10 W/m2/um), in 1e-17 erg/s/cm2/A
FKS = 4.283e-11 * 10**(-0.4 * 7.359) / 1e-17
VARIANTS = [('A0_pca', 'PCA', 'A0 (Vega)'), ('A2_pca', 'PCA', 'A2 (Kurucz)'),
            ('A0', 'TelFit grid', 'A0 (Vega)'),
            ('A2', 'TelFit grid', 'A2 (Kurucz)')]


def rnd(a, n=4):
    """Round an array to a list for JSON (NaN -> None).  Generated by JXP
    and Claude."""
    return [None if not np.isfinite(v) else round(float(v), n)
            for v in np.asarray(a, dtype=float)]


def coadds():
    """Counts of the two coadded standards.  Generated by JXP and
    Claude."""
    out = {}
    for s in ['std1', 'std2']:
        sp = OneSpec.from_file(FLUX / f'coadd1d_{s}_HIP59174.fits',
                               chk_version=False)
        g = sp.mask.astype(bool) & (sp.wave > 1)
        out[s] = dict(w=rnd(sp.wave[g][::2], 1), c=rnd(sp.flux[g][::2], 0))
    return out


def variant(key):
    """Zeropoints, residuals and stats of one sensfunc variant.
    Generated by JXP and Claude."""
    sens = SensFunc.from_file(FLUX / f'sens_{key}/sens_HIP59174_{key}.fits',
                              chk_version=False)
    st, tm = sens.sens, sens.telluric.model
    res = dict(std=[])
    for k in range(len(st)):
        w = st['SENS_WAVE'][k]
        z = st['SENS_ZEROPOINT_FIT'][k]
        ok = (w >= st['WAVE_MIN'][k]) & (w <= st['WAVE_MAX'][k]) & (w > 1)
        fw = st['SENS_FLUXED_STD_WAVE'][k]
        ff = st['SENS_FLUXED_STD_FLAM'][k]
        fm = st['SENS_STD_MODEL_FLAM'][k]
        g = st['SENS_FLUXED_STD_MASK'][k].astype(bool) & (fw > 1) & (fm > 0)
        tell = np.interp(fw, tm['WAVE'][k], tm['TELLURIC'][k])
        r = ff[g] / fm[g]
        clear, deep = tell[g] > 0.95, tell[g] < 0.8
        brg = np.abs(fw[g] - 21661) < 40
        res['std'] += [dict(
            wmin=round(float(st['WAVE_MIN'][k])),
            wmax=round(float(st['WAVE_MAX'][k])),
            zw=rnd(w[ok][::3], 1), zp=rnd(z[ok][::3], 4),
            rw=rnd(fw[g][::2], 1), r=rnd(r[::2], 4),
            tell=rnd(tell[g][::2], 3),
            chi2=round(float(tm['CHI2'][k])),
            clear=round(float(np.std(r[clear])), 4),
            deep=round(float(np.std(r[deep])), 4),
            brg=round(float(np.mean(r[brg])), 3))]
    wsp, zsp = sens.wave[:, 0], sens.zeropoint[:, 0]
    ok = (wsp > 1) & (zsp > 5)
    res['splice'] = dict(w=rnd(wsp[ok][::3], 1), zp=rnd(zsp[ok][::3], 4))
    return sens, res


def overlap(sens):
    """Zeropoint difference of the two standards in their overlap, and the
    dome-flat ratio of their slits.  Generated by JXP and Claude."""
    st = sens.sens
    lo, hi = float(st['WAVE_MIN'][1]), float(st['WAVE_MAX'][0])
    x = np.arange(np.ceil(lo), hi, 10.)
    zs = []
    for k in range(2):
        w, z = st['SENS_WAVE'][k], st['SENS_ZEROPOINT_FIT'][k]
        ok = (w >= st['WAVE_MIN'][k]) & (w <= st['WAVE_MAX'][k]) & (w > 1)
        zs += [np.interp(x, w[ok], z[ok])]
    flat = FlatImages.from_file(CAL / 'Flat_A_0_DET01.fits',
                                chk_version=False)
    slits = SlitTraceSet.from_file(CAL / 'Slits_A_0_DET01.fits.gz',
                                   chk_version=False)
    sp = {s['spat_id']: s for s in slit_flat_spectra(flat, slits)}
    f = np.interp(x, sp[337]['wave'], sp[337]['flux']) \
        / np.interp(x, sp[469]['wave'], sp[469]['flux'])
    # Smooth the flat ratio a little (51 A) for the plot
    k = np.ones(5) / 5
    fs = np.convolve(f, k, mode='same')
    fs[:2], fs[-2:] = f[:2], f[-2:]
    return dict(w=rnd(x, 0), dzp=rnd(zs[1] - zs[0], 4),
                flat=rnd(2.5 * np.log10(fs), 4))


def offsets(sens):
    """Fitted telluric-model offsets in MOIRCS px.  Generated by JXP and
    Claude."""
    out = []
    for w, off in telluric_offset(sens):
        sel = slice(None, None, max(1, w.size // 300))
        out += [dict(w=rnd(w[sel], 1), px=rnd(off[sel] / DISP, 3))]
    return out


def model_levels():
    """Stellar models against 2MASS Ks.  Generated by JXP and Claude."""
    out = {}
    for t in ['A0', 'A2']:
        sp = standard.get_standard_spectrum(spectral_type=t, V_mag=7.45)
        w, f = np.asarray(sp.wave), np.asarray(sp.flux)
        g = (w > 21300) & (w < 21900) & (np.abs(w - 21661) > 80)
        out[t] = dict(ratio=round(float(np.median(f[g]) / FKS), 3),
                      npts=int(g.sum()))
    return out


def ratios():
    """F2/F1 from the flats, the sky check, and the slit counts.
    Generated by JXP and Claude."""
    t = np.loadtxt(FLUX / 'flat_ratio_det1_to_det2.txt')
    sel = slice(None, None, 4)
    s = np.loadtxt(FLUX / 'sky_ratio.txt')
    return dict(
        w=rnd(t[sel, 0], 0), f1=rnd(t[sel, 1], 1), f2=rnd(t[sel, 2], 1),
        n1=[int(v) for v in t[sel, 3]], n2=[int(v) for v in t[sel, 4]],
        rraw=rnd(t[sel, 5], 4), r=rnd(t[sel, 6], 4),
        bins=dict(w=rnd(s[:, 0], 0), nmin=[int(v) for v in s[:, 1]],
                  flat=rnd(s[:, 2], 4), sky=rnd(s[:, 3], 4)))


def transfer():
    """Zeropoints of the two chip-2 sens files and the fluxing checks.
    Generated by JXP and Claude."""
    d = SensFunc.from_file(FLUX / 'sens_HIP59174_A0_pca_det2_direct.fits',
                           chk_version=False)
    r = SensFunc.from_file(FLUX / 'sens_HIP59174_A0_pca_det2_flatratio.fits',
                           chk_version=False)
    w = d.wave[:, 0]
    ok = (w > 1) & (d.zeropoint[:, 0] > 5)
    sel = np.where(ok)[0][::3]
    files = []
    for f in sorted((FLUX / 'fluxed').glob('spec1d_*.fits')):
        sobjs = SpecObjs.from_fitsfile(f, chk_version=False)
        nbad = 0
        for s in sobjs:
            nbad += int(np.sum((s.OPT_COUNTS_IVAR > 0)
                               & (s.OPT_FLAM_IVAR <= 0)))
        name = f.name.replace('spec1d_', '').replace('.fits', '')
        files += [dict(name=name, nobj=int(sobjs.nobj), masked=nbad)]
    return dict(w=rnd(w[sel], 1), direct=rnd(d.zeropoint[sel, 0], 4),
                flatratio=rnd(r.zeropoint[sel, 0], 4), files=files)


def write_html():
    """Fill the template with data.json.  Generated by JXP and Claude."""
    data = (OUT / 'data.json').read_text()
    html = (OUT / 'template.html').read_text().replace('__DATA__', data)
    out = OUT / 'vbk_fluxing_report.html'
    out.write_text(html)
    print(f'Wrote {out} ({out.stat().st_size / 1e3:.0f} kB)')


def main():
    """Write report_impl7/data.json and the report page.  Generated by
    JXP and Claude."""
    OUT.mkdir(exist_ok=True)
    if '--html-only' not in sys.argv:
        var = {}
        for key, tel, star in VARIANTS:
            sens, v = variant(key)
            v.update(tel=tel, star=star)
            var[key] = v
            if key == 'A0_pca':
                adopted = sens
        data = dict(coadds=coadds(), variants=var,
                    overlap=overlap(adopted), offsets=offsets(adopted),
                    models=model_levels(), ratios=ratios(),
                    transfer=transfer())
        (OUT / 'data.json').write_text(
            json.dumps(data, separators=(',', ':')))
        print(f'Wrote {OUT / "data.json"} '
              f'({(OUT / "data.json").stat().st_size / 1e3:.0f} kB)')
    write_html()


if __name__ == '__main__':
    main()
