"""
Collect the numbers for the Implementation #5 report (VB_K reidentify
archive) into report_impl5/data.json.

Usage: python make_report_impl5.py [--html-only]

With --html-only, only rebuild report_impl5/vbk_reid_report.html from
the existing data.json and template.html.

Reads run3 (holy-grail) and run5 (reidentify) Calibrations, the
installed archive, the tune/reid_*.txt test outputs, and reruns
DET01 slit 758 leave-one-out with match_toler 2.0 and 0.75.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json
import logging
import re
import sys
from pathlib import Path

import numpy as np
from astropy.table import Table

from pypeit import dataPaths
from pypeit.core.wavecal import waveio
from pypeit.wavecalib import WaveCalib

import compare_wave_runs
import make_vbk_reid
import test_reid

logging.disable(logging.WARNING)
HERE = Path(__file__).resolve().parent
OUT = HERE / 'report_impl5'
STEP = 4    # downsampling of the spectra for the plots


def archive_data():
    """
    Archive spectra (downsampled, normalized) and the OH line list.

    Generated by JXP and Claude.

    Returns:
        dict: rows (id, det, spat, w0, w1, wave, flux) and lines.
    """
    tbl = Table.read(dataPaths.reid_arxiv.get_file_path(
        'subaru_moircs_VB_K.fits'))
    rows = []
    for r in tbl:
        f = r['flux'] / np.percentile(r['flux'], 99.5)
        rows.append(dict(id=int(r['order']), det=int(r['order']) // 10000,
                         spat=int(r['order']) % 10000,
                         w0=round(float(r['wave'][0]), 1),
                         w1=round(float(r['wave'][-1]), 1),
                         wave=np.round(r['wave'][::STEP], 1).tolist(),
                         flux=np.round(f[::STEP], 3).tolist()))
    lines = waveio.load_line_lists(['OH_MOSFIRE_K'])[0]['wave']
    return dict(rows=rows, lines=np.round(np.sort(lines), 2).tolist())


def slit_data():
    """
    Per-slit comparison of run3 (holy-grail) and run5 (reidentify).

    Generated by JXP and Claude.

    Returns:
        list: One dict per science slit.
    """
    out = []
    for det in [1, 2]:
        name = f'WaveCalib_A_0_DET0{det}.fits'
        wr = WaveCalib.from_file(HERE / 'run3' / 'Calibrations' / name,
                                 chk_version=False)
        wn = WaveCalib.from_file(HERE / 'run5' / 'Calibrations' / name,
                                 chk_version=False)
        for r, n in zip(wr.wv_fits, wn.wv_fits):
            if r is None or r.pypeitfit is None:
                continue
            sel = (r.wave_soln > r.wave_fit.min()) \
                & (r.wave_soln < r.wave_fit.max())
            dw = np.abs(n.wave_soln[sel] - r.wave_soln[sel])
            out.append(dict(
                det=det, spat=int(r.spat_id),
                w0=round(float(n.wave_soln[0])), w1=round(float(
                    n.wave_soln[-1])),
                hg_n=len(r.wave_fit), hg_rms=round(float(r.rms), 3),
                hg_true=round(float(compare_wave_runs.true_rms(r)), 3),
                re_n=len(n.wave_fit), re_rms=round(float(n.rms), 3),
                re_true=round(float(compare_wave_runs.true_rms(n)), 3),
                dmed=round(float(np.median(dw)), 3),
                dmax=round(float(dw.max()), 3)))
    return out


def test_data():
    """
    Parse the offline reidentify tests (tune/reid_*.txt).

    Generated by JXP and Claude.

    Returns:
        dict: file key -> list of per-slit dicts (det, spat, rms, n,
        dmed, dmax; None if no fit).
    """
    files = {'self_2.0': 'reid_self.txt', 'loo_2.0': 'reid_loo.txt',
             'xdet_2.0': 'reid_xdet.txt'}
    for m in ['self', 'loo', 'xdet']:
        for t in ['0.75', '0.5']:
            files[f'{m}_{t}'] = f'reid_{m}_mt{t}.txt'
    for k in [2, 3, 4]:
        files[f'xdet_nreid{k}'] = f'reid_xdet_nreid{k}.txt'
    out = {}
    for key, fn in files.items():
        rows = []
        for line in (HERE / 'tune' / fn).read_text().splitlines():
            m = re.match(r'^\s+([12])\s+(\d+)\s', line)
            if m is None:
                continue
            p = line.split()
            if 'no' in p:
                rows.append(dict(det=int(p[0]), spat=int(p[1]), rms=None,
                                 n=0, dmed=None, dmax=None))
                continue
            rows.append(dict(det=int(p[0]), spat=int(p[1]),
                             rms=float(p[5]), n=int(p[6]),
                             dmed=float(p[7]), dmax=float(p[8])))
        out[key] = rows
    return out


def slit758():
    """
    Leave-one-out solutions of DET01 slit 758 with match_toler 2.0 and
    0.75, and its sky spectrum near the red end on each scale against
    the median of the other slits.

    Generated by JXP and Claude.

    Returns:
        dict: pixel grid, dlambda curves, and the spectral window.
    """
    redux = HERE / 'run3'
    hg = WaveCalib.from_file(redux / 'Calibrations' /
                             'WaveCalib_A_0_DET01.fits', chk_version=False)
    i = [k for k, w in enumerate(hg.wv_fits)
         if w is not None and w.spat_id == 758][0]
    h = hg.wv_fits[i]
    fn = HERE / 'reid' / 'vbk_758_report.fits'
    make_vbk_reid.write_arxiv(make_vbk_reid.select_rows(
        redux, [1, 2], exclude=[10758], verbose=False), fn)
    x = np.arange(h.wave_soln.size)
    sols, lines = {}, {}
    for tol in [2.0, 0.75]:
        fit = test_reid.run_reid(hg, 1, fn, [i],
                                 {'match_toler': tol}).get(str(i))
        sols[tol] = fit.pypeitfit.eval(x / (x.size - 1))
        lines[tol] = np.round(np.sort(fit.wave_fit), 1).tolist()
    fn.unlink()
    pix = x[::5]
    # Reference: median of the other slits that cover the window
    grid = np.arange(22600., 23700., 1.)
    refs = []
    for det in [1, 2]:
        wc = WaveCalib.from_file(redux / 'Calibrations' /
                                 f'WaveCalib_A_0_DET0{det}.fits',
                                 chk_version=False)
        for w in wc.wv_fits:
            if w is None or w.pypeitfit is None \
                    or (det == 1 and w.spat_id == 758):
                continue
            if w.wave_soln[0] < grid[0] and w.wave_soln[-1] > grid[-1]:
                s = np.interp(grid, w.wave_soln, w.spec)
                refs.append(s / np.percentile(s, 99))
    ref = np.median(refs, axis=0)

    def norm(wave):
        s = np.interp(grid, wave, h.spec)
        return np.round(s / np.percentile(s, 99), 3).tolist()

    return dict(pix=pix.tolist(),
                dl_default=np.round(sols[2.0][::5] - h.wave_soln[::5],
                                    2).tolist(),
                dl_075=np.round(sols[0.75][::5] - h.wave_soln[::5],
                                2).tolist(),
                lines_default=lines[2.0], lines_075=lines[0.75],
                lines_hg=np.round(np.sort(h.wave_fit), 1).tolist(),
                grid=grid.tolist(), nref=len(refs),
                ref=np.round(ref, 3).tolist(), hg=norm(h.wave_soln),
                reid=norm(sols[2.0]))


def write_html():
    """
    Insert data.json into template.html and write the report page.

    Generated by JXP and Claude.

    Returns:
        Path: The report file.
    """
    data = (OUT / 'data.json').read_text().replace('</', '<\\/')
    html = (OUT / 'template.html').read_text().replace('__DATA__', data)
    outfile = OUT / 'vbk_reid_report.html'
    outfile.write_text(html)
    print(f'Wrote {outfile} ({outfile.stat().st_size / 1e3:.0f} kB)')
    return outfile


def main():
    """Write report_impl5/data.json and the report page.  Generated by
    JXP and Claude."""
    OUT.mkdir(exist_ok=True)
    if '--html-only' not in sys.argv:
        data = dict(archive=archive_data(), slits=slit_data(),
                    tests=test_data(), s758=slit758())
        (OUT / 'data.json').write_text(
            json.dumps(data, separators=(',', ':')))
        print(f'Wrote {OUT / "data.json"} '
              f'({(OUT / "data.json").stat().st_size / 1e3:.0f} kB)')
    write_html()


if __name__ == '__main__':
    main()
