"""Check the VB_K OH wavelength solutions against the slit positions in
the mask image.

Usage: python mask_wave_check.py <redux_dir> [outdir]

A slit's position along the dispersion direction in the mask (its row
in the mask image, in PypeIt orientation) shifts its spectrum along the
detector.  At a fixed detector row, the wavelength should therefore
change linearly with the slit's mask row, by about the dispersion
(1.96 A/px) per pixel.  For each detector:

1. Find the slit apertures in the mask image (``mask_image/
   find_apertures.py``) and match them to the traced science slits by
   spatial position (traced slits sit 0-25 px to the left).
2. Measure each slit's mask row: the background-subtracted centroid of
   the aperture along the rows, per column over the central part of
   the aperture, fitted with a line in the column (the slits are
   slightly tilted) and evaluated at the aperture centre.  Touching
   slits are measured separately.
3. Evaluate each slit's OH solution at fixed detector rows (slit
   centre), fit wavelength = a + b * mask_row per detector row, and
   report the residuals in pixels (divided by the local dispersion).
   Only rows inside the slit's range of fitted OH lines enter the fit.
   The linear relation alone leaves residuals of several pixels that
   vary smoothly with the slit's spatial position (curvature of the
   spectra across the field), so a second model adds a quadratic in
   the spatial position: wavelength = a + b * mask_row + c * spat
   + d * spat**2.  For each slit the residuals give a zero point (the
   median) and a shape term (the range along the detector, over the
   rows where all slits enter the fit).  Slits
   departing by more than 3 robust sigma of their chip and > 1 px are
   flagged.
4. If ``<outdir>/arc_offsets.txt`` exists (``arc_check.py``), the
   per-slit zero points are compared with the Ar-line offsets of the
   same slits: a real error of the OH solution would appear in both.

Writes ``<outdir>/mask_wave.txt`` (per slit and row), the summary
``mask_wave_summary.txt``, and the figure ``mask_wave.png``.

Not part of PypeIt.  Generated by JXP and Claude.
"""
import sys
from pathlib import Path

import numpy as np
from astropy.table import Table, vstack
from matplotlib import pyplot as plt

from pypeit.slittrace import SlitTraceSet
from pypeit.wavecalib import WaveCalib

sys.path.insert(0, str(Path(__file__).resolve().parent / 'mask_image'))
from find_apertures import find  # noqa: E402
from load_mask import load  # noqa: E402

ROWS = np.array([150, 400, 650, 900, 1150, 1400, 1650, 1900])
HALF = 12  # rows on each side of the aperture used for the centroid
EDGE = 0.2  # fraction of the aperture width skipped at each side
MAXSHIFT = 40  # px; maximum spatial offset traced slit - mask aperture
FLAG_PX = 1.0  # minimum departure (px) for a flag
FLAG_SIG = 3.0  # and minimum departure in robust sigma
COLORS = {1: '#2a78d6', 2: '#eb6834'}


def mask_row(im, row0, col_lo, col_hi):
    """Row centroid of a slit aperture in the mask image.

    Generated by JXP and Claude.

    Args:
        im (numpy.ndarray): Mask image (PypeIt orientation).
        row0 (float): Approximate spectral centre (row) of the aperture.
        col_lo, col_hi (int): Spatial range (columns) of the aperture.

    Returns:
        tuple: centroid row at the aperture centre, the tilt (rows per
        column), and the rms of the per-column centroids about the
        linear fit.
    """
    w = col_hi - col_lo
    cols = np.arange(int(col_lo + EDGE * w), int(col_hi - EDGE * w))
    r0 = int(np.round(row0))
    rows = np.arange(r0 - HALF, r0 + HALF + 1)
    cen = []
    for c in cols:
        prof = im[rows, c].astype(float)
        # Background from the rows at the window ends
        bkg = np.median(np.r_[prof[:4], prof[-4:]])
        f = np.clip(prof - bkg, 0., None)
        # Iterate the centroid in a +-7 row window around the peak
        cc = rows[np.argmax(f)]
        for _ in range(3):
            m = np.abs(rows - cc) <= 7
            cc = np.sum(rows[m] * f[m]) / np.sum(f[m])
        cen.append(cc)
    cen = np.array(cen)
    p = np.polyfit(cols, cen, 1)
    res = cen - np.polyval(p, cols)
    good = np.abs(res) < 5 * np.std(res) + 0.05
    p = np.polyfit(cols[good], cen[good], 1)
    xc = 0.5 * (col_lo + col_hi)
    return (float(np.polyval(p, xc)), float(p[0]),
            float(np.std(cen[good] - np.polyval(p, cols[good]))))


def match_slits(apert, slits, good):
    """Match traced science slits to mask-image slit apertures.

    Generated by JXP and Claude.

    Args:
        apert (Table): Apertures (``find_apertures.find``).
        slits (SlitTraceSet): Traced slits.
        good (list): Indices of the solved science slits.

    Returns:
        dict: slit index -> aperture row in ``apert``.
    """
    ap = apert[apert['type'] == 'slit']
    left, right, _ = slits.select_edges()
    cen = 0.5 * (left + right)[slits.nspec // 2]
    out = {}
    for i in good:
        # Traced slits sit at or left of the mask apertures
        d = ap['spat_cen'] - cen[i]
        j = int(np.argmin(np.abs(d)))
        if np.abs(d[j]) < MAXSHIFT:
            out[i] = ap[j]
    used = [r['spat_cen'] for r in out.values()]
    if len(set(used)) != len(used):
        raise ValueError('Two traced slits matched to one aperture')
    return out


def measure_det(redux, det):
    """Mask rows and wavelengths at fixed detector rows for one detector.

    Generated by JXP and Claude.

    Args:
        redux (Path): Reduction directory.
        det (int): 1-indexed detector.

    Returns:
        Table: one row per (slit, detector row).
    """
    cal = redux / 'Calibrations'
    slits = SlitTraceSet.from_file(cal / f'Slits_A_0_DET0{det}.fits.gz',
                                   chk_version=False)
    wc = WaveCalib.from_file(cal / f'WaveCalib_A_0_DET0{det}.fits',
                             chk_version=False)
    im, _ = load(det)
    apert = find(det)
    good = [i for i, w in enumerate(wc.wv_fits)
            if w is not None and w.pypeitfit is not None]
    matched = match_slits(apert, slits, good)
    rows = []
    for i, ap in matched.items():
        wfit = wc.wv_fits[i]
        y, tilt, rms = mask_row(im, ap['spec_cen'], int(ap['spat_lo']),
                                int(ap['spat_hi']))
        wave = wfit.wave_soln[ROWS]
        disp = np.gradient(wfit.wave_soln)[ROWS]
        inside = (wave >= wfit.wave_fit.min()) & (wave <= wfit.wave_fit.max())
        for r, w, d, ok in zip(ROWS, wave, disp, inside):
            rows.append((det, int(slits.spat_id[i]), float(ap['spat_cen']),
                         y, tilt, rms, int(r), w, d, bool(ok)))
    return Table(rows=rows, names=('det', 'spat_id', 'mask_spat', 'mask_row',
                                   'mask_tilt', 'mask_rms', 'row', 'wave',
                                   'disp', 'in_fit_range'))


def fit_rows(tab, nspat=0):
    """Fit wavelength vs mask row (plus a polynomial in the slit's
    spatial position) at each detector row.

    Generated by JXP and Claude.

    Args:
        tab (Table): ``measure_det`` output for one detector.
        nspat (int): Order of the polynomial in the spatial position
            (0: linear in the mask row only).

    Returns:
        tuple: residuals (px, for all rows, including extrapolated
        ones) and the slope in the mask row (A per mask px) per
        detector row.
    """
    res = np.full(len(tab), np.nan)
    slopes = {}
    y = tab['mask_row'] - 700.
    sp = (tab['mask_spat'] - 1024.) / 1000.
    design = np.vstack([np.ones(len(tab)), y]
                       + [sp ** k for k in range(1, nspat + 1)]).T
    for r in np.unique(tab['row']):
        m = tab['row'] == r
        ok = np.where(m & tab['in_fit_range'])[0]
        if ok.size < design.shape[1] + 3:
            continue
        coef, *_ = np.linalg.lstsq(design[ok], tab['wave'][ok], rcond=None)
        res[m] = (tab['wave'][m] - design[m] @ coef) / tab['disp'][m]
        slopes[int(r)] = coef[1]
    return res, slopes


def arc_offsets(path):
    """Per-slit Ar-line offsets (mean ThAr image) about each chip's
    shift-plus-rotation line, from ``arc_check.py``.

    Generated by JXP and Claude.

    Args:
        path (Path): ``arc_offsets.txt``.

    Returns:
        dict: (det, spat_id) -> residual offset (px); empty if no file.
    """
    if not path.exists():
        return {}
    t = Table.read(path, format='ascii.fixed_width')
    t = t[t['frame'] == 'mean']
    out = {}
    for det in (1, 2):
        td = t[t['det'] == det]
        sids = np.unique(td['spat_id'])
        med = np.array([np.median(td['offset'][td['spat_id'] == k])
                        for k in sids])
        p = np.polyfit(sids, med, 1)
        out.update({(det, int(k)): float(m - np.polyval(p, k))
                    for k, m in zip(sids, med)})
    return out


def summarize(tab, arc):
    """Print the fits, residuals per slit, and flags.

    Generated by JXP and Claude.

    Args:
        tab (Table): All slits and rows, with ``resid_lin`` and
            ``resid_spat``.
        arc (dict): ``arc_offsets`` output.

    Returns:
        list: Lines of text.
    """
    out = []
    for det in (1, 2):
        t = tab[tab['det'] == det]
        fit = t['in_fit_range']
        out.append(f'== DET0{det}: {np.unique(t["spat_id"]).size} slits '
                   'matched to mask apertures ==')
        for col, lab in (('resid_lin', 'linear in mask row'),
                         ('resid_spat', '+ quadratic in spatial position')):
            r = t[col][fit]
            out.append(f'  {lab}: rms {np.sqrt(np.mean(r ** 2)):.3f} px, '
                       f'max |res| {np.max(np.abs(r)):.3f} px')
        zp = {k: np.median(t['resid_spat'][fit & (t['spat_id'] == k)])
              for k in np.unique(t['spat_id'])}
        # Shape range over the rows where every slit enters the fit (the
        # fit changes where a slit drops out)
        nslit = np.unique(t['spat_id']).size
        full = [r for r in np.unique(t['row'])
                if np.sum(fit & (t['row'] == r)) == nslit]
        infull = np.isin(t['row'], full)
        out.append(f'  shape range over rows {full[0]}-{full[-1]} (all '
                   'slits in their fitted range)')
        v = np.array(list(zp.values()))
        sig = 1.4826 * np.median(np.abs(v - np.median(v)))
        out.append(f'  per-slit zero points (quadratic model): robust sigma '
                   f'{sig:.3f} px')
        out.append('   slit mask_spat mask_row   tilt | lin: median  '
                   '| spat: zero pt  shape range | arc resid | n')
        for k in np.unique(t['spat_id']):
            ts = t[(t['spat_id'] == k) & fit]
            t0 = t[t['spat_id'] == k][0]
            rs = t['resid_spat'][(t['spat_id'] == k) & fit & infull]
            flag = ''
            if abs(zp[k]) > max(FLAG_PX, FLAG_SIG * sig):
                flag = '  <-- departs'
            a = arc.get((det, int(k)))
            astr = '     -   ' if a is None else f'{a:+8.2f} '
            out.append(f'  {k:5d} {t0["mask_spat"]:8.1f} {t0["mask_row"]:8.2f}'
                       f' {t0["mask_tilt"]:+.4f} | '
                       f'{np.median(ts["resid_lin"]):+6.2f}       | '
                       f'{zp[k]:+6.2f}  {rs.max() - rs.min():6.2f}       | '
                       f'{astr} | {len(ts)}{flag}')
        if arc:
            k = [x for x in zp if (det, int(x)) in arc]
            c = np.corrcoef([zp[x] for x in k], [arc[(det, int(x))]
                                                  for x in k])[0, 1]
            out.append(f'  correlation of the zero points with the arc '
                       f'residuals: r = {c:+.2f} ({len(k)} slits)')
    return out


def plot(tab, slopes, outfile):
    """Wavelength vs mask row at the middle row, and residuals.

    Generated by JXP and Claude.

    Args:
        tab (Table): All slits and rows.
        slopes (dict): det -> {row: slope (A per mask px)}.
        outfile (str): PNG file name.
    """
    fig, axes = plt.subplots(2, 2, figsize=(11, 7))
    rmid = ROWS[len(ROWS) // 2]
    for col, det in enumerate((1, 2)):
        t = tab[tab['det'] == det]
        ax = axes[0, col]
        m = t['row'] == rmid
        ok = m & t['in_fit_range']
        ax.plot(t['mask_row'][ok], t['wave'][ok] / 1e4, 'o',
                color=COLORS[det])
        if np.any(m & ~ok):
            ax.plot(t['mask_row'][m & ~ok], t['wave'][m & ~ok] / 1e4, 'o',
                    mfc='none', color=COLORS[det], label='extrapolated')
        x = np.array([t['mask_row'].min(), t['mask_row'].max()])
        p = np.polyfit(t['mask_row'][ok], t['wave'][ok], 1)
        ax.plot(x, np.polyval(p, x) / 1e4, color='0.4', lw=0.8,
                label='linear fit')
        ax.set_title(f'DET0{det}: wavelength at detector row {rmid} '
                     f'(slope {slopes[det][int(rmid)]:+.3f} A/px)',
                     loc='left', fontsize=10)
        ax.set_xlabel('slit row in the mask image (px)')
        ax.set_ylabel('wavelength (um)')
        ax.legend(fontsize=8, frameon=False)
        ax = axes[1, col]
        for s in np.unique(t['spat_id']):
            ts = t[t['spat_id'] == s]
            ok = ts['in_fit_range']
            l, = ax.plot(ts['row'][ok], ts['resid_spat'][ok], 'o-', ms=3,
                         lw=0.7, label=str(s))
            ax.plot(ts['row'][~ok], ts['resid_spat'][~ok], 'o', mfc='none',
                    ms=3, color=l.get_color())
        ax.axhline(0., color='k', lw=0.5)
        ax.set_ylim(-3.5, 3.5)
        ax.set_xlabel('detector row (spectral pixel)')
        ax.set_ylabel('residual (px), with spatial term')
        ax.legend(fontsize=6, ncol=7, frameon=False, loc='lower left')
    for ax in axes.flat:
        for sp in ('top', 'right'):
            ax.spines[sp].set_visible(False)
    fig.tight_layout()
    fig.savefig(outfile, dpi=130)
    plt.close(fig)


def main():
    """Run the check on both detectors.  Generated by JXP and Claude."""
    redux = Path(sys.argv[1] if len(sys.argv) > 1 else 'run5')
    outdir = Path(sys.argv[2] if len(sys.argv) > 2 else 'wavecheck')
    outdir.mkdir(exist_ok=True)
    tabs, slopes = [], {}
    for det in (1, 2):
        t = measure_det(redux, det)
        t['resid_lin'], slopes[det] = fit_rows(t, 0)
        t['resid_spat'], _ = fit_rows(t, 2)
        tabs.append(t)
    tab = vstack(tabs)
    for c in ('mask_row', 'wave', 'disp', 'resid_lin', 'resid_spat'):
        tab[c].format = '.3f'
    tab.write(outdir / 'mask_wave.txt', format='ascii.fixed_width',
              overwrite=True)
    text = summarize(tab, arc_offsets(outdir / 'arc_offsets.txt'))
    for det in (1, 2):
        text.append(f'DET0{det} slope (A per mask px) by detector row: '
                    + ' '.join(f'{r}:{s:+.3f}'
                               for r, s in slopes[det].items()))
    print('\n'.join(text))
    (outdir / 'mask_wave_summary.txt').write_text('\n'.join(text) + '\n')
    plot(tab, slopes, outdir / 'mask_wave.png')
    print(f'Wrote {outdir}/mask_wave.txt, mask_wave_summary.txt, '
          'mask_wave.png')


if __name__ == '__main__':
    main()
