"""Sky residuals on bright OH lines versus the continuum.

Usage: python ohline_resid.py <redux_dir>

For each science spec2d and detector, compares chi = (sci - sky -
obj) * sqrt(ivarmodel) on bright-OH-line pixels with the inter-line
pixels.  In A-B frames the sky model is only the A-B residual, so the
lines are found in the sky (arc) spectrum stored in the WaveCalib file:
pixels whose wavelength falls where that spectrum is > 3x its median: robust std and the
fraction |chi| > 5.  Tilt or wavelength errors show up as excess
residuals on the lines.

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import sys
from pathlib import Path

import numpy as np

from pypeit import spec2dobj
from pypeit.wavecalib import WaveCalib


def rstd(x):
    """Robust standard deviation (1.4826 MAD).

    Generated by JXP and Claude.

    Args:
        x (numpy.ndarray): Values.

    Returns:
        float: Robust std.
    """
    return 1.4826 * np.median(np.abs(x - np.median(x)))


redux = Path(sys.argv[1])
for f in sorted((redux / 'Science').glob('spec2d_*.fits')):
    for det in ['DET01', 'DET02']:
        s2d = spec2dobj.Spec2DObj.from_file(f, det, chk_version=False)
        segm = s2d.slits.slit_img()
        good = (s2d.bpmmask.mask == 0) & (segm >= 0)
        chi = (s2d.sciimg - s2d.skymodel - s2d.objmodel) \
            * np.sqrt(s2d.ivarmodel)
        wc = WaveCalib.from_file(
            redux / 'Calibrations' / f'WaveCalib_A_0_{det}.fits',
            chk_version=False)
        line = np.zeros_like(good)
        for i, sid in enumerate(wc.spat_ids):
            ws = wc.wv_fits[i]
            if ws is None or ws.pypeitfit is None:
                continue
            m = good & (segm == sid)
            sky = wc.arc_spectra[:, i]
            skyimg = np.interp(s2d.waveimg[m], ws.wave_soln, sky)
            line[m] = skyimg > 3 * np.median(sky)
        cont = good & ~line
        print(f'{f.name[7:19]} {det}: OH lines ({line.sum():7d} px) '
              f'rstd {rstd(chi[line]):.3f} |chi|>5 '
              f'{np.mean(np.abs(chi[line]) > 5) * 100:.3f}% | between '
              f'rstd {rstd(chi[cont]):.3f} |chi|>5 '
              f'{np.mean(np.abs(chi[cont]) > 5) * 100:.3f}%')
