"""Compare the traced slits with the apertures in the mask image.

Usage: python plot_slits.py <redux_dir> <det>

Matches each traced slit to the nearest mask-image aperture by spatial
centre, prints the match table, and saves ``slits_<redux>_DET0N.png``
with the slit edges over the trace (flat) image.

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from astropy.table import Table

from pypeit.slittrace import SlitTraceSet
from pypeit.edgetrace import EdgeTraceSet

redux = Path(sys.argv[1])
det = int(sys.argv[2])
cal = redux / 'Calibrations'
slits = SlitTraceSet.from_file(cal / f'Slits_A_0_DET0{det}.fits.gz',
                               chk_version=False)
edges = EdgeTraceSet.from_file(cal / f'Edges_A_0_DET0{det}.fits.gz',
                               chk_version=False)
mask = Table.read(Path(__file__).parent / 'mask_image'
                  / f'apertures_det{det}.csv')

left, right, _ = slits.select_edges()
mid = slits.nspec // 2
print(f'DET0{det}: {slits.nslits} traced slits; mask: '
      f'{np.sum(mask["type"] == "slit")} slits, '
      f'{np.sum(mask["type"] == "box")} boxes')
used = np.zeros(len(mask), dtype=bool)
for i in range(slits.nslits):
    fl = ','.join(slits.bitmask.flagged_bits(slits.mask[i])) or '-'
    j = np.argmin(np.abs(mask['spat_cen'] - slits.spat_id[i]))
    used[j] = True
    print(f'  spat_id {slits.spat_id[i]:5d} [{left[mid, i]:7.1f},'
          f'{right[mid, i]:7.1f}] w={right[mid, i] - left[mid, i]:5.1f} '
          f'{fl:10s} <- mask {mask["type"][j]:4s} '
          f'[{mask["spat_lo"][j]:4d},{mask["spat_hi"][j]:4d}] '
          f'w={mask["spat_hi"][j] - mask["spat_lo"][j]:3d}')
for j in np.where(~used)[0]:
    print(f'  NOT TRACED: mask {mask["type"][j]} '
          f'[{mask["spat_lo"][j]}, {mask["spat_hi"][j]}]')

img = edges.traceimg.image
fig, ax = plt.subplots(figsize=(12, 10))
ax.imshow(img, origin='lower', cmap='gray',
          vmin=np.percentile(img, 5), vmax=np.percentile(img, 99))
y = np.arange(slits.nspec)
for i in range(slits.nslits):
    c = 'C1' if slits.mask[i] else 'C0'
    ax.plot(left[:, i], y, c, lw=0.8)
    ax.plot(right[:, i], y, c, lw=0.8, ls='--')
    ax.text(0.5 * (left[mid, i] + right[mid, i]), mid, str(slits.spat_id[i]),
            color=c, rotation=90, fontsize=7, ha='center')
for r in mask:
    ax.axvspan(r['spat_lo'], r['spat_hi'], ymin=0.98, ymax=1.0,
               color='C3' if r['type'] == 'box' else 'C2')
ax.set_title(f'{redux.name} DET0{det}: traced edges (blue: good, orange: '
             'flagged); mask apertures (top: green slit, red box)')
fig.savefig(f'slits_{redux.name}_DET0{det}.png', dpi=90,
            bbox_inches='tight')
