"""Read noise from the H2RG reference pixels, per frame type.

The reference columns (raw x = 1-4 and 2045-2048) see no light.  The
robust std of their A-B difference, divided by sqrt(2) and times the
gain, is the read noise per frame for that ``DET-NSMP``.  The value
with the per-row common mode removed is also given.

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import numpy as np
from astropy.io import fits

import vbk_paths

# Raw data: the minimum example set (environment variable MOIRCS_VBK_DATA)
GAIN = {1: 2.07, 2: 1.99}


def rstd(x):
    """Robust standard deviation (1.4826 MAD).

    Generated by JXP and Claude.

    Args:
        x (numpy.ndarray): Values.

    Returns:
        float: Robust std.
    """
    return 1.4826 * np.median(np.abs(x - np.median(x)))


for det in [1, 2]:
    for sub in ['std1', 'std2', 'sci', 'domeflat_off', 'domeflat_on',
                'arc']:
        files = vbk_paths.group_files(sub, det_id=det)
        diff = fits.getdata(files[0], 0).astype(float) \
            - fits.getdata(files[1], 0).astype(float)
        ref = np.hstack([diff[:, 0:4], diff[:, 2044:2048]])
        ref_w = ref - np.median(ref, axis=1)[:, None]
        nsmp = fits.getheader(files[0])['DET-NSMP']
        rn = rstd(ref) / np.sqrt(2) * GAIN[det]
        rn_w = rstd(ref_w) / np.sqrt(2) * GAIN[det] * np.sqrt(8 / 7)
        model = 17.5 / np.sqrt(nsmp)
        print(f'DET0{det} {sub:12s} DET-NSMP={nsmp:2d}: RN {rn:5.2f} e- '
              f'(row common mode removed {rn_w:5.2f}); model {model:5.2f}')
