"""Sky-subtraction residuals and 2D views of the science A-B frames.

Usage: python skysub_check.py <redux_dir>

For each science spec2d and detector: chi = (sci - sky - obj) *
sqrt(ivarmodel) over good slit pixels, robust std (1.4826 MAD) and
the fraction |chi| > 5, overall, per slit, and for wavelengths above
2.3 um (thermal continuum).  Also the column-to-column (striping)
pattern: rms of the per-column median of chi along the spectral
direction.  Saves ``skysub_<redux>_<frame>.png`` with the residual
images.

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit import spec2dobj


def rstd(x):
    """Robust standard deviation (1.4826 MAD).

    Generated by JXP and Claude.

    Args:
        x (numpy.ndarray): Values.

    Returns:
        float: Robust std.
    """
    return 1.4826 * np.median(np.abs(x - np.median(x)))


redux = Path(sys.argv[1])
for f in sorted((redux / 'Science').glob('spec2d_*CC0958*.fits')):
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))
    for k, det in enumerate(['DET01', 'DET02']):
        s2d = spec2dobj.Spec2DObj.from_file(f, det, chk_version=False)
        good = (s2d.bpmmask.mask == 0) & (s2d.slits.slit_img() >= 0)
        resid = s2d.sciimg - s2d.skymodel - s2d.objmodel
        chi = resid * np.sqrt(s2d.ivarmodel)
        g = good & np.isfinite(chi)
        red = g & (s2d.waveimg > 23000.)
        print(f'{f.name[:20]} {det}: chi rstd {rstd(chi[g]):.3f}, '
              f'|chi|>5 {np.mean(np.abs(chi[g]) > 5) * 100:.3f}%; '
              f'>2.3um rstd {rstd(chi[red]):.3f}')
        # Striping: median chi per column (within slits), along spectral
        segm = s2d.slits.slit_img()
        per_slit = []
        for sid in s2d.slits.spat_id[s2d.slits.mask == 0]:
            m = g & (segm == sid)
            cols = np.unique(np.where(m)[1])
            colmed = np.array([np.median(chi[:, c][m[:, c]]) for c in cols])
            per_slit.append(f'{sid}:{rstd(chi[m]):.2f}/'
                            f'{np.std(colmed):.2f}')
        print('   slit:chi_rstd/colmed_std  ' + ' '.join(per_slit))
        show = np.where(good, resid, 0.)
        v = 3 * rstd(resid[g])
        axes[k].imshow(show, origin='lower', cmap='gray', vmin=-v, vmax=v,
                       aspect='auto')
        axes[k].set_title(f'{det}: sci - sky - obj (+/-3 sigma)')
    fig.suptitle(f.name)
    fig.savefig(f'skysub_{redux.name}_{f.name[7:19]}.png', dpi=70,
                bbox_inches='tight')
