"""Offset of the standards' OH lines from the science frames' OH lines.

Usage: python std_oh_offset.py <redux_dir>

The standards share the calibration group of the science frames, so
they use the OH wavelength solution measured in the science frames
(~2.3 h earlier).  For each science slit, extract the sky spectrum
(mean over the central half of the slit, following the slit centre)
from each raw standard frame and from science frame A, detect the OH
lines in both, match them (< 2 px), and report the median offset
(standard - science) in pixels and its scatter.

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import sys
from pathlib import Path

import numpy as np

from pypeit.core import arc
from pypeit.images import rawimage
from pypeit.par import pypeitpar
from pypeit.slittrace import SlitTraceSet
from pypeit.spectrographs.util import load_spectrograph

import vbk_paths

# Raw data: the minimum example set (environment variable MOIRCS_VBK_DATA)
SCI = vbk_paths.raw_file(352031)
STDS = [vbk_paths.raw_file(n)
        for n in vbk_paths.GROUPS['std1'] + vbk_paths.GROUPS['std2']]


def sky_spectra(img, slits):
    """Extract a sky spectrum per good slit from the central half.

    Generated by JXP and Claude.

    Args:
        img (numpy.ndarray): Processed (oriented) image.
        slits (SlitTraceSet): Slits.

    Returns:
        dict: spat_id -> 1D spectrum (median over the central half).
    """
    left, right, _ = slits.select_edges()
    out = {}
    rows = np.arange(slits.nspec)
    for i in np.where(slits.mask == 0)[0]:
        w = right[:, i] - left[:, i]
        lo = np.round(left[:, i] + 0.25 * w).astype(int)
        hi = np.round(right[:, i] - 0.25 * w).astype(int)
        out[slits.spat_id[i]] = np.array(
            [np.median(img[r, lo[r]:hi[r]]) for r in rows])
    return out


def lines(spec):
    """Centroids of the OH lines detected at > 10 sigma.

    Generated by JXP and Claude.

    Args:
        spec (numpy.ndarray): Sky spectrum.

    Returns:
        numpy.ndarray: Line centroids (pixels).
    """
    _, _, cen, _, _, good, _, _ = arc.detect_lines(spec, sigdetect=10.,
                                                   fwhm=6.)
    return cen[good]


redux = Path(sys.argv[1] if len(sys.argv) > 1 else 'run1')
spec = load_spectrograph('subaru_moircs')
par = pypeitpar.ProcessImagesPar(use_biasimage=False, use_overscan=False,
                                 use_darkimage=False, use_pixelflat=False,
                                 use_illumflat=False, use_specillum=False,
                                 mask_cr=False)
for det in [1, 2]:
    slits = SlitTraceSet.from_file(
        redux / 'Calibrations' / f'Slits_A_0_DET0{det}.fits.gz',
        chk_version=False)
    ref = sky_spectra(rawimage.RawImage(SCI, spec, det).process(par).image,
                      slits)
    ref_lines = {k: lines(v) for k, v in ref.items()}
    for f in STDS:
        sky = sky_spectra(rawimage.RawImage(f, spec, det).process(par).image,
                          slits)
        med, nl, sids = [], 0, []
        for sid, s in sky.items():
            c = lines(s)
            r = ref_lines[sid]
            d = np.array([c0 - r[np.argmin(np.abs(r - c0))] for c0 in c])
            d = d[np.abs(d) < 2.]
            if d.size >= 5:
                med.append(np.median(d))
                sids.append(sid)
                nl += d.size
        med = np.array(med)
        print(f'DET0{det} {f.name}: {med.size} slits, {nl} lines; '
              f'offset median {np.median(med):+.3f} px, slit-to-slit '
              f'std {np.std(med):.3f} px, range [{med.min():+.2f}, '
              f'{med.max():+.2f}]')
        # Linear trend with the slit's spatial position (rotation)
        p = np.polyfit(sids, med, 1)
        print(f'    vs spat_id: slope {p[0] * 1000:+.3f} px per 1000 px, '
              f'rms about the line {np.std(med - np.polyval(p, sids)):.3f}'
              f' px; per slit: ' + ' '.join(f'{s}:{m:+.2f}'
                                         for s, m in zip(sids, med)))
