"""
Offline test of 'reidentify' for MOIRCS VB_K against the holy-grail
solutions of a reduction (run3).  Adapted from the HK500 tune_reid.py.

Usage: python test_reid.py <redux_dir> <mode> [archive] [key=value,...]

Modes:
    self   -- every slit against one archive (default: the installed
              subaru_moircs_VB_K.fits); self-referential.
    loo    -- leave-one-out: each slit against an archive built without
              that slit (made with make_vbk_reid.py into reid/).
    xdet   -- cross-detector: DET01 slits against a DET02-only archive
              and vice versa.

The optional key=value list overrides WavelengthSolutionPar values
(e.g. nreid_min=3); use archive "-" for the default archive.

For each science slit: rms (px), number of lines, and the median and
maximum |lambda_reid - lambda_holy| over the fitted range of the
holy-grail solution (A).  "good" = rms < 0.5 px, >= 30 lines, and max
|dlambda| < 2 A (~1 px) everywhere in that range.  (A median-only
criterion missed a solution off by 12-37 A over the last 300 px.)

Not part of PypeIt.  Generated by JXP and Claude.
"""
import logging
import os
import sys
from pathlib import Path

import numpy as np

from pypeit.core.wavecal import autoid
from pypeit.spectrographs.util import load_spectrograph
from pypeit.wavecalib import WaveCalib

import make_vbk_reid
import vbk_paths

logging.disable(logging.WARNING)
HERE = Path(__file__).resolve().parent
# A raw science frame, for the VB_K parameters (MOIRCS_VBK_DATA)
RAW = vbk_paths.raw_file(352031)
SPEC = load_spectrograph('subaru_moircs')


def run_reid(hg, det, arxiv, islits, kw=None):
    """
    Reidentify the holy-grail arc spectra of selected slits.

    Generated by JXP and Claude.

    Args:
        hg (WaveCalib): Holy-grail calibration (gives the arc spectra
            and the measured FWHMs).
        det (int): Detector number.
        arxiv (str): Path or name of the reid arxiv.
        islits (list): Slit indices to solve.
        kw (dict, optional): WavelengthSolutionPar overrides.

    Returns:
        dict: Slit index (str) -> WaveFit or None.
    """
    par = SPEC.config_specific_par(RAW)['calibrations']['wavelengths']
    par['method'] = 'reidentify'
    par['reid_arxiv'] = str(arxiv)
    for k, v in (kw or {}).items():
        par[k] = v
    arcs = hg.arc_spectra
    fwhms = np.array([None if w is None else w.fwhm for w in hg.wv_fits],
                     dtype=object)
    nonlin = SPEC.get_detector_par(det).nonlinear_counts()
    reid = autoid.ArchiveReid(arcs, par['lamps'], par,
                              ok_mask=np.array(islits),
                              measured_fwhms=fwhms,
                              nonlinear_counts=nonlin)
    _, fits = reid.get_results()
    return fits


def compare(hg, i, fit):
    """
    Compare a reidentified solution with holy-grail for one slit.

    Generated by JXP and Claude.

    Args:
        hg (WaveCalib): Holy-grail calibration.
        i (int): Slit index.
        fit (WaveFit or None): Reidentified fit.

    Returns:
        dict: rms, nlin, median/max |dlambda| (A), good flag; None
        values if there is no fit.
    """
    if fit is None or fit.pypeitfit is None:
        return dict(rms=None, nlin=0, dmed=None, dmax=None, good=False)
    h = hg.wv_fits[i]
    x = np.arange(h.wave_soln.size)
    wt = fit.pypeitfit.eval(x / (x.size - 1))
    sel = (h.wave_soln > h.wave_fit.min()) & (h.wave_soln < h.wave_fit.max())
    dw = np.abs(wt[sel] - h.wave_soln[sel])
    out = dict(rms=float(fit.rms), nlin=len(fit.pixel_fit),
               dmed=float(np.median(dw)), dmax=float(dw.max()))
    out['good'] = out['rms'] < 0.5 and out['nlin'] >= 30 \
        and out['dmax'] < 2.
    return out


def main():
    """Command-line wrapper.  Generated by JXP and Claude."""
    redux = Path(sys.argv[1])
    mode = sys.argv[2]
    arxiv = sys.argv[3] if len(sys.argv) > 3 and sys.argv[3] != '-' \
        else 'subaru_moircs_VB_K.fits'
    kw = eval(f"dict({sys.argv[4] if len(sys.argv) > 4 else ''})")
    (HERE / 'reid').mkdir(exist_ok=True)
    print(f'# mode={mode} redux={redux} arxiv={arxiv} par={kw}')
    print('# det spat   hg_rms hg_n | rms    n  med|dl| max|dl|  good')
    for det in [1, 2]:
        hg = WaveCalib.from_file(
            redux / 'Calibrations' / f'WaveCalib_A_0_DET0{det}.fits',
            chk_version=False)
        islits = [i for i, w in enumerate(hg.wv_fits)
                  if w is not None and w.pypeitfit is not None]
        results = {}
        if mode == 'self':
            fits = run_reid(hg, det, arxiv, islits, kw)
            results = {i: fits.get(str(i)) for i in islits}
        elif mode == 'xdet':
            other = 3 - det
            fn = HERE / 'reid' / f'vbk_det{other}only_{os.getpid()}.fits'
            rows = make_vbk_reid.select_rows(redux, [other], verbose=False)
            make_vbk_reid.write_arxiv(rows, fn)
            fits = run_reid(hg, det, fn, islits, kw)
            results = {i: fits.get(str(i)) for i in islits}
        elif mode == 'loo':
            for i in islits:
                aid = det * 10000 + int(hg.wv_fits[i].spat_id)
                fn = HERE / 'reid' / f'vbk_loo_{aid}_{os.getpid()}.fits'
                rows = make_vbk_reid.select_rows(redux, [1, 2],
                                                 exclude=[aid],
                                                 verbose=False)
                make_vbk_reid.write_arxiv(rows, fn)
                results[i] = run_reid(hg, det, fn, [i], kw).get(str(i))
                fn.unlink()
        else:
            raise ValueError(f'Unknown mode {mode}')
        ngood, rmss = 0, []
        for i in islits:
            h = hg.wv_fits[i]
            c = compare(hg, i, results[i])
            ngood += c['good']
            if c['rms'] is None:
                print(f'  {det} {int(h.spat_id):5d}   {h.rms:.3f} '
                      f'{len(h.wave_fit):3d} | no fit')
                continue
            rmss.append(c['rms'])
            print(f'  {det} {int(h.spat_id):5d}   {h.rms:.3f} '
                  f'{len(h.wave_fit):3d} | {c["rms"]:.3f} {c["nlin"]:3d} '
                  f'{c["dmed"]:7.2f} {c["dmax"]:7.2f}  '
                  f'{"GOOD" if c["good"] else "BAD"}')
        print(f'DET0{det} {mode} {kw}: {ngood}/{len(islits)} good, '
              f'median rms {np.median(rmss):.3f}, max {np.max(rmss):.3f}')


if __name__ == '__main__':
    main()
