"""
Transfer a MOIRCS sensitivity function from one detector to the other.

MOIRCS has two optically independent channels (detectors 1 and 2), and a
standard star is usually observed on one of them only.  This one-off script
builds a sensitivity function for the other detector from the one measured
on the standard's detector, and splits two-detector spec1d files so that
each detector can be fluxed with its own sensitivity function.

Two transfer modes are available:

- ``direct``: zp_target = zp_source + 2.5 log10(s), with a constant scale
  ``s`` (default 1, i.e. the source sensitivity function as it is).
- ``flatratio``: zp_target = zp_source + 2.5 log10 R(lambda), with
  R = F_target / F_source the ratio of the processed (lamp-on minus
  lamp-off) dome-flat spectra of the two detectors; see
  :func:`flat_ratio`.  R is defined only where both detectors have slits
  at the same wavelength; the zeropoint is left undefined (NaN, masked in
  fluxing) elsewhere instead of being extrapolated.

The default for this mode is still to be decided with the PypeIt team and
the MOIRCS instrument scientist, so the code lives in the dev suite for
now.  It uses only public PypeIt classes (``SensFunc``, ``SpecObjs``,
``FlatImages``, ``SlitTraceSet``) so that the functions can move into the
package unchanged.

Usage::

    # F2/F1 and the transferred sensitivity function
    python transfer_sensfunc.py sens sens_std.fits run5/Calibrations \\
        --from-det 1 --to-det 2 --mode flatratio --qa flux/flat_ratio

    # split a two-detector spec1d file into one file per detector
    python transfer_sensfunc.py split spec1d_xxx.fits --outdir flux

Generated by JXP and Claude
"""

import argparse
import copy
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from astropy.io import fits
from scipy import ndimage

from pypeit import log
from pypeit.core import flux_calib
from pypeit.flatfield import FlatImages
from pypeit.sensfunc import SensFunc
from pypeit.slittrace import SlitTraceSet
from pypeit.specobjs import SpecObjs
from pypeit.spectrographs.util import load_spectrograph


def slit_flat_spectra(flat, slits, spat_frac=0.8, spec_trim=10):
    """
    Collapse the raw dome flat along each science slit.

    The processed lamp-on minus lamp-off flat (``pixelflat_raw``) is
    collapsed with :func:`collapse_slits`, using the flat's wavelength
    image (``pixelflat_waveimg``, built from the detector's wavelength
    solution).

    Args:
        flat (:class:`~pypeit.flatfield.FlatImages`):
            Flat calibration of one detector; it must hold
            ``pixelflat_raw`` and ``pixelflat_waveimg``.
        slits (:class:`~pypeit.slittrace.SlitTraceSet`):
            Slit edges of the same detector.
        spat_frac, spec_trim:
            See :func:`collapse_slits`.

    Returns:
        :obj:`list`: See :func:`collapse_slits`.

    Generated by JXP and Claude
    """
    if flat.pixelflat_raw is None or flat.pixelflat_waveimg is None:
        raise ValueError('The flat must hold pixelflat_raw and '
                         'pixelflat_waveimg.')
    return collapse_slits(flat.pixelflat_raw, flat.pixelflat_waveimg, slits,
                          spat_frac=spat_frac, spec_trim=spec_trim)


def collapse_slits(image, waveimg, slits, spat_frac=0.8, spec_trim=10):
    """
    Collapse an image along each science slit, in counts per Angstrom.

    For each good, non-alignment-box slit, the image is collapsed along
    the spatial direction with a median over the central ``spat_frac`` of
    the slit, so the result is per spatial pixel and does not depend on the
    slit length.  It is then divided by the local dispersion at the slit
    centre, from ``waveimg``, to give counts per Angstrom.

    Args:
        image (`numpy.ndarray`_):
            Image in PypeIt orientation (spectral, spatial), e.g. a dome
            flat or a sky frame.
        waveimg (`numpy.ndarray`_):
            Wavelength image (Angstrom) of the same detector.
        slits (:class:`~pypeit.slittrace.SlitTraceSet`):
            Slit edges of the same detector.
        spat_frac (:obj:`float`, optional):
            Fraction of the slit length, centred on the slit, used in the
            spatial median.
        spec_trim (:obj:`int`, optional):
            Number of spectral pixels dropped at each end of the slit.

    Returns:
        :obj:`list`: One :obj:`dict` per slit, with keys ``spat_id``,
        ``wave`` (Angstrom, increasing) and ``flux`` (counts per Angstrom
        per spatial pixel).

    Generated by JXP and Claude
    """
    raw = image
    nspec = raw.shape[0]
    rows = np.arange(nspec)
    # Science slits only: skip the alignment-star boxes and bad slits
    box = slits.bitmask.flagged(slits.mask, flag='BOXSLIT')
    good = (slits.mask == 0) & np.logical_not(box)
    left, right, _ = slits.select_edges(flexure=None)
    spectra = []
    for i in np.where(good)[0]:
        # Central part of the slit at each spectral row
        cen = 0.5 * (left[:, i] + right[:, i])
        half = 0.5 * spat_frac * (right[:, i] - left[:, i])
        lo = np.ceil(cen - half).astype(int)
        hi = np.floor(cen + half).astype(int) + 1
        flux = np.array([np.median(raw[j, lo[j]:hi[j]]) for j in rows])
        wave = waveimg[rows, np.round(cen).astype(int)]
        # Counts per Angstrom: divide by the local dispersion
        disp = np.abs(np.gradient(wave))
        keep = (wave > 0) & (disp > 0)
        keep[:spec_trim] = False
        keep[nspec - spec_trim:] = False
        srt = np.argsort(wave[keep])
        spectra += [dict(spat_id=int(slits.spat_id[i]),
                         wave=wave[keep][srt],
                         flux=(flux[keep] / disp[keep])[srt])]
    return spectra


def average_flat_spectrum(wave_grid, spectra, scale_slits=True, niter=5):
    """
    Average per-slit flat spectra on a common wavelength grid.

    Each slit covers only part of the grid, and the slits differ in
    illumination (dome screen, vignetting) by up to ~10%.  A plain mean
    then jumps where a slit starts or ends.  With ``scale_slits``, the
    spectra are modelled as ``F_s(lambda) = a_s S(lambda)`` and the scales
    ``a_s`` are solved iteratively, with their geometric mean fixed to 1 so
    that ``S`` keeps the detector's mean level.

    Args:
        wave_grid (`numpy.ndarray`_):
            Common wavelength grid (Angstrom).
        spectra (:obj:`list`):
            Output of :func:`slit_flat_spectra`.
        scale_slits (:obj:`bool`, optional):
            Fit a relative scale per slit before averaging.
        niter (:obj:`int`, optional):
            Number of iterations for the slit scales.

    Returns:
        :obj:`tuple`: ``flux`` (`numpy.ndarray`_, mean flat spectrum on
        ``wave_grid``; NaN where no slit covers it), ``nslit``
        (`numpy.ndarray`_, number of slits per grid point), and ``scales``
        (`numpy.ndarray`_, the slit scales ``a_s``; all 1 if
        ``scale_slits`` is False).

    Generated by JXP and Claude
    """
    # One row per slit, NaN outside the slit's own range
    stack = np.full((len(spectra), wave_grid.size), np.nan)
    for k, spec in enumerate(spectra):
        inside = (wave_grid >= spec['wave'][0]) \
            & (wave_grid <= spec['wave'][-1])
        stack[k, inside] = np.interp(wave_grid[inside], spec['wave'],
                                     spec['flux'])
    nslit = np.sum(np.isfinite(stack), axis=0)
    scales = np.ones(len(spectra))
    if scale_slits:
        for _ in range(niter):
            mean = np.nanmean(stack / scales[:, None], axis=0)
            scales = np.array([np.nanmedian(row / mean) for row in stack])
            scales /= np.exp(np.mean(np.log(scales)))
    with np.errstate(invalid='ignore'):
        flux = np.nanmean(stack / scales[:, None], axis=0) \
            if np.any(nslit) else np.full(wave_grid.size, np.nan)
    flux[nslit == 0] = np.nan
    return flux, nslit, scales


def flat_ratio(flat_source, slits_source, flat_target, slits_target,
               dwave=2.0, smooth_pix=101, min_slits=1, scale_slits=True):
    """
    Measure R(lambda) = F_target / F_source from the dome flats.

    F is the processed lamp-on minus lamp-off dome flat of each detector,
    collapsed along each science slit, converted to counts per Angstrom
    with that detector's wavelength solution, and averaged over slits on a
    common wavelength grid (:func:`slit_flat_spectra`,
    :func:`average_flat_spectrum`).  The ratio is smoothed with a running
    median.  Both detectors are exposed simultaneously, so no exposure-time
    correction is needed.

    Limits: each channel sees a different half of the dome screen, so the
    ratio includes any illumination difference; the slit widths are
    assumed equal (the per-pixel median normalises only the slit length);
    and R is defined only where both detectors have at least ``min_slits``
    slits.

    Args:
        flat_source, flat_target (:class:`~pypeit.flatfield.FlatImages`):
            Flat calibrations of the source and target detectors.
        slits_source, slits_target (:class:`~pypeit.slittrace.SlitTraceSet`):
            Slit edges of the source and target detectors.
        dwave (:obj:`float`, optional):
            Step of the common wavelength grid (Angstrom).
        smooth_pix (:obj:`int`, optional):
            Width of the running median applied to the ratio, in grid
            points.
        min_slits (:obj:`int`, optional):
            Minimum number of slits per detector for R to be defined.
        scale_slits (:obj:`bool`, optional):
            Passed to :func:`average_flat_spectrum`.

    Returns:
        :obj:`dict`: ``wave`` (grid), ``ratio_raw`` and ``ratio`` (raw and
        smoothed R; NaN where undefined), ``gpm`` (where R is defined),
        ``flux_source``/``flux_target`` (mean flat spectra),
        ``nslit_source``/``nslit_target``, and ``scales_source``/
        ``scales_target`` and ``spectra_source``/``spectra_target`` (per
        slit).

    Generated by JXP and Claude
    """
    spec_s = slit_flat_spectra(flat_source, slits_source)
    spec_t = slit_flat_spectra(flat_target, slits_target)
    if len(spec_s) == 0 or len(spec_t) == 0:
        raise ValueError('No science slits on one of the detectors.')
    wmin = min(s['wave'][0] for s in spec_s + spec_t)
    wmax = max(s['wave'][-1] for s in spec_s + spec_t)
    wave = np.arange(np.floor(wmin), np.ceil(wmax) + dwave, dwave)
    f_s, n_s, a_s = average_flat_spectrum(wave, spec_s,
                                          scale_slits=scale_slits)
    f_t, n_t, a_t = average_flat_spectrum(wave, spec_t,
                                          scale_slits=scale_slits)
    gpm = (n_s >= min_slits) & (n_t >= min_slits) & (f_s > 0) & (f_t > 0)
    ratio_raw = np.full(wave.size, np.nan)
    ratio_raw[gpm] = f_t[gpm] / f_s[gpm]
    # Running median over the defined part only.  The narrow absorption
    # dips seen by both channels mostly cancel in the ratio; the median
    # removes what is left of them and the noise.
    ratio = np.full(wave.size, np.nan)
    ratio[gpm] = ndimage.median_filter(ratio_raw[gpm], size=smooth_pix,
                                       mode='nearest')
    return dict(wave=wave, ratio_raw=ratio_raw, ratio=ratio, gpm=gpm,
                flux_source=f_s, flux_target=f_t, nslit_source=n_s,
                nslit_target=n_t, scales_source=a_s, scales_target=a_t,
                spectra_source=spec_s, spectra_target=spec_t)


def transfer_zeropoint(sens, mode, ratio_wave=None, ratio=None, scale=1.0):
    """
    Build the sensitivity function of the target detector.

    Only the arrays used by fluxing (``wave``, ``zeropoint``) and the
    derived ``throughput`` are changed; the standard-star tables and the
    telluric model still describe the source detector.

    Args:
        sens (:class:`~pypeit.sensfunc.SensFunc`):
            Sensitivity function of the source detector, as read from a
            sens file (one spliced or single zeropoint vector).
        mode (:obj:`str`):
            ``'direct'`` (zp + 2.5 log10 ``scale``) or ``'flatratio'``
            (zp + 2.5 log10 R).
        ratio_wave, ratio (`numpy.ndarray`_, optional):
            Wavelength grid and R = F_target / F_source (NaN where
            undefined), e.g. from :func:`flat_ratio`.  Required for
            ``'flatratio'``.
        scale (:obj:`float`, optional):
            Constant scale for ``'direct'``.

    Returns:
        :class:`~pypeit.sensfunc.SensFunc`: A copy of ``sens`` with the
        zeropoint replaced.  In ``'flatratio'`` mode, the zeropoint is NaN
        where R is undefined (such pixels are masked by fluxing).

    Generated by JXP and Claude
    """
    if sens.zeropoint.ndim != 2 or sens.zeropoint.shape[1] != 1:
        raise ValueError('Expected a single (or spliced) zeropoint vector.')
    new = copy.deepcopy(sens)
    wave = sens.wave[:, 0]
    zp = sens.zeropoint[:, 0].copy()
    gpm = wave > 1.0
    if mode == 'direct':
        if scale <= 0:
            raise ValueError('scale must be positive.')
        zp[gpm] += 2.5 * np.log10(scale)
    elif mode == 'flatratio':
        if ratio_wave is None or ratio is None:
            raise ValueError('flatratio mode needs ratio_wave and ratio.')
        ok = np.isfinite(ratio) & (ratio > 0)
        r = np.full(wave.size, np.nan)
        # Interpolate only inside the range where R is defined; no
        # extrapolation, and interior gaps stay undefined
        inside = gpm & (wave >= ratio_wave[ok].min()) \
            & (wave <= ratio_wave[ok].max())
        r[inside] = np.interp(wave[inside], ratio_wave, ratio)
        zp[gpm] += 2.5 * np.log10(r[gpm])
    else:
        raise ValueError(f'Unknown mode: {mode}')
    new.zeropoint = zp[:, None]
    # Throughput, for the QA only (-1 where undefined, as in SensFunc)
    thru = np.full(wave.size, -1.0)
    ok = gpm & np.isfinite(zp)
    spectrograph = load_spectrograph(sens.PYP_SPEC)
    thru[ok] = flux_calib.zeropoint_to_throughput(
        wave[ok], zp[ok], spectrograph.telescope.eff_aperture())
    new.throughput = thru[:, None]
    return new


def split_spec1d_by_det(spec1dfile, outdir=None, chk_version=False):
    """
    Split a spec1d file into one file per detector.

    ``pypeit_flux_calib`` applies one sensitivity function to every
    object of a spec1d file, whatever its detector.  Splitting the file
    lets each detector be fluxed with its own sensitivity function.  The
    original file is not changed.

    Args:
        spec1dfile (:obj:`str`, `Path`_):
            Input spec1d file.
        outdir (:obj:`str`, `Path`_, optional):
            Output directory; default is the input file's directory.
        chk_version (:obj:`bool`, optional):
            Passed to :meth:`~pypeit.specobjs.SpecObjs.from_fitsfile`.

    Returns:
        :obj:`list`: The written files, named
        ``<input stem>_<DET>.fits``.

    Generated by JXP and Claude
    """
    spec1dfile = Path(spec1dfile)
    outdir = spec1dfile.parent if outdir is None else Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    allobj = SpecObjs.from_fitsfile(spec1dfile, chk_version=chk_version)
    outfiles = []
    for det in np.unique(allobj.DET):
        sobjs = SpecObjs.from_fitsfile(spec1dfile, det=det,
                                       chk_version=chk_version)
        outfile = outdir / f'{spec1dfile.stem}_{det}.fits'
        sobjs.write_to_fits(sobjs.header, str(outfile), overwrite=True)
        outfiles += [outfile]
    return outfiles


def plot_flat_ratio(result, outroot, from_det, to_det):
    """
    Save a QA plot and a text table of the flat ratio.

    Args:
        result (:obj:`dict`):
            Output of :func:`flat_ratio`.
        outroot (:obj:`str`, `Path`_):
            Output root; writes ``<outroot>.png`` and ``<outroot>.txt``.
        from_det, to_det (:obj:`int`):
            Source and target detectors, for the labels.

    Generated by JXP and Claude
    """
    w = result['wave'] / 1e4
    fig, ax = plt.subplots(3, 1, figsize=(9, 10), sharex=True)
    for key, det, col in [('source', from_det, 'C0'),
                          ('target', to_det, 'C3')]:
        for spec, a in zip(result[f'spectra_{key}'],
                           result[f'scales_{key}']):
            ax[0].plot(spec['wave'] / 1e4, spec['flux'], color=col,
                       lw=0.4, alpha=0.4)
        ax[0].plot(w, result[f'flux_{key}'], color=col, lw=1.5,
                   label=f'DET0{det} (mean of slits)')
    ax[0].set_ylabel('flat counts / A / pix')
    ax[0].legend()
    ax[1].plot(w, result['ratio_raw'], color='0.6', lw=0.6, label='raw')
    ax[1].plot(w, result['ratio'], color='k', lw=1.5, label='smoothed')
    ax[1].set_ylabel(f'R = F{to_det}/F{from_det}')
    ax[1].legend()
    ax[2].plot(w, result['nslit_source'], color='C0',
               label=f'DET0{from_det}')
    ax[2].plot(w, result['nslit_target'], color='C3', label=f'DET0{to_det}')
    ax[2].set_ylabel('slits')
    ax[2].set_xlabel('wavelength (um)')
    ax[2].legend()
    fig.tight_layout()
    fig.savefig(f'{outroot}.png', dpi=120)
    plt.close(fig)
    tab = np.column_stack([result['wave'], result['flux_source'],
                           result['flux_target'], result['nslit_source'],
                           result['nslit_target'], result['ratio_raw'],
                           result['ratio']])
    np.savetxt(f'{outroot}.txt', tab, fmt='%.1f %.3f %.3f %d %d %.5f %.5f',
               header='wave F_source F_target n_source n_target R_raw R')


def main():
    """
    Command-line wrapper; see the module docstring.

    Generated by JXP and Claude
    """
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[1],
                                     formatter_class=argparse
                                     .RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='cmd', required=True)
    p = sub.add_parser('sens', help='write a transferred sens file')
    p.add_argument('sensfile', help='source sens file')
    p.add_argument('calib_dir', help='Calibrations directory with the '
                   'Flat and Slits files of both detectors')
    p.add_argument('--from-det', type=int, required=True)
    p.add_argument('--to-det', type=int, required=True)
    p.add_argument('--mode', choices=['direct', 'flatratio'],
                   required=True)
    p.add_argument('--scale', type=float, default=1.0,
                   help='constant scale s for the direct mode')
    p.add_argument('--calib-key', default='A_0',
                   help='calibration key in the file names, e.g. A_0')
    p.add_argument('--min-slits', type=int, default=1)
    p.add_argument('--no-scale-slits', action='store_true',
                   help='plain mean over slits')
    p.add_argument('-o', '--outfile', help='output sens file')
    p.add_argument('--qa', help='output root for the flat-ratio QA')
    p = sub.add_parser('split', help='split a spec1d file by detector')
    p.add_argument('spec1dfile')
    p.add_argument('--outdir')
    args = parser.parse_args()

    if args.cmd == 'split':
        for f in split_spec1d_by_det(args.spec1dfile, outdir=args.outdir):
            log.info(f'Wrote {f}')
        return

    sens = SensFunc.from_file(args.sensfile, chk_version=False)
    ratio_wave, ratio = None, None
    if args.mode == 'flatratio':
        cdir = Path(args.calib_dir)

        def load(det):
            """
            Read the flat and slit calibrations of detector ``det``.

            Generated by JXP and Claude
            """
            flat = FlatImages.from_file(
                cdir / f'Flat_{args.calib_key}_DET{det:02d}.fits',
                chk_version=False)
            slits = SlitTraceSet.from_file(
                cdir / f'Slits_{args.calib_key}_DET{det:02d}.fits.gz',
                chk_version=False)
            return flat, slits

        result = flat_ratio(*load(args.from_det), *load(args.to_det),
                            min_slits=args.min_slits,
                            scale_slits=not args.no_scale_slits)
        ratio_wave, ratio = result['wave'], result['ratio']
        ok = result['gpm']
        log.info(f'R defined over {ratio_wave[ok].min():.0f}-'
                 f'{ratio_wave[ok].max():.0f} A')
        # Report the parts of the sensitivity function without R
        swave = sens.wave[:, 0]
        swave = swave[swave > 1.0]
        for lo, hi, side in [(swave.min(), ratio_wave[ok].min(), 'blue'),
                             (ratio_wave[ok].max(), swave.max(), 'red')]:
            if hi > lo:
                log.warning(f'No flat ratio at {lo:.0f}-{hi:.0f} A '
                            f'({side} end); zeropoint left undefined.')
        if args.qa is not None:
            plot_flat_ratio(result, args.qa, args.from_det, args.to_det)
    new = transfer_zeropoint(sens, args.mode, ratio_wave=ratio_wave,
                             ratio=ratio, scale=args.scale)
    outfile = args.outfile
    if outfile is None:
        stem = Path(args.sensfile).stem
        outfile = f'{stem}_det{args.to_det}_{args.mode}.fits'
    # Keep the source primary header and record the transfer
    hdr = fits.getheader(args.sensfile)
    hdr['SENSXFER'] = (args.mode, 'sensfunc transfer mode')
    hdr['SENSFROM'] = (args.from_det, 'source detector')
    hdr['SENSTO'] = (args.to_det, 'target detector')
    hdr['SENSSRC'] = (Path(args.sensfile).name, 'source sens file')
    if args.mode == 'direct':
        hdr['SENSSCL'] = (args.scale, 'constant scale')
    new.to_file(outfile, primary_hdr=hdr, overwrite=True)
    log.info(f'Wrote {outfile}')


if __name__ == '__main__':
    main()
