"""Offline holy-grail tuning for MOIRCS VB_K on the run1 arc spectra.

Usage: python tune_holy.py "<par overrides>" [redux_dir]
  e.g. python tune_holy.py "lamps=['OH_MOSFIRE_K'], fwhm=6.0"

Re-runs holy-grail on the extracted OH spectra stored in the reference
WaveCalib files (default run1), with the MOIRCS VB_K parameters plus
the given overrides, and compares every solution with the reference
one (median |dlambda| over the fitted range).  A solution is "good" if
rms < 0.5 px, >= 30 lines, and |dlambda| < 2 A (1 px).

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import sys
import logging
import time
from pathlib import Path

import numpy as np

from pypeit.wavecalib import WaveCalib
from pypeit.core.wavecal import autoid
from pypeit.spectrographs.util import load_spectrograph

logging.disable(logging.WARNING)
RAW = Path('/mnt/s1data01/work/research/pypeit-development/'
           'test_data_moircs/VB_K/example_MO_CC0958PA200_1/sci/'
           'MCSA00352031.fits')
kw = eval(f"dict({sys.argv[1] if len(sys.argv) > 1 else ''})")
ref_dir = Path(sys.argv[2] if len(sys.argv) > 2 else 'run1')
spec = load_spectrograph('subaru_moircs')
summary = []
for det in [1, 2]:
    ref = WaveCalib.from_file(
        ref_dir / 'Calibrations' / f'WaveCalib_A_0_DET0{det}.fits',
        chk_version=False)
    arcs = ref.arc_spectra
    par = spec.config_specific_par(RAW)['calibrations']['wavelengths']
    for k, v in kw.items():
        par[k] = v
    ok = np.array([i for i, w in enumerate(ref.wv_fits)
                   if w is not None and w.pypeitfit is not None])
    fwhms = np.zeros(arcs.shape[1], dtype=object)
    for i in ok:
        fwhms[i] = ref.wv_fits[i].fwhm
    t0 = time.time()
    hg = autoid.HolyGrail(arcs, par['lamps'], par=par, ok_mask=ok,
                          measured_fwhms=fwhms,
                          spectrograph='subaru_moircs',
                          nonlinear_counts=spec.get_detector_par(
                              det).nonlinear_counts())
    _, fits = hg.get_results()
    x = np.arange(arcs.shape[0]) / (arcs.shape[0] - 1)
    ngood, rms = 0, []
    for i in ok:
        f, h = fits.get(str(i)), ref.wv_fits[i]
        if f is None or f.pypeitfit is None:
            print(f'  DET0{det} spat {ref.spat_ids[i]:5d} FAIL')
            continue
        wt = f.pypeitfit.eval(x)
        sel = (h.wave_soln > h.wave_fit.min()) \
            & (h.wave_soln < h.wave_fit.max())
        dw = np.median(np.abs(wt[sel] - h.wave_soln[sel]))
        good = f.rms < 0.5 and len(f.pixel_fit) >= 30 and dw < 2.
        ngood += good
        rms.append(f.rms)
        print(f'  DET0{det} spat {ref.spat_ids[i]:5d} rms {f.rms:.3f} '
              f'n={len(f.pixel_fit):3d} |dw|={dw:7.2f} A '
              f'(ref rms {h.rms:.3f} n={len(h.pixel_fit)}) '
              f'{"GOOD" if good else "BAD"}')
    summary.append(f'DET0{det}: {ngood}/{len(ok)} good, median rms '
                   f'{np.median(rms):.3f}, {time.time() - t0:.0f} s')
print(kw)
print('\n'.join(summary))
