"""
Locations of the MOIRCS VB_K example data for the scripts in this
directory.

The raw data are not in the repository.  Set the environment variable
``MOIRCS_VBK_DATA`` to the directory that holds the example sets, i.e.
``MO_CC0958PA200_1_minimum`` (one A-B pair with all calibrations) and
``MO_CC0958PA200_1_20260529`` (the full night).  Each set is a flat
directory with the chip-1 and chip-2 files of every frame.

The scripts were first written for frame-type subdirectories
(``domeflat_on``, ``sci``, ``std1``, ...).  :data:`GROUPS` keeps those
groups as lists of chip-1 frame numbers; the chip-2 file of a frame has
the next number.

Generated by JXP and Claude
"""

import os
from pathlib import Path

from astropy.io import fits

ENV = 'MOIRCS_VBK_DATA'
MINIMUM = 'MO_CC0958PA200_1_minimum'
NIGHT = 'MO_CC0958PA200_1_20260529'

# Chip-1 frame numbers of the former subdirectories (minimum set)
GROUPS = {
    'domeflat_on': [351895, 351897, 351899, 351901, 351903, 351905, 351907],
    'domeflat_off': [351909, 351911, 351913, 351915, 351917, 351919,
                     351921],
    'sci': [352031, 352033],
    'std1': [352125, 352127],
    'std2': [352141, 352143],
    'arc': [351935, 351937, 351939, 351941],
    'mos_mask': [351943],
}


def data_dir(name=MINIMUM):
    """
    Return the directory of one example set.

    Generated by JXP and Claude

    Args:
        name (:obj:`str`, optional):
            Name of the set (:data:`MINIMUM` or :data:`NIGHT`).

    Returns:
        `Path`_: The directory.

    Raises:
        RuntimeError: If ``MOIRCS_VBK_DATA`` is not set or the set is not
        found there.
    """
    root = os.environ.get(ENV)
    if root is None:
        raise RuntimeError(
            f'Set the environment variable {ENV} to the directory that '
            f'holds the VB_K example sets ({MINIMUM}, {NIGHT}).')
    path = Path(root).expanduser() / name
    if not path.is_dir():
        raise RuntimeError(f'{path} not found; check {ENV}.')
    return path


def raw_file(frameno, name=MINIMUM):
    """
    Return the path of one raw file.

    Generated by JXP and Claude

    Args:
        frameno (:obj:`int`):
            Frame number (e.g. 352031 for ``MCSA00352031.fits``).
        name (:obj:`str`, optional):
            Name of the example set.

    Returns:
        `Path`_: The file.
    """
    return data_dir(name) / f'MCSA{frameno:08d}.fits'


def group_files(group, det_id=None, name=MINIMUM):
    """
    Return the raw files of one of the former subdirectories.

    Generated by JXP and Claude

    Args:
        group (:obj:`str`):
            Key of :data:`GROUPS` (e.g. ``domeflat_on``).
        det_id (:obj:`int`, optional):
            Keep only the files of this chip (``DET-ID``, 1 or 2); all
            files if None.
        name (:obj:`str`, optional):
            Name of the example set.

    Returns:
        :obj:`list`: Sorted file paths (both chips, or one chip).
    """
    files = sorted(raw_file(n + k, name=name)
                   for n in GROUPS[group] for k in (0, 1))
    if det_id is None:
        return files
    return [f for f in files if fits.getheader(f)['DET-ID'] == det_id]
