"""Find the slits and alignment boxes in the MOIRCS VB_K mask image.

Apertures are connected regions above a threshold in the 3x3
median-filtered mask image (PypeIt orientation: spectral = rows,
spatial = columns).  Boxes are ~40x40 px; slits are ~13-15 px along
the spectral axis.  Touching slits (one region > 200 px wide) are
split at the gap in their spatial profile.  Writes
``apertures_det{1,2}.csv``.

Generated by JXP and Claude (dev script, not part of PypeIt).
"""
import numpy as np
from astropy.table import Table
from scipy import ndimage

from load_mask import load

THRESH = 150.  # counts; slits peak at ~1e4
MINPEAK = 2000.  # reject faint ghosts (peak ~300) below bright slits


def split_region(im, rows, cols):
    """Split a region of touching slits at the gaps in its profile.

    Generated by JXP and Claude.

    Args:
        im (numpy.ndarray): Mask image.
        rows (slice): Spectral extent of the region.
        cols (slice): Spatial extent of the region.

    Returns:
        list: (start, stop) spatial column ranges, one per slit.
    """
    # The touching slits may be offset along the spectral axis, so use
    # the maximum over rows
    prof = np.max(ndimage.median_filter(im[rows, cols], 3), axis=0)
    on = prof > 0.3 * np.median(prof)
    lab, n = ndimage.label(on)
    return [(cols.start + s.start, cols.start + s.stop)
            for (s,) in ndimage.find_objects(lab) if s.stop - s.start > 10]


def find(det):
    """Return a table of the apertures on one detector.

    Generated by JXP and Claude.

    Args:
        det (int): 1-indexed detector.

    Returns:
        astropy.table.Table: One row per aperture, with its type
        (``slit``/``box``), spectral centre, and spatial range.
    """
    im, _ = load(det)
    lab, _ = ndimage.label(ndimage.median_filter(im, 3) > THRESH)
    rows = []
    for o in ndimage.find_objects(lab):
        h = o[0].stop - o[0].start
        w = o[1].stop - o[1].start
        if h * w < 50 or im[o].max() < MINPEAK:
            continue  # hot pixels and ghosts
        kind = 'box' if h > 30 else 'slit'
        spans = [(o[1].start, o[1].stop)] if w < 200 \
            else split_region(im, o[0], o[1])
        # Flux-weighted spectral centre (row) of the aperture
        prof = im[o].sum(axis=1)
        ycen = o[0].start + np.sum(np.arange(h) * prof) / prof.sum()
        for s0, s1 in spans:
            rows.append((kind, ycen, s0, s1, 0.5 * (s0 + s1)))
    tab = Table(rows=rows, names=('type', 'spec_cen', 'spat_lo',
                                  'spat_hi', 'spat_cen'))
    tab.sort('spat_cen')
    return tab


if __name__ == '__main__':
    for det in [1, 2]:
        tab = find(det)
        tab.write(f'apertures_det{det}.csv', overwrite=True)
        nslit = np.sum(tab['type'] == 'slit')
        nbox = np.sum(tab['type'] == 'box')
        print(f'DET0{det}: {nslit} slits, {nbox} boxes')
        tab['spec_cen'].format = '.1f'
        tab.pprint(max_lines=-1)
