"""Load the MOIRCS VB_K mask image in PypeIt orientation.
Generated by JXP and Claude (dev script, not part of PypeIt)."""
from pathlib import Path

import numpy as np

from pypeit.spectrographs.util import load_spectrograph
from pypeit.images import rawimage
from pypeit.par import pypeitpar

RAW = Path('/mnt/s1data01/work/research/pypeit-development/'
           'test_data_moircs/VB_K/example_MO_CC0958PA200_1')
MASK = RAW / 'mos_mask' / 'MCSA00351943.fits'


def load(det):
    """Return the trimmed, oriented mask image (counts) for ``det``.

    Generated by JXP and Claude."""
    spec = load_spectrograph('subaru_moircs')
    par = pypeitpar.ProcessImagesPar(use_biasimage=False,
                                     use_overscan=False,
                                     use_darkimage=False,
                                     use_pixelflat=False,
                                     use_illumflat=False,
                                     use_specillum=False,
                                     apply_gain=False, mask_cr=False)
    img = rawimage.RawImage(MASK, spec, det).process(par)
    return img.image, img.fullmask.bpm
