"""Load the MOIRCS VB_K mask image in PypeIt orientation.
Generated by JXP and Claude (dev script, not part of PypeIt)."""
import sys
from pathlib import Path

from pypeit.spectrographs.util import load_spectrograph
from pypeit.images import rawimage
from pypeit.par import pypeitpar

# The shared module vbk_paths.py (raw-data location) is one level up
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import vbk_paths  # noqa: E402

# Mask image of the minimum example set (MOIRCS_VBK_DATA)
MASK = vbk_paths.raw_file(vbk_paths.GROUPS['mos_mask'][0])


def load(det):
    """Return the trimmed, oriented mask image (counts) for ``det``.

    Generated by JXP and Claude."""
    spec = load_spectrograph('subaru_moircs')
    par = pypeitpar.ProcessImagesPar(use_biasimage=False,
                                     use_overscan=False,
                                     use_darkimage=False,
                                     use_pixelflat=False,
                                     use_illumflat=False,
                                     use_specillum=False,
                                     apply_gain=False, mask_cr=False)
    img = rawimage.RawImage(MASK, spec, det).process(par)
    return img.image, img.fullmask.bpm
