"""
Compare 2D coadds of the VB_K science A-B pair made with the header dither
offsets and with the same offsets of the opposite sign.

For the target slit (DET01 slit 469 in the single frames), the
sky-subtracted image ``sciimg - skymodel`` is collapsed along the
spectral direction (median over the central rows) for frame A, frame B,
and the two coadds, and plotted against the position across the slit.

Usage::

    python plot_coadd2d_test.py

Generated by JXP and Claude
"""

from pathlib import Path

import matplotlib
import numpy as np

from pypeit import spec2dobj

matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402 (after the backend is set)

HERE = Path(__file__).resolve().parent
SCI = HERE.parent / 'run5' / 'Science'
FILES = {
    'frame A (single)':
        SCI / 'spec2d_MCSA00352031-CC0958_PA200_1_MOIRCS_'
              '20260529T060511.128.fits',
    'frame B (single)':
        SCI / 'spec2d_MCSA00352033-CC0958_PA200_1_MOIRCS_'
              '20260529T060843.130.fits',
    'coadd, header offsets (-26.7 px)':
        HERE / 'header' / 'Science_coadd'
        / 'spec2d_MCSA00352031-MCSA00352033-CC0958_PA200_1.fits',
    'coadd, flipped offsets (+26.7 px)':
        HERE / 'flip_all' / 'Science_coadd'
        / 'spec2d_MCSA00352031-MCSA00352033-CC0958_PA200_1.fits',
}


def slit_profile(path, near, det='DET01', rows=(300, 1700)):
    """
    Collapse the sky-subtracted image of one slit along the spectrum.

    Generated by JXP and Claude

    Args:
        path (`Path`_):
            spec2d file.
        near (:obj:`float`):
            Approximate spatial position of the slit centre; the slit with
            the closest centre is used (slit IDs differ in coadds).
        det (:obj:`str`, optional):
            Detector name.
        rows (:obj:`tuple`, optional):
            Spectral rows (start, end) used for the median.

    Returns:
        tuple: Position across the slit (pixels from the left edge), the
        median profile divided by its robust noise, and the slit ID.
    """
    s2d = spec2dobj.Spec2DObj.from_file(str(path), det, chk_version=False)
    left, right, _ = s2d.slits.select_edges()
    mid = s2d.sciimg.shape[0] // 2
    centre = 0.5 * (left[mid] + right[mid])
    i = int(np.argmin(np.abs(centre - near)))
    lo = int(np.ceil(left[mid, i])) + 1
    hi = int(np.floor(right[mid, i])) - 1
    img = (s2d.sciimg - s2d.skymodel)[rows[0]:rows[1], lo:hi]
    prof = np.median(img, axis=0)
    # Noise of the median profile from its outer quarter on each side
    edge = np.r_[prof[:len(prof) // 4], prof[-len(prof) // 4:]]
    noise = 1.4826 * np.median(np.abs(edge - np.median(edge)))
    return np.arange(lo, hi) - left[mid, i], prof / noise, \
        s2d.slits.spat_id[i]


def main():
    """
    Write ``coadd2d_test_profiles.png``.

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(8, 4.2))
    # Slit 469 is centred near spatial pixel 469 in the single frames; in
    # the coadds the slit IDs refer to the coadd frame, so the centre
    # positions are taken from the coadd's own slit list
    for (label, path), near in zip(FILES.items(), [469, 469, 406, 404]):
        x, y, sid = slit_profile(path, near)
        ax.plot(x, y, lw=1.5, label=f'{label} [slit {sid}]')
    ax.axhline(0, color='0.5', lw=0.8)
    ax.set_xlabel('position across the slit (px from the left edge)')
    ax.set_ylabel('median (sci - sky) / noise')
    ax.set_title('VB_K DET01 target slit: A-B frames and 2D coadds',
                 loc='left')
    ax.legend(fontsize=8, frameon=False)
    fig.tight_layout()
    out = HERE / 'coadd2d_test_profiles.png'
    fig.savefig(out, dpi=110)
    print(f'Wrote {out}')


if __name__ == '__main__':
    main()
