"""
Build the PypeIt reid_arxiv wavelength template for INT/IDS R1200B.

The template combines:

- the arc frame in ``INT_20201218/arc.fits`` (CuAr+CuNe lamps, EEV10
  detector, R1200B grating at CENWAVE=4502), from which a boxcar arc
  spectrum is extracted at the slit position used for the IRAF
  solution; and
- the IRAF ``identify`` solution in ``idarc_bs.ms`` (11 CuI/ArI/ArII
  lines), whose (pixel, wavelength) pairs are refit with a 4th-order
  Chebyshev polynomial (RMS = 0.22 A) to assign wavelengths to every
  pixel.

Wavelength *decreases* with row number on the raw EEV10 frame, so the
template is flipped to the PypeIt convention (wavelength increasing).
The output file, ``int_ids_R1200B.fits``, is written directly into the
PypeIt source tree under ``pypeit/data/arc_lines/reid_arxiv/``.

Run with the pypeit14b conda environment:

    python build_R1200B_template.py

Generated by JXP and Claude.
"""
from pathlib import Path

import numpy as np
from astropy.io import fits

import pypeit
from pypeit.core.wavecal import wvutils

# Input files (this script lives in pypeitdev/int_ids/)
HERE = Path(__file__).resolve().parent
ARC_FILE = HERE / 'INT_20201218' / 'arc.fits'

# IRAF identify solution from idarc_bs.ms: (1-indexed pixel along the
# 4200-row spectral axis, reference wavelength in Angstroms)
IRAF_PIX = np.array([404.24, 641.47, 1115.69, 1356.93, 1581.08,
                     1817.42, 2066.76, 2229.90, 2538.72, 2741.64,
                     3066.38])
IRAF_WAV = np.array([5218.19925, 5105.54203, 4879.89345, 4764.89841,
                     4657.93789, 4545.0853, 4425.98808, 4348.07774,
                     4200.66873, 4103.90912, 3946.1])

# Detector layout from the raw headers (see int_ids.py):
# TRIMSEC rows 1:4099, BIASSEC rows 4105:4190 (1-indexed)
DATA_ROWS = slice(0, 4099)
OSCAN_ROWS = slice(4104, 4190)
# Spatial aperture of the IRAF extraction (aplow/aphigh 168:178)
APERTURE = slice(167, 178)

# Chebyshev fit order for the pixel -> wavelength relation
FIT_ORDER = 4


def main():
    """
    Extract the arc spectrum, attach wavelengths, and write the
    template.

    Inputs are the module-level constants above; the output is the
    file ``int_ids_R1200B.fits`` written into the PypeIt source tree
    (``pypeit/data/arc_lines/reid_arxiv/``).

    Generated by JXP and Claude.
    """
    # Extract a median boxcar spectrum at the IRAF aperture and remove
    # the bias level measured from the overscan rows
    arc = fits.getdata(ARC_FILE, 1).astype(float)
    spec = np.median(arc[:, APERTURE], axis=1)
    spec -= np.median(spec[OSCAN_ROWS])
    spec = spec[DATA_ROWS]

    # Wavelengths for every (1-indexed) pixel from the Chebyshev refit
    # of the IRAF line identifications
    coef = np.polynomial.chebyshev.chebfit(IRAF_PIX, IRAF_WAV, FIT_ORDER)
    resid = IRAF_WAV - np.polynomial.chebyshev.chebval(IRAF_PIX, coef)
    print(f'Chebyshev order {FIT_ORDER} fit to {len(IRAF_PIX)} lines: '
          f'RMS = {resid.std():.3f} A')
    wave = np.polynomial.chebyshev.chebval(
        np.arange(1, len(spec) + 1, dtype=float), coef)

    # Flip to the PypeIt convention: wavelength increasing with pixel.
    # This matches specflip=True in the int_ids spectrograph class.
    wave = wave[::-1]
    spec = spec[::-1]
    print(f'Template coverage: {wave[0]:.1f} - {wave[-1]:.1f} A '
          f'({len(wave)} pixels)')

    # Write into the PypeIt source tree so full_template can find it
    outpath = (Path(pypeit.__file__).resolve().parent
               / 'data' / 'arc_lines' / 'reid_arxiv')
    wvutils.write_template(wave, spec, 1, str(outpath),
                           'int_ids_R1200B.fits', overwrite=True)


if __name__ == '__main__':
    main()
