"""
Build the HIRES-format ``angle_fits`` + ``composite_arc`` archives for
Shane/Hamspec (the `method='echelle'` wavelength-calibration inputs).

Generated by JXP and Claude.

Per Q&A 29-34, Shane/Hamspec uses the Keck/HIRES order-identification approach:
predict the order coverage and per-order wavelength solution from the
instrument angles (an initial guess), then refine by cross-correlation.  That
needs two `reid_arxiv` files in the exact HIRES formats consumed by
`pypeit.core.wavecal.echelle.predict_ech_arcspec`:

  shane_hamspec_composite_arc.fits
     HDU1 params (order_min/max, norders, wave_min/max, dloglam, dv)
     HDU2/3/4 = wave / arc / gpm, each (nspec, norders), each column the order's
                own log-lambda ramp (left-aligned, zero-padded), gpm True where
                valid.  Columns indexed by (m - order_min); column 0 = reddest.

  shane_hamspec_angle_fits.fits
     HDU1 params (funcs, ranges, order_min/max, norders, ech_n_final, ...)
     HDU2 ech_angle_coeffs (norders, ech_n_final+1, n_ech_coeff): per-order
          wavelength-solution coefficients as a function of echelle angle.
     HDU3 xd_angle_coeffs (n_xdisp, xd_poly+1): reddest-order spatial position
          as a function of cross-disperser angle.

Source of the per-order solution: the XIDL `Arc_01_fit.idl` (orders m=65-146;
Report 04).  We have a single well-measured setting, so the angle dependence is
**linear** (Q32): the cross-disperser (dewar) slope is geometric
(0.0667 px/order-pixel = 1/15 um, Q31) and the echelle (grating-tilt) slope is
anchored by the measured 3.3 px shift (Q34); both use the **raw stepper counts**
GTILTRAW / DHEITVAL as the angle variable (Q33).

Inputs:  Arc_01_fit.idl
Outputs: the two FITS files in PypeIt's reid_arxiv data dir (or --dry -> local).
"""

import sys
from pathlib import Path

import numpy as np
from numpy.polynomial import legendre as L
from astropy.io import fits
from astropy.table import Table

from pypeit import dataPaths

import read_xidl_arc as xidl
import read_iraf_arc as iraf_arc

ROOT = Path(__file__).resolve().parent.parent

# Source of the per-order solution: 'iraf' (102 orders, m=58-159) or 'xidl'
# (64 orders, m=65-146).  NOTE (Q36b): extending to the IRAF set was tried and
# gave *worse* results (23-24 orders solved @ ~0.35 px vs 27 @ 0.278 px for
# XIDL) — my IRAF per-order wavelengths (fit from the raw ecidentify lines) are
# less accurate than the polished XIDL solution, and the blue orders still do
# not match.  XIDL is the better archive, so default back to it.
ARC_SOURCE = 'xidl'

# --- Reference setting of the dev-suite data (the anchor) ---
ECH_ANCHOR = 9194.0      # GTILTRAW (grating tilt) of the data
XD_ANCHOR = 20359.0      # DHEITVAL (dewar height, micron) of the data
# Geometry / measured slopes (Report 05 §8)
PIX_UM = 15.0                          # detector pixel size (Q31)
ORDER_SPACING_PIX = 16.0               # cross-dispersion order spacing (Rpt 01)
XD_SLOPE = 1.0 / PIX_UM / ORDER_SPACING_PIX   # orders per micron of dewar
ECH_N_FINAL = 4          # per-order wavelength polynomial degree


def _fit_order_wave(wave_order, nspec):
    """
    Fit one order's wavelength solution as a Legendre series in normalized
    pixel (x in [0,1]), matching PypeIt's evaluate_fit convention.

    Generated by JXP and Claude.

    Args:
        wave_order (`numpy.ndarray`_): vacuum wavelengths (npix,), 0 where bad.
        nspec (int): number of spectral pixels.

    Returns:
        `numpy.ndarray`_: (ECH_N_FINAL+1,) Legendre coefficients, or None.
    """
    good = wave_order > 0
    if good.sum() < ECH_N_FINAL + 2:
        return None
    x01 = np.arange(wave_order.size) / float(wave_order.size - 1)
    xnn = 2.0 * x01 - 1.0                       # [0,1] -> [-1,1]
    return L.legfit(xnn[good], wave_order[good], ECH_N_FINAL)


def build(outdir=None):
    """
    Build and write both archive files.

    Generated by JXP and Claude.

    Args:
        outdir (:obj:`str` or `pathlib.Path`, optional):
            Output directory.  If None, PypeIt's reid_arxiv data dir.

    Returns:
        :obj:`tuple`: (composite_path, angle_path).
    """
    if ARC_SOURCE == 'iraf':
        orders, wave, spec = iraf_arc.load()
    elif ARC_SOURCE == 'cooke':
        # The Cooke 16Nov10 solution is binned 2x1 (2048 pix); resample to the
        # dev-suite 1x1 grid (4096) with specbin=2.  It is far line-richer
        # (~36 lines/order incl. the blue) than our default XIDL solution.
        from pypeit.core.wavecal import templates
        cooke = (ROOT / 'Cooke_data' / 'redo_from_scratch' / 'Arcs' / 'Fits'
                 / 'Arc_01_fit.idl')
        orders, wave, spec = templates.xidl_esihires(
            str(cooke), specbin=2, log10=True)
    else:
        orders, wave, spec = xidl.load(ROOT / 'Arc_01_fit.idl')[:3]
    isort = np.argsort(orders)
    orders, wave, spec = orders[isort], wave[isort], spec[isort]

    order_min, order_max = int(orders.min()), int(orders.max())
    norders = order_max - order_min + 1          # 82 (m=65..146), with gaps

    # Common log-lambda step (median over orders)
    dloglam = np.median([np.median(np.diff(np.log10(w[w > 0]))) for w in wave])
    dv = 299792.458 * np.log(10.0) * dloglam

    # Per-order resample onto the order's own log-lambda ramp; size the grid.
    resampled = {}   # m -> (wave, arc, n)
    for m, w, s in zip(orders, wave, spec):
        g = w > 0
        lw0, lw1 = np.log10(w[g].min()), np.log10(w[g].max())
        n = int(np.ceil((lw1 - lw0) / dloglam)) + 1
        lgrid = lw0 + dloglam * np.arange(n)
        arc_i = np.interp(lgrid, np.log10(w[g]), s[g])
        resampled[int(m)] = (10.0**lgrid, arc_i, n)

    # Per-order Legendre wave-solution coeffs; interpolate across order number
    # to fill the gaps (XIDL solved 64 of the 82 orders in the span).
    present_m, present_coeff = [], []
    for m, w, _ in zip(orders, wave, spec):
        c = _fit_order_wave(w, w.size)
        if c is not None:
            present_m.append(int(m))
            present_coeff.append(c)
    present_m = np.array(present_m)
    present_coeff = np.array(present_coeff)            # (npresent, ECH_N_FINAL+1)

    all_m = np.arange(order_min, order_max + 1)
    nspec = max(v[2] for v in resampled.values())

    # ---- composite_arc arrays (nspec, norders), column = m - order_min ----
    # EVERY order in the span gets a valid wave ramp + gpm=True so the core
    # predict_ech_arcspec never sees an empty order (it crashes on empty gpm).
    # Present orders carry the real ThAr arc; gap orders carry arc=0 (they
    # simply won't match in the cross-correlation).
    cwave = np.zeros((nspec, norders))
    carc = np.zeros((nspec, norders))
    cgpm = np.zeros((nspec, norders), dtype=bool)
    for m in all_m:
        col = m - order_min
        if m in resampled:
            wv, ar, n = resampled[m]
            cwave[:n, col] = wv
            carc[:n, col] = ar
            cgpm[:n, col] = True
        else:
            # Gap order: synthesize a wave ramp from the interpolated solution
            coeff = np.array([np.interp(m, present_m, present_coeff[:, ic])
                              for ic in range(ECH_N_FINAL + 1)])
            x01 = np.arange(nspec) / float(nspec - 1)
            wv = L.legval(2.0 * x01 - 1.0, coeff)
            cwave[:, col] = wv
            cgpm[:, col] = wv > 0           # arc stays 0 (no real lines)

    wave_min = float(cwave[cgpm].min())
    wave_max = float(cwave[cgpm].max())
    # ech_angle_coeffs: (norders, ECH_N_FINAL+1, n_ech_coeff=1) -> constant in
    # echelle angle (Q34: the ~3 px grating-tilt shift is absorbed by the
    # cross-correlation refine; v1 holds the per-order shape fixed).
    ech_angle_coeffs = np.zeros((norders, ECH_N_FINAL + 1, 1))
    for ic in range(ECH_N_FINAL + 1):
        ech_angle_coeffs[:, ic, 0] = np.interp(all_m, present_m,
                                               present_coeff[:, ic])

    # xd_angle_coeffs: reddest order (= order_min) as a linear function of the
    # dewar height (xdangle).  Anchor at the data setting; slope from geometry.
    xd_min, xd_max = XD_ANCHOR - 2000.0, XD_ANCHOR + 2000.0
    xn_anchor = 2.0 * (XD_ANCHOR - xd_min) / (xd_max - xd_min) - 1.0
    c1 = XD_SLOPE * (xd_max - xd_min) / 2.0           # legendre L1 coeff
    c0 = order_min - c1 * xn_anchor                   # so eval(anchor)=order_min
    xd_angle_coeffs = np.array([[c0, c1]])            # (n_xdisp=1, 2)

    # ---- params table (HDU1), mirroring keck_hires columns ----
    params = Table()
    params['ech_xmin'] = [ECH_ANCHOR - 500.0]
    params['ech_xmax'] = [ECH_ANCHOR + 500.0]
    params['norders'] = [norders]
    params['order_min'] = [order_min]
    params['order_max'] = [order_max]
    params['ech_n_final'] = [ECH_N_FINAL]
    params['ech_coeff_fit_order'] = [[0]]             # constant in ech angle
    params['ech_func'] = ['legendre']
    params['wave_func'] = ['legendre']
    params['wave_xmin'] = [0.0]
    params['wave_xmax'] = [1.0]
    params['xd_xmin'] = [xd_min]
    params['xd_xmax'] = [xd_max]
    params['xdisp_vec'] = [['Hamspec']]               # one cross-disperser
    params['xd_polyorder'] = [1]
    params['xd_func'] = ['legendre']

    # ---- composite_arc params (HDU1) ----
    cparams = Table()
    cparams['arxiv_file'] = ['Arc_01_fit.idl']
    cparams['order_min'] = [order_min]
    cparams['order_max'] = [order_max]
    cparams['norders'] = [norders]
    cparams['wave_min'] = [wave_min]
    cparams['wave_max'] = [wave_max]
    cparams['dloglam'] = [dloglam]
    cparams['dv'] = [dv]

    if outdir is None:
        outdir = dataPaths.reid_arxiv.path
    outdir = Path(outdir)
    comp_path = outdir / 'shane_hamspec_composite_arc.fits'
    ang_path = outdir / 'shane_hamspec_angle_fits.fits'

    # Write composite_arc (HDU1 table, HDU2/3/4 images)
    fits.HDUList([
        fits.PrimaryHDU(),
        fits.BinTableHDU(cparams, name='PARAMS'),
        fits.ImageHDU(cwave, name='WAVE'),
        fits.ImageHDU(carc, name='ARC'),
        fits.ImageHDU(cgpm.astype(np.int16), name='GPM'),
    ]).writeto(comp_path, overwrite=True)

    # Write angle_fits (HDU1 table, HDU2 ech coeffs, HDU3 xd coeffs)
    fits.HDUList([
        fits.PrimaryHDU(),
        fits.BinTableHDU(params, name='PARAMS'),
        fits.ImageHDU(ech_angle_coeffs, name='ECH_ANGLE_COEFFS'),
        fits.ImageHDU(xd_angle_coeffs, name='XD_ANGLE_COEFFS'),
    ]).writeto(ang_path, overwrite=True)

    print(f'composite_arc -> {comp_path}')
    print(f'  nspec={nspec}, norders={norders} (m={order_min}-{order_max}), '
          f'present={present_m.size}, dv={dv:.2f} km/s')
    print(f'angle_fits   -> {ang_path}')
    print(f'  ech_angle_coeffs {ech_angle_coeffs.shape}, '
          f'xd_angle_coeffs {xd_angle_coeffs.shape}, XD_SLOPE={XD_SLOPE:.5f} '
          f'orders/um')
    return comp_path, ang_path


if __name__ == '__main__':
    if '--dry' in sys.argv:
        build(outdir=ROOT / 'scripts')
    else:
        build()
