"""
Characterize the Shane/Hamspec ThAr wavelength solution and make QA figures.

Generated by JXP and Claude.

Combines the IRAF ecidentify database and the XIDL solution to describe the
format that a PypeIt echelle wavelength archive must reproduce:

  - wavelength coverage vs. physical order (both reductions)
  - dispersion (AA/pixel) vs. order
  - identified-line density vs. order (IRAF)
  - an example extracted ThAr order spectrum (XIDL ``sv_aspec``)

Inputs:
    The IRAF database and XIDL save file in ``pypeitdev/shane_hamspec``.

Outputs:
    PNG figures written to ``pypeitdev/shane_hamspec/Reports`` with the
    ``04_figN_*`` prefix, plus a printed summary.
"""

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import parse_iraf_ecthar as iraf
import read_xidl_arc as xidl


def main():
    """
    Build the characterization figures and print a comparison summary.

    Generated by JXP and Claude.

    Returns:
        :obj:`dict`: A few headline numbers used by the report.
    """
    root = Path(__file__).resolve().parent.parent
    reports = root / 'Reports'

    # --- IRAF ecidentify ---
    ec = iraf.parse(root / 'IRAF' / 'ecTHAR20240125.rsfbo_1')
    f = ec['features']
    iraf_orders = np.unique(f['order'])
    iraf_wmin = np.array([f['wave_ref'][f['order'] == o].min()
                          for o in iraf_orders])
    iraf_wmax = np.array([f['wave_ref'][f['order'] == o].max()
                          for o in iraf_orders])
    iraf_npo = np.array([np.sum(f['order'] == o) for o in iraf_orders])

    # --- XIDL ---
    xo, xw, xs, xrms = xidl.load(root / 'Arc_01_fit.idl')
    xwmin = np.array([w[w > 0].min() if np.any(w > 0) else np.nan
                      for w in xw])
    xwmax = np.array([w[w > 0].max() if np.any(w > 0) else np.nan
                      for w in xw])
    # central dispersion AA/pix per XIDL order
    npix = xw.shape[1]
    disp = np.array([np.nanmedian(np.abs(np.diff(w[w > 0])))
                     if np.any(w > 0) else np.nan for w in xw])

    # ---- Figure 1: wavelength coverage vs order ----
    fig, ax = plt.subplots(figsize=(9, 6))
    for o, lo, hi in zip(iraf_orders, iraf_wmin, iraf_wmax):
        ax.plot([lo, hi], [o, o], color='C0', lw=1.2,
                label='IRAF (line span)' if o == iraf_orders[0] else None)
    ax.plot(np.nanmin([xwmin, xwmax], axis=0), xo, 'r.', ms=4,
            label='XIDL order min (vac)')
    ax.plot(np.nanmax([xwmin, xwmax], axis=0), xo, 'm.', ms=4,
            label='XIDL order max (vac)')
    ax.set_xlabel('Wavelength [AA]')
    ax.set_ylabel('Physical echelle order m')
    ax.set_title('Shane/Hamspec ThAr: wavelength coverage vs order')
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(reports / '04_fig1_coverage.png', dpi=90)
    plt.close(fig)

    # ---- Figure 2: dispersion & line density vs order ----
    fig, axs = plt.subplots(2, 1, figsize=(9, 7), sharex=True)
    axs[0].plot(xo, disp, 'o-', ms=3)
    axs[0].set_ylabel('|dispersion| [AA/pix]')
    axs[0].set_title('XIDL central dispersion vs order')
    axs[1].plot(iraf_orders, iraf_npo, 's-', ms=3, color='C2')
    axs[1].set_xlabel('Physical echelle order m')
    axs[1].set_ylabel('IRAF lines / order')
    axs[1].set_title('Identified ThAr lines per order (IRAF)')
    fig.tight_layout()
    fig.savefig(reports / '04_fig2_dispersion_lines.png', dpi=90)
    plt.close(fig)

    # ---- Figure 3: example extracted ThAr order ----
    kk = xo.size // 2
    fig, ax = plt.subplots(figsize=(10, 4))
    good = xw[kk] > 0
    ax.plot(xw[kk][good], xs[kk][good], lw=0.6)
    ax.set_xlabel('Wavelength [AA, vac]')
    ax.set_ylabel('Counts')
    ax.set_title(f'Example XIDL ThAr order m={xo[kk]} '
                 f'({xw[kk][good].min():.0f}-{xw[kk][good].max():.0f} AA)')
    fig.tight_layout()
    fig.savefig(reports / '04_fig3_example_order.png', dpi=90)
    plt.close(fig)

    # ---- Summary ----
    print('=== IRAF ecidentify ===')
    iraf.summary(root / 'IRAF' / 'ecTHAR20240125.rsfbo_1')
    print('\n=== XIDL Arc_01_fit.idl ===')
    xidl.summary(root / 'Arc_01_fit.idl')
    print('\nFigures written to', reports)

    return dict(iraf_orders=(int(iraf_orders.min()), int(iraf_orders.max())),
                xidl_orders=(int(xo.min()), int(xo.max())),
                disp_med=float(np.nanmedian(disp)))


if __name__ == '__main__':
    main()
