"""
Compare the instrument configuration of the legacy ThAr solution to the
dev-suite raw arcs.

Generated by JXP and Claude.

The wavelength archive (`reid_arxiv`) is only useful if it was taken in the
*same* configuration as the data being reduced.  For Shane/Hamspec the relevant
cards are the grating tilt (GTILTRAW -> echangle, sets wavelength) and the
dewar height (DHEITRAW/DHEITVAL -> xdangle / cross-disperser, sets which orders
land where).  This script prints those cards for the IRAF reference arc (the
source of the archive) and for the dev-suite raw ThAr frames so the two can be
compared at a glance.

Inputs:
    The IRAF reference FITS in ``pypeitdev/shane_hamspec/IRAF`` and the raw
    arcs in ``RAW_DATA/shane_hamspec/Hamilton``.

Outputs:
    Prints a small comparison table.
"""

from pathlib import Path

from astropy.io import fits

CARDS = ['DATE', 'OBJECT', 'GTILTRAW', 'DHEITRAW', 'DHEITVAL', 'PLATENAM']


def _row(label, hdr):
    """Format one comparison row. Generated by JXP and Claude."""
    vals = ' | '.join(f'{c}={hdr.get(c, "--")}' for c in CARDS)
    return f'{label:14s} {vals}'


def main():
    """
    Print the config cards for the archive source vs the raw arcs.

    Generated by JXP and Claude.

    Returns:
        :obj:`None`
    """
    root = Path(__file__).resolve().parent.parent
    raw = (root.parent.parent / 'RAW_DATA' / 'shane_hamspec' / 'Hamilton')

    print('Archive source (legacy ThAr that built shane_hamspec.fits):')
    h = fits.open(root / 'IRAF' / 'THAR20240125.rsfbo_1.fits')[0].header
    print('  ' + _row('IRAF ThAr', h))

    print('\nDev-suite raw arcs (the data being reduced):')
    for f in ['d2084.fits', 'd2085.fits']:
        h = fits.open(raw / f)[0].header
        print('  ' + _row(f, h))

    print('\nNote: GTILTRAW (grating tilt) and DHEITRAW (dewar height) differ '
          'between the archive and the raw data -> different wavelength zero '
          'point and order placement -> reidentification cross-correlation '
          'fails (cc well below threshold).')


if __name__ == '__main__':
    main()
