"""
Parse the IRAF ``ecidentify`` database for the Shane/Hamspec ThAr arc.

Generated by JXP and Claude.

The file ``IRAF/ecTHAR20240125.rsfbo_1`` is the text database written by the
IRAF ``ecidentify`` task.  It contains, for a ThAr exposure:

  - a ``features`` block: one line per identified arc line, with columns
        aperture  order  pixel  wave_fit  wave_ref  weight  flag1  flag2
    where ``order`` is the *physical* echelle order number and ``pixel`` is
    the position along the dispersion axis (1-indexed).
  - a ``coefficients`` block: the global 2D (pixel x order) Chebyshev fit
    that IRAF uses to map (pixel, order) -> order*wavelength.

This module parses both and exposes simple helpers used by the wavelength
deep-dive report.

Inputs:
    ecidentify database path (str / Path).

Outputs (via :func:`parse`):
    dict with
        'features'  : structured ndarray (aperture, order, pixel, wave_fit,
                      wave_ref, weight)
        'coeff'     : 1D ndarray of the raw coefficient block
        'fit'       : dict describing the 2D solution (function, xorder,
                      yorder, xmin, xmax, omin, omax, mlambda0)
"""

from pathlib import Path

import numpy as np


def parse(db_file):
    """
    Parse an IRAF ecidentify database file.

    Generated by JXP and Claude.

    Args:
        db_file (:obj:`str` or `pathlib.Path`):
            Path to the ``ecTHAR*`` ecidentify database.

    Returns:
        :obj:`dict`: See module docstring for the keys returned.
    """
    lines = Path(db_file).read_text().splitlines()

    feat = []
    coeff = []
    in_coeff = False
    n_coeff = 0
    for line in lines:
        s = line.strip()
        if s.startswith('coefficients'):
            # e.g. "coefficients\t28"
            n_coeff = int(s.split()[-1])
            in_coeff = True
            continue
        if in_coeff:
            # The coefficient block is one float per line
            try:
                coeff.append(float(s))
            except ValueError:
                in_coeff = False
            continue
        # Feature lines: 8 whitespace-separated numeric columns
        parts = s.split()
        if len(parts) == 8:
            try:
                ap = int(parts[0])
                order = int(parts[1])
                pix = float(parts[2])
                wfit = float(parts[3])
                wref = float(parts[4])
                wgt = float(parts[5])
                feat.append((ap, order, pix, wfit, wref, wgt))
            except ValueError:
                pass

    features = np.array(
        feat,
        dtype=[('aperture', int), ('order', int), ('pixel', float),
               ('wave_fit', float), ('wave_ref', float), ('weight', float)])
    coeff = np.array(coeff, dtype=float)

    # The IRAF 2D fit header is the first 8 coefficients:
    #   function, xorder, yorder, xterms, xmin, xmax, ymin(order), ymax(order)
    fit = {}
    if coeff.size >= 8:
        fit = dict(function=int(coeff[0]), xorder=int(coeff[1]),
                   yorder=int(coeff[2]), xterms=int(coeff[3]),
                   xmin=coeff[4], xmax=coeff[5],
                   omin=coeff[6], omax=coeff[7],
                   mlambda0=coeff[8] if coeff.size > 8 else np.nan)
    return dict(features=features, coeff=coeff, fit=fit)


def summary(db_file):
    """
    Print a human-readable summary of the ecidentify solution.

    Generated by JXP and Claude.

    Args:
        db_file (:obj:`str` or `pathlib.Path`): ecidentify database path.

    Returns:
        :obj:`dict`: The parsed dictionary from :func:`parse`.
    """
    d = parse(db_file)
    f = d['features']
    orders = np.unique(f['order'])
    print(f'Features identified : {f.size}')
    print(f'Apertures/orders    : {orders.size} '
          f'(physical order {orders.min()}-{orders.max()})')
    print(f'Wavelength range    : {f["wave_ref"].min():.1f} - '
          f'{f["wave_ref"].max():.1f} AA (IRAF uses air)')
    # m*lambda product (grating constant)
    ml = f['order'] * f['wave_ref']
    print(f'm*lambda            : median {np.median(ml):.0f} AA, '
          f'std {np.std(ml):.0f}')
    # residuals of the IRAF fit (fit - ref), in mAA
    resid = (f['wave_fit'] - f['wave_ref']) * 1e3
    print(f'Fit residual (fit-ref): RMS {np.std(resid):.1f} mAA, '
          f'max |{np.max(np.abs(resid)):.0f}| mAA')
    # lines per order
    npo = np.array([np.sum(f['order'] == o) for o in orders])
    print(f'Lines/order         : median {int(np.median(npo))}, '
          f'min {npo.min()}, max {npo.max()}')
    if d['fit']:
        print(f'2D fit              : function={d["fit"]["function"]} '
              f'(1=cheby), xorder={d["fit"]["xorder"]}, '
              f'yorder={d["fit"]["yorder"]}, '
              f'mlambda0={d["fit"]["mlambda0"]:.1f}')
    return d


if __name__ == '__main__':
    here = Path(__file__).resolve().parent.parent
    db = here / 'IRAF' / 'ecTHAR20240125.rsfbo_1'
    summary(db)
