"""
Figures for Report 08 — diagnosing the Cooke 2-D wavecal SVD failure.

Generated by JXP and Claude.

Two figures:
  1. Predicted order coverage before vs after the angle_fits anchor fix,
     compared with the orders the data actually covers — showing why almost no
     order found an archive match (and the 2-D fit collapsed to one order).
  2. The per-order wavelength RMS of the 27 orders solved after the fix.

Inputs:
    The Cooke WaveCalib produced by the (now passing) reduction.

Outputs:
    08_fig1_order_prediction.png, 08_fig2_rms.png in Reports/.
"""

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit.wavecalib import WaveCalib

ROOT = Path(__file__).resolve().parent.parent
REPORTS = ROOT / 'Reports'
WV = (ROOT / 'Cooke_data' / 'redo_from_scratch' / 'PypeIt' / 'cooke_redux'
      / 'Calibrations' / 'WaveCalib_A_0_DET01.fits')


def main():
    """Build the two diagnosis figures. Generated by JXP and Claude."""
    # ---- fig1: order-coverage prediction old vs new vs observed ----
    fig, ax = plt.subplots(figsize=(9, 3.2))
    ax.barh(3, 123 - 66, left=66, height=0.6, color='C2',
            label='data covers (m=66-123)')
    ax.barh(2, 125 - 62, left=62, height=0.6, color='C0',
            label='predicted AFTER fix (62-125)')
    ax.barh(1, 78 - 15, left=15, height=0.6, color='C3',
            label='predicted BEFORE fix (15-78)')
    ax.set_yticks([1, 2, 3])
    ax.set_yticklabels(['before', 'after', 'data'])
    ax.set_xlabel('echelle order m')
    ax.set_title('Order-coverage prediction: anchor built for pre-flip '
                 'xdangle\nmissed the data (overlap drove the SVD crash)')
    ax.legend(fontsize=8, loc='lower right')
    fig.tight_layout()
    fig.savefig(REPORTS / '08_fig1_order_prediction.png', dpi=90)
    plt.close(fig)

    # ---- fig2: per-order RMS after the fix ----
    wv = WaveCalib.from_file(str(WV))
    fits = [f for f in wv.wv_fits if f is not None and f.rms is not None]
    orders = np.array([f.ech_order for f in fits])
    rms = np.array([f.rms for f in fits])
    isort = np.argsort(orders)
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.plot(orders[isort], rms[isort], 'o-', ms=4)
    ax.axhline(0.3, color='r', ls=':', label='0.3 pix threshold')
    ax.set_xlabel('echelle order m')
    ax.set_ylabel('per-order RMS [pix]')
    ax.set_title(f'Cooke WaveCalib after the fix: {orders.size} orders solved, '
                 f'median RMS {np.median(rms):.3f} pix')
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(REPORTS / '08_fig2_rms.png', dpi=90)
    plt.close(fig)
    print(f'orders solved {orders.size} (m={orders.min()}-{orders.max()}), '
          f'median RMS {np.median(rms):.3f}; wrote 2 figures')


if __name__ == '__main__':
    main()
