"""
Figures for Report 09 — the dev-suite (Cooke) full run.

Generated by JXP and Claude.

Three figures from the passing dev-suite reduction of the pushed Cooke frames:
  1. per-order WaveCalib RMS;
  2. a sky-subtracted spec2d cutout showing the standard star's trace across a
     few orders (it is clearly present);
  3. the per-order peak flux of the standard vs order number -- strong signal
     in every order, yet automatic object finding detected nothing (the orders
     are only ~7 px wide).

Inputs:
    REDUX_OUT/shane_hamspec/Hamilton calibrations + Science spec2d.

Outputs:
    09_fig{1,2,3}_*.png in Reports/.
"""

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from astropy.visualization import ZScaleInterval

from pypeit.wavecalib import WaveCalib
from pypeit import spec2dobj

ROOT = Path(__file__).resolve().parent.parent
REPORTS = ROOT / 'Reports'
REDUX = (ROOT.parent.parent / 'REDUX_OUT' / 'shane_hamspec' / 'Hamilton')


def main():
    """Build the three Report-09 figures. Generated by JXP and Claude."""
    # --- fig1: per-order WaveCalib RMS ---
    wv = WaveCalib.from_file(
        str(REDUX / 'Calibrations' / 'WaveCalib_A_0_DET01.fits'))
    fits = [f for f in wv.wv_fits if f is not None and f.rms is not None]
    o = np.array([f.ech_order for f in fits])
    r = np.array([f.rms for f in fits])
    isort = np.argsort(o)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(o[isort], r[isort], 'o-', ms=4)
    ax.axhline(0.3, color='r', ls=':', label='0.3 pix')
    ax.set_xlabel('echelle order m')
    ax.set_ylabel('per-order RMS [pix]')
    ax.set_title(f'Cooke dev-suite WaveCalib: {o.size} orders, '
                 f'median RMS {np.median(r):.3f} pix')
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(REPORTS / '09_fig1_wavecal_rms.png', dpi=90)
    plt.close(fig)

    # --- load spec2d ---
    s = spec2dobj.Spec2DObj.from_file(
        str(next((REDUX / 'Science').glob('spec2d_*.fits'))), 'DET01')
    resid = s.sciimg - s.skymodel
    slits = s.slits
    edges = slits.select_edges()
    left, right = edges[0], edges[1]
    row = s.sciimg.shape[0] // 2

    # --- fig2: sky-subtracted cutout across a few mid orders ---
    mid = slits.nslits // 2
    l = int(left[row, mid]) - 4
    r2 = int(right[row, mid + 4]) + 4
    cut = resid[row - 250:row + 250, l:r2]
    z = ZScaleInterval()
    lo, hi = z.get_limits(cut)
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.imshow(cut, origin='lower', vmin=lo, vmax=hi, cmap='gray',
              aspect='auto')
    ax.set_xlabel('spatial pixel (cutout)')
    ax.set_ylabel('spectral pixel (cutout)')
    ax.set_title('Sky-subtracted standard (HR 7373): the star trace is\n'
                 'clearly present in each ~7 px order (vertical streaks)')
    fig.tight_layout()
    fig.savefig(REPORTS / '09_fig2_star_present.png', dpi=90)
    plt.close(fig)

    # --- fig3: per-order peak flux of the standard ---
    peaks, ords = [], []
    for mm in range(slits.nslits):
        a = int(np.round(left[row, mm]))
        b = int(np.round(right[row, mm]))
        if b - a < 4:
            continue
        prof = np.nanmedian(resid[row - 200:row + 200, a:b], axis=0)
        peaks.append(np.nanmax(prof))
        ords.append(mm)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(ords, peaks, 'o-', ms=3)
    ax.set_xlabel('order index (spatial)')
    ax.set_ylabel('sky-sub peak flux [counts]')
    ax.set_title('Standard star is bright in every order — yet automatic\n'
                 'object finding detected 0 (orders too narrow, ~7 px)')
    fig.tight_layout()
    fig.savefig(REPORTS / '09_fig3_peakflux.png', dpi=90)
    plt.close(fig)
    print('wrote 3 figures; wavecal orders', o.size,
          'median RMS', round(float(np.median(r)), 3))


if __name__ == '__main__':
    main()
