"""
Plot QA figures from the Shane/Hamspec WaveCalib solution.

Generated by JXP and Claude.

Reads the ``WaveCalib`` calibration produced by the passing end-to-end
reduction and makes summary figures for Report 05:

  - per-order wavelength RMS vs echelle order (+ line counts)
  - wavelength coverage and m*lambda vs order
  - an example solved order (arc + wavelength solution + identified lines)
  - fit residuals for that order

Inputs:
    Path to ``WaveCalib_A_0_DET01.fits`` (defaults to the dev-suite REDUX_OUT).

Outputs:
    PNGs written to ``pypeitdev/shane_hamspec/Reports`` (05_fig2..5).
"""

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit.wavecalib import WaveCalib

ROOT = Path(__file__).resolve().parent.parent
REDUX = (ROOT.parent.parent / 'REDUX_OUT' / 'shane_hamspec' / 'Hamilton'
         / 'Calibrations' / 'WaveCalib_A_0_DET01.fits')
REPORTS = ROOT / 'Reports'


def main(wvfile=REDUX):
    """
    Build the WaveCalib QA figures.

    Generated by JXP and Claude.

    Args:
        wvfile (:obj:`str` or `pathlib.Path`): WaveCalib FITS path.

    Returns:
        :obj:`list`: paths of the figures written.
    """
    wv = WaveCalib.from_file(str(wvfile))
    fits = [f for f in wv.wv_fits if f is not None and f.rms is not None]
    orders = np.array([f.ech_order for f in fits])
    rms = np.array([f.rms for f in fits])
    nlines = np.array([f.pixel_fit.size for f in fits])
    cwave = np.array([f.cen_wave for f in fits])
    wmin = np.array([f.wave_soln[f.wave_soln > 0].min() for f in fits])
    wmax = np.array([f.wave_soln.max() for f in fits])

    out = []

    # ---- fig2: RMS and line count vs order ----
    fig, axs = plt.subplots(2, 1, figsize=(9, 7), sharex=True)
    axs[0].plot(orders, rms, 'o-', ms=4)
    axs[0].axhline(0.3, color='r', ls=':', label='0.3 pix threshold')
    axs[0].set_ylabel('per-order RMS [pix]')
    axs[0].set_title(f'Shane/Hamspec WaveCalib: {orders.size} solved orders '
                     f'(median RMS {np.median(rms):.2f} pix)')
    axs[0].legend(fontsize=8)
    axs[1].plot(orders, nlines, 's-', ms=4, color='C2')
    axs[1].set_xlabel('echelle order m')
    axs[1].set_ylabel('ThAr lines used')
    fig.tight_layout()
    p = REPORTS / '05_fig2_rms_vs_order.png'
    fig.savefig(p, dpi=90); plt.close(fig); out.append(p)

    # ---- fig3: wavelength coverage + m*lambda vs order ----
    fig, axs = plt.subplots(1, 2, figsize=(12, 5))
    for o, lo, hi in zip(orders, wmin, wmax):
        axs[0].plot([lo, hi], [o, o], color='C0', lw=1.3)
    axs[0].set_xlabel('wavelength [AA]')
    axs[0].set_ylabel('echelle order m')
    axs[0].set_title('Solved-order wavelength coverage')
    axs[1].plot(orders, orders * cwave, 'o', ms=4)
    axs[1].set_xlabel('echelle order m')
    axs[1].set_ylabel(r'$m \times \lambda_{\rm cen}$ [AA]')
    axs[1].set_title('Grating constant (should be ~constant)')
    fig.tight_layout()
    p = REPORTS / '05_fig3_coverage.png'
    fig.savefig(p, dpi=90); plt.close(fig); out.append(p)

    # ---- pick the best-RMS order for the example/residual plots ----
    best = fits[int(np.argmin(rms))]

    # ---- fig4: example solved order (arc + lines) ----
    fig, ax = plt.subplots(figsize=(11, 4))
    good = best.wave_soln > 0
    ax.plot(best.wave_soln[good], best.spec[good], lw=0.6)
    for wl in best.wave_fit:
        ax.axvline(wl, color='r', alpha=0.35, lw=0.6)
    ax.set_xlabel('wavelength [AA]')
    ax.set_ylabel('counts')
    ax.set_title(f'Example solved order m={best.ech_order} '
                 f'(RMS {best.rms:.3f} pix, {best.pixel_fit.size} lines); '
                 f'red = identified ThAr')
    fig.tight_layout()
    p = REPORTS / '05_fig4_example_order.png'
    fig.savefig(p, dpi=90); plt.close(fig); out.append(p)

    # ---- fig5: fit residuals for that order ----
    model_wave = best.pypeitfit.eval(best.pixel_fit / best.xnorm)
    resid = (best.wave_fit - model_wave) / best.cen_disp   # in pixels
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.axhline(0, color='k', lw=0.8, ls=':')
    ax.plot(best.wave_fit, resid, 'o', ms=5)
    ax.set_xlabel('wavelength [AA]')
    ax.set_ylabel('fit residual [pix]')
    ax.set_title(f'Order m={best.ech_order} fit residuals '
                 f'(RMS {best.rms:.3f} pix)')
    fig.tight_layout()
    p = REPORTS / '05_fig5_residuals.png'
    fig.savefig(p, dpi=90); plt.close(fig); out.append(p)

    print(f'solved orders: {orders.size} (m={orders.min()}-{orders.max()})')
    print(f'median RMS {np.median(rms):.3f} pix; wrote {len(out)} figures')
    for p in out:
        print('  ', p.name)
    return out


if __name__ == '__main__':
    main()
