"""
Read the IRAF wavelength solution + extracted arc for Shane/Hamspec.

Generated by JXP and Claude.

This is the IRAF analogue of ``read_xidl_arc`` and is used to extend the
composite-arc / angle_fits archive from the 64 XIDL orders (m=65-146) to the
full IRAF set of 102 orders (m=58-159).

Source files (in ``pypeitdev/shane_hamspec/IRAF``):
  - ``ecTHAR20240125.rsfbo_1``  : ecidentify database of identified ThAr lines
                                  (order, pixel, air wavelength).
  - ``THAR20240125.rsfbo_1.fits``: the extracted ThAr arc, 103 rows x 4096 pix.
                                   Row index = order - 57 (verified: identified
                                   line pixels land on that row's peaks).

For each order we fit its identified lines (air wavelength vs normalized pixel)
with a Legendre polynomial, evaluate it on the 4096-pixel grid, and convert to
vacuum with the same ``pypeit`` ``airtovac`` used elsewhere.  The matching arc
spectrum is taken from the rsfbo row.

Inputs:
    The IRAF directory.

Outputs (via :func:`load`):
    orders (N,), wave (N, npix) vacuum AA, spec (N, npix), for the orders that
    have enough identified lines to fit.
"""

from pathlib import Path

import numpy as np
from numpy.polynomial import legendre as L
from astropy.io import fits
from astropy import units

from pypeit.core.wave import airtovac

import parse_iraf_ecthar as iraf

ROOT = Path(__file__).resolve().parent.parent
ROW_OFFSET = 57          # rsfbo row index = order - 57 (verified)
NPIX = 4096
MAXDEG = 4               # max Legendre degree for a per-order wave fit


def load(iraf_dir=None, min_lines=4):
    """
    Load the IRAF per-order wavelength solution and arc spectra.

    Generated by JXP and Claude.

    Args:
        iraf_dir (:obj:`str` or `pathlib.Path`, optional):
            Path to the ``IRAF`` directory.  Defaults to the project location.
        min_lines (:obj:`int`):
            Minimum identified lines required to fit an order.

    Returns:
        :obj:`tuple`: ``(orders, wave, spec)`` with ``wave`` in vacuum AA and
        shapes (N,), (N, NPIX), (N, NPIX).
    """
    iraf_dir = Path(iraf_dir) if iraf_dir is not None else ROOT / 'IRAF'
    feat = iraf.parse(iraf_dir / 'ecTHAR20240125.rsfbo_1')['features']
    arcimg = fits.open(iraf_dir / 'THAR20240125.rsfbo_1.fits')[0].data

    x01 = np.arange(NPIX) / float(NPIX - 1)
    xnn = 2.0 * x01 - 1.0
    orders, waves, specs = [], [], []
    for m in np.unique(feat['order']):
        sel = feat['order'] == m
        if sel.sum() < min_lines:
            continue
        row = int(m) - ROW_OFFSET
        if row < 0 or row >= arcimg.shape[0]:
            continue
        pix = feat['pixel'][sel] - 1.0           # 1-indexed -> 0-indexed
        wv_air = feat['wave_ref'][sel]
        deg = int(min(MAXDEG, sel.sum() - 2))
        coeff = L.legfit(2.0 * (pix / (NPIX - 1)) - 1.0, wv_air, deg)
        wv_air_full = L.legval(xnn, coeff)
        wv_vac = airtovac(wv_air_full * units.AA).value
        orders.append(int(m))
        waves.append(wv_vac)
        specs.append(arcimg[row].astype(float))

    return (np.array(orders), np.array(waves), np.array(specs))


def summary(iraf_dir=None):
    """
    Print a short characterization of the IRAF archive.

    Generated by JXP and Claude.

    Args:
        iraf_dir (:obj:`str` or `pathlib.Path`, optional): IRAF directory.

    Returns:
        :obj:`tuple`: ``(orders, wave, spec)`` from :func:`load`.
    """
    orders, wave, spec = load(iraf_dir)
    mid = wave[:, NPIX // 2]
    ml = orders * mid
    print(f'IRAF orders fit   : {orders.size} '
          f'(m={orders.min()}-{orders.max()})')
    print(f'wavelength range  : {np.nanmin(wave[wave > 0]):.1f} - '
          f'{np.nanmax(wave):.1f} AA (vacuum)')
    print(f'm*lambda (center) : median {np.nanmedian(ml):.0f} AA')
    return orders, wave, spec


if __name__ == '__main__':
    summary()
