"""
Inspect the Cooke XIDL hamspec reduction and assess how it can improve our
Shane/Hamspec wavelength calibration.

Generated by JXP and Claude.

The folder ``Cooke_data/redo_from_scratch`` is a full XIDL (Hamilton-pipeline)
reduction of a hamspec dataset (UT 16 Nov 2010, binned 2x1 -> 2048 spectral
pixels).  Its wavelength solution lives in
``Arcs/Fits/Arc_01_fit.idl`` and is read with the same
:func:`pypeit.core.wavecal.templates.xidl_esihires` we already use.

Why it matters: our current `reid_arxiv` (built from the earlier
``pypeitdev/shane_hamspec/Arc_01_fit.idl``) only solves the red half of the
format (m=65-97) because its bluer orders are line-poor (~10 ThAr lines/order).
The Cooke solution is far richer (80 orders, ~36 lines/order, ~39 in the blue),
so resampled to the dev-suite binning (2048->4096) it is a strong candidate to
replace/extend our composite arc and finally pull in the blue orders.

Inputs:
    The Cooke ``Arc_01_fit.idl`` and our current ``Arc_01_fit.idl``.

Outputs (via :func:`inspect`):
    prints a comparison and writes ``Reports/06_fig1_linedensity.png``.
"""

from pathlib import Path

import numpy as np
from scipy.io import readsav
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit.core.wavecal import templates

ROOT = Path(__file__).resolve().parent.parent
COOKE = ROOT / 'Cooke_data' / 'redo_from_scratch' / 'Arcs' / 'Fits' / \
    'Arc_01_fit.idl'
OURS = ROOT / 'Arc_01_fit.idl'


def _stats(idl_file):
    """
    Characterize one XIDL arc solution.

    Generated by JXP and Claude.

    Args:
        idl_file (:obj:`str` or `pathlib.Path`): XIDL ``Arc_01_fit.idl``.

    Returns:
        :obj:`dict`: orders, wavelength range, per-order line counts, RMS, and
        the raw ``sv_aspec`` pixel size.
    """
    orders, wave, spec = templates.xidl_esihires(str(idl_file), log10=True)
    d = readsav(str(idl_file))
    nlin = d['sv_lines']['NLIN']
    nlin = nlin[nlin > 0]
    func = d['all_arcfit']['FUNC']
    rms = d['all_arcfit']['RMS'][np.array([f in (b'CHEBY', b'POLY')
                                           for f in func])]
    wmin = np.nanmin([w[w > 0].min() for w in wave if np.any(w > 0)])
    wmax = np.nanmax(wave)
    # per-order line counts aligned with order number (for the figure).
    # The recarrays are padded to 100 rows; guess_ordr gives the real orders,
    # so truncate the line counts to match.
    guess = d['guess_ordr']
    nlin_all = d['sv_lines']['NLIN'][:guess.size]
    return dict(orders=orders, npix=d['sv_aspec'].shape[1],
                nord=orders.size, wmin=float(wmin), wmax=float(wmax),
                nlin_med=int(np.median(nlin)), nlin_max=int(nlin.max()),
                rms_maa=float(np.log(10) * 6000 * np.median(rms) * 1e3),
                order_axis=guess, nlin_per_order=nlin_all)


def inspect():
    """
    Compare the Cooke solution to our current one and make a figure.

    Generated by JXP and Claude.

    Returns:
        :obj:`tuple`: (cooke_stats, ours_stats) dicts.
    """
    c = _stats(COOKE)
    o = _stats(OURS)
    for name, s in [('Cooke (16Nov10, 2x1)', c), ('Ours (current archive)', o)]:
        print(f'{name}:')
        print(f'   orders {s["nord"]} (m={s["orders"].min()}-'
              f'{s["orders"].max()}), npix={s["npix"]}')
        print(f'   wave {s["wmin"]:.0f}-{s["wmax"]:.0f} AA, '
              f'lines/order median {s["nlin_med"]} (max {s["nlin_max"]}), '
              f'RMS ~{s["rms_maa"]:.1f} mAA')

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(c['order_axis'], c['nlin_per_order'], 'o-', ms=4,
            label=f'Cooke (median {c["nlin_med"]}/order)')
    ax.plot(o['order_axis'], o['nlin_per_order'], 's-', ms=4, color='C3',
            label=f'Ours (median {o["nlin_med"]}/order)')
    ax.set_xlabel('echelle order m')
    ax.set_ylabel('identified ThAr lines / order')
    ax.set_title('ThAr line density per order: Cooke vs current archive')
    ax.legend()
    fig.tight_layout()
    out = ROOT / 'Reports' / '06_fig1_linedensity.png'
    fig.savefig(out, dpi=90)
    plt.close(fig)
    print(f'wrote {out}')
    return c, o


if __name__ == '__main__':
    inspect()
