"""
Cross-correlate observed Shane/Hamspec arc orders against the XIDL archive.

Generated by JXP and Claude.

Report 05 concluded the NIRES reidentification failed because the legacy
archive (2024 setting) and the dev-suite raw data (2014 setting) are different
configurations.  JXP pushed back: even so, a given *physical* order m contains
the same ThAr lines, so a per-order cross-correlation (with shift AND stretch)
should still match if the wavelength coverage overlaps.  This module tests that
directly on the **red side** of the format (where ThAr lines are strong, but
not the reddest orders, which are line-poor).

It:
  1. rebuilds the observed per-order arc spectra from the existing
     ``Slits``/``Arc`` calibration products (via ``arc.get_censpec``);
  2. loads the XIDL archive orders (``read_xidl_arc``);
  3. for chosen red-side XIDL orders, scans every observed order with the fast
     ``wvutils.xcorr_shift`` to find the best match, then refines the best
     candidate with ``wvutils.xcorr_shift_stretch`` (shift + stretch);
  4. prints the results and plots the best overlay.

Inputs:
    REDUX_OUT calibrations for shane_hamspec/Hamilton and ``Arc_01_fit.idl``.

Outputs:
    Prints best shift/stretch/cc per probed order; writes
    ``Reports/05_fig1_xcorr_best.png``.
"""

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from pypeit.slittrace import SlitTraceSet
from pypeit.images.buildimage import ArcImage
from pypeit.core import arc
from pypeit.core.wavecal import wvutils

import read_xidl_arc as xidl

# Repo paths
ROOT = Path(__file__).resolve().parent.parent
CALIB = (ROOT.parent.parent / 'REDUX_OUT' / 'shane_hamspec' / 'Hamilton'
         / 'Calibrations')


def observed_arccen():
    """
    Rebuild the observed per-order arc spectra from the calibration products.

    Generated by JXP and Claude.

    Returns:
        `numpy.ndarray`_: Arc spectra, shape (nspec, nslits), one boxcar-
        extracted arc per traced order.
    """
    slits = SlitTraceSet.from_file(
        next(CALIB.glob('Slits_A_0_DET01.fits*')))
    arcimg = ArcImage.from_file(next(CALIB.glob('Arc_A_0_DET01.fits')))
    slit_cen = slits.select_edges()[0] * 0 + \
        (slits.select_edges()[0] + slits.select_edges()[1]) / 2.0
    slitmask = slits.slit_img()
    arccen, _, _ = arc.get_censpec(slit_cen, slitmask, arcimg.image,
                                   verbose=False)
    return arccen


def explore(xidl_orders_to_probe=(80, 90, 100, 110)):
    """
    Cross-correlate the probed XIDL orders against all observed orders.

    Generated by JXP and Claude.

    Args:
        xidl_orders_to_probe (:obj:`tuple`):
            Physical order numbers (red side, line-rich) to test.

    Returns:
        :obj:`list`: One dict per probed order with the best-match results.
    """
    arccen = observed_arccen()
    nspec, nslits = arccen.shape
    xo, xw, xs, _ = xidl.load(ROOT / 'Arc_01_fit.idl')

    results = []
    for m in xidl_orders_to_probe:
        if m not in xo:
            continue
        arxiv = xs[xo == m][0]
        # Fast scan: best simple-xcorr cc over all observed orders
        best = (-2.0, -1, 0.0)  # cc, slit, shift
        for s in range(nslits):
            obs = arccen[:, s]
            if not np.any(np.isfinite(obs)) or np.nanmax(obs) <= 0:
                continue
            shift, cc = wvutils.xcorr_shift(arxiv, np.nan_to_num(obs),
                                            percent_ceil=50.0)
            if cc > best[0]:
                best = (cc, s, shift)
        cc0, sbest, shift0 = best
        # Refine the best candidate with shift+stretch
        obs = np.nan_to_num(arccen[:, sbest])
        out = wvutils.xcorr_shift_stretch(
            arxiv, obs, cc_thresh=-1.0,
            shift_mnmx=(-0.3, 0.3), stretch_mnmx=(0.9, 1.1))
        success, shift, stretch, stretch2, corr, shift_cc, corr_cc = out
        results.append(dict(order=m, slit=sbest, cc_scan=cc0,
                            cc_refined=corr, shift=shift, stretch=stretch))
        print(f'XIDL m={m:3d}: best observed order #{sbest:3d}  '
              f'cc(scan)={cc0:.3f}  ->  shift/stretch refine: '
              f'cc={corr if corr is not None else float("nan"):.3f}, '
              f'shift={shift if shift is not None else float("nan"):.1f}, '
              f'stretch={stretch if stretch is not None else float("nan"):.4f}')

    # Plot the single best (highest refined cc) overlay
    if results:
        bestr = max(results, key=lambda r: (r['cc_refined'] or -2))
        m = bestr['order']
        arxiv = xs[xo == m][0]
        obs = np.nan_to_num(arccen[:, bestr['slit']])
        obst = wvutils.shift_and_stretch(
            obs, bestr['shift'] or 0.0, bestr['stretch'] or 1.0, 0.0)
        fig, ax = plt.subplots(figsize=(11, 4))
        a = arxiv / np.nanmax(arxiv)
        o = obst / np.nanmax(obst) if np.nanmax(obst) > 0 else obst
        ax.plot(a, lw=0.7, label=f'XIDL archive m={m}')
        ax.plot(o, lw=0.7, alpha=0.8,
                label=f'observed order #{bestr["slit"]} '
                      f'(shift {bestr["shift"]:.1f}, '
                      f'stretch {bestr["stretch"]:.4f})')
        ax.set_xlabel('pixel')
        ax.set_ylabel('normalized counts')
        ax.set_title(f'Best red-side match: cc={bestr["cc_refined"]:.3f}')
        ax.legend(fontsize=8)
        fig.tight_layout()
        fig.savefig(ROOT / 'Reports' / '05_fig1_xcorr_best.png', dpi=90)
        plt.close(fig)
    return results


if __name__ == '__main__':
    explore()
