"""
Check the holy-grail bdisp patch on the MOIRCS VB_K test mask: run
holy-grail on the run3 sky spectra with the installed (patched) PypeIt
and compare with the fix-B variant tested by holy_rms_check.py
(holy_rms_rerun.json).

Usage (after ``git apply holygrail_bdisp_from_matched_lines.patch`` in
PypeIt, or with PYTHONPATH pointing to a patched copy):
    python verify_fixb.py

Not part of PypeIt.  Generated by JXP and Claude.
"""
import json
import sys
from multiprocessing import Pool
from pathlib import Path

import numpy as np

DEV = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(DEV))
import holy_rms_check as H  # noqa: E402
from pypeit.core.wavecal import autoid  # noqa: E402
from pypeit.wavecalib import WaveCalib  # noqa: E402

RAW = ('/mnt/s1data01/work/research/pypeit-development/test_data_moircs/'
       'VB_K/example_MO_CC0958PA200_1/sci/MCSA00352031.fits')


def job(det):
    """Run holy-grail on one detector.  Generated by JXP and Claude."""
    return H.run_holy((str(DEV / 'run3'), RAW, det, 'asis'))


def main():
    """Compare and print.  Generated by JXP and Claude."""
    print(f'autoid: {autoid.__file__}')
    with Pool(2) as p:
        res = p.map(job, [1, 2])
    ref = json.loads((DEV / 'holy_rms_rerun.json').read_text())
    nbad = 0
    print('det spat | patched bdisp rms true n | fixB rms true n | '
          'max|dl| vs run3 (patched, fixB)')
    for det, _, out in res:
        wc = WaveCalib.from_file(DEV / 'run3' / 'Calibrations'
                                 / f'WaveCalib_A_0_DET0{det}.fits',
                                 chk_version=False)
        stored = {int(w.spat_id): w.wave_soln for w in wc.wv_fits
                  if w is not None and w.pypeitfit is not None}
        for spat, o in sorted(out.items()):
            r = ref[f'{det}_{spat}']
            dl = float(np.max(np.abs(np.array(o['wave']) - stored[spat])))
            same = (abs(o['rms'] - r['B_rms']) < 1e-9
                    and o['nlin'] == r['B_nlin']
                    and abs(dl - r['dl_B']) < 1e-6)
            nbad += not same
            print(f"  {det} {spat:5d} | {o['bdisp']:.3f} {o['rms']:.4f} "
                  f"{o['true_rms']:.4f} {o['nlin']:3d} | {r['B_rms']:.4f} "
                  f"{r['B_true_rms']:.4f} {r['B_nlin']:3d} | {dl:.3f} "
                  f"{r['dl_B']:.3f} {'SAME' if same else 'DIFF'}")
    print('slits differing from tested fix B:', nbad)


if __name__ == '__main__':
    main()
